### ISSUE TITLE
where is the VisualStudio Code extension for ESP-IDF?

### ISSUE THREAD

**Issue by beta-tester** [espressif/vscode-esp-idf-extension#1]
hi,
i am looking for the VisualStudio Code extension for ESP-IDF, but this repository is empty.
will the VS Code extension for ESP-IDF come soon?

**Comment by chillophil** [comment]
Unfortunately, there is none at the moment - as far as I know.

But you could configure VSCode by yourself. You just need the C/C++ Extension and configure it properly to find includes and definitions.

You could also create tasks/build-target to simplify the use of the Makefile.

And you could also give PlatformIO a try.

**Comment by SoumeshBanerjee** [comment]
ESP-IDF VSCode Extension is out now, Please check it out!
