### ISSUE TITLE
Make sure you have the build tools installed and set in $PATH (VSC-324)

### ISSUE THREAD

**Issue by syeedhaiderali** [espressif/vscode-esp-idf-extension#100]
I had used ESP-IDF with vs code and it worked fine but after a month it stops working and showing error. Kindly guide

**Screenshots**
![image](https://user-images.githubusercontent.com/20606725/82113869-8dd78880-9772-11ea-8b4d-dd23b329c5f0.png)

**Environment**

- OS Name & Version: [Windows 10]
- VSCode Version: [e.g. 1.45.1]
- ESP-IDF Version: [e.g. v4.0]
- Python Version: [e.g. 3.7.3]

**Logs**
{"user":true,"message":"Make sure you have the build tools installed and set in $PATH","stack":"Error: spawn cmake ENOENT\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)\n\tat onErrorNT (internal/child_process.js:456:16)\n\tat processTicksAndRejections (internal/process/task_queues.js:77:11)","level":"error","timestamp":"2020-05-16T07:32:17.171Z"}

**Comment by mitchjs** [comment]
you need to get PR #95 merged in and build you own vsix and install to VSCode
as of v0.2.1 which is causing this issue
if you dont know or cant set up to build your own vsix
(it was pretty easy)
i can send you a vsix with pr #95 in it

**Comment by SoumeshBanerjee** [comment]
Possible duplicate #93

**Comment by aks11** [comment]
can someone provide the vsix file with PR#95

**Comment by mitchjs** [comment]
@aks11 this should be it... it will install as v0.2.1-pr95
disable auto update of extensions, or you'll get v0.2.1 

[esp-idf-extension.zip](https://github.com/espressif/vscode-esp-idf-extension/files/4641561/esp-idf-extension.zip)

**Comment by hmcosentini** [comment]
@mitchjs Thanks I disabled the auto-update and installed from the .vsix it is working. When you plan to release the update in vscode?

**Comment by SoumeshBanerjee** [comment]
We have a plan to release this as soon as #95 is merged (possibly today EOD or tomorrow)

**Comment by syeedhaiderali** [comment]
Thanks @mitchjs it's working now. @SoumeshBanerjee thanks to you also and I am waiting for the new release.
