### ISSUE TITLE
ESP-IDF不能烧录程序 (VSC-1134)

### ISSUE THREAD

**Issue by woshiwstt50123** [espressif/vscode-esp-idf-extension#1002]
### OS

Windows

### Operating System version

Windows11 22H2

### Visual Studio Code version

1.73.1

### ESP-IDF version

5.0.2

### Python version

3.11.2

### Doctor command output

---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "c:\\Users\\TangTao\\esp\\tools\\xtensa-esp32-elf\\esp-2022r1-11.2.0\\xtensa-esp32-elf\\bin\\xtensa-esp32-elf-gcc.exe",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            },
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
}

### Extension

{\"espIdfPath\":true,\"espAdfPath\":false,\"espMdfPath\":false,\"espMatterPath\":false,\"espIdfToolsPaths\":{\"c:<HOMEPATH>\\\\esp\\\\tools\\\\xtensa-esp-elf-gdb\\\\11.2_20220823\\\\xtensa-esp-elf-gdb\\\\bin\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\riscv32-esp-elf-gdb\\\\11.2_20220823\\\\riscv32-esp-elf-gdb\\\\bin\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\xtensa-esp32-elf\\\\esp-2022r1-11.2.0\\\\xtensa-esp32-elf\\\\bin\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\xtensa-esp32s2-elf\\\\esp-2022r1-11.2.0\\\\xtensa-esp32s2-elf\\\\bin\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\xtensa-esp32s3-elf\\\\esp-2022r1-11.2.0\\\\xtensa-esp32s3-elf\\\\bin\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\riscv32-esp-elf\\\\esp-2022r1-11.2.0\\\\riscv32-esp-elf\\\\bin\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\esp32ulp-elf\\\\2.35_20220830\\\\esp32ulp-elf\\\\bin\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\cmake\\\\3.24.0\\\\bin\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\openocd-esp32\\\\v0.11.0-esp32-20221026\\\\openocd-esp32\\\\bin\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\ninja\\\\1.10.2\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\idf-exe\\\\1.0.3\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\ccache\\\\4.6.2\\\\ccache-4.6.2-windows-x86_64\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\dfu-util\\\\0.9\\\\dfu-util-0.9-win64\":true,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\esp-rom-elfs\\\\20220823\":true},\"pythonBinPath\":true,\"toolsPath\":true},\"configurationSpacesValidation\":{\"customExtraPaths\":{\"c:<HOMEPATH>\\\\esp\\\\tools\\\\xtensa-esp-elf-gdb\\\\11.2_20220823\\\\xtensa-esp-elf-gdb\\\\bin\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\riscv32-esp-elf-gdb\\\\11.2_20220823\\\\riscv32-esp-elf-gdb\\\\bin\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\xtensa-esp32-elf\\\\esp-2022r1-11.2.0\\\\xtensa-esp32-elf\\\\bin\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\xtensa-esp32s2-elf\\\\esp-2022r1-11.2.0\\\\xtensa-esp32s2-elf\\\\bin\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\xtensa-esp32s3-elf\\\\esp-2022r1-11.2.0\\\\xtensa-esp32s3-elf\\\\bin\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\riscv32-esp-elf\\\\esp-2022r1-11.2.0\\\\riscv32-esp-elf\\\\bin\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\esp32ulp-elf\\\\2.35_20220830\\\\esp32ulp-elf\\\\bin\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\cmake\\\\3.24.0\\\\bin\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\openocd-esp32\\\\v0.11.0-esp32-20221026\\\\openocd-esp32\\\\bin\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\ninja\\\\1.10.2\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\idf-exe\\\\1.0.3\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\ccache\\\\4.6.2\\\\ccache-4.6.2-windows-x86_64\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\dfu-util\\\\0.9\\\\dfu-util-0.9-win64\":false,\"c:<HOMEPATH>\\\\esp\\\\tools\\\\esp-rom-elfs\\\\20220823\":false},\"espAdfPath\":false,\"espIdfPath\":false,\"espMatterPath\":false,\"espMdfPath\":false,\"gitPath\":false,\"pythonBinPath\":false,\"toolsPath\":false,\"systemEnvPath\":true},\"debugAdapterRequirements\":{\"output\":\"C:<HOMEPATH>\\\\esp\\\\esp-idf\\\\tools\\\\check_python_dependencies.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html\\r\\n  import pkg_resources\\r\\nPython requirements are satisfied.\",\"result\":\"C:<HOMEPATH>\\\\esp\\\\esp-idf\\\\tools\\\\check_python_dependencies.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html\\r\\n  import pkg_resources\\r\\nPython requirements are satisfied.\"},\"espIdfToolsVersions\":[{\"actual\":\"11.2_20220823\",\"description\":\"GDB for Xtensa\",\"doesToolExist\":true,\"env\":{},\"expected\":\"11.2_20220823\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"xtensa-esp-elf-gdb\",\"name\":\"xtensa-esp-elf-gdb\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\xtensa-esp-elf-gdb\\\\11.2_20220823\\\\xtensa-esp-elf-gdb\\\\bin\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"11.2_20220823\",\"description\":\"GDB for RISC-V\",\"doesToolExist\":true,\"env\":{},\"expected\":\"11.2_20220823\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"riscv32-esp-elf-gdb\",\"name\":\"riscv32-esp-elf-gdb\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\riscv32-esp-elf-gdb\\\\11.2_20220823\\\\riscv32-esp-elf-gdb\\\\bin\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"esp-2022r1-11.2.0\",\"description\":\"Toolchain for Xtensa (ESP32) based on GCC\",\"doesToolExist\":true,\"env\":{},\"expected\":\"esp-2022r1-11.2.0\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"xtensa-esp32-elf\",\"name\":\"xtensa-esp32-elf\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\xtensa-esp32-elf\\\\esp-2022r1-11.2.0\\\\xtensa-esp32-elf\\\\bin\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"esp-2022r1-11.2.0\",\"description\":\"Toolchain for Xtensa (ESP32-S2) based on GCC\",\"doesToolExist\":true,\"env\":{},\"expected\":\"esp-2022r1-11.2.0\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"xtensa-esp32s2-elf\",\"name\":\"xtensa-esp32s2-elf\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\xtensa-esp32s2-elf\\\\esp-2022r1-11.2.0\\\\xtensa-esp32s2-elf\\\\bin\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"esp-2022r1-11.2.0\",\"description\":\"Toolchain for Xtensa (ESP32-S3) based on GCC\",\"doesToolExist\":true,\"env\":{},\"expected\":\"esp-2022r1-11.2.0\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"xtensa-esp32s3-elf\",\"name\":\"xtensa-esp32s3-elf\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\xtensa-esp32s3-elf\\\\esp-2022r1-11.2.0\\\\xtensa-esp32s3-elf\\\\bin\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"esp-2022r1-11.2.0\",\"description\":\"Toolchain for 32-bit RISC-V based on GCC\",\"doesToolExist\":true,\"env\":{},\"expected\":\"esp-2022r1-11.2.0\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"riscv32-esp-elf\",\"name\":\"riscv32-esp-elf\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\riscv32-esp-elf\\\\esp-2022r1-11.2.0\\\\riscv32-esp-elf\\\\bin\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"2.35_20220830\",\"description\":\"Toolchain for ESP32 ULP coprocessor\",\"doesToolExist\":true,\"env\":{},\"expected\":\"2.35_20220830\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"esp32ulp-elf\",\"name\":\"esp32ulp-elf\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\esp32ulp-elf\\\\2.35_20220830\\\\esp32ulp-elf\\\\bin\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"3.24.0\",\"description\":\"CMake build system\",\"doesToolExist\":true,\"env\":{},\"expected\":\"3.24.0,3.16.3\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"cmake\",\"name\":\"cmake\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\cmake\\\\3.24.0\\\\bin\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"v0.11.0-esp32-20221026\",\"description\":\"OpenOCD for ESP32\",\"doesToolExist\":true,\"env\":{\"OPENOCD_SCRIPTS\":\"c:<HOMEPATH>\\\\esp\\\\openocd-esp32\\\\v0.11.0-esp32-20221026/openocd-esp32/share/openocd/scripts\"},\"expected\":\"v0.11.0-esp32-20221026\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"openocd-esp32\",\"name\":\"openocd-esp32\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\openocd-esp32\\\\v0.11.0-esp32-20221026\\\\openocd-esp32\\\\bin\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"1.10.2\",\"description\":\"Ninja build system\",\"doesToolExist\":true,\"env\":{},\"expected\":\"1.10.2\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"ninja\",\"name\":\"ninja\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\ninja\\\\1.10.2\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"1.0.3\",\"description\":\"IDF wrapper tool for Windows\",\"doesToolExist\":true,\"env\":{},\"expected\":\"1.0.3\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"idf-exe\",\"name\":\"idf-exe\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\idf-exe\\\\1.0.3\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"4.6.2\",\"description\":\"Ccache (compiler cache)\",\"doesToolExist\":true,\"env\":{\"IDF_CCACHE_ENABLE\":\"1\"},\"expected\":\"4.6.2\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"ccache\",\"name\":\"ccache\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\ccache\\\\4.6.2\\\\ccache-4.6.2-windows-x86_64\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"0.9\",\"description\":\"dfu-util (Device Firmware Upgrade Utilities)\",\"doesToolExist\":true,\"env\":{},\"expected\":\"0.9\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"dfu-util\",\"name\":\"dfu-util\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\dfu-util\\\\0.9\\\\dfu-util-0.9-win64\",\"progress\":\"0.00%\",\"progressDetail\":\"\"},{\"actual\":\"No command version\",\"description\":\"ESP ROM ELFs\",\"doesToolExist\":true,\"env\":{\"ESP_ROM_ELF_DIR\":\"c:<HOMEPATH>\\\\esp\\\\esp-rom-elfs\\\\20220823/\"},\"expected\":\"\",\"hashResult\":true,\"hasFailed\":false,\"id\":\"esp-rom-elfs\",\"name\":\"esp-rom-elfs\",\"path\":\"c:<HOMEPATH>\\\\esp\\\\esp-rom-elfs\\\\20220823\",\"progress\":\"0.00%\",\"progressDetail\":\"\"}],\"espIdfVersion\":{\"output\":\"v5.0.2\\n\",\"result\":\"5.0.2\"},\"extensionRequirements\":{\"output\":\"C:<HOMEPATH>\\\\esp\\\\esp-idf\\\\tools\\\\check_python_dependencies.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html\\r\\n  import pkg_resources\\r\\nPython requirements are satisfied.\",\"result\":\"C:<HOMEPATH>\\\\esp\\\\esp-idf\\\\tools\\\\check_python_dependencies.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html\\r\\n  import pkg_resources\\r\\nPython requirements are satisfied.\"},\"gitVersion\":{\"output\":\"git version 2.39.2.windows.1\\n\",\"result\":\"2.39.2.windows.1\"},\"idfCheckRequirements\":{\"output\":\"C:<HOMEPATH>\\\\esp\\\\esp-idf\\\\tools\\\\check_python_dependencies.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html\\r\\n  import pkg_resources\\r\\nPython requirements are satisfied.\",\"result\":\"C:<HOMEPATH>\\\\esp\\\\esp-idf\\\\tools\\\\check_python_dependencies.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html\\r\\n  import pkg_resources\\r\\nPython requirements are satisfied.\"},\"launchJson\":\"{\\n  \\\"version\\\": \\\"0.2.0\\\",\\n  \\\"configurations\\\": [\\n    {\\n      \\\"type\\\": \\\"espidf\\\",\\n      \\\"name\\\": \\\"Launch\\\",\\n      \\\"request\\\": \\\"launch\\\"\\n    }\\n  ]\\n}\",\"pipVersion\":{\"output\":\"pip 23.1.2 from c:<HOMEPATH>\\\\esp\\\\python_env\\\\idf5.0_py3.11_env\\\\Lib\\\\site-packages\\\\pip (python 3.11)\\r\\r\\n\",\"result\":\"23.1.2\"},\"pythonPackages\":{\"output\":\"[{\\\"name\\\": \\\"bitstring\\\", \\\"version\\\": \\\"4.0.2\\\"}, {\\\"name\\\": \\\"CacheControl\\\", \\\"version\\\": \\\"0.13.1\\\"}, {\\\"name\\\": \\\"certifi\\\", \\\"version\\\": \\\"2023.5.7\\\"}, {\\\"name\\\": \\\"cffi\\\", \\\"version\\\": \\\"1.15.1\\\"}, {\\\"name\\\": \\\"charset-normalizer\\\", \\\"version\\\": \\\"3.1.0\\\"}, {\\\"name\\\": \\\"click\\\", \\\"version\\\": \\\"8.0.4\\\"}, {\\\"name\\\": \\\"colorama\\\", \\\"version\\\": \\\"0.4.6\\\"}, {\\\"name\\\": \\\"construct\\\", \\\"version\\\": \\\"2.10.68\\\"}, {\\\"name\\\": \\\"contextlib2\\\", \\\"version\\\": \\\"21.6.0\\\"}, {\\\"name\\\": \\\"cryptography\\\", \\\"version\\\": \\\"36.0.2\\\"}, {\\\"name\\\": \\\"ecdsa\\\", \\\"version\\\": \\\"0.18.0\\\"}, {\\\"name\\\": \\\"esp-coredump\\\", \\\"version\\\": \\\"1.5.0\\\"}, {\\\"name\\\": \\\"esp-debug-backend\\\", \\\"version\\\": \\\"1.0.3\\\"}, {\\\"name\\\": \\\"esptool\\\", \\\"version\\\": \\\"4.5.1\\\"}, {\\\"name\\\": \\\"filelock\\\", \\\"version\\\": \\\"3.12.2\\\"}, {\\\"name\\\": \\\"freertos-gdb\\\", \\\"version\\\": \\\"1.0.2\\\"}, {\\\"name\\\": \\\"future\\\", \\\"version\\\": \\\"0.18.2\\\"}, {\\\"name\\\": \\\"gcovr\\\", \\\"version\\\": \\\"6.0\\\"}, {\\\"name\\\": \\\"idf-component-manager\\\", \\\"version\\\": \\\"1.2.3\\\"}, {\\\"name\\\": \\\"idna\\\", \\\"version\\\": \\\"3.4\\\"}, {\\\"name\\\": \\\"Jinja2\\\", \\\"version\\\": \\\"3.0.3\\\"}, {\\\"name\\\": \\\"kconfiglib\\\", \\\"version\\\": \\\"14.1.0\\\"}, {\\\"name\\\": \\\"lxml\\\", \\\"version\\\": \\\"4.9.2\\\"}, {\\\"name\\\": \\\"MarkupSafe\\\", \\\"version\\\": \\\"2.1.3\\\"}, {\\\"name\\\": \\\"msgpack\\\", \\\"version\\\": \\\"1.0.5\\\"}, {\\\"name\\\": \\\"packaging\\\", \\\"version\\\": \\\"23.1\\\"}, {\\\"name\\\": \\\"pip\\\", \\\"version\\\": \\\"23.1.2\\\"}, {\\\"name\\\": \\\"pycparser\\\", \\\"version\\\": \\\"2.21\\\"}, {\\\"name\\\": \\\"pyelftools\\\", \\\"version\\\": \\\"0.27\\\"}, {\\\"name\\\": \\\"pygdbmi\\\", \\\"version\\\": \\\"0.9.0.2\\\"}, {\\\"name\\\": \\\"Pygments\\\", \\\"version\\\": \\\"2.15.1\\\"}, {\\\"name\\\": \\\"pyparsing\\\", \\\"version\\\": \\\"3.0.9\\\"}, {\\\"name\\\": \\\"pyserial\\\", \\\"version\\\": \\\"3.5\\\"}, {\\\"name\\\": \\\"pywin32\\\", \\\"version\\\": \\\"306\\\"}, {\\\"name\\\": \\\"PyYAML\\\", \\\"version\\\": \\\"6.0\\\"}, {\\\"name\\\": \\\"reedsolo\\\", \\\"version\\\": \\\"1.6.0\\\"}, {\\\"name\\\": \\\"requests\\\", \\\"version\\\": \\\"2.31.0\\\"}, {\\\"name\\\": \\\"requests-file\\\", \\\"version\\\": \\\"1.5.1\\\"}, {\\\"name\\\": \\\"requests-toolbelt\\\", \\\"version\\\": \\\"1.0.0\\\"}, {\\\"name\\\": \\\"schema\\\", \\\"version\\\": \\\"0.7.5\\\"}, {\\\"name\\\": \\\"setuptools\\\", \\\"version\\\": \\\"68.0.0\\\"}, {\\\"name\\\": \\\"six\\\", \\\"version\\\": \\\"1.16.0\\\"}, {\\\"name\\\": \\\"tqdm\\\", \\\"version\\\": \\\"4.65.0\\\"}, {\\\"name\\\": \\\"urllib3\\\", \\\"version\\\": \\\"1.26.16\\\"}, {\\\"name\\\": \\\"websocket-client\\\", \\\"version\\\": \\\"1.6.1\\\"}, {\\\"name\\\": \\\"windows-curses\\\", \\\"version\\\": \\\"2.3.1\\\"}]\\r\\n\",\"result\":\"[{\\\"name\\\": \\\"bitstring\\\", \\\"version\\\": \\\"4.0.2\\\"}, {\\\"name\\\": \\\"CacheControl\\\", \\\"version\\\": \\\"0.13.1\\\"}, {\\\"name\\\": \\\"certifi\\\", \\\"version\\\": \\\"2023.5.7\\\"}, {\\\"name\\\": \\\"cffi\\\", \\\"version\\\": \\\"1.15.1\\\"}, {\\\"name\\\": \\\"charset-normalizer\\\", \\\"version\\\": \\\"3.1.0\\\"}, {\\\"name\\\": \\\"click\\\", \\\"version\\\": \\\"8.0.4\\\"}, {\\\"name\\\": \\\"colorama\\\", \\\"version\\\": \\\"0.4.6\\\"}, {\\\"name\\\": \\\"construct\\\", \\\"version\\\": \\\"2.10.68\\\"}, {\\\"name\\\": \\\"contextlib2\\\", \\\"version\\\": \\\"21.6.0\\\"}, {\\\"name\\\": \\\"cryptography\\\", \\\"version\\\": \\\"36.0.2\\\"}, {\\\"name\\\": \\\"ecdsa\\\", \\\"version\\\": \\\"0.18.0\\\"}, {\\\"name\\\": \\\"esp-coredump\\\", \\\"version\\\": \\\"1.5.0\\\"}, {\\\"name\\\": \\\"esp-debug-backend\\\", \\\"version\\\": \\\"1.0.3\\\"}, {\\\"name\\\": \\\"esptool\\\", \\\"version\\\": \\\"4.5.1\\\"}, {\\\"name\\\": \\\"filelock\\\", \\\"version\\\": \\\"3.12.2\\\"}, {\\\"name\\\": \\\"freertos-gdb\\\", \\\"version\\\": \\\"1.0.2\\\"}, {\\\"name\\\": \\\"future\\\", \\\"version\\\": \\\"0.18.2\\\"}, {\\\"name\\\": \\\"gcovr\\\", \\\"version\\\": \\\"6.0\\\"}, {\\\"name\\\": \\\"idf-component-manager\\\", \\\"version\\\": \\\"1.2.3\\\"}, {\\\"name\\\": \\\"idna\\\", \\\"version\\\": \\\"3.4\\\"}, {\\\"name\\\": \\\"Jinja2\\\", \\\"version\\\": \\\"3.0.3\\\"}, {\\\"name\\\": \\\"kconfiglib\\\", \\\"version\\\": \\\"14.1.0\\\"}, {\\\"name\\\": \\\"lxml\\\", \\\"version\\\": \\\"4.9.2\\\"}, {\\\"name\\\": \\\"MarkupSafe\\\", \\\"version\\\": \\\"2.1.3\\\"}, {\\\"name\\\": \\\"msgpack\\\", \\\"version\\\": \\\"1.0.5\\\"}, {\\\"name\\\": \\\"packaging\\\", \\\"version\\\": \\\"23.1\\\"}, {\\\"name\\\": \\\"pip\\\", \\\"version\\\": \\\"23.1.2\\\"}, {\\\"name\\\": \\\"pycparser\\\", \\\"version\\\": \\\"2.21\\\"}, {\\\"name\\\": \\\"pyelftools\\\", \\\"version\\\": \\\"0.27\\\"}, {\\\"name\\\": \\\"pygdbmi\\\", \\\"version\\\": \\\"0.9.0.2\\\"}, {\\\"name\\\": \\\"Pygments\\\", \\\"version\\\": \\\"2.15.1\\\"}, {\\\"name\\\": \\\"pyparsing\\\", \\\"version\\\": \\\"3.0.9\\\"}, {\\\"name\\\": \\\"pyserial\\\", \\\"version\\\": \\\"3.5\\\"}, {\\\"name\\\": \\\"pywin32\\\", \\\"version\\\": \\\"306\\\"}, {\\\"name\\\": \\\"PyYAML\\\", \\\"version\\\": \\\"6.0\\\"}, {\\\"name\\\": \\\"reedsolo\\\", \\\"version\\\": \\\"1.6.0\\\"}, {\\\"name\\\": \\\"requests\\\", \\\"version\\\": \\\"2.31.0\\\"}, {\\\"name\\\": \\\"requests-file\\\", \\\"version\\\": \\\"1.5.1\\\"}, {\\\"name\\\": \\\"requests-toolbelt\\\", \\\"version\\\": \\\"1.0.0\\\"}, {\\\"name\\\": \\\"schema\\\", \\\"version\\\": \\\"0.7.5\\\"}, {\\\"name\\\": \\\"setuptools\\\", \\\"version\\\": \\\"68.0.0\\\"}, {\\\"name\\\": \\\"six\\\", \\\"version\\\": \\\"1.16.0\\\"}, {\\\"name\\\": \\\"tqdm\\\", \\\"version\\\": \\\"4.65.0\\\"}, {\\\"name\\\": \\\"urllib3\\\", \\\"version\\\": \\\"1.26.16\\\"}, {\\\"name\\\": \\\"websocket-client\\\", \\\"version\\\": \\\"1.6.1\\\"}, {\\\"name\\\": \\\"windows-curses\\\", \\\"version\\\": \\\"2.3.1\\\"}]\\r\\n\"},\"pythonVersion\":{\"output\":\"Python 3.11.2\\r\\n\",\"result\":\"3.11.2\"},\"systemInfo\":{\"architecture\":\"x64\",\"envPath\":\"C:\\\\WINDOWS;C:\\\\WINDOWS\\\\system32;C:\\\\WINDOWS\\\\System32\\\\Wbem;C:\\\\WINDOWS\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\;C:\\\\WINDOWS\\\\System32\\\\OpenSSH\\\\;C:\\\\Program Files\\\\dotnet\\\\;C:\\\\Program Files\\\\Git\\\\cmd;C:\\\\Program Files\\\\LINQPad7;C:\\\\Program Files\\\\LLVM\\\\bin;C:\\\\Program Files\\\\Microsoft\\\\jdk-11.0.16.101-hotspot\\\\bin;C:\\\\Program Files\\\\Microsoft SQL Server\\\\160\\\\Tools\\\\Binn\\\\;C:\\\\Program Files\\\\Microsoft SQL Server\\\\Client SDK\\\\ODBC\\\\170\\\\Tools\\\\Binn\\\\;C:\\\\Program Files\\\\Microsoft SQL Server\\\\160\\\\DTS\\\\Binn\\\\;C:\\\\Program Files\\\\PowerShell\\\\7\\\\;C:\\\\Program Files\\\\xmake;C:\\\\Program Files (x86)\\\\Microsoft SQL Server\\\\160\\\\Tools\\\\Binn\\\\;C:\\\\Program Files (x86)\\\\VMware\\\\VMware Workstation\\\\bin\\\\;C:\\\\Program Files\\\\Microsoft SQL Server\\\\Client SDK\\\\O;C:<HOMEPATH>\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python311\\\\;C:<HOMEPATH>\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python311\\\\Scripts\\\\;C:<HOMEPATH>\\\\esp\\\\tools\\\\cmake\\\\3.24.0\\\\bin;C:<HOMEPATH>\\\\esp\\\\tools\\\\ninja\\\\1.10.2\\\\\",\"extensionVersion\":\"1.6.3\",\"language\":\"zh-cn\",\"shell\":\"C:\\\\Program Files\\\\PowerShell\\\\7\\\\pwsh.exe\",\"platform\":\"win32\",\"systemName\":\"10.0.22621\",\"vscodeVersion\":\"1.73.1\"},\"workspaceFolder\":\"c:<HOMEPATH>\\\\MyWork\\\\ESP_C6\\\\hello_world\",\"projectConfigurations\":{}}","timestamp":"2023-07-03T06:56:17.576Z"}

### Description

我希望把实例程序烧录到ESP32-DevKitC开发板中，但是打不开OpenOCD Server。我希望OpenOCD Server正常打开。

### Debug Message

```plain
c:\Users\TangTao\esp\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin\openocd.exe


[OpenOCD]
Open On-Chip Debugger v0.11.0-esp32-20221026 (2022-10-26-14:48)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html

[OpenOCD]
debug_level: 2


[OpenOCD]
adapter speed: 20000 kHz


[OpenOCD]
Info : Listening on port 6666 for tcl connections

[OpenOCD]
Info : Listening on port 4444 for telnet connections

[OpenOCD]
❌ Error: no device found
Error: unable to open f
[OpenOCD]
tdi device with vid 0403, pid 6010, description '*', serial '*' at bus location '*'

[OpenOCD]
❌ Error: no device found
Error: unable to
[OpenOCD]
 open ftdi device with vid 0403, pid 6014, description '*', serial '*' at bus location '*'

[OpenOCD]


[OpenOCD]
[Stopped] : OpenOCD Server
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Have you configured the openOCD config files ? Your doctor command output is incomplete.

Check the `ESP-IDF: Select OpenOCD Board Configuration` command and choose your board. Make sure the connection to your device is correct.

**Comment by woshiwstt50123** [comment]
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/36841937/1a2a1f7c-9b78-490d-a6d9-b84983161689)
这个是我能选择的所有选项，目前我选择的是“esp32 chip(via ESP USB bridge)”。从电脑的设备管理器上可以看到esp32确实已经连接到电脑上了，对应的端口是Silicon Labs CP210x USB to UART Bridge。

**Comment by brianignacio5** [comment]
The devkitC doesn't have  USB-to-JTAG bridge. You need and external JTAG as described in [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/configure-other-jtag.html)

You can also check the [openOCD troubleshooting page](https://github.com/espressif/openocd-esp32/wiki/Troubleshooting-FAQ)

**Comment by woshiwstt50123** [comment]
CMSIS-DAP可以代替external JTAG吗

**Comment by woshiwstt50123** [comment]
这个问题已经解决了。一般的jtag仿真器好像确实有问题，需要新的仿真器。
