### ISSUE TITLE
"Add vscode configuration folder" uses absolute path instead of ${config:idf.toolsPath} for compilerPath (VSC-1156)

### ISSUE THREAD

**Issue by DanTup** [espressif/vscode-esp-idf-extension#1010]
### OS

MacOS

### Operating System version

Ventura 13.4.1

### Visual Studio Code version

1.80.1

### ESP-IDF version

5.1

### Python version

3.9.6

### Doctor command output

No idea.. when I run the command I see a notification saying it's preparing something, then it vanishes and there is no obvious output added anywhere (no new open files, nothing in Output, Debug Console or Terminal).

### Description

When I run the **ESP-IDF: Add vscode configuration folder** it always adds the following in `.vscode/c_cpp_properties.json`:

```
"compilerPath": "/Users/danny/Dev/Microcontrollers/ESP/Tools/tools/riscv32-esp-elf/esp-12.2.0_20230208/riscv32-esp-elf/bin/riscv32-esp-elf-gcc",
```

This absolute path causes issues if this file is committing to source control (which I want to do because I had to customise it to add `"forcedInclude": [ "${workspaceFolder}/build/config/sdkconfig.h" ]` to prevent some squiggles in the editor).

I can change it to:

```
"compilerPath": "${config:idf.toolsPath}/tools/riscv32-esp-elf/esp-12.2.0_20230208/riscv32-esp-elf/bin/riscv32-esp-elf-gcc",
```

And this works fine. So I think it would be better if the generated path used `${config:idf.toolsPath}` rather than a full absolute path.

### Debug Message

```plain
N/A
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by radurentea** [comment]
Hi @DanTup,

I've made the modifications you've requested. Could you try this version and see if it satisfies your request? [esp-idf-extension.vsix.zip](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/812811539.zip)

In regards to Doctor command, it copies the output to your clipboard. So you have to open a file and use CMD + V to paste it.
