### ISSUE TITLE
ERROR: ./bin/python doesn't exist

### ISSUE THREAD

**Issue by daniel-frenkel** [espressif/vscode-esp-idf-extension#1036]
### OS

Linux

### Operating System version

Ubuntu 22.04.3 LTS

### Visual Studio Code version

1.81.1

### ESP-IDF version

5.1.1

### Python version

3.10

### Doctor command output

N/A. Doctor does not work.

### Description

When using the VS Code plugin to run ESP-IDF SDK Configuration Editor (menuconfig), the extension is looking in the wrong Python folder even though the correct location was specified during installation.

This is only an issue in VS Code and not when using the terminal. 

I have specified it to look in the python_env folder during installation.

### Debug Message

```plain
ERROR: ./bin/python doesn't exist! Please run the install script or "idf_tools.py install-python-env" in order to create it
```

### Other Steps to Reproduce

I have deleted the extension as well as the python_env folder. I then ran ./install.sh and created a new environment folder.

Then I installed the VS Code plugin and directed it to the folder. This still did not fix it.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Erhannis** [comment]
@daniel-frenkel What did the problem turn out to be?  I'm getting this, too.

**Comment by daniel-frenkel** [comment]
@Erhannis it's been a while, but I believe that I went into the ESP-IDF extension settings and manually set the path to the right directory
