### ISSUE TITLE
ESP-IDF 5.1.1 with VSCODE problem show examples (IDFGH-11097) (VSC-1189)

### ISSUE THREAD

**Issue by filzek** [espressif/vscode-esp-idf-extension#1042]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

release 5.1.1

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

ESP-IDF 5.1.1 with VSCODE problem show examples, vscode says: "ESP-IDF: Loading Examples"   forever and does nothing.

### What is the actual behavior?

work and show examples

### Steps to reproduce.

install latest VSCODE and install ESPRESSIF extension. Setup express 5.1.1 release, after finish try to ES-IDF examples show.

Doest nothing.

**Comment by brianignacio5** [comment]
Based on the video this is not an error. You just didn't choose the ESP-IDF framework on the selection. You can configure multiple frameworks and see examples of each based on the documentation.
