### ISSUE TITLE
Configure ESP-IDF extension fails at the stage of downloading tools at Python 3.8 (VSC-329)

### ISSUE THREAD

**Issue by an-dr** [espressif/vscode-esp-idf-extension#105]
**Describe the bug**
Hi guys! I'm preparing a debugging training right now and experimenting with the clean installation of the extension.

I've faced with the bug breaking the configuration process with the Python 3.8.2 (Python 2 works).

**To Reproduce**
- Create a new project
- Call >ESP-IDF: Configure ESP-IDF extension
- At the step of downloading tools you'll get the error

**Expected behavior**
Installing of the tools and appearing of the button "Next"

**Screenshots**
![Screenshot from 2020-05-18 13-42-31](https://user-images.githubusercontent.com/4987803/82209424-8a2c3900-990d-11ea-8c78-a0c78c4b2873.png)

**Environment (please complete the following information):**

- OS Name & Version: Ubuntu 20.04
- VSCode Version: 1.45.1
- ESP-IDF Version: 4.2
- Python Version: 3.8.2

**Logs**
[esp-idf_output_panel.log](https://github.com/espressif/vscode-esp-idf-extension/files/4643907/esp-idf_output_panel.log)
[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/4643908/esp_idf_vsc_ext.log)

**Comment by brianignacio5** [comment]
You are missing the python package `bdist_wheel` which is not part of IDF_PATH/requirements.txt or $EXTENSION_DIR/esp_debug_adapter/requirements.txt.

Should we add it to DAP requirements.txt or specify it is needed in the docs?

**Comment by an-dr** [comment]
@brianignacio5 `bdist_wheel` is not a standalone package. As I understand, it is a part of either wheel or setuptools. Anyway, I have installed both.
Investigating further

**Comment by brianignacio5** [comment]
`pip install --upgrade pip` wheel and `pip3 install --upgrade pip wheel` before configure esp-idf extension ?

**Comment by ebabcock72** [comment]
I am having the exact same issue. Your suggested "--upgrade" commands did not work for me.
