### ISSUE TITLE
No warning when configuring extension on Linux and venv package not installed (VSC-1205)

### ISSUE THREAD

**Issue by zikalino** [espressif/vscode-esp-idf-extension#1061]
### OS

Linux

### Operating System version

Ubuntu / WSL

### ESP-IDF version

5.2

### Python version

3.8

### Doctor command output

not applicable

### Description

When configuring extension on new setup of Ubuntu on WSL, it's necessary to install:

    sudo apt-get update
    sudo apt install python3-pip
    sudo apt install python3-venv

If these are not installed, extension will display a warning:

**"/usr/bin/python3 -m pip" is not valid (ERROR_INVALID_PIP)**

However it doesn't complain about missing **venv** up front. Instead it fails at the very end of the configuration process.

It would be nice if there was similar warning up front.

Note that if the users install **venv** after failure, and retry the process, they will encounter another issue:

**/home/zim/esp/esp-idf already exists. Delete it or use another location. (ERROR_EXISTING_ESP_IDF)**

and will have to manually delete the repo in order to restart.

### Debug Message

```plain
not applicable
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by radurentea** [comment]
Hi @zikalino,

It's a good idea, currently is covered in both the extension documentation and on IDF documentation, but a message during setup for linux users could definitely help the new users.
