### ISSUE TITLE
Configure IDF Extension - Advanced option is a bit confusing (VSC-1206)

### ISSUE THREAD

**Issue by zikalino** [espressif/vscode-esp-idf-extension#1062]
### OS

Windows

### Operating System version

Ubuntu / WSL

### ESP-IDF version

5.1

### Python version

3.8

### Doctor command output

not applicable

### Description

This is just my observation. I think the **Advanced** flow may be a bit confusing for users. I wanted to try **Advanced** mode after trying **Express** to see the difference.
When choosing **Advanced** I was initially taken to the same view as in case of **Express** option.
I saw exactly the same **Enter ESP-IDF Tools directory (IDF_TOOLS_PATH)** field, and then **Install** button.
At first I thought I pressed wrong button, then finally I tried **Install** button.

**Install** button indicate that there are no further options, so perhaps it should be replaced with **Configure Tools** in **Advanced** option? **Enter ESP-IDF Tools directory (IDF_TOOLS_PATH)** could be also placed in a second screen.

### Debug Message

```plain
not applicable
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Thanks for the feedback ! It is the same screen but we should display different text if it is advanced mode. Will update it soon
