### ISSUE TITLE
Debug adapter cli.py bug? (VSC-1208)

### ISSUE THREAD

**Issue by parfnick** [espressif/vscode-esp-idf-extension#1063]
### OS

Windows

### Operating System version

Windos 10

### ESP-IDF version

5.1.1

### Python version

3.11

### Doctor command output

empty

### Description

In cli.py script:

__def cli(ctx, **kwargs):
    args_main = DaArgs(**ctx.params)
    # Modificators
    if args_main.developer_mode == DaDevModes.X86:
        args_main.debug = 5
        args_main.log_file = "debug.log"
        args_main.oocd_mode = DaOpenOcdModes.NO_OOCD
        args_main.toolchain_prefix = ""
        args_main.elfpath = ""

    if args_main.developer_mode == DaDevModes.CON_CHECK:
        args_main.debug = 4
        args_main.port = 43474
        args_main.oocd_mode = DaOpenOcdModes.NO_OOCD
        args_main.toolchain_prefix = ""
        args_main.log_file = "debug.log"
    # Real work starts here
    
    dbg_a = DebugAdapter(args=args_main)
    dbg_a.log_cmd(A2VSC_STARTED_STRING)
    dbg_a.adapter_run()__

args_main.**toolchain_prefix** can be **None**. After it is used in split() function, ay-ay-ai ;)

### Debug Message

```plain
*  Executing task in folder balloon: C:/Espressif/python_env/idf5.1_py3.11_env/Scripts/python.exe c:\Users\parfn\.vscode\extensions\espressif.esp-idf-extension-1.6.5/esp_debug_adapter/debug_adapter_main.py -e D:\Projects\Devices\firmware\projects\esp32\vscode\balloon/build/balloon.elf -s C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20230419/openocd-esp32/share/openocd/scripts -ip localhost -dn custom -om connect_to_instance 

Traceback (most recent call last):
  File "c:\Users\parfn\.vscode\extensions\espressif.esp-idf-extension-1.6.5/esp_debug_adapter/debug_adapter_main.py", line 30, in <module>
    cli(sys.argv[1:])
  File "C:\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\parfn\.vscode\extensions\espressif.esp-idf-extension-1.6.5\esp_debug_adapter\debug_adapter\cli.py", line 146, in cli
    dbg_a = DebugAdapter(args=args_main)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\parfn\.vscode\extensions\espressif.esp-idf-extension-1.6.5\esp_debug_adapter\debug_adapter\debug_adapter.py", line 
87, in __init__
    _, self.target_triple = os.path.split(args.toolchain_prefix)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 213, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command C:/Espressif/python_env/idf5.1_py3.11_env/Scripts/python.exe c:\Users\parfn\.vscode\extensions\espressif.esp-idf-extension-1.6.5/esp_debug_adapter/debug_adapter_main.py -e D:\Projects\Devices\firmware\projects\esp32\vscode\balloon/build/balloon.elf -s C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20230419/openocd-esp32/share/openocd/scripts -ip localhost -dn custom -om connect_to_instance" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
I think the issue is that you are running the esp-idf debug adapter from tasks.json which is not the intended use of the debug adapter. The reason why is failing is because you didn't specify a proper IDF_TARGET (esp32, esp32s2, etc.) and the toolchain with `-t xtensa-esp32-elf-`. Since this `.vscode/tasks.json` file can be modified by the user at anytime it was not updated but will update with default target esp32 and default toolchain prefix.

Please refer to the debugging tutorial [here](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/debugging.md) for the typical use of debug adapter.
