### ISSUE TITLE
Error when building sdkconfig.defaults (VSC-1209)

### ISSUE THREAD

**Issue by modi12jin** [espressif/vscode-esp-idf-extension#1064]
### OS

Linux

### Operating System version

Ubuntu 22.04.2 LTS

### Visual Studio Code version

1.79.1

### ESP-IDF version

5.1

### Python version

3.10.12

### Doctor command output

Set default sdkconfig file in project

### Description

![截图 2023-10-20 15-35-22](https://github.com/espressif/vscode-esp-idf-extension/assets/40233017/1f43f8f4-b15e-4ff9-a06a-5a40fedc3474)

### Debug Message

```plain
none
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by radurentea** [comment]
Hi @modi12jin,

Thanks for the bug report. It seems the command has been removed from the source code and we should probably remove it from the list of commands. 

To create a default SDK config, you can use the following command **ESP-IDF: SDK Configuration editor (menuconfig)**
