### ISSUE TITLE
toolsPath problem with fresh installation (VSC-1221)

### ISSUE THREAD

**Issue by Shoyur** [espressif/vscode-esp-idf-extension#1073]
### OS

Windows

### Operating System version

windows 11

### Visual Studio Code version

1.84.1

### ESP-IDF version

5.1.1

### Python version

3.10.7

### Doctor command output

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.22621 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files\Common Files\Oracle\Java\javapath;C:\Python310\Scripts\;C:\Python310\;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\mingw64\x86_64-8.1.0-release-posix-seh-rt_v6-rev0\mingw64\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:<HOMEPATH>\AppData\Local\GitHubDesktop\bin;%USERPROFILE%\.dotnet\tools;C:<HOMEPATH>\AppData\Roaming\npm;C:\mingw64\x86_64-8.1.0-release-posix-seh-rt_v6-rev0\mingw64\bin;C:<HOMEPATH>\AppData\Local\Programs\Microsoft VS Code\bin;C:<HOMEPATH>\AppData\Local\Programs\jaguar; 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.84.1 
Visual Studio Code language en 
Visual Studio Code shell C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.6.5 
Workspace folder c:\PROG\esp-idf\ESP-IDF_projects\Nano-Lift 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) c:\PROG\esp-idf\ESP-IDF_container\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
Custom extra paths (idf.customExtraPaths) c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin;c:\PROG\esp-idf\ESP-IDF_tools\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin;c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin;c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp32s2-elf\esp-12.2.0_20230208\xtensa-esp32s2-elf\bin;c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp32s3-elf\esp-12.2.0_20230208\xtensa-esp32s3-elf\bin;c:\PROG\esp-idf\ESP-IDF_tools\tools\riscv32-esp-elf\esp-12.2.0_20230208\riscv32-esp-elf\bin;c:\PROG\esp-idf\ESP-IDF_tools\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;c:\PROG\esp-idf\ESP-IDF_tools\tools\cmake\3.24.0\bin;c:\PROG\esp-idf\ESP-IDF_tools\tools\openocd-esp32\v0.12.0-esp32-20230419\openocd-esp32\bin;c:\PROG\esp-idf\ESP-IDF_tools\tools\ninja\1.10.2;c:\PROG\esp-idf\ESP-IDF_tools\tools\idf-exe\1.0.3;c:\PROG\esp-idf\ESP-IDF_tools\tools\ccache\4.8\ccache-4.8-windows-x86_64;c:\PROG\esp-idf\ESP-IDF_tools\tools\dfu-util\0.11\dfu-util-0.11-win64;c:\PROG\esp-idf\ESP-IDF_tools\tools\esp-rom-elfs\20230320
Custom extra vars (idf.customExtraVars)
    OPENOCD_SCRIPTS: c:\PROG\esp-idf\ESP-IDF_tools\tools\openocd-esp32\v0.12.0-esp32-20230419/openocd-esp32/share/openocd/scripts
    IDF_CCACHE_ENABLE: 1
    ESP_ROM_ELF_DIR: c:\PROG\esp-idf\ESP-IDF_tools\tools\esp-rom-elfs\20230320/
Virtual env Python Path (idf.pythonBinPath) c:\PROG\esp-idf\ESP-IDF_tools\python_env\idf5.1_py3.11_env\Scripts\python.exe
Serial port (idf.port) COM8
OpenOCD Configs (idf.openOcdConfigs) board/esp32s3-bridge.cfg
ESP-IDF Tools Path (idf.toolsPath) c:\PROG\esp-idf\ESP-IDF_tools
Git Path (idf.gitPath) c:\PROG\esp-idf\ESP-IDF_tools\tools\idf-git\2.39.2\cmd\git.exe
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-IDF Custom extra paths
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp32s2-elf\esp-12.2.0_20230208\xtensa-esp32s2-elf\bin: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp32s3-elf\esp-12.2.0_20230208\xtensa-esp32s3-elf\bin: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\riscv32-esp-elf\esp-12.2.0_20230208\riscv32-esp-elf\bin: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\cmake\3.24.0\bin: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\openocd-esp32\v0.12.0-esp32-20230419\openocd-esp32\bin: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\ninja\1.10.2: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\idf-exe\1.0.3: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\ccache\4.8\ccache-4.8-windows-x86_64: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\dfu-util\0.11\dfu-util-0.11-win64: true
Access to c:\PROG\esp-idf\ESP-IDF_tools\tools\esp-rom-elfs\20230320: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path true
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp32s2-elf\esp-12.2.0_20230208\xtensa-esp32s2-elf\bin: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\xtensa-esp32s3-elf\esp-12.2.0_20230208\xtensa-esp32s3-elf\bin: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\riscv32-esp-elf\esp-12.2.0_20230208\riscv32-esp-elf\bin: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\cmake\3.24.0\bin: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\openocd-esp32\v0.12.0-esp32-20230419\openocd-esp32\bin: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\ninja\1.10.2: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\idf-exe\1.0.3: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\ccache\4.8\ccache-4.8-windows-x86_64: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\dfu-util\0.11\dfu-util-0.11-win64: false
Spaces in c:\PROG\esp-idf\ESP-IDF_tools\tools\esp-rom-elfs\20230320: false
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.39.2.windows.1
ESP-IDF version 5.1.1
Python version 3.11.2
Python's pip version 23.3.1
-------------------------------------------------- Project configuration settings ----------------------------------------------------------
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitarray version: 2.8.2
bitstring version: 4.1.2
CacheControl version: 0.13.1
certifi version: 2023.7.22
cffi version: 1.16.0
charset-normalizer version: 3.3.2
click version: 8.0.4
colorama version: 0.4.6
construct version: 2.10.69
contextlib2 version: 21.6.0
cryptography version: 39.0.2
ecdsa version: 0.18.0
esp-coredump version: 1.7.0
esp-debug-backend version: 1.0.3
esp-idf-kconfig version: 1.4.0
esp-idf-monitor version: 1.3.3
esp-idf-panic-decoder version: 0.2.0
esp-idf-size version: 0.4.3
esptool version: 4.7.dev2
filelock version: 3.13.1
freertos-gdb version: 1.0.2
gcovr version: 6.0
idf-component-manager version: 1.4.1
idna version: 3.4
Jinja2 version: 3.0.3
kconfiglib version: 14.1.0
lxml version: 4.9.3
MarkupSafe version: 2.1.3
msgpack version: 1.0.7
packaging version: 23.2
pip version: 23.3.1
pycparser version: 2.21
pyelftools version: 0.29
pygdbmi version: 0.9.0.2
Pygments version: 2.16.1
pyparsing version: 3.0.9
pyserial version: 3.5
pywin32 version: 306
PyYAML version: 6.0.1
reedsolo version: 1.7.0
requests version: 2.31.0
requests-file version: 1.5.1
requests-toolbelt version: 1.0.0
schema version: 0.7.5
setuptools version: 68.2.2
six version: 1.16.0
tqdm version: 4.66.1
urllib3 version: 1.26.18
websocket-client version: 1.6.4
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "${config:idf.toolsPath}\\tools\\xtensa-esp32-elf\\esp-12.2.0_20230208\\xtensa-esp32-elf\\bin\\xtensa-esp32-elf-gcc.exe",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
 
--------------------------------------------------------------------------------------------------------------------------------------------

### Description

esp32.com never loads...

I used platform.io in the past but i wanted to go straight esp-idf framework this time.

First project, i notice :
portTICK_PERIOD_MS 
error
(identifier "CONFIG_FREERTOS_HZ" is undefinedC/C++(20))
and then
[11/9/2023, 1:39:54 PM] Unable to resolve configuration with compilerPath "${env:IDF_TOOLS_PATH}\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe".  Using "C:\mingw64\x86_64-8.1.0-release-posix-seh-rt_v6-rev0\mingw64\bin\gcc.exe" instead.
in output pane
and now i see in
c_cpp_properties.json
"compilerPath": "${config:idf.toolsPath}\\tools\\xtensa-esp32-elf\\esp-12.2.0_20230208\\xtensa-esp32-elf\\bin\\xtensa-esp32-elf-gcc.exe",
in yellow
and hovering it says
Cannot find "c:\PROG\esp-idf\ESP-IDF_projects\Nano-Lift\${env:IDF_TOOLS_PATH}\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe".
Like it added
c:\PROG\esp-idf\ESP-IDF_projects\Nano-Lift\
in front so ofc its an error, but why it does that
cause settings.json has
"idf.toolsPathWin": "c:\\PROG\\esp-idf\\ESP-IDF_tools"

merry thank you.

EDIT:
I can edit the compilerpath but if i start a new project, same problem again.
And whatever i search for, i dont know why i see the 
identifier "CONFIG_FREERTOS_HZ" is undefined
it seems weird to me (im not an expert),
but i can see links between all of them successfully
i mean :
portTICK_PERIOD_MS
>
#define portTICK_PERIOD_MS          ( ( TickType_t ) 1000 / configTICK_RATE_HZ )
in portmacro.h
>
#define configTICK_RATE_HZ                           CONFIG_FREERTOS_HZ
in FreeRTOSConfig.h

everything is present...

### Debug Message

```plain
[11/9/2023, 1:39:54 PM] Unable to resolve configuration with compilerPath "${env:IDF_TOOLS_PATH}\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe".  Using "C:\mingw64\x86_64-8.1.0-release-posix-seh-rt_v6-rev0\mingw64\bin\gcc.exe" instead.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Please check out the https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/C_CPP_CONFIGURATION.md

or just update this file and add :

`"compileCommands": "${workspaceFolder}/build/compile_commands.json"`
