### ISSUE TITLE
[Feature Request]: Add the "save configuration as default" button (VSC-1254)

### ISSUE THREAD

**Issue by boris-gu** [espressif/vscode-esp-idf-extension#1090]
**Is your feature request related to a problem? Please describe.**
I have only recently started using ESP-IDF and it is still difficult for me to remember the commands in the terminal for some actions. What I have already encountered is the command `idf.py save-defconfig`

**Describe the solution you'd like**
Add a button for this action when you right-click on the sdkconfig file

**Describe alternatives you've considered**
Add an action when pressing the F1 button

**Additional context**
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/44787162/3df6f3a9-486f-4830-92db-da3faa56bbb5)

**Comment by brianignacio5** [comment]
Thank you for the feature request @boris-gu , sound like a nice idea! Will cook a PR very soon
