### ISSUE TITLE
Cannot run OpenOCD with v0.1.2 (VSC-200)

### ISSUE THREAD

**Issue by jankrejci** [espressif/vscode-esp-idf-extension#11]
It is not possible to start an OpenOCD debugger from the task or via the status bar button. It was working in the previous version.

When I press the status bar button, the following error is raised
```
this.openOcdConfigFilesList.forEach is not a function
```
If a try to start the OpenOCD task, this error is raised
```
'${config:idf.openOcdScriptsPathWin}'
can not be resolved because setting
'idf.openOcdScriptsPathWin' not found.
```
Obviously, there are missing configure variables and probably something else
```
config:idf.openOcdBin
config:idf.openOcdScriptsPath
command:espIdf.getOpenOcdConfigs
```

Windows 10, VSCode 1.41.1, ESP Extension 0.1.2, ESP-IDF Version 4, Python 3.7.3

**Comment by brianignacio5** [comment]
Thanks for the issue. Will fix on v0.1.3 !
