### ISSUE TITLE
Add "preferred build folder"/config to c_cpp_properties.json (VSC-1266)

### ISSUE THREAD

**Issue by ziidonato** [espressif/vscode-esp-idf-extension#1104]
**Is your feature request related to a problem? Please describe.**
Every time I create a project, I have to manually add the configuration folder to c_cpp_properties.json. I understand that it's not generated until the first build, and I understand that the destination is configurable, but from what I've read, you can easily access the workspace configuration in vscode extensions, and building the project is as easy as "idf.py build" with some environment variables.

**Describe the solution you'd like**
Generate sdkconfig.h when the project is created, and add it to c_cpp_properties.json

**Describe alternatives you've considered**
Manually adding it -  this is a request to implement a feature so I don't have to do this anymore

**Comment by brianignacio5** [comment]
We updated the template c_cpp_properties.json to use compile_commands.json by default.
