### ISSUE TITLE
[Feature Request]: Stop using VS Code pop-up notification for builds, flashing project messages. (VSC-1272)

### ISSUE THREAD

**Issue by Seefer** [espressif/vscode-esp-idf-extension#1114]
This window pop-up obscures the terminal window output when I click on build or flash etc. I feel the proper place for messages of this nature should be sent to the terminal output windows instead of the GUI-based VS Code notification pop-up.

**Comment by brianignacio5** [comment]
With the PR https://github.com/espressif/vscode-esp-idf-extension/pull/1087 you can define how notifications are handle by this extension by using a `ESP-IDF: Select output and notification mode` command which allows to define a `idf.notificationMode` configuration setting to:

1) Show task output and notifications
2) Show only task output
3) Show only notification
4) Show nothing

**Comment by brianignacio5** [comment]
Does it happen when there is no errors or only when errors appear @txf- ?

**Comment by Seefer** [comment]
It happens when simply building or flashing a project. The pop-up notification window seems redundant considering there's build and flash progress information being shown in the terminal window. I feel such messages are best output to the Terminal window and the notification windows is best used for situations where a problem has occurred, and user response is required.

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/129484/1682fa0d-31ab-48c0-b3ca-29550b311a59)

**Comment by txf-** [comment]
> Does it happen when there is no errors or only when errors appear @txf- ?

It happens on success as well as failure.

**Comment by brianignacio5** [comment]
> It happens when simply building or flashing a project. The pop-up notification window seems redundant considering there's build and flash progress information being shown in the terminal window. I feel such messages are best output to the Terminal window and the notification windows is best used for situations where a problem has occurred, and user response is required.
> 
> ![image](https://private-user-images.githubusercontent.com/129484/298080027-1682fa0d-31ab-48c0-b3ca-29550b311a59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODE1MTcsIm5iZiI6MTcwNTk4MTIxNywicGF0aCI6Ii8xMjk0ODQvMjk4MDgwMDI3LTE2ODJmYTBkLTMxYWItNDhjMC1iM2NhLTI5NTUwYjMxMWE1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwMzQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTgzZTc0NTQxMmQ3ZWU1ODhjZTg4MGI2ZjBjMmVkM2ZiZDg2ZjczMzE3ODEyZTc3OWEwOTYyZTk5NmVhODBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kW7N53pTGnEFgr1SSFJH93YIiLD-pFKQRBIQ2KKrn0A)

As I mentioned before, you can disable this pop-ups if you want with the mentioned command or configuration setting.

**Comment by brianignacio5** [comment]
I've added the PR https://github.com/espressif/vscode-esp-idf-extension/pull/1118 to hide the progress notification based on `idf.notificationMode`. With this PR, Progress notification should be disabled when `idf.notificationMode` is different than `All` or `Notification`
