### ISSUE TITLE
Installation instructons no longer work for visual studio - no such extension (VSC-1273)

### ISSUE THREAD

**Issue by RiverExplorer** [espressif/vscode-esp-idf-extension#1115]
### OS

Windows

### Operating System version

Windo2s 10

### Visual Studio Code version

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.8.5

### ESP-IDF version

no clue, it will not install

### Python version

NA

### Doctor command output

Step 4 in the installation says to search for "ESP-IDF Extension". No such extension shows up.

### Description

Step 4 in the installation says to search for "ESP-IDF Extension". No such extension shows up.

### Debug Message

```plain
Step 4 in the installation says to search for "ESP-IDF Extension". No such extension shows up.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
This extension is for Visual Studio Code not Visual Studio.

Apologies for the confusion.
