### ISSUE TITLE
Clicking the info icon in menuconfig does not display detailed information (VSC-1279)

### ISSUE THREAD

**Issue by zys91** [espressif/vscode-esp-idf-extension#1121]
### OS

Windows

### Operating System version

Windows 11

### Visual Studio Code version

1.85.2

### ESP-IDF version

4.4.6

### Python version

3.8.7

### Doctor command output

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.22631 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\dotnet\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\NetSarang\Xftp 7\;C:\Program Files (x86)\NetSarang\Xshell 7\;C:\Program Files\Git\cmd;E:\ZYS\工具\ping-tools;E:\ZYS\工具\ESP-TOOLS;C:\Program Files\mingw64\bin\;C:\Program Files\CMake\bin\;D:\Android\Sdk\platform-tools;C:\Program Files\dotnet\;D:\Program Files\MATLAB\R2022b\runtime\win64;D:\Program Files\MATLAB\R2022b\bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk-17\bin;C:<HOMEPATH>\AppData\Local\Programs\Python\Python38\Scripts\;C:<HOMEPATH>\AppData\Local\Programs\Python\Python38\;C:<HOMEPATH>\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Fiddler;C:<HOMEPATH>\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandi\Bandizip;C:\Program Files\Bandizip\;C:<HOMEPATH>\.dotnet\tools;C:<HOMEPATH>\AppData\Roaming\npm 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.85.2 
Visual Studio Code language zh-cn 
Visual Studio Code shell C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.7.0 
Workspace folder d:\Program\Espressif\esp-idf\examples\wifi\iperf 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) d:\Program\Espressif\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
Custom extra paths (idf.customExtraPaths) d:\Program\Espressif\tools\xtensa-esp-elf-gdb\11.2_20220823\xtensa-esp-elf-gdb\bin;d:\Program\Espressif\tools\riscv32-esp-elf-gdb\11.2_20220823\riscv32-esp-elf-gdb\bin;d:\Program\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\bin;d:\Program\Espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s2-elf\bin;d:\Program\Espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s3-elf\bin;d:\Program\Espressif\tools\riscv32-esp-elf\esp-2021r2-patch5-8.4.0\riscv32-esp-elf\bin;d:\Program\Espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;d:\Program\Espressif\tools\cmake\3.23.1\bin;d:\Program\Espressif\tools\openocd-esp32\v0.12.0-esp32-20230419\openocd-esp32\bin;d:\Program\Espressif\tools\ninja\1.10.2;d:\Program\Espressif\tools\idf-exe\1.0.3;d:\Program\Espressif\tools\ccache\4.3\ccache-4.3-windows-64;d:\Program\Espressif\tools\dfu-util\0.9\dfu-util-0.9-win64
Custom extra vars (idf.customExtraVars)
    OPENOCD_SCRIPTS: d:\Program\Espressif\tools\openocd-esp32\v0.12.0-esp32-20230419/openocd-esp32/share/openocd/scripts
    IDF_CCACHE_ENABLE: 1
Virtual env Python Path (idf.pythonBinPath) d:\Program\Espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe
Serial port (idf.port) COM6
OpenOCD Configs (idf.openOcdConfigs) board/esp32c3-ftdi.cfg
ESP-IDF Tools Path (idf.toolsPath) d:\Program\Espressif
Git Path (idf.gitPath) d:\Program\Espressif\tools\idf-git\2.39.2\cmd\git.exe
Notification Mode (idf.notificationMode) All
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-IDF Custom extra paths
Access to d:\Program\Espressif\tools\xtensa-esp-elf-gdb\11.2_20220823\xtensa-esp-elf-gdb\bin: true
Access to d:\Program\Espressif\tools\riscv32-esp-elf-gdb\11.2_20220823\riscv32-esp-elf-gdb\bin: true
Access to d:\Program\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\bin: true
Access to d:\Program\Espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s2-elf\bin: true
Access to d:\Program\Espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s3-elf\bin: true
Access to d:\Program\Espressif\tools\riscv32-esp-elf\esp-2021r2-patch5-8.4.0\riscv32-esp-elf\bin: true
Access to d:\Program\Espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: true
Access to d:\Program\Espressif\tools\cmake\3.23.1\bin: true
Access to d:\Program\Espressif\tools\openocd-esp32\v0.12.0-esp32-20230419\openocd-esp32\bin: true
Access to d:\Program\Espressif\tools\ninja\1.10.2: true
Access to d:\Program\Espressif\tools\idf-exe\1.0.3: true
Access to d:\Program\Espressif\tools\ccache\4.3\ccache-4.3-windows-64: true
Access to d:\Program\Espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path true
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in d:\Program\Espressif\tools\xtensa-esp-elf-gdb\11.2_20220823\xtensa-esp-elf-gdb\bin: false
Spaces in d:\Program\Espressif\tools\riscv32-esp-elf-gdb\11.2_20220823\riscv32-esp-elf-gdb\bin: false
Spaces in d:\Program\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\bin: false
Spaces in d:\Program\Espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s2-elf\bin: false
Spaces in d:\Program\Espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32s3-elf\bin: false
Spaces in d:\Program\Espressif\tools\riscv32-esp-elf\esp-2021r2-patch5-8.4.0\riscv32-esp-elf\bin: false
Spaces in d:\Program\Espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: false
Spaces in d:\Program\Espressif\tools\cmake\3.23.1\bin: false
Spaces in d:\Program\Espressif\tools\openocd-esp32\v0.12.0-esp32-20230419\openocd-esp32\bin: false
Spaces in d:\Program\Espressif\tools\ninja\1.10.2: false
Spaces in d:\Program\Espressif\tools\idf-exe\1.0.3: false
Spaces in d:\Program\Espressif\tools\ccache\4.3\ccache-4.3-windows-64: false
Spaces in d:\Program\Espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: false
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.39.2.windows.1
ESP-IDF version 4.4.6
Python version 3.8.7
Python's pip version 20.3.3
-------------------------------------------------- Project configuration settings ----------------------------------------------------------
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 3.1.9
Brotli version: 1.1.0
cachecontrol version: 0.13.1
certifi version: 2023.11.17
cffi version: 1.16.0
charset-normalizer version: 3.3.2
click version: 8.0.4
colorama version: 0.4.6
construct version: 2.10.54
contextlib2 version: 21.6.0
cryptography version: 41.0.5
ecdsa version: 0.18.0
esp-debug-backend version: 1.0.3
esp-windows-curses version: 0.1
filelock version: 3.13.1
Flask version: 0.12.5
Flask-Compress version: 1.14
Flask-SocketIO version: 2.9.6
future version: 0.18.3
gcovr version: 6.0
gdbgui version: 0.13.2.0
gevent version: 1.5.0
greenlet version: 3.0.1
idf-component-manager version: 1.4.1
idna version: 3.4
itsdangerous version: 2.0.1
Jinja2 version: 3.0.3
kconfiglib version: 13.7.1
lxml version: 4.9.3
MarkupSafe version: 2.1.3
msgpack version: 1.0.7
packaging version: 23.2
pip version: 20.3.3
pycparser version: 2.21
pyelftools version: 0.30
pygdbmi version: 0.9.0.2
pygments version: 2.17.2
pyparsing version: 2.3.1
pyserial version: 3.5
python-engineio version: 3.14.2
python-socketio version: 4.6.1
pywin32 version: 306
PyYAML version: 6.0.1
reedsolo version: 1.5.4
requests version: 2.31.0
requests-file version: 1.5.1
requests-toolbelt version: 1.0.0
schema version: 0.7.5
setuptools version: 69.0.3
six version: 1.16.0
tqdm version: 4.66.1
urllib3 version: 1.26.18
websocket-client version: 1.6.4
Werkzeug version: 0.16.1
wheel version: 0.36.2
windows-curses version: 2.3.2
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements from d:\Program\Espressif\esp-idf\requirements.txt are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements from c:<HOMEPATH>\.vscode\extensions\espressif.esp-idf-extension-1.7.0\esp_debug_adapter\requirements.txt are satisfied.
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at Unknown error in ESP-IDF Doctor Command
--------------------------------------------------------------------------------------------------------------------------------------------

### Description

Open SDK Configuration Editor（menuconfig），click info icon in the upper right corner of the entry does not display detailed information，plugin version 1.6.5 is ok，update to 1.7.0 occurs this bug

### Debug Message

```plain
None
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Hi @zys91 thanks for reporting this. Made a fix in this PR https://github.com/espressif/vscode-esp-idf-extension/pull/1123

Please take a look if you can.

**Comment by zys91** [comment]
All right, everything seems to be back to normal, thank you

**Comment by brianignacio5** [comment]
If you find the extension useful. Please leave us a review in the [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension)
