### ISSUE TITLE
Setting target for ESP32-C3 fails (VSC-1281)

### ISSUE THREAD

**Issue by myles-parfeniuk** [espressif/vscode-esp-idf-extension#1124]
### OS

Windows

### Operating System version

Windows 10

### Visual Studio Code version

1.85.1

### ESP-IDF version

5.2.0

### Python version

3.11.5

### Doctor command output

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.19045 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:<HOMEPATH>\AppData\Local\Programs\Python\Python311;C:<HOMEPATH>\AppData\Local\Programs\Python\Python311\Scripts;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\MATLAB\R2023a\bin;C:\Program Files\Microchip\xc16\v2.10\bin;C:\Program Files\Microchip\xc32\v4.21\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:<HOMEPATH>\.cargo\bin;C:<HOMEPATH>\AppData\Local\Programs\Python\Python311;C:<HOMEPATH>\AppData\Local\Programs\Python\Python311\Scripts;C:<HOMEPATH>\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microchip\xc8\v2.41\bin;C:\ProgramData\myles\GitHubDesktop\bin;C:<HOMEPATH>\AppData\Local\Microsoft\WinGet\Packages\Helix.Helix_Microsoft.Winget.Source_8wekyb3d8bbwe\helix-23.05-x86_64-windows; 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.85.1 
Visual Studio Code language en 
Visual Studio Code shell C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.7.0 
Workspace folder d:\development\esp\projects\idf_5_2\c3_testing 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) C:<HOMEPATH>\esp\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
Custom extra paths (idf.customExtraPaths) C:\esp\tools\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin;C:\esp\tools\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin;C:\esp\tools\tools\xtensa-esp-elf\esp-13.2.0_20230928\xtensa-esp-elf\bin;C:\esp\tools\tools\riscv32-esp-elf\esp-13.2.0_20230928\riscv32-esp-elf\bin;C:\esp\tools\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;C:\esp\tools\tools\cmake\3.24.0\bin;C:\esp\tools\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin;C:\esp\tools\tools\ninja\1.11.1;C:\esp\tools\tools\idf-exe\1.0.3;C:\esp\tools\tools\ccache\4.8\ccache-4.8-windows-x86_64;C:\esp\tools\tools\dfu-util\0.11\dfu-util-0.11-win64;C:\esp\tools\tools\esp-rom-elfs\20230320
Custom extra vars (idf.customExtraVars)
    OPENOCD_SCRIPTS: C:\esp\tools\tools\openocd-esp32\v0.12.0-esp32-20230921/openocd-esp32/share/openocd/scripts
    IDF_CCACHE_ENABLE: 1
    ESP_ROM_ELF_DIR: C:\esp\tools\tools\esp-rom-elfs\20230320/
Virtual env Python Path (idf.pythonBinPath) C:\esp\tools\python_env\idf5.2_py3.11_env\Scripts\python.exe
Serial port (idf.port) COM1
OpenOCD Configs (idf.openOcdConfigs) board/esp32c3-ftdi.cfg
ESP-IDF Tools Path (idf.toolsPath) C:\esp\tools
Git Path (idf.gitPath) C:\esp\tools\tools\idf-git\2.30.1\cmd\git.exe
Notification Mode (idf.notificationMode) All
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-IDF Custom extra paths
Access to C:\esp\tools\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin: true
Access to C:\esp\tools\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin: true
Access to C:\esp\tools\tools\xtensa-esp-elf\esp-13.2.0_20230928\xtensa-esp-elf\bin: true
Access to C:\esp\tools\tools\riscv32-esp-elf\esp-13.2.0_20230928\riscv32-esp-elf\bin: true
Access to C:\esp\tools\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: true
Access to C:\esp\tools\tools\cmake\3.24.0\bin: true
Access to C:\esp\tools\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin: true
Access to C:\esp\tools\tools\ninja\1.11.1: true
Access to C:\esp\tools\tools\idf-exe\1.0.3: true
Access to C:\esp\tools\tools\ccache\4.8\ccache-4.8-windows-x86_64: true
Access to C:\esp\tools\tools\dfu-util\0.11\dfu-util-0.11-win64: true
Access to C:\esp\tools\tools\esp-rom-elfs\20230320: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path true
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in C:\esp\tools\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin: false
Spaces in C:\esp\tools\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin: false
Spaces in C:\esp\tools\tools\xtensa-esp-elf\esp-13.2.0_20230928\xtensa-esp-elf\bin: false
Spaces in C:\esp\tools\tools\riscv32-esp-elf\esp-13.2.0_20230928\riscv32-esp-elf\bin: false
Spaces in C:\esp\tools\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: false
Spaces in C:\esp\tools\tools\cmake\3.24.0\bin: false
Spaces in C:\esp\tools\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin: false
Spaces in C:\esp\tools\tools\ninja\1.11.1: false
Spaces in C:\esp\tools\tools\idf-exe\1.0.3: false
Spaces in C:\esp\tools\tools\ccache\4.8\ccache-4.8-windows-x86_64: false
Spaces in C:\esp\tools\tools\dfu-util\0.11\dfu-util-0.11-win64: false
Spaces in C:\esp\tools\tools\esp-rom-elfs\20230320: false
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.30.1.windows.1
ESP-IDF version 5.2.0
Python version 3.11.5
Python's pip version 23.3.2
-------------------------------------------------- Project configuration settings ----------------------------------------------------------
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitarray version: 2.8.1
bitstring version: 4.1.2
CacheControl version: 0.13.1
certifi version: 2023.7.22
cffi version: 1.15.1
charset-normalizer version: 3.2.0
click version: 8.0.4
colorama version: 0.4.6
construct version: 2.10.70
contextlib2 version: 21.6.0
cryptography version: 41.0.7
ecdsa version: 0.18.0
esp-coredump version: 1.10.0
esp-debug-backend version: 1.0.3
esp-idf-kconfig version: 1.4.2
esp-idf-monitor version: 1.4.0
esp-idf-panic-decoder version: 1.0.1
esp-idf-size version: 1.1.0
esptool version: 4.7.0
filelock version: 3.12.4
freertos-gdb version: 1.0.2
gcovr version: 6.0
idf-component-manager version: 1.4.1
idna version: 3.4
intelhex version: 2.3.0
Jinja2 version: 3.0.3
kconfiglib version: 14.1.0
lxml version: 4.9.3
markdown-it-py version: 3.0.0
MarkupSafe version: 2.1.3
mdurl version: 0.1.2
msgpack version: 1.0.6
packaging version: 23.2
pip version: 23.3.2
pyclang version: 0.4.2
pycparser version: 2.21
pyelftools version: 0.30
pygdbmi version: 0.9.0.2
Pygments version: 2.16.1
pyparsing version: 3.1.1
pyserial version: 3.5
pywin32 version: 306
PyYAML version: 6.0.1
reedsolo version: 1.7.0
requests version: 2.31.0
requests-file version: 1.5.1
requests-toolbelt version: 1.0.0
rich version: 13.7.0
schema version: 0.7.5
setuptools version: 69.0.3
six version: 1.16.0
tqdm version: 4.66.1
urllib3 version: 1.26.16
websocket-client version: 1.7.0
windows-curses version: 2.3.1
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements are satisfied.
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at Unknown error in ESP-IDF Doctor Command
--------------------------------------------------------------------------------------------------------------------------------------------

### Description

Cannot set the target correctly despite it working within CLI with esp-idf exported outside of VsCode. 

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/138414207/91791ba7-9151-4237-b8b1-9507b39256dd)

### Debug Message

```plain
//Running idf.py set-target command after setting target through ESP-IDF extension GUI:

PS D:\development\esp\projects\idf_5_2\c3_testing> idf.py set-target esp32c3
Adding "set-target"'s dependency "fullclean" to list of commands with default set of options.
Executing action: fullclean
Build directory 'D:\development\esp\projects\idf_5_2\c3_testing\build' is empty. Nothing to clean.
Executing action: set-target
Set Target to: esp32c3, new sdkconfig will be created.
Target 'esp32c3' specified on command line is not consistent with target 'esp32' in the environment.

//Resulting error after attempting to flash: 

A fatal error occurred: This chip is ESP32-C3 not ESP32. Wrong --chip argument?
CMake Error at run_serial_tool.cmake:66 (message):

  C:/esp/tools/python_env/idf5.2_py3.11_env/Scripts/python.exe;;C:/Users/myles/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32
  failed.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Can you use the `ESP-IDF: Set Espressif device target` extension command or just click at the target in the status bar

**Comment by myles-parfeniuk** [comment]
Yes, I set the target using the extension command before opening this issue, unfortunately it did not correct the problem.

The target appears correctly on the status bar:
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/138414207/e2a0de70-6f87-4041-984d-c765216cfefe)

**Comment by brianignacio5** [comment]
Could you try closing this terminal and open a new esp-idf terminal ?

**Comment by myles-parfeniuk** [comment]
> Could you try closing this terminal and open a new esp-idf terminal ?
Issue resolved, this worked perfectly. Thank you.

**Comment by brianignacio5** [comment]
Glad it works!

If you find the extension useful. Please leave us a review in the [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension)
