### ISSUE TITLE
The details in IDF menuconfig cannot be opened (VSC-1284)

### ISSUE THREAD

**Issue by Tinyu-Zhao** [espressif/vscode-esp-idf-extension#1126]
### OS

MacOS

### Operating System version

12.7.3 

### Visual Studio Code version

1.86.0

### ESP-IDF version

5.1.2

### Python version

3.9.6

### Doctor command output

[report.txt](https://github.com/espressif/vscode-esp-idf-extension/files/14155616/report.txt)

### Extension

[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/14155606/esp_idf_vsc_ext.log)

### Description

Unable to expand details properly when clicking on menuconfig in ESP-IDF, such as in video 1.

https://github.com/espressif/vscode-esp-idf-extension/assets/44396641/afdae3dd-5248-4621-b5c5-0e4955a12a83

Expected behavior, such as video 2.

https://github.com/espressif/vscode-esp-idf-extension/assets/44396641/ced7811a-64f7-43a7-a3e4-69bdcdba062a

### Debug Message

```plain
None
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
This is a duplicate of #1121

**Comment by Tinyu-Zhao** [comment]
Thank you, perfectly resolved.

**Comment by Tinyu-Zhao** [comment]
> This is a duplicate of #1121

Thank you, perfectly resolved.

**Comment by brianignacio5** [comment]
If you find the extension useful. Please leave us a review in the [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension)
