### ISSUE TITLE
Python not found by bash at compiling when executing ESP-IDF size task (VSC-1289)

### ISSUE THREAD

**Issue by edolis** [espressif/vscode-esp-idf-extension#1129]
### OS

Windows

### Operating System version

Windows 10

### Visual Studio Code version

1.86.0

### ESP-IDF version

5.1.2

### Python version

coming with ESP-IDF

### Doctor command output

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.19045 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\Zulu\zulu-11\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Calibre2\;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Agilent\IO Libraries Suite\bin;C:\Program Files\IVI Foundation\VISA\Win64\agvisa;C;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\dotnet\;C:\Program Files\Crucial\Crucial Storage Executive;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common Files\Acronis\FileProtector\;C:\Program Files (x86)\Common Files\Acronis\FileProtector64\;D:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;D:\Program Files\ffmpeg\bin;D:<HOMEPATH>\.espressif\python_env\idf5.1_py3.11_env\Scripts;C:<HOMEPATH>\AppData\Local\Microsoft\WindowsApps;C:<HOMEPATH>\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:<HOMEPATH>\AppData\Local\Programs\Microsoft VS Code\bin;C:<HOMEPATH>\AppData\Roaming\npm;C:\Program Files\Git\bin; 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.86.0 
Visual Studio Code language en 
Visual Studio Code shell C:\Program Files\Git\bin\bash.exe 
ESP-IDF Extension version 1.7.0 
Workspace folder d:\MyStuff\Progetti\P014_fermChamber\AUT\P014\blink 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) D:<HOMEPATH>\esp\v5.1.2\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
Custom extra paths (idf.customExtraPaths) D:<HOMEPATH>\.espressif\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin;D:<HOMEPATH>\.espressif\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin;D:<HOMEPATH>\.espressif\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin;D:<HOMEPATH>\.espressif\tools\xtensa-esp32s2-elf\esp-12.2.0_20230208\xtensa-esp32s2-elf\bin;D:<HOMEPATH>\.espressif\tools\xtensa-esp32s3-elf\esp-12.2.0_20230208\xtensa-esp32s3-elf\bin;D:<HOMEPATH>\.espressif\tools\riscv32-esp-elf\esp-12.2.0_20230208\riscv32-esp-elf\bin;D:<HOMEPATH>\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;D:<HOMEPATH>\.espressif\tools\cmake\3.24.0\bin;D:<HOMEPATH>\.espressif\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin;D:<HOMEPATH>\.espressif\tools\ninja\1.10.2;D:<HOMEPATH>\.espressif\tools\idf-exe\1.0.3;D:<HOMEPATH>\.espressif\tools\ccache\4.8\ccache-4.8-windows-x86_64;D:<HOMEPATH>\.espressif\tools\dfu-util\0.11\dfu-util-0.11-win64;D:<HOMEPATH>\.espressif\tools\esp-rom-elfs\20230320
Custom extra vars (idf.customExtraVars)
    OPENOCD_SCRIPTS: D:<HOMEPATH>\.espressif\tools\openocd-esp32\v0.12.0-esp32-20230921/openocd-esp32/share/openocd/scripts
    IDF_CCACHE_ENABLE: 1
    ESP_ROM_ELF_DIR: D:<HOMEPATH>\.espressif\tools\esp-rom-elfs\20230320/
Virtual env Python Path (idf.pythonBinPath) D:<HOMEPATH>\.espressif\python_env\idf5.1_py3.11_env\Scripts\python.exe
Serial port (idf.port) COM1
OpenOCD Configs (idf.openOcdConfigs) board/esp32-bridge.cfg
ESP-IDF Tools Path (idf.toolsPath) D:<HOMEPATH>\.espressif
Git Path (idf.gitPath) D:<HOMEPATH>\.espressif\tools\idf-git\2.39.2\cmd\git.exe
Notification Mode (idf.notificationMode) All
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-IDF Custom extra paths
Access to D:<HOMEPATH>\.espressif\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin: true
Access to D:<HOMEPATH>\.espressif\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin: true
Access to D:<HOMEPATH>\.espressif\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin: true
Access to D:<HOMEPATH>\.espressif\tools\xtensa-esp32s2-elf\esp-12.2.0_20230208\xtensa-esp32s2-elf\bin: true
Access to D:<HOMEPATH>\.espressif\tools\xtensa-esp32s3-elf\esp-12.2.0_20230208\xtensa-esp32s3-elf\bin: true
Access to D:<HOMEPATH>\.espressif\tools\riscv32-esp-elf\esp-12.2.0_20230208\riscv32-esp-elf\bin: true
Access to D:<HOMEPATH>\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: true
Access to D:<HOMEPATH>\.espressif\tools\cmake\3.24.0\bin: true
Access to D:<HOMEPATH>\.espressif\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin: true
Access to D:<HOMEPATH>\.espressif\tools\ninja\1.10.2: true
Access to D:<HOMEPATH>\.espressif\tools\idf-exe\1.0.3: true
Access to D:<HOMEPATH>\.espressif\tools\ccache\4.8\ccache-4.8-windows-x86_64: true
Access to D:<HOMEPATH>\.espressif\tools\dfu-util\0.11\dfu-util-0.11-win64: true
Access to D:<HOMEPATH>\.espressif\tools\esp-rom-elfs\20230320: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path true
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in D:<HOMEPATH>\.espressif\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin: false
Spaces in D:<HOMEPATH>\.espressif\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin: false
Spaces in D:<HOMEPATH>\.espressif\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin: false
Spaces in D:<HOMEPATH>\.espressif\tools\xtensa-esp32s2-elf\esp-12.2.0_20230208\xtensa-esp32s2-elf\bin: false
Spaces in D:<HOMEPATH>\.espressif\tools\xtensa-esp32s3-elf\esp-12.2.0_20230208\xtensa-esp32s3-elf\bin: false
Spaces in D:<HOMEPATH>\.espressif\tools\riscv32-esp-elf\esp-12.2.0_20230208\riscv32-esp-elf\bin: false
Spaces in D:<HOMEPATH>\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: false
Spaces in D:<HOMEPATH>\.espressif\tools\cmake\3.24.0\bin: false
Spaces in D:<HOMEPATH>\.espressif\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin: false
Spaces in D:<HOMEPATH>\.espressif\tools\ninja\1.10.2: false
Spaces in D:<HOMEPATH>\.espressif\tools\idf-exe\1.0.3: false
Spaces in D:<HOMEPATH>\.espressif\tools\ccache\4.8\ccache-4.8-windows-x86_64: false
Spaces in D:<HOMEPATH>\.espressif\tools\dfu-util\0.11\dfu-util-0.11-win64: false
Spaces in D:<HOMEPATH>\.espressif\tools\esp-rom-elfs\20230320: false
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.39.2.windows.1
ESP-IDF version 5.1.2
Python version 3.11.2
Python's pip version 24.0
-------------------------------------------------- Project configuration settings ----------------------------------------------------------
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitarray version: 2.9.2
bitstring version: 4.1.4
CacheControl version: 0.14.0
certifi version: 2024.2.2
cffi version: 1.16.0
charset-normalizer version: 3.3.2
click version: 8.0.4
colorama version: 0.4.6
construct version: 2.10.70
contextlib2 version: 21.6.0
cryptography version: 39.0.2
ecdsa version: 0.18.0
esp-coredump version: 1.10.0
esp-debug-backend version: 1.0.3
esp-idf-kconfig version: 1.4.2
esp-idf-monitor version: 1.4.0
esp-idf-panic-decoder version: 1.0.1
esp-idf-size version: 1.1.0
esptool version: 4.7.0
filelock version: 3.13.1
freertos-gdb version: 1.0.2
idf-component-manager version: 1.4.2
idna version: 3.6
intelhex version: 2.3.0
kconfiglib version: 14.1.0
markdown-it-py version: 3.0.0
mdurl version: 0.1.2
msgpack version: 1.0.7
packaging version: 23.2
pip version: 24.0
pycparser version: 2.21
pyelftools version: 0.29
pygdbmi version: 0.9.0.2
Pygments version: 2.17.2
pyparsing version: 3.0.9
pyserial version: 3.5
pywin32 version: 306
PyYAML version: 6.0.1
reedsolo version: 1.7.0
requests version: 2.31.0
requests-file version: 1.5.1
requests-toolbelt version: 1.0.0
rich version: 13.7.0
schema version: 0.7.5
setuptools version: 69.0.3
six version: 1.16.0
tqdm version: 4.66.1
urllib3 version: 1.26.18
windows-curses version: 2.3.2
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "${config:idf.toolsPathWin}\\tools\\xtensa-esp32-elf\\esp-12.2.0_20230208\\xtensa-esp32-elf\\bin\\xtensa-esp32-elf-gcc.exe",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
 
--------------------------------------------------------------------------------------------------------------------------------------------

### Extension

{"user":true,"message":"Something went wrong while trying to build the project","stack":"Error: Task ESP-IDF Size exited with code 127\n\tat \\dist\\extension.js:2:1520389\n\tat g.value (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:160:19731)\n\tat r.y (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:80:1902)\n\tat r.z (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:80:1972)\n\tat r.fire (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:80:2188)\n\tat r.$onDidEndTaskProcess (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:153:52912)","level":"error","timestamp":"2024-02-06T15:52:54.472Z"}

### Description

I cannot get python to be found by bash when compiling the Blink example, after a fresh installation of the ESP-IDF extension.
I am getting this error in the log
 ```
Executing task: D:\Users\edolis\.espressif\python_env\idf5.1_py3.11_env\Scripts\python.exe D:\Users\edolis\esp\v5.1.2\esp-idf\tools\idf_size.py d:\MyStuff\Progetti\P014_fermChamber\AUT\P014\blink\build\blink.map 

bash: D:Usersedolis.espressifpython_envidf5.1_py3.11_envScriptspython.exe: command not found
```

- I have checked and all the 3 files (python.exe, idf_size.py and blink.map ) are available in the place specified.
 
I have uninstalled python (no standalone Python installation, no WindowsApp Python, removed all reference in PATH)
I have uninstalled the VS code ESP-IDF, deleted the D:\Users\edolis\.espressif\python_env and reinstalled the extension as per installation instructions, but I still run into the same error.

I have no idea what to try next.
Many thanks for your attention.

### Debug Message

```plain
*  Executing task: D:\Users\edolis\.espressif\python_env\idf5.1_py3.11_env\Scripts\python.exe D:\Users\edolis\esp\v5.1.2\esp-idf\tools\idf_size.py d:\MyStuff\Progetti\P014_fermChamber\AUT\P014\blink\build\blink.map 

bash: D:Usersedolis.espressifpython_envidf5.1_py3.11_envScriptspython.exe: command not found

 *  The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-i', '-c', 'D:\Users\edolis\.espressif\python_env\idf5.1_py3.11_env\Scripts\python.exe D:\Users\edolis\esp\v5.1.2\esp-idf\tools\idf_size.py d:\MyStuff\Progetti\P014_fermChamber\AUT\P014\blink\build\blink.map'" terminated with exit code: 127.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Any specific reason you need to use git bash for the size task ? Have you tried using Powershell in terminal ? You can use powershell  only for esp-idf extension tasks by settings the powershell.exe path in `idf.customTerminalExecutable` and `idf.customTerminalExecutableArgs` for arguments like `--login`.

Besides this, I think there is an issue with the way Bash parses the file path if you write this in a bash terminal does it work ?

```bash
/d/Users/edolis/.espressif/python_env/idf5.1_py3.11_env/Scripts/python.exe /d/Users/edolis/esp/v5.1.2/esp-idf/tools/idf_size.py /d/MyStuff/Progetti/P014_fermChamber/AUT/P014/blink/build/blink.map
```

**Comment by edolis** [comment]
thanks Brian - no specific reason apart from trying to stick to the recommended environment/tutorial- I am trying to understand whether to switch from Arduino extension to ESP-IDF for a larger project, and still trying to understand how to work in this environment. 

And yes, 

`/d/Users/edolis/.espressif/python_env/idf5.1_py3.11_env/Scripts/python.exe /d/Users/edolis/esp/v5.1.2/esp-idf/tools/idf_size.py /d/MyStuff/Progetti/P014_fermChamber/AUT/P014/blink/build/blink.map`

is working -  I'm getting this output.
`/d/Users/edolis/.espressif/python_env/idf5.1_py3.11_env/Scripts/python.exe /d/Users/edolis/esp/v5.1.2/esp-idf/tools/idf_size.py /d/MyStuff/Progetti/P014_fermChamber/AUT/P014/blink/build/blink.map

Total sizes:

Used static DRAM:   10704 bytes ( 170032 remain, 5.9% used) 
      .data size:    8536 bytes
      .bss  size:    2168 bytes
Used static IRAM:   49146 bytes (  81926 remain, 37.5% used)
      .text size:   48119 bytes
   .vectors size:    1027 bytes
Used Flash size :  124607 bytes
           .text:   84695 bytes
         .rodata:   39656 bytes
Total image size:  182289 bytes (.bin may be padded larger) `

Any way I can modify the environment to make this syntax the used one and remove the problem? I think I'll  probably need bash following tutorials soon or later and fixing the core issue would make things easier.

Thank you so much!

**Comment by brianignacio5** [comment]
I think the thing is that using Bash for Windows as Terminal Profile is not the default use case. Tutorials were written using macOS setup and it uses `zsh`. For Windows you could follow the tutorial using Powershell as your terminal profile by selecting the default profile with `Terminal: Select Default Profile` command as shown here https://code.visualstudio.com/docs/terminal/profiles

If you want to keep your terminal profile to Bash, you can always set the terminal just for esp-idf extension tasks with the settings I mentioned before.

Let me know if you have any issues.

**Comment by edolis** [comment]
Thanks again, Brian. 
much clearer now.
For us newcomers, I recommend that a note/configuration step is added for Windows users to the extension configuration/-installation tutorial, which seems to be covering the specifics of both Linux and Windows - without this note though.
I understand that must seem trivial to you, but notice that a failure in compiling °hello, world!° sample projects puts off newcomers (now I understand that failing bash step is just to compute the size statistics, so it's not critical in any way. But I get that just now, unfortunately - after one day of re-installation (and killing my former python environment, too) and bothering you)

For other newcomers, here is the setting

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/2226075/d745e442-bab8-44a9-8dfe-2392d30ac1d9)

setting this, the extension compiles sample codes without any problems on Windows.

As for the `idf.customTerminalExecutableArgs` setting - I have found no documentation for the syntax or the setting itself - even searching in the Github repository
[idf.customTerminalExecutableArgs](https://github.com/search?q=repo%3Aespressif%2Fvscode-esp-idf-extension%20idf.customTerminalExecutableArgs&type=code)

so it's a bit obscure to me if/how it should be populated - how I would be supposed to pick the arguments and so on. Could not find examples/documentation around.

In any case you have been a lifesaver and I truly admire the huge hard work you are doing. Apologies for my not being able to figure out the cherry on top on my own :)

**Comment by brianignacio5** [comment]
Thanks @edolis  your feedback is most appreciated! Will add a note of this in the docs.

If you find the extension useful. Please leave us a review in the [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension)
