### ISSUE TITLE
Plugin spams with messages (VSC-1295)

### ISSUE THREAD

**Issue by chedim** [espressif/vscode-esp-idf-extension#1135]
### OS

MacOS

### Operating System version

n/a

### Visual Studio Code version

n/a

### ESP-IDF version

n/a

### Python version

n/a

### Doctor command output

n/a

### Extension

n/a

### Description

The plugin spams with error message notifications every time something goes wrong, which is very annoying as, for example, it requires dismissing notification popups every time a build fails. A user can see that their build failed in the build output window, could you not do this or at least hide the popups after a timeout?

Thank you.

### Debug Message

```plain
n/a
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Segfault1602** [comment]
A pretty bad example of this: if you unplug your device while the OpenOCD Server is running, OpenOCD gets into a retry loop until the device is found again. Each failed retry generate 2 or 3 notifications every ~1 second until either the device is found again or OpenOCD Server is stopped and at this point you can easily have >20 popup to dismiss.

![esp-idf-spam](https://github.com/espressif/vscode-esp-idf-extension/assets/3288084/8591a8fd-d4ef-4bbf-8c91-5d638dfee739)

**Comment by radurentea** [comment]
Hi,

Thanks for the feedback! We'll investigate these specific scenarios to explore alternative approaches that may differ from our existing solutions.

### Present Setup:
To tailor your notification preferences
* navigate to **Command Palette** > **Open Settings (UI),** 
* look for **Idf: Notification Mode**
* choose the option that aligns with your needs. For your situations, "**Output**" might be the most suitable choice.

Alternatively, you can insert the following line into your `settings.json`: "**idf.notificationMode": "Output**"
