### ISSUE TITLE
After creating multiple configs -> menuconfig does not start anymore (VSC-1298)

### ISSUE THREAD

**Issue by Reneg973** [espressif/vscode-esp-idf-extension#1139]
### OS

Windows

### Operating System version

Windows 11

### Visual Studio Code version

1.86.1

### ESP-IDF version

5.2

### Python version

3.9

### Doctor command output

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.22000 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files\TortoiseGit\bin;C:<HOMEPATH>\AppData\Local\Programs\Python\Python39\Scripts\;C:<HOMEPATH>\AppData\Local\Programs\Python\Python39\;C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2020-q4-major\bin;C:<HOMEPATH>\AppData\Local\Microsoft\WindowsApps;C:<HOMEPATH>\AppData\Local\GitHubDesktop\bin;C:\Programs\Microsoft VS Code\bin 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.86.1 
Visual Studio Code language en 
Visual Studio Code shell C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.7.0 
Workspace folder d:\ESP32S3_LCD_7\Panel1\rgb_panel 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) d:\SysGCC\esp32\esp-idf\v5.2\v5.2\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
Custom extra paths (idf.customExtraPaths) D:\SysGCC\esp32\tools\tools\xtensa-esp-elf-gdb\12.1_20231023\xtensa-esp-elf-gdb\bin;D:\SysGCC\esp32\tools\tools\riscv32-esp-elf-gdb\12.1_20231023\riscv32-esp-elf-gdb\bin;D:\SysGCC\esp32\tools\tools\xtensa-esp-elf\esp-13.2.0_20230928\xtensa-esp-elf\bin;D:\SysGCC\esp32\tools\tools\riscv32-esp-elf\esp-13.2.0_20230928\riscv32-esp-elf\bin;D:\SysGCC\esp32\tools\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;D:\SysGCC\esp32\tools\tools\cmake\3.24.0\bin;D:\SysGCC\esp32\tools\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin;D:\SysGCC\esp32\tools\tools\ninja\1.11.1;D:\SysGCC\esp32\tools\tools\idf-exe\1.0.3;D:\SysGCC\esp32\tools\tools\ccache\4.8\ccache-4.8-windows-x86_64;D:\SysGCC\esp32\tools\tools\dfu-util\0.11\dfu-util-0.11-win64;D:\SysGCC\esp32\tools\tools\esp-rom-elfs\20230320
Custom extra vars (idf.customExtraVars)
    OPENOCD_SCRIPTS: D:\SysGCC\esp32\tools\tools\openocd-esp32\v0.12.0-esp32-20230921/openocd-esp32/share/openocd/scripts
    IDF_CCACHE_ENABLE: 1
    ESP_ROM_ELF_DIR: D:\SysGCC\esp32\tools\tools\esp-rom-elfs\20230320/
Virtual env Python Path (idf.pythonBinPath) D:\SysGCC\esp32\tools\python_env\idf5.2_py3.11_env\Scripts\python.exe
Serial port (idf.port) COM1
OpenOCD Configs (idf.openOcdConfigs) board/esp32s3-bridge.cfg
ESP-IDF Tools Path (idf.toolsPath) D:\SysGCC\esp32\tools
Git Path (idf.gitPath) \Git\cmd\git.exe
Notification Mode (idf.notificationMode) All
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-IDF Custom extra paths
Access to D:\SysGCC\esp32\tools\tools\xtensa-esp-elf-gdb\12.1_20231023\xtensa-esp-elf-gdb\bin: true
Access to D:\SysGCC\esp32\tools\tools\riscv32-esp-elf-gdb\12.1_20231023\riscv32-esp-elf-gdb\bin: true
Access to D:\SysGCC\esp32\tools\tools\xtensa-esp-elf\esp-13.2.0_20230928\xtensa-esp-elf\bin: true
Access to D:\SysGCC\esp32\tools\tools\riscv32-esp-elf\esp-13.2.0_20230928\riscv32-esp-elf\bin: true
Access to D:\SysGCC\esp32\tools\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: true
Access to D:\SysGCC\esp32\tools\tools\cmake\3.24.0\bin: true
Access to D:\SysGCC\esp32\tools\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin: true
Access to D:\SysGCC\esp32\tools\tools\ninja\1.11.1: true
Access to D:\SysGCC\esp32\tools\tools\idf-exe\1.0.3: true
Access to D:\SysGCC\esp32\tools\tools\ccache\4.8\ccache-4.8-windows-x86_64: true
Access to D:\SysGCC\esp32\tools\tools\dfu-util\0.11\dfu-util-0.11-win64: true
Access to D:\SysGCC\esp32\tools\tools\esp-rom-elfs\20230320: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path true
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in D:\SysGCC\esp32\tools\tools\xtensa-esp-elf-gdb\12.1_20231023\xtensa-esp-elf-gdb\bin: false
Spaces in D:\SysGCC\esp32\tools\tools\riscv32-esp-elf-gdb\12.1_20231023\riscv32-esp-elf-gdb\bin: false
Spaces in D:\SysGCC\esp32\tools\tools\xtensa-esp-elf\esp-13.2.0_20230928\xtensa-esp-elf\bin: false
Spaces in D:\SysGCC\esp32\tools\tools\riscv32-esp-elf\esp-13.2.0_20230928\riscv32-esp-elf\bin: false
Spaces in D:\SysGCC\esp32\tools\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: false
Spaces in D:\SysGCC\esp32\tools\tools\cmake\3.24.0\bin: false
Spaces in D:\SysGCC\esp32\tools\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin: false
Spaces in D:\SysGCC\esp32\tools\tools\ninja\1.11.1: false
Spaces in D:\SysGCC\esp32\tools\tools\idf-exe\1.0.3: false
Spaces in D:\SysGCC\esp32\tools\tools\ccache\4.8\ccache-4.8-windows-x86_64: false
Spaces in D:\SysGCC\esp32\tools\tools\dfu-util\0.11\dfu-util-0.11-win64: false
Spaces in D:\SysGCC\esp32\tools\tools\esp-rom-elfs\20230320: false
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version undefined
ESP-IDF version undefined
Python version undefined
Python's pip version undefined
-------------------------------------------------- Project configuration settings ----------------------------------------------------------
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages undefined
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages undefined
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at Unknown error in ESP-IDF Doctor Command
--------------------------------------------------------------------------------------------------------------------------------------------

### Extension

version 1.7.0

### Description

Menuconfig works as long as there are no multiple configurations.
After [](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/multiple_config.md) switching of configurations works and building them too, but menuconfig doesn't appear anymore.

### Debug Message

```plain
none
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Could you provide more informative about the multiple configurations like which settings are entailed, the extension log and the errors you see from ESP-IDF Output  when running menuconfig. Also how are you running menuconfig and steps to reproduce your issue.
