### ISSUE TITLE
esp-idf can't trigger the set up process in archlinux (VSC-1304)

### ISSUE THREAD

**Issue by need-it-github** [espressif/vscode-esp-idf-extension#1144]
### OS

Linux

### Operating System version

archlinux

### Visual Studio Code version

1.86.2

### ESP-IDF version

5.2

### Python version

3.12

### Doctor command output

Error looking for python in system
<img width="464" alt="Snipaste_2024-02-23_23-50-39" src="https://github.com/espressif/vscode-esp-idf-extension/assets/68671117/0c00ba7e-b59c-4a87-8f28-7c0b7e2f1893">

### Extension

{
	"message": "Command failed: which -a python; which -a python3\n/bin/sh: line 1: which: command not found\n/bin/sh: line 1: which: command not found\n",
	"stack": "Error: Command failed: which -a python; which -a python3\n/bin/sh: line 1: which: command not found\n/bin/sh: line 1: which: command not found\n\n\tat ChildProcess.exithandler (node:child_process:420:12)\n\tat ChildProcess.emit (node:events:514:28)\n\tat maybeClose (node:internal/child_process:1091:16)\n\tat ChildProcess._handle.onexit (node:internal/child_process:302:5)",
	"level": "error",
	"timestamp": "2024-02-23T15:53:25.167Z"
}

### Description

After setting up the esp-idf development environment in archlinux, the esp-idf extension cannot trigger the setup process.

### Debug Message

```plain
{
	"message": "Command failed: which -a python; which -a python3\n/bin/sh: line 1: which: command not found\n/bin/sh: line 1: which: command not found\n",
	"stack": "Error: Command failed: which -a python; which -a python3\n/bin/sh: line 1: which: command not found\n/bin/sh: line 1: which: command not found\n\n\tat ChildProcess.exithandler (node:child_process:420:12)\n\tat ChildProcess.emit (node:events:514:28)\n\tat maybeClose (node:internal/child_process:1091:16)\n\tat ChildProcess._handle.onexit (node:internal/child_process:302:5)",
	"level": "error",
	"timestamp": "2024-02-23T15:53:25.167Z"
}
```

### Other Steps to Reproduce

Archlinux have to install the 'which' command to trigger the setup process.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by need-it-github** [comment]
`sudo pacman -S which`

**Comment by brianignacio5** [comment]
I'm not very sure what can we do here. `which` should be part of most Linux Distribution but maybe is not the case. We can't really install it ourselves from extension (no root privileges).

What would be a better way to find existing python executable in the OS ?
