### ISSUE TITLE
The command on setup page to add rules for openOCD on Linux is incorrect (VSC-1310)

### ISSUE THREAD

**Issue by NaHCO3-code** [espressif/vscode-esp-idf-extension#1151]
### OS

Linux

### Operating System version

Manjaro Linux x86_64 6.6.16-2

### Visual Studio Code version

1.86.2

### ESP-IDF version

5.2.0

### Python version

3.11.7

### Doctor command output

Not related

### Description

There is a command on the setup page after installation for Linux users to add rules for permission delegation in USB devices in `/etc/udev/rules.d/`.

The correct command should be `sudo cp -n ~/.espressif/tools/openocd-esp32/.../60-openocd.rules /etc/udev/rules.d`

But the actually the command is `sudo cp -n [object Object] /etc/udev/rules.d`

It may be a Javascript object, but didn't display correctly.

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/80567300/301a887c-ffcd-4eb5-86f1-8235ad33f650)

### Debug Message

```plain
-
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
This is fixed in master and will be available in the next release.

You can try it with this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/workflows/ci/master/esp-idf-extension.vsix.zip)
