### ISSUE TITLE
How Can I install the extension in offline mode, my internet is not stable (VSC-1312)

### ISSUE THREAD

**Issue by VALERYRAMIREZ** [espressif/vscode-esp-idf-extension#1153]
### OS

Windows

### Operating System version

Windows 10 Pro 64 bits

### Visual Studio Code version

1.86.2

### ESP-IDF version

1.7.0

### Python version

not installed

### Doctor command output

not installed

### Extension

[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/14466705/esp_idf_vsc_ext.log)

Please see the attached file

### Description

Impossible to install the extension because my internet is not istable and the installation allways falls, when the internet goes back then the installation starts again 

### Debug Message

```plain
esp-idf folder exists, please remove it or rename it to continue with the installation
```

### Other Steps to Reproduce

none

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
You can use an existing ESP-IDF setup in your system by selecting `Find ESP-IDF in your system` from Select ESP-IDF version dropdown when using the `ESP-IDF: Configure ESP-IDF extension` command.
