### ISSUE TITLE
Question: is there a way to disable the ESP-IDF extension Welcome screen in VSC? (VSC-1313)

### ISSUE THREAD

**Issue by mbratch** [espressif/vscode-esp-idf-extension#1154]
### OS

Windows

### Operating System version

Windows 11

### Visual Studio Code version

1.7.0

### ESP-IDF version

5.1.2

### Python version

3.11.2

### Doctor command output

NA

### Description

Every time I open an existing ESP-IDF project in VSC, I will start working on a source file and then the annoying ESP-IDF plugin Welcome tab opens, interrupting what I was doing. It takes awhile for the tab to appear after opening a project so it adds considerable delay to working after opening a project. After I open a project, I start working and editing, and this tab will suddenly interrupt the work and take over as the focused tab.

Here's the tab I'm referring to.

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/7990964/f3c60c7f-b9f1-485f-ae7b-f880e2a45f17)

Is there a way to turn off this welcome tab from opening automatically? The behavior is very annoying.

### Debug Message

```plain
NA
```

### Other Steps to Reproduce

Just open an existing ESP-IDF project and wait.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by mbratch** [comment]
Sorry... I finally found some solutions after further searching.

**Comment by brianignacio5** [comment]
You could also set the `idf.showOnboardingOnInit: false` in your .vscode/settings.json or User settings

If you find the extension useful. Please leave us a review in the [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension)

**Comment by RobinKayGeoMoby** [comment]
> Sorry... I'm totally blind and I was being daft. There is a checkbox in the upper left corner. Sheesh. On a related note, I did try setting startupEditor option to "none" but that didn't block the welcome tab.

I have the same problem and not seeing any checkbox.

**Comment by brianignacio5** [comment]
![Screenshot 2024-04-24 at 16 03 20](https://github.com/espressif/vscode-esp-idf-extension/assets/6033246/4868363b-4cb6-4951-a64f-801d1f73539d)

You could also set the `idf.showOnboardingOnInit: false` in your .vscode/settings.json or User settings

**Comment by RobinKayGeoMoby** [comment]
Thanks Brian,

I appreciate the follow-up.

Regards,
Robin

**Comment by riscy00** [comment]
This worked
