### ISSUE TITLE
jtag调试和下载工作不正常 (VSC-1336)

### ISSUE THREAD

**Issue by nanshanISCK** [espressif/vscode-esp-idf-extension#1172]
### OS

Windows

### Operating System version

win11 专业工作站版

### Visual Studio Code version

1.87.2

### ESP-IDF version

5.2.1

### Python version

idf插件自动安装的py

### Doctor command output

[OpenOCD]
Open On-Chip Debugger v0.12.0-esp32-20230921 (2023-09-21-13:40)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html

[OpenOCD]
debug_level: 2

[OpenOCD]
Info : only one transport option; autoselecting 'jtag'

[OpenOCD]
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000

[OpenOCD]
Info : Listening on port 6666 for tcl connections
Info : Listeni
[OpenOCD]
ng on port 4444 for telnet connections

[OpenOCD]
Info : esp_usb_jtag: serial (54:32
[OpenOCD]
:04:87:E8:80)
Info : esp_usb_jtag: Device found. Base speed 40000KHz, div range 1 to 255

[OpenOCD]
Info : clock speed 40000 kHz

[OpenOCD]
Info : JTAG tap: esp32c3.cpu t
[OpenOCD]
ap/device found: 0x00005c25 (mfg: 0x612 (Espressif Systems), part: 0x0005, ver: 0x0)

[OpenOCD]
Info : [esp32c3] datacount=2 pro
[OpenOCD]
gbufsize=16

[Flash]
Failed to flash (via JTag), due to some unknown error in tcl, please try to relaunch open-ocd
[OpenOCD]
❌ Error: [esp32c3] Timed out a
[OpenOCD]
fter 5s waiting for busy to go low (abstractcs=0x10001202). Increase the timeout with riscv set_command_timeout_sec.

[OpenOCD]
❌ Error: [esp32c3] Timed out after 5s waiting for bus
[OpenOCD]
❌ y to go low (abstractcs=0x10001202). Increase the timeout with riscv set_command_timeout_sec.
Error: [esp32c3] Fatal: Failed to read s0.
Warn : target esp32c3 examination failed
Info : starting gdb server for esp32c3 on 3333
Info : Listening on port 3333 for gdb connections
Info : accepting 'tcl' connection on tcp/6666
[OpenOCD]

Info : dropped 'tcl' connection

### Extension

[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/14760424/esp_idf_vsc_ext.log)

### Description

可以使用内建usb串口下载固件，但是无法使用jtag调试和下载固件，微软自带的驱动不能用，然后我用zadig更新了libwdi提供商的驱动，也不能正常工作

### Debug Message

```plain
我的launch.json里是这些，并没有logLevel
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
}
```

### Other Steps to Reproduce

win11家庭版也是一样的问题

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
You can try to increase the timeout with `set remotetimeout 10` in openOCD launch arguments `idf.openOcdLaunchArgs: ["set remotetimeout 10"]`
