### ISSUE TITLE
Blink example with issues (VSC-355)

### ISSUE THREAD

**Issue by versamodule** [espressif/vscode-esp-idf-extension#118]
Just installed this extension on a new PC today. Install went well. 
I selected the Blink example. It compiled fine, however when you open blink.c There are 2 issues in the "problems" tab. 

![Problems](https://user-images.githubusercontent.com/6456652/84189048-37502800-aa5a-11ea-8743-a012c5674735.jpg)

Also, I would like to see the compilation in progress, over just a popup. Is there a way to enable that ? 

![Annotation 2020-06-09 135713](https://user-images.githubusercontent.com/6456652/84189097-4afb8e80-aa5a-11ea-85da-45fd14726057.jpg)

**Comment by brianignacio5** [comment]
The compilation process is shown in the Output tab-> ESP-IDF Build.

Did you configure the C/C++ extension as shown in [Configuration of c_cpp_properties.json file](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/C_CPP_CONFIGURATION.md)

**Comment by versamodule** [comment]
Thanks for the Tip, that worked. 
Ya, i dont get anything in the output tab. I looked there first before mentioning it. 

![Annotation 2020-06-09 221155](https://user-images.githubusercontent.com/6456652/84222882-4b1d7d80-aa9e-11ea-9195-e4fc7dd4bf06.jpg)

**Comment by brianignacio5** [comment]
There is a dropdown that says `Tasks`, change it to `ESP-IDF Build`

**Comment by brianignacio5** [comment]
Closing this issue since it seems resolved.
