### ISSUE TITLE
Shortcuts are in conflict with Inline Chat(Github Copilot) shortcut (VSC-1350)

### ISSUE THREAD

**Issue by DPirate** [espressif/vscode-esp-idf-extension#1187]
### OS

Windows

### Operating System version

macOS 13.6.4

### Visual Studio Code version

1.89.0

### ESP-IDF version

v1.7.1

### Python version

3.12.4

### Doctor command output

Not Applicable

### Description

The shortcut "cmd+I" is used by inline chat feature of github copilot. The same combination is also used by various shortcuts of this extension as the first key.  Therefore, after enabling this extension vscode starts waiting for second key instead of triggering the inline chat.

### Debug Message

```plain
Not Applicable
```

### Other Steps to Reproduce

Need to have github copilot enabled. Try using "cmd+I" shortcut while editing a file, if this extension is disabled it will trigger the inline chat otherwise it won't.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
You can modify your keybinding shortcuts with https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor

Is hard to come with a right set of keybinding that doesn't collide with other extensions. Let see if can update default ones to avoid conflicts.
