### ISSUE TITLE
[Feature Request]: 建议 SDK Configuration editor 中 文本输入框 禁止滚轮增减数值 (VSC-1351)

### ISSUE THREAD

**Issue by MosamXu** [espressif/vscode-esp-idf-extension#1189]
SDK Configuration editor 中的文本输入框，获得焦点后，滚轮滚动，输入框的数值会随着滚动而增减，建议禁止这一行为，它会导致很多意外情况，而且非常难查。例如，“The length of APP ELF SHA is stored in RAM(chars)“下的文本框，默认值为16，如果文本框获得焦点后滚轮滚动，它的值改变，这种意外情况很难定位问题。因此建议禁止这一行为

**Comment by brianignacio5** [comment]
Should have a fix in [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/1676829356.zip)
