### ISSUE TITLE
"Show all ESP-IDF tags" not working (VSC-1354)

### ISSUE THREAD

**Issue by gonzabrusco** [espressif/vscode-esp-idf-extension#1193]
### OS

Windows

### Operating System version

Windows 11

### Visual Studio Code version

1.89.1 (latest)

### ESP-IDF version

4.4.4

### Python version

Latest

### Doctor command output

No applicable

### Description

When trying to configure the IDF extension, when I mark the option "Show all ESP-IDF tags" it does not update the list of available IDF versions to install. I want to install version 4.4.4 but it does not show in the list.

### Debug Message

```plain
No applicable
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by gonzabrusco** [comment]
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/2846883/15186e80-ad12-4abc-852e-d7dcbe9c7673)

**Comment by brianignacio5** [comment]
I'm not sure why but GitHub api https://api.github.com/repos/espressif/esp-idf/tags just show these tags.

**Comment by gonzabrusco** [comment]
Strange! Is there a way to force the extension to use 4.4.4? Or at least could you tell me how to do it manually?

**Comment by gonzabrusco** [comment]
I've found the problem @brianignacio5 

Github is limiting the amount of entries per request. You have to specify if you need more! 

For example:
https://api.github.com/repos/espressif/esp-idf/tags?per_page=5000

Doc:
https://docs.github.com/es/rest/using-the-rest-api/using-pagination-in-the-rest-api?apiVersion=2022-11-28
