### ISSUE TITLE
Something went wrong while trying to build the project, serial port don't work even after full system restart (VSC-1355)

### ISSUE THREAD

**Issue by DawidGurdzinski2** [espressif/vscode-esp-idf-extension#1194]
### OS

Windows

### Operating System version

Windows11

### Visual Studio Code version

1.89.1

### ESP-IDF version

5.1.1

### Python version

3.11.2

### Doctor command output

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.22631 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\CMake\bin;C:<HOMEPATH>\AppData\Local\Programs\Python\Python312\Scripts\;C:<HOMEPATH>\AppData\Local\Programs\Python\Python312\;C:<HOMEPATH>\AppData\Local\Programs\Python\Launcher\;C:<HOMEPATH>\AppData\Local\Microsoft\WindowsApps;C:\msys64\mingw64\bin;C:<HOMEPATH>\AppData\Local\Programs\Microsoft VS Code\bin 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.89.1 
Visual Studio Code language en 
Visual Studio Code shell C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.7.1 
Workspace folder c:<HOMEPATH>\Desktop\EspExample\AOSYW\EMG 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) C:\Users\Dawid\esp\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
ESP-HomeKit-SDK Path (idf.espHomeKitSdkPath) ${env:HOMEKIT_PATH}
Custom extra paths (idf.customExtraPaths) C:\Users\Dawid\.espressif\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin;C:\Users\Dawid\.espressif\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin;C:\Users\Dawid\.espressif\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin;C:\Users\Dawid\.espressif\tools\xtensa-esp32s2-elf\esp-12.2.0_20230208\xtensa-esp32s2-elf\bin;C:\Users\Dawid\.espressif\tools\xtensa-esp32s3-elf\esp-12.2.0_20230208\xtensa-esp32s3-elf\bin;C:\Users\Dawid\.espressif\tools\riscv32-esp-elf\esp-12.2.0_20230208\riscv32-esp-elf\bin;C:\Users\Dawid\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;C:\Users\Dawid\.espressif\tools\cmake\3.24.0\bin;C:\Users\Dawid\.espressif\tools\openocd-esp32\v0.12.0-esp32-20230419\openocd-esp32\bin;C:\Users\Dawid\.espressif\tools\ninja\1.10.2;C:\Users\Dawid\.espressif\tools\idf-exe\1.0.3;C:\Users\Dawid\.espressif\tools\ccache\4.8\ccache-4.8-windows-x86_64;C:\Users\Dawid\.espressif\tools\dfu-util\0.11\dfu-util-0.11-win64;C:\Users\Dawid\.espressif\tools\esp-rom-elfs\20230320
Custom extra vars (idf.customExtraVars)
    OPENOCD_SCRIPTS: C:\Users\Dawid\.espressif\tools\openocd-esp32\v0.12.0-esp32-20230419/openocd-esp32/share/openocd/scripts
    IDF_CCACHE_ENABLE: 1
    ESP_ROM_ELF_DIR: C:\Users\Dawid\.espressif\tools\esp-rom-elfs\20230320/
Virtual env Python Path (idf.pythonBinPath) C:\Users\Dawid\.espressif\python_env\idf5.1_py3.11_env\Scripts\python.exe
Serial port (idf.port) COM15
OpenOCD Configs (idf.openOcdConfigs) board/esp32c3-bridge.cfg
ESP-IDF Tools Path (idf.toolsPath) C:\Users\Dawid\.espressif
Git Path (idf.gitPath) C:<HOMEPATH>\.espressif\tools\idf-git\2.39.2\cmd\git.exe
Notification Mode (idf.notificationMode) All
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) false
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-HomeKit Path (idf.espHomeKitSdkPath) false
Access to ESP-IDF Custom extra paths
Access to C:\Users\Dawid\.espressif\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin: true
Access to C:\Users\Dawid\.espressif\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin: true
Access to C:\Users\Dawid\.espressif\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin: true
Access to C:\Users\Dawid\.espressif\tools\xtensa-esp32s2-elf\esp-12.2.0_20230208\xtensa-esp32s2-elf\bin: true
Access to C:\Users\Dawid\.espressif\tools\xtensa-esp32s3-elf\esp-12.2.0_20230208\xtensa-esp32s3-elf\bin: true
Access to C:\Users\Dawid\.espressif\tools\riscv32-esp-elf\esp-12.2.0_20230208\riscv32-esp-elf\bin: true
Access to C:\Users\Dawid\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: true
Access to C:\Users\Dawid\.espressif\tools\cmake\3.24.0\bin: true
Access to C:\Users\Dawid\.espressif\tools\openocd-esp32\v0.12.0-esp32-20230419\openocd-esp32\bin: true
Access to C:\Users\Dawid\.espressif\tools\ninja\1.10.2: true
Access to C:\Users\Dawid\.espressif\tools\idf-exe\1.0.3: true
Access to C:\Users\Dawid\.espressif\tools\ccache\4.8\ccache-4.8-windows-x86_64: true
Access to C:\Users\Dawid\.espressif\tools\dfu-util\0.11\dfu-util-0.11-win64: true
Access to C:\Users\Dawid\.espressif\tools\esp-rom-elfs\20230320: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path true
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-HomeKit-SDK Path (idf.espHomeKitSdkPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in C:\Users\Dawid\.espressif\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin: false
Spaces in C:\Users\Dawid\.espressif\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin: false
Spaces in C:\Users\Dawid\.espressif\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin: false
Spaces in C:\Users\Dawid\.espressif\tools\xtensa-esp32s2-elf\esp-12.2.0_20230208\xtensa-esp32s2-elf\bin: false
Spaces in C:\Users\Dawid\.espressif\tools\xtensa-esp32s3-elf\esp-12.2.0_20230208\xtensa-esp32s3-elf\bin: false
Spaces in C:\Users\Dawid\.espressif\tools\riscv32-esp-elf\esp-12.2.0_20230208\riscv32-esp-elf\bin: false
Spaces in C:\Users\Dawid\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: false
Spaces in C:\Users\Dawid\.espressif\tools\cmake\3.24.0\bin: false
Spaces in C:\Users\Dawid\.espressif\tools\openocd-esp32\v0.12.0-esp32-20230419\openocd-esp32\bin: false
Spaces in C:\Users\Dawid\.espressif\tools\ninja\1.10.2: false
Spaces in C:\Users\Dawid\.espressif\tools\idf-exe\1.0.3: false
Spaces in C:\Users\Dawid\.espressif\tools\ccache\4.8\ccache-4.8-windows-x86_64: false
Spaces in C:\Users\Dawid\.espressif\tools\dfu-util\0.11\dfu-util-0.11-win64: false
Spaces in C:\Users\Dawid\.espressif\tools\esp-rom-elfs\20230320: false
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.39.2.windows.1
ESP-IDF version x.x
Python version 3.11.2
Python's pip version 24.0
-------------------------------------------------- Project configuration settings ----------------------------------------------------------
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitarray version: 2.9.2
bitstring version: 4.2.2
CacheControl version: 0.14.0
certifi version: 2024.2.2
cffi version: 1.16.0
charset-normalizer version: 3.3.2
click version: 8.0.4
colorama version: 0.4.6
construct version: 2.10.70
contextlib2 version: 21.6.0
cryptography version: 39.0.2
ecdsa version: 0.19.0
esp-coredump version: 1.11.0
esp-debug-backend version: 1.0.3
esp-idf-kconfig version: 1.4.2
esp-idf-monitor version: 1.4.0
esp-idf-panic-decoder version: 1.0.1
esp-idf-size version: 1.3.0
esptool version: 4.7.0
filelock version: 3.14.0
freertos-gdb version: 1.0.3
idf-component-manager version: 1.5.2
idna version: 3.7
intelhex version: 2.3.0
kconfiglib version: 14.1.0
markdown-it-py version: 3.0.0
mdurl version: 0.1.2
msgpack version: 1.0.8
packaging version: 24.0
pip version: 24.0
pycparser version: 2.22
pyelftools version: 0.29
pygdbmi version: 0.9.0.2
Pygments version: 2.18.0
pyparsing version: 3.0.9
pyserial version: 3.5
pywin32 version: 306
PyYAML version: 6.0.1
reedsolo version: 1.7.0
requests version: 2.31.0
requests-file version: 1.5.1
requests-toolbelt version: 1.0.0
rich version: 13.7.1
schema version: 0.7.7
setuptools version: 69.5.1
six version: 1.16.0
tqdm version: 4.66.4
urllib3 version: 1.26.18
windows-curses version: 2.3.3
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Error
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Error
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "${config:idf.toolsPathWin}\\tools\\riscv32-esp-elf\\esp-12.2.0_20230208\\riscv32-esp-elf\\bin\\riscv32-esp-elf-gcc.exe",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${config:idf.espIdfPath}/App/**",
                "${config:idf.espIdfPathWin}/App/**",
                "${config:idf.espAdfPath}/App/**",
                "${config:idf.espAdfPathWin}/App/**",
                "${workspaceFolder}/build/config",
                "${workspaceFolder}/**"
            ],
           
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${config:idf.espIdfPath}/App",
                    "${config:idf.espIdfPathWin}/App",
                    "${config:idf.espAdfPath}/App/**",
                    "${config:idf.espAdfPathWin}/App/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
 
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at Unknown error in ESP-IDF Doctor Command
--------------------------------------------------------------------------------------------------------------------------------------------

### Description

I Can't use correctly esp-idf even after formatting whole system to base state (no personal data). Extension don't execute ninja command

### Debug Message

```plain
*  Executing task: ninja  

ninja: error: loading 'build.ninja': The system cannot find the file specified.


 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command ninja " terminated with exit code: 1.
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Could you share your extension log ?

Seems that there might be an issue with your python packages.

**Comment by DawidGurdzinski2** [comment]
i can't paste extension info because it have  166,970 chars. so i upload file.
[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/15376143/esp_idf_vsc_ext.log)

**Comment by brianignacio5** [comment]
It seems that the extension can't access your esp-idf directory `C:\\Users\\Dawid\\esp\\esp-idf` as described in 

`{"message":"Cannot access filePath: C:\\Users\\Dawid\\esp\\esp-idf","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\Dawid\\esp\\esp-idf'\n\tat Object.accessSync (node:fs:264:3)\n\tat t.accessSync (node:electron/js2c/node_init:2:8888)\n\tat ke (\\dist\\extension.js:2:1394261)\n\tat \\dist\\extension.js:2:1741020\n\tat \\dist\\extension.js:2:1741991\n\tat async \\dist\\extension.js:2:1739252","level":"error","timestamp":"2024-05-19T14:11:03.996Z"}`

**Comment by DawidGurdzinski2** [comment]
I think the problem is that somehow in Win11 esp-idf extension take my online account username instead of my computer username and use is as a path.
Is there any fix for that?

**Comment by brianignacio5** [comment]
Just update the `idf.espIdfPathWin` in your settings.json with the correct path or use the `ESP-IDF: Configure ESP-IDF extension` and use the correct path there.

**Comment by brianignacio5** [comment]
Closing this issue due to lack of response here. Comment here if you need more assistance.
