### ISSUE TITLE
[Feature Request]: Add "Reconfigure" Button (VSC-1356)

### ISSUE THREAD

**Issue by viayie** [espressif/vscode-esp-idf-extension#1197]
**Is your feature request related to a problem? Please describe.**
After making changes in the `SDK Configuration Editor(menuconfig)` and saving them, I have to trigger a full build to regenerate the `compile_command.json`. 
This is necessary for vscode to correctly expand macros, enabling accurate code navigation and inactive code region display. However, a full build is time-consuming and not always necessary.
<img width="718" alt="image" src="https://github.com/espressif/vscode-esp-idf-extension/assets/44696504/c0c575d3-ac85-4559-8a6d-5e1a2681e796">

**Describe the solution you'd like**
I would like a solution similar to other commands (`Build`, `Full Clean`, `Flash`, `Monitor`, etc). Specifically, I would like a `Reconfigure` button that corresponds to the `idf.py reconfigure` function. This would allow me to regenerate the `compile_command.json` without triggering a full build.
<img width="266" alt="image" src="https://github.com/espressif/vscode-esp-idf-extension/assets/44696504/09ffcf88-717e-4127-853a-c945a4285c67">

**Describe alternatives you've considered**
I've considered manually running `idf.py reconfigure` in the `Open ESP-IDF terminal`, but it is not as convenient as having a dedicated `Reconfigure` button directly in the editor.

**Additional context**
None.

**Comment by Chris-R-U** [comment]
I find the problem too，thanks boy

**Comment by brianignacio5** [comment]
Please try this feature with this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/1526620398.zip)
