### ISSUE TITLE
[vscode Registers/Peripherals change]:  (VSC-1358)

### ISSUE THREAD

**Issue by ilangr-skyplug** [espressif/vscode-esp-idf-extension#1199]
I was able to configure my vscode to enter debug when using ESP-PROG that is connected to ESP32-S3-DevKitC-1-N8 JTAG.
I can see watch, disassembly, memory, stack, registers & ESP-IDF: Peripherals.
For some reason I can't change the value of any of the registers or ESP peripherals in debug. 
All modern IDEs allows the programmer to change registers on the fly...
I was asked by your support to open a ticket for it

**Comment by brianignacio5** [comment]
Have you try with the new Eclipse CDT Adapter in master ?

**Comment by ilangr-skyplug** [comment]
Hi @brianignacio5 ,
No I haven't tried it. Is it a vscode extension?

**Comment by brianignacio5** [comment]
So in [this Pull Request](https://github.com/espressif/vscode-esp-idf-extension/pull/1131) we added a new debug adapter from Eclipse CDT team here which should improve the debugging experience.

Please take a look with current GitHub master [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/workflows/ci/master/esp-idf-extension.vsix.zip) and follow the update [debugging tutorial](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/debugging.md)

**Comment by ilangr-skyplug** [comment]
Thanks @brianignacio5 . I'll look at it
