### ISSUE TITLE
groupadd fails (VSC-1360)

### ISSUE THREAD

**Issue by powerteqtpitman** [espressif/vscode-esp-idf-extension#1201]
### OS

Windows

### Operating System version

Windows 10

### Visual Studio Code version

1.89.1

### ESP-IDF version

latest

### Python version

3.10

### Doctor command output

I don't know how to get this

### Description

I am following this tutorial: https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/using-docker-container.md

When I get to the step of opening the dev container I get the following output and then a dialog that says it failed:

https://pastebin.com/p847zTaS

### Debug Message

```plain
I am not getting this far
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Open your project `.devcontainer` directory `Dockerfile` and change `ARG USER_UID=1000` to `ARG USER_UID=1050`

**Comment by powerteqtpitman** [comment]
That fixed it. Thanks.
