### ISSUE TITLE
[Feature Request]: add KCONFIG option name in UI (VSC-1423)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/vscode-esp-idf-extension#1240]
## Feature Request

When hitting the (i) button, it should say the name of the KCONFIG option. e.g. CONFIG_COMPILER_STACK_CHECK or whatever

Why? I like to use the UI to explore the various options. But then to actually search it online, or in my code, etc, I need to know the real name.

Finding out the real name from the UI is hard. 

---

<img width="451" alt="Screenshot 2024-07-03 at 2 16 36 PM" src="https://github.com/espressif/vscode-esp-idf-extension/assets/1863934/cf1de795-84ef-40b2-9b26-f4d72c7414a4">

**Comment by brianignacio5** [comment]
Hi @chipweinberger could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/1676829356.zip) ? We made this feature in #1241

**Comment by chipweinberger** [comment]
i'm away for a few weeks on vacation, but thanks @brianignacio5 

this is really nice  

Ill try to find a moment :)
