### ISSUE TITLE
[Feature Request]: Option to omit stopping at app_main (VSC-1438)

### ISSUE THREAD

**Issue by gudvinr** [espressif/vscode-esp-idf-extension#1253]
**Is your feature request related to a problem? Please describe.**

I never break on `app_main` entry unless I want to specifically debug startup process from get-go.

You can't simply set breakpoint whenever you want and then build, flash and wait for breakpoint to trigger.  
You need to wait for app_main triggering first and then continue.

**Describe the solution you'd like**

Add an option to suppress breaking on `app_main`.  

`esp_debug_backend` already has `start_func` parameter in `exec_run`, which can be set to empty string to skip adding breakpoint.

~~**Describe alternatives you've considered**~~

~~**Additional context**~~

**Comment by brianignacio5** [comment]
So by default the new debug adapter  has these init commands (not written in launch.json itself but in extension code):

```json
"initCommands": [
        "set remote hardware-watchpoint-limit {IDF_TARGET_CPU_WATCHPOINT_NUM}",
        "mon reset halt",
        "maintenance flush register-cache",
        "thb app_main"
      ],
```

You can open the launch.json and modify `initCommands` to remove line that sets breakpoint in app_main `thb app_main`.

```json
"initCommands": [
        "set remote hardware-watchpoint-limit {IDF_TARGET_CPU_WATCHPOINT_NUM}",
        "mon reset halt",
        "maintenance flush register-cache"
      ],
```

**Comment by brianignacio5** [comment]
How about we add the `c` after the `thb app_main` as done in [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/using-debugger.html#command-line) ? 

I'm trying to keep default behavior as default as possible. Although is possible to add something like `runToEntryPoint ` a regular will prefer just to set a breakpoint in the debugger UI itself.

**Comment by brianignacio5** [comment]
I've made these changes in #1261 

You can try these changes using this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/1738641938.zip) to see if it works for you. Same for the trailing comma issue here.

**Comment by brianignacio5** [comment]
Sorry for late reply @gudvinr  I've added the launch.json `initialBreakpoint` option and remove the initial breakpoint from being set by default. So if user wants to have a breakpoint in app_main the would need `initialBreakpoint: "app_main"` in launch.json.

**Comment by brianignacio5** [comment]
Can you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/1784799047.zip) ?

Setting `"initialBreakpoint" : ""` should ignore the initial breakpoint.

**Comment by brianignacio5** [comment]
If you find the extension useful. Please leave us a review in the [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension)
