### ISSUE TITLE
ERROR : Invalid ESP-IDF while configuring esp-idf extension (VSC-1440)

### ISSUE THREAD

**Issue by sunilkumar105** [espressif/vscode-esp-idf-extension#1255]
### OS

Windows

### Operating System version

11

### Visual Studio Code version

1.9.1.1

### ESP-IDF version

1.8.0

### Python version

3.8.7

### Doctor command output

Looking in links: c:\Users\sunil\AppData\Local\Temp\tmpb_5u636i

Processing c:\users\sunil\appdata\local\temp\tmpb_5u636i\setuptools-65.5.0-py3-none-any.whl

Processing c:\users\sunil\appdata\local\temp\tmpb_5u636i\pip-22.3.1-py3-none-any.whl

Installing collected packages: setuptools, pip

Successfully installed pip-22.3.1 setuptools-65.5.0

Invalid ESP-IDF

### Extension

Looking in links: c:\Users\sunil\AppData\Local\Temp\tmpb_5u636i

Processing c:\users\sunil\appdata\local\temp\tmpb_5u636i\setuptools-65.5.0-py3-none-any.whl

Processing c:\users\sunil\appdata\local\temp\tmpb_5u636i\pip-22.3.1-py3-none-any.whl

Installing collected packages: setuptools, pip

Successfully installed pip-22.3.1 setuptools-65.5.0

Invalid ESP-IDF

### Description

i tried everything, changing version of esp-idf and all

### Debug Message

```plain
Looking in links: c:\Users\sunil\AppData\Local\Temp\tmpb_5u636i

Processing c:\users\sunil\appdata\local\temp\tmpb_5u636i\setuptools-65.5.0-py3-none-any.whl

Processing c:\users\sunil\appdata\local\temp\tmpb_5u636i\pip-22.3.1-py3-none-any.whl

Installing collected packages: setuptools, pip

Successfully installed pip-22.3.1 setuptools-65.5.0

Invalid ESP-IDF
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
You just copied the output 3 times in the different sections. You provide no information required by the issue template. 

How are we to understand your environment or find where the error is if you skip the required troubleshooting information ?
