### ISSUE TITLE
cp command does not take -n anymore  (VSC-1441)

### ISSUE THREAD

**Issue by hpuri** [espressif/vscode-esp-idf-extension#1256]
### OS

Linux

### Operating System version

24.04

### Visual Studio Code version

1.91.1

### ESP-IDF version

5.x

### Python version

3.9

### Doctor command output

not relevant

### Extension

ESP-IDF Extension for Visual Studio Code
All settings have been configured.
For Linux users, OpenOCD needs to add 60-openocd.rules for permission delegation in USB devices to be added in /etc/udev/rules.d/.

Run this command in a terminal with sudo privileges:

sudo cp -n /home/hmp/.espressif/tools/openocd-esp32/v0.12.0-esp32-20240318/openocd-esp32/share/openocd/contrib/60-openocd.rules /etc/udev/rules.d

The command should be changed to 

sudo cp --update=none /home/hmp/.espressif/tools/openocd-esp32/v0.12.0-esp32-20240318/openocd-esp32/share/openocd/contrib/60-openocd.rules /etc/udev/rules.d

### Description

syntax of a command while setting up a new environment in linux is incorrect

### Debug Message

```plain
NA
```

### Other Steps to Reproduce

sudo cp -n /home/hmp/.espressif/tools/openocd-esp32/v0.12.0-esp32-20240318/openocd-esp32/share/openocd/contrib/60-openocd.rules /etc/udev/rules.d
Version: 1.8.0
See what's new
Repository
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
Version:: command not found
> 

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by radurentea** [comment]
Hi @hpuri,

Thank you for bringing this to our attention and suggesting the improved command!
