### ISSUE TITLE
[Feature Request]: Sort related functions in a reasonable order (VSC-1457)

### ISSUE THREAD

**Issue by Tinyu-Zhao** [espressif/vscode-esp-idf-extension#1273]
**Is your feature request related to a problem? Please describe.**

I don't know from which version, compile project, burn program, serial monitor and build & flash & monitor are separated by "burn mode" selection and "debug"

In many cases, the burning mode of a project is basically unchanged. Debugging is very common and can be placed in the front. The current function arrangement position feels very unreasonable. The most commonly used "four-piece set": compile project, burn program, serial monitor and build & flash & monitor are separated by "burn mode" selection and "debug".

I feel it is very awkward to use. I have to look at the picture before clicking every time.

<img width="736" alt="image" src="https://github.com/user-attachments/assets/cc48bdba-55ea-4322-ac71-957e82e29e24">

**Describe the solution you'd like**

I want to sort them in the order of "Build Project, Burn Device, Serial Monitor, Build & Flash & Monitor".
Just like the previous version, Please put debugging and selecting burning mode in other places, do not break the order of "Build Project, Burn Device, Serial Monitor, Build & Flash & Monitor"
<img width="407" alt="image" src="https://github.com/user-attachments/assets/b4da17da-9404-4af9-bfef-9644f72572cf">

**Comment by brianignacio5** [comment]
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/1846487595.zip) ?

**Comment by Tinyu-Zhao** [comment]
This extention does a great job, thank you very much.
