### ISSUE TITLE
"Configure ESP-IDF extension" fails to install GCC toolchains (VSC-1481)

### ISSUE THREAD

**Issue by badlogic** [espressif/vscode-esp-idf-extension#1301]
### OS

MacOS

### Operating System version

macOS 14.5 (23F79)

### Visual Studio Code version

1.81.1

### ESP-IDF version

1.6.5

### Python version

3.12.5

### Doctor command output

N/A

### Extension

Installing package GDB for Xtensa
Installing tar.gz package GDB for Xtensa
Installing package GDB for RISC-V
Installing tar.gz package GDB for RISC-V
Installing package Toolchain for Xtensa (ESP32) based on GCC
Current system platform: macos-arm64
Installing tools: 

Installing package Toolchain for Xtensa (ESP32-S2) based on GCC
Current system platform: macos-arm64
Installing tools: 

Installing package Toolchain for Xtensa (ESP32-S3) based on GCC
Current system platform: macos-arm64
Installing tools: 

Installing package Toolchain for 32-bit RISC-V based on GCC
Current system platform: macos-arm64
Installing tools: 

Installing package Toolchain for ESP32 ULP coprocessor
Installing tar.gz package Toolchain for ESP32 ULP coprocessor
Installing package OpenOCD for ESP32
Installing tar.gz package OpenOCD for ESP32
Installing package ESP ROM ELFs
Installing tar.gz package ESP ROM ELFs

Creating a new Python environment in /Users/badlogic/.espressif/python_env/idf5.1_py3.12_env
Downloading https://dl.espressif.com/dl/esp-idf/espidf.constraints.v5.1.txt
Destination: /Users/badlogic/.espressif/espidf.constraints.v5.1.txt.tmp

0%
100%
Done
Looking in indexes: https://pypi.org/simple, https://dl.espressif.com/pypi
Ignoring importlib_metadata: markers 'python_version < "3.8"' don't match your environment
Collecting setuptools (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 3))
  Using cached https://dl.espressif.com/pypi/setuptools/setuptools-71.0.0-py3-none-any.whl (908 kB)
Collecting packaging (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 4))
  Using cached https://dl.espressif.com/pypi/packaging/packaging-24.1-py3-none-any.whl (53 kB)
Collecting click (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 7))
  Using cached https://dl.espressif.com/pypi/click/click-8.1.7-py3-none-any.whl (97 kB)
Collecting pyserial (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 8))
  Using cached https://dl.espressif.com/pypi/pyserial/pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting cryptography (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 9))
  Using cached https://dl.espressif.com/pypi/cryptography/cryptography-39.0.2-cp36-abi3-macosx_10_12_universal2.whl (5.4 MB)
Collecting pyparsing (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 10))
  Using cached https://dl.espressif.com/pypi/pyparsing/pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting pyelftools (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 11))
  Using cached https://dl.espressif.com/pypi/pyelftools/pyelftools-0.29-py2.py3-none-any.whl (174 kB)
Collecting idf-component-manager (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/idf-component-manager/idf_component_manager-2.0.3-py3-none-any.whl (150 kB)
Collecting esp-coredump (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 13))
  Using cached https://dl.espressif.com/pypi/esp-coredump/esp_coredump-1.11.0-py3-none-any.whl (45 kB)
Collecting esptool (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 14))
  Using cached https://dl.espressif.com/pypi/esptool/esptool-4.7.0-py3-none-any.whl (370 kB)
Collecting esp-idf-kconfig (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 15))
  Using cached https://dl.espressif.com/pypi/esp-idf-kconfig/esp_idf_kconfig-1.4.3-py3-none-any.whl (44 kB)
Collecting esp-idf-monitor (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 16))
  Using cached https://dl.espressif.com/pypi/esp-idf-monitor/esp_idf_monitor-1.4.0-py3-none-any.whl (44 kB)
Collecting esp-idf-size (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 17))
  Using cached https://dl.espressif.com/pypi/esp-idf-size/esp_idf_size-1.5.0-py3-none-any.whl (76 kB)
Collecting esp-idf-panic-decoder (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 18))
  Using cached https://dl.espressif.com/pypi/esp-idf-panic-decoder/esp_idf_panic_decoder-1.1.0-py3-none-any.whl (18 kB)
Collecting construct (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 19))
  Using cached https://dl.espressif.com/pypi/construct/construct-2.10.70-py3-none-any.whl (63 kB)
Collecting freertos_gdb (from -r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 22))
  Using cached https://dl.espressif.com/pypi/freertos-gdb/freertos_gdb-1.0.3-py3-none-any.whl (14 kB)
Collecting cffi>=1.12 (from cryptography->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 9))
  Using cached https://dl.espressif.com/pypi/cffi/cffi-1.17.0-cp312-cp312-macosx_11_0_arm64.whl (178 kB)
Collecting colorama (from idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/colorama/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting pyyaml (from idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/pyyaml/PyYAML-6.0.2-cp312-cp312-macosx_11_0_arm64.whl (173 kB)
Collecting requests (from idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/requests/requests-2.32.3-py3-none-any.whl (64 kB)
Collecting requests-file (from idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/requests-file/requests_file-2.1.0-py2.py3-none-any.whl (4.2 kB)
Collecting requests-toolbelt (from idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/requests-toolbelt/requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Collecting tqdm (from idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/tqdm/tqdm-4.66.5-py3-none-any.whl (78 kB)
Collecting jsonref (from idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/jsonref/jsonref-1.1.0-py3-none-any.whl (9.4 kB)
Collecting pydantic (from idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/pydantic/pydantic-2.8.2-py3-none-any.whl (423 kB)
Collecting pydantic-core (from idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached pydantic_core-2.23.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.6 kB)
Collecting pydantic-settings (from idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/pydantic-settings/pydantic_settings-2.4.0-py3-none-any.whl (23 kB)
Collecting pygdbmi>=0.9.0.2 (from esp-coredump->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 13))
  Using cached https://dl.espressif.com/pypi/pygdbmi/pygdbmi-0.11.0.0-py3-none-any.whl (21 kB)
Collecting bitstring>=3.1.6 (from esptool->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 14))
  Using cached https://dl.espressif.com/pypi/bitstring/bitstring-4.2.3-py3-none-any.whl (71 kB)
Collecting ecdsa>=0.16.0 (from esptool->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 14))
  Using cached https://dl.espressif.com/pypi/ecdsa/ecdsa-0.19.0-py2.py3-none-any.whl (149 kB)
Collecting reedsolo<1.8,>=1.5.3 (from esptool->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 14))
  Using cached https://dl.espressif.com/pypi/reedsolo/reedsolo-1.7.0-py3-none-any.whl (32 kB)
Collecting intelhex (from esptool->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 14))
  Using cached https://dl.espressif.com/pypi/intelhex/intelhex-2.3.0-py2.py3-none-any.whl (50 kB)
Collecting kconfiglib>=13.7.1 (from esp-idf-kconfig->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 15))
  Using cached https://dl.espressif.com/pypi/kconfiglib/kconfiglib-14.1.0-py2.py3-none-any.whl (145 kB)
Collecting rich (from esp-idf-size->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 17))
  Using cached https://dl.espressif.com/pypi/rich/rich-13.8.0-py3-none-any.whl (241 kB)
Collecting bitarray<3.0.0,>=2.9.0 (from bitstring>=3.1.6->esptool->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 14))
  Using cached https://dl.espressif.com/pypi/bitarray/bitarray-2.9.2-cp312-cp312-macosx_11_0_arm64.whl (124 kB)
Collecting pycparser (from cffi>=1.12->cryptography->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 9))
  Using cached https://dl.espressif.com/pypi/pycparser/pycparser-2.22-py3-none-any.whl (117 kB)
Collecting six>=1.9.0 (from ecdsa>=0.16.0->esptool->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 14))
  Using cached https://dl.espressif.com/pypi/six/six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting annotated-types>=0.4.0 (from pydantic->idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/annotated-types/annotated_types-0.7.0-py3-none-any.whl (13 kB)
Collecting pydantic-core (from idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/pydantic-core/pydantic_core-2.20.1-cp312-cp312-macosx_11_0_arm64.whl (1.8 MB)
Collecting typing-extensions>=4.6.1 (from pydantic->idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/typing-extensions/typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting python-dotenv>=0.21.0 (from pydantic-settings->idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/python-dotenv/python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Collecting charset-normalizer<4,>=2 (from requests->idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/charset-normalizer/charset_normalizer-3.3.2-cp312-cp312-macosx_11_0_arm64.whl (119 kB)
Collecting idna<4,>=2.5 (from requests->idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/idna/idna-3.8-py3-none-any.whl (66 kB)
Collecting urllib3<3,>=1.21.1 (from requests->idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/urllib3/urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
Collecting certifi>=2017.4.17 (from requests->idf-component-manager->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 12))
  Using cached https://dl.espressif.com/pypi/certifi/certifi-2024.8.30-py3-none-any.whl (167 kB)
Collecting markdown-it-py>=2.2.0 (from rich->esp-idf-size->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 17))
  Using cached https://dl.espressif.com/pypi/markdown-it-py/markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich->esp-idf-size->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 17))
  Using cached https://dl.espressif.com/pypi/pygments/pygments-2.18.0-py3-none-any.whl (1.2 MB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->esp-idf-size->-r /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt (line 17))
  Using cached https://dl.espressif.com/pypi/mdurl/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: reedsolo, pyserial, pygdbmi, pyelftools, intelhex, bitarray, urllib3, typing-extensions, tqdm, six, setuptools, pyyaml, python-dotenv, pyparsing, pygments, pycparser, packaging, mdurl, kconfiglib, jsonref, idna, freertos_gdb, esp-idf-panic-decoder, construct, colorama, click, charset-normalizer, certifi, bitstring, annotated-types, requests, pydantic-core, markdown-it-py, esp-idf-kconfig, ecdsa, cffi, rich, requests-toolbelt, requests-file, pydantic, cryptography, pydantic-settings, esptool, esp-idf-size, idf-component-manager, esp-coredump, esp-idf-monitor
Successfully installed annotated-types-0.7.0 bitarray-2.9.2 bitstring-4.2.3 certifi-2024.8.30 cffi-1.17.0 charset-normalizer-3.3.2 click-8.1.7 colorama-0.4.6 construct-2.10.70 cryptography-39.0.2 ecdsa-0.19.0 esp-coredump-1.11.0 esp-idf-kconfig-1.4.3 esp-idf-monitor-1.4.0 esp-idf-panic-decoder-1.1.0 esp-idf-size-1.5.0 esptool-4.7.0 freertos_gdb-1.0.3 idf-component-manager-2.0.3 idna-3.8 intelhex-2.3.0 jsonref-1.1.0 kconfiglib-14.1.0 markdown-it-py-3.0.0 mdurl-0.1.2 packaging-24.1 pycparser-2.22 pydantic-2.8.2 pydantic-core-2.20.1 pydantic-settings-2.4.0 pyelftools-0.29 pygdbmi-0.11.0.0 pygments-2.18.0 pyparsing-3.0.9 pyserial-3.5 python-dotenv-1.0.1 pyyaml-6.0.2 reedsolo-1.7.0 requests-2.32.3 requests-file-2.1.0 requests-toolbelt-1.0.0 rich-13.8.0 setuptools-71.0.0 six-1.16.0 tqdm-4.66.5 typing-extensions-4.12.2 urllib3-1.26.20
Installing Python packages
 Constraint file: /Users/badlogic/.espressif/espidf.constraints.v5.1.txt
 Requirement files:
  - /Users/badlogic/esp/esp-idf/tools/requirements/requirements.core.txt

Installing ESP-IDF extension python packages in /Users/badlogic/.espressif/python_env/idf5.1_py3.12_env/bin/python ...

Collecting gcovr (from -r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/requirements.txt (line 1))
  Using cached gcovr-7.2-py2.py3-none-any.whl.metadata (10.0 kB)
Collecting websocket_client (from -r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/requirements.txt (line 2))
  Using cached websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
Collecting jinja2 (from gcovr->-r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/requirements.txt (line 1))
  Using cached Jinja2-3.0.3-py3-none-any.whl.metadata (3.5 kB)
Collecting lxml (from gcovr->-r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/requirements.txt (line 1))
  Using cached lxml-5.3.0-cp312-cp312-macosx_10_9_universal2.whl.metadata (3.8 kB)
Collecting colorlog (from gcovr->-r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/requirements.txt (line 1))
  Using cached colorlog-6.8.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pygments>=2.13.0 in /Users/badlogic/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages (from gcovr->-r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/requirements.txt (line 1)) (2.18.0)
Collecting MarkupSafe>=2.0 (from jinja2->gcovr->-r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/requirements.txt (line 1))
  Using cached MarkupSafe-2.1.5-cp312-cp312-macosx_10_9_universal2.whl.metadata (3.0 kB)
Using cached gcovr-7.2-py2.py3-none-any.whl (198 kB)
Using cached websocket_client-1.8.0-py3-none-any.whl (58 kB)
Using cached colorlog-6.8.2-py3-none-any.whl (11 kB)
Using cached Jinja2-3.0.3-py3-none-any.whl (133 kB)
Using cached lxml-5.3.0-cp312-cp312-macosx_10_9_universal2.whl (8.2 MB)
Using cached MarkupSafe-2.1.5-cp312-cp312-macosx_10_9_universal2.whl (18 kB)
Installing collected packages: websocket_client, MarkupSafe, lxml, colorlog, jinja2, gcovr
Successfully installed MarkupSafe-2.1.5 colorlog-6.8.2 gcovr-7.2 jinja2-3.0.3 lxml-5.3.0 websocket_client-1.8.0

Installing ESP-IDF Debug Adapter python packages in /Users/badlogic/.espressif/python_env/idf5.1_py3.12_env/bin/python ...

Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Requirement already satisfied: setuptools>=21 in /Users/badlogic/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages (from -r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/esp_debug_adapter/requirements.txt (line 1)) (71.0.0)
Collecting setuptools>=21 (from -r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/esp_debug_adapter/requirements.txt (line 1))
  Using cached setuptools-74.0.0-py3-none-any.whl.metadata (6.7 kB)
Collecting click (from -r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/esp_debug_adapter/requirements.txt (line 3))
  Using cached click-8.0.4-py3-none-any.whl.metadata (3.2 kB)
Collecting esp-debug-backend (from -r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/esp_debug_adapter/requirements.txt (line 4))
  Using cached esp_debug_backend-1.0.3-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: requests>=2.21.0 in /Users/badlogic/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages (from -r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/esp_debug_adapter/requirements.txt (line 6)) (2.32.3)
Collecting pygdbmi>=0.9.0.0 (from esp-debug-backend->-r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/esp_debug_adapter/requirements.txt (line 4))
  Using cached pygdbmi-0.9.0.2-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/badlogic/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages (from requests>=2.21.0->-r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/esp_debug_adapter/requirements.txt (line 6)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/badlogic/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages (from requests>=2.21.0->-r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/esp_debug_adapter/requirements.txt (line 6)) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/badlogic/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages (from requests>=2.21.0->-r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/esp_debug_adapter/requirements.txt (line 6)) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /Users/badlogic/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages (from requests>=2.21.0->-r /Users/badlogic/.vscode/extensions/espressif.esp-idf-extension-1.6.5/esp_debug_adapter/requirements.txt (line 6)) (2024.8.30)
Using cached setuptools-74.0.0-py3-none-any.whl (1.3 MB)
Using cached click-8.0.4-py3-none-any.whl (97 kB)
Using cached esp_debug_backend-1.0.3-py3-none-any.whl (23 kB)
Using cached pygdbmi-0.9.0.2-py3-none-any.whl (16 kB)
Installing collected packages: pygdbmi, setuptools, esp-debug-backend, click
  Attempting uninstall: pygdbmi
    Found existing installation: pygdbmi 0.11.0.0
    Uninstalling pygdbmi-0.11.0.0:
      Successfully uninstalled pygdbmi-0.11.0.0
  Attempting uninstall: setuptools
    Found existing installation: setuptools 71.0.0
    Uninstalling setuptools-71.0.0:
      Successfully uninstalled setuptools-71.0.0
  Attempting uninstall: click
    Found existing installation: click 8.1.7
    Uninstalling click-8.1.7:
      Successfully uninstalled click-8.1.7
Successfully installed click-8.0.4 esp-debug-backend-1.0.3 pygdbmi-0.9.0.2 setuptools-74.0.0

Python requirements has been installed
/bin/sh: riscv32-esp-elf-gcc: command not found
Command failed: riscv32-esp-elf-gcc --version
/bin/sh: riscv32-esp-elf-gcc: command not found
Error checking riscv32-esp-elf version
Error: Command failed: riscv32-esp-elf-gcc --version
/bin/sh: riscv32-esp-elf-gcc: command not found

/bin/sh: xtensa-esp32s3-elf-gcc: command not found
Command failed: xtensa-esp32s3-elf-gcc --version
/bin/sh: xtensa-esp32s3-elf-gcc: command not found
Error checking xtensa-esp32s3-elf version
Error: Command failed: xtensa-esp32s3-elf-gcc --version
/bin/sh: xtensa-esp32s3-elf-gcc: command not found

/bin/sh: xtensa-esp32s2-elf-gcc: command not found
Command failed: xtensa-esp32s2-elf-gcc --version
/bin/sh: xtensa-esp32s2-elf-gcc: command not found
Error checking xtensa-esp32s2-elf version
Error: Command failed: xtensa-esp32s2-elf-gcc --version
/bin/sh: xtensa-esp32s2-elf-gcc: command not found

/bin/sh: xtensa-esp32-elf-gcc: command not found
Command failed: xtensa-esp32-elf-gcc --version
/bin/sh: xtensa-esp32-elf-gcc: command not found
Error checking xtensa-esp32-elf version
Error: Command failed: xtensa-esp32-elf-gcc --version
/bin/sh: xtensa-esp32-elf-gcc: command not found

/usr/bin/git

### Description

When installing ESP-IDF through this extension (`CMD + P > ESP-IDF: Configure ESP-IDF extension` using the `Express` setup), everything gets downloaded properly, including the various GCC toolchains in `.espressif/dist`. 

But the extension fails to unpack these GCC toolchains. See the end of the log output above, which probes for the existance of each GCC version and fails.

For some reason, not all tar.xz/gz files in `.espressif/dist` are not unpacked. The extension successfully unpacks the following tools into `.espressif/tools`

- esp-rom-elfs
- esp32ulp-elf
- openocd-esp32
- riscv32-esp-elf-gdb
- xtensa-esp-elf-gdb

It fails for all other GCC toolchains. It appears the extension does not set the targets that should get installed. The `install.sh` script that comes with ESP-IDF sets all targets for installation by default. I assume the extension does not?

The problem can be fixed, by opening a terminal and executing `~/esp/esp-idf/install.sh`. The script successfully unpacks the remaining files in `.espressif/dist`.

I have not tried the installation process on another machine (as I lack a second machine). If this is indeed an issue on all Macs, it will confuse a lot of new comers :)

### Debug Message

```plain
N/A
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
You are using an old version of the extension. Could you try updating to newest version first ?

**Comment by badlogic** [comment]
Ah, you're right! I'm stuck on an older VS Code build. The extension manager installed the the latest compatible ESP-IDF exfension, which is indeed quite old.

Newest VS Code + newest ESP-IDF extension works as intended! Sorry for adding to the work load unnecessarily!

**Comment by brianignacio5** [comment]
No worries, that what we are here for !

If you find the extension useful, please consider leaving us a review in the [Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension)
