### ISSUE TITLE
[Feature Request]: Allow setting hostname for the extension when running code-server in docker environment and / or with tailscale (VSC-1490)

### ISSUE THREAD

**Issue by csvke** [espressif/vscode-esp-idf-extension#1311]
**Is your feature request related to a problem? Please describe.**
When running ESP-IDF VS Code extension installed in a Code-Server instance on a host machine, clinking `Configure ESP-IDF Extension` returns a blank page when visit by a browser in a client.
Seems to me the extension is trying to load the page in localhost, which makes sense if the extension is installed locally on a machine, but it will not work if VS Code is accessed through a browser remotely with Code Server. 
Using `code-server --host x.x.x.x` will not work in this case as that parameter aren't passed through to the code executed in individual VS Code extensions.

**Describe the solution you'd like**
I suspect if the ESP-IDF VS Code extension can define it's hostname instead of `localhost`, `Configure ESP-IDF Extension` can be loaded because Code-Server will automatically configure auto forwarding with proxy.
The goal is to have a host machine like a Raspberry Pi to connect to a ESP32 and start to program and debug with it via a web browser. 

**Describe alternatives you've considered**
Tried to look into `package.json` but only `OpenOCD Server` can have a customised hostname.

**Comment by brianignacio5** [comment]
When you open the `ESP-IDF: Configure ESP-IDF extension`, could you open the Command Palette (F1) and find the `Webview: Open Webview Developer Tools` and check if there is any error in the console output.

**Comment by brianignacio5** [comment]
Closing this issue for lack of response. Comment here if you need more assistance.
