### ISSUE TITLE
Same icon for different functions (VSC-1493)

### ISSUE THREAD

**Issue by SergeyKharenko** [espressif/vscode-esp-idf-extension#1316]
### OS

Linux

### Operating System version

Fedora Linux 40

### Visual Studio Code version

1.93.1

### ESP-IDF version

v5.2.2

### Python version

3.12.6

### Doctor command output

No need~

### Description

`SDK Configuration Editor` and `Build Project` have the same icon(gear icon) on status bar. This caused a lot of trouble for development～
This problem occurs on at least 3 machines with the fedora40 system, and the best way to reproduce it is to do nothing, just find a random fedora40 system and install this plugin,  quite simple!
In previous versions I remember that `Build Project` was marked as a **Cylinder**, was it modified in a recent update?
It may not be difficult to solve, hope it can be solved soon ♥️♥️♥️
![image](https://github.com/user-attachments/assets/cd5b0d7e-7fa3-4ae1-a7c6-49f92614dcaa)

### Debug Message

```plain
No need~
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Which version of this extension are you using ? 

The latest marketplace version has updated the build icon in status bar.

**Comment by SergeyKharenko** [comment]
It seems that the icon theme on vscode caused this issue. It could be closed. 
Thank you very much for your answer!!!
