### ISSUE TITLE
Hide "Search Error Hints" Tab (VSC-1500)

### ISSUE THREAD

**Issue by shebbys** [espressif/vscode-esp-idf-extension#1325]
### OS

MacOS

### Operating System version

13.4.1

### Visual Studio Code version

1.93.1

### ESP-IDF version

1.8.1

### Python version

3.9.16

### Doctor command output

n/a

### Description

How do you hide the "ESP-IDF: Search Error Hints" Tab?

<img width="370" alt="Screenshot 2024-10-03 at 12 27 01 PM" src="https://github.com/user-attachments/assets/04400cbc-26cf-4c20-be0f-bea7771ad5f3">

### Debug Message

```plain
n/a
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by radurentea** [comment]
Hi @shebbys,

To hide the functionality you just need to right click the "..." and deselect it like in this screenshot:
![image](https://github.com/user-attachments/assets/e878312b-1eb2-4217-9d4c-588ac93ce4b2)

Or right click directly the "ESP-IDF: Search Error Hint" and press the Hide option:
![image](https://github.com/user-attachments/assets/8f3839be-d45b-43aa-a153-51187bbc0cb7)

Let me know if you've managed to hide it!

**Comment by shebbys** [comment]
For some reason I dont have the same options when I do that:

<img width="477" alt="Screenshot 2024-10-07 at 9 45 46 AM" src="https://github.com/user-attachments/assets/ab522aea-0489-431b-87a3-3953c76ccd3a">

**Comment by radurentea** [comment]
You are using left click, but you need to use right click

**Comment by shebbys** [comment]
OMG THANK YOU!! 

I had to use an external mouse to get the right click to work!
