### ISSUE TITLE
Debugger problem with project configuration added (VSC-1512)

### ISSUE THREAD

**Issue by executer-uno** [espressif/vscode-esp-idf-extension#1334]
### OS

Windows

### Operating System version

Windows 10 Pro

### Visual Studio Code version

1.8.0 (with hotfix from here https://github.com/espressif/vscode-esp-idf-extension/issues/1283)

### ESP-IDF version

5.1.4

### Python version

Python 3.11.2

### Doctor command output

[DOCTOR_output.txt](https://github.com/user-attachments/files/17598261/DOCTOR_output.txt)

### Extension

[extensionLOG.txt](https://github.com/user-attachments/files/17598207/extensionLOG.txt)

### Description

I have a project for ESP32S3 with Project Configurations added. And as soon as configurations were added - JTAG Debug failed to launch (debug via ESP32S3 built in USB JTAG).
So I made some workaround, based on clear [HelloWorld example](https://github.com/espressif/esp-idf/tree/master/examples/get-started/hello_world) - there are two projects in attached archive - hello_world and hello_world_no_config. Second one works great, so Im sure thar hardware and environment are Ok and able to debug via ESP32S3 built in USB JTAG, but project with configuration - not managed to start debug session.
[IDF_HelloWorld_JTAG.zip](https://github.com/user-attachments/files/17597793/IDF_HelloWorld_JTAG.zip)

**hello_world_no_config - works properly.**
compile, download (via UART), monitor - ok. debug - ok, connected and waiting on void app_main(void) entry point. Here is reference OUTPUT  log:
[proper_OUTPUT.txt](https://github.com/user-attachments/files/17598243/proper_OUTPUT.txt)

**hello_world - no debug session starts.**
As soon as project config added (at least one) via ESP-IDF Open Project configuration wizard debug stops working. 
Here is esp_idf_project_configuration.json (also in attached projects):
```
{
  "config_uno": {
    "build": {
      "compileArgs": [],
      "ninjaArgs": [],
      "buildDirectoryPath": "",
      "sdkconfigDefaults": [],
      "sdkconfigFilePath": ""
    },
    "env": {},
    "flashBaudRate": "",
    "idfTarget": "esp32s3",
    "monitorBaudRate": "",
    "openOCD": {
      "debugLevel": 4,
      "configs": [
        "board/esp32s3-builtin.cfg"
      ],
      "args": []
    },
    "tasks": {
      "preBuild": "",
      "preFlash": "",
      "postBuild": "",
      "postFlash": ""
    }
  }
}

```

So, after compile, download (via UART) and check HelloWorld in Monitoring Device console, calling DEBUG button makes following actions:
Error banner appears
![image](https://github.com/user-attachments/assets/c24d627f-944f-4727-bc6c-3bf2e47cd504)
Open OCD server launched and I see restarts of the ESP by the HelloWorld firmware:

```

C:\esp\esp_tools\tools\xtensa-esp-elf-gdb\12.1_20231023\xtensa-esp-elf-gdb\bin\xtensa-esp32s3-elf-gdb.exe


C:\esp\esp_tools\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin\openocd.exe


[/Flash]
[OpenOCD]
Open On-Chip Debugger v0.12.0-esp32-20230921 (2023-09-21-13:40)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html

debug_level: 2

Info : only
 one transport option; autoselecting 'jtag'
Info : esp_usb_jtag: VID set to 0x303a and P
ID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000

Info : Listening 
on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections

Info : esp_usb_jtag:
 serial (DC:54:75:F1:7D:14)
Info : esp_usb_jtag: Device found. Base spe
ed 40000KHz, div range 1 to 255
Info : clock spee
d 40000 kHz

Info : JTAG tap
: esp32s3.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: e
sp32s3.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)

Info : starting gdb server for e
sp32s3.cpu0 on 3333
Info : Listening on port 3333 for gdb conn
ections

Info : [esp32s
3.cpu0] Debug controller was reset.
Info : [esp32s3.cpu0] Core was reset.

Info : [esp32s3
.cpu1] Debug controller was reset.
Info : [esp32s3.cpu1] Core was reset.

Info : [esp32s3.cpu0] Target halted, P
C=0x40378FBA, debug_reason=00000000

Info : [esp32s3
.cpu0] Reset cause (3) - (Software core reset)

Info : [esp32s3.cpu1] Target hal
ted, PC=0x40378FBA, debug_reason=00000000

Info : [esp3
2s3.cpu1] Reset cause (3) - (Software core reset)

Info : [esp32s3.c
pu0] Debug controller was reset.
Info : [esp32s3.cpu0] Core was reset.

Info : [esp32s3.
cpu1] Debug controller was reset.
Info : [esp32s3.cpu1] Core was reset.

Info : [esp32s3.cpu0] 
Target halted, PC=0x4004883B, debug_reason=00000000

Info : [esp32s3.
cpu0] Reset cause (3) - (Software core reset)

Info : [esp32s3.cpu1] 
Target halted, PC=0x40041A76, debug_reason=00000000

Info : [esp32s3
.cpu1] Reset cause (3) - (Software core reset)

Info : [esp32s3.c
pu0] Debug controller was reset.
Info : [esp32s3.cpu0] Core was reset.

Info : [
esp32s3.cpu1] Debug controller was reset.
Info : [esp32s3.cpu1] Core wa
s reset.

Info : [esp32s3.c
pu0] Target halted, PC=0x40048C2B, debug_reason=00000000

Info : [esp32s3.cpu0] Reset cause (12) - (Software CPU0 reset)

Info : [esp32s3.cpu1] T
arget halted, PC=0x40041A76, debug_reason=00000000

Info : [esp32s3.cp
u1] Reset cause (12) - (Software CPU1 reset)

Info : [esp32s3.cpu
0] Debug controller was reset.
Info : [esp32s3.cpu0] Core was reset.

Info : [esp3
2s3.cpu1] Debug controller was reset.
Info : [esp32s3.cpu1] Core wa
s reset.

Info : [esp32s3.cpu0] 
Target halted, PC=0x4004883B, debug_reason=00000000

Info : [e
sp32s3.cpu0] Reset cause (12) - (Software CPU0 reset)

... and so on ...
```

But no debug session launched in VSC.

### Debug Message

```plain
See "Description" section
```

### Other Steps to Reproduce

Just for clarification I also made a test with actual varsion of ESP IDF VSC Extension v1.8.1.
Build, Download, Monitor - fine.
Debug - launches OpenOCD and connects Debug session, hurray! Is it really works now!?
Disconnect debug session, select only project configuration exists "config_uno" and make a final try to be sure: 
Debug button:
```
C:\esp\esp_tools\tools\xtensa-esp-elf-gdb\12.1_20231023\xtensa-esp-elf-gdb\bin\xtensa-esp32s3-elf-gdb.exe
C:\esp\esp_tools\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin\openocd.exe
```
And stops, no luck 💥

Check if OpenOCD launches at all via ESP menu > Start/Stop OpenOCD Server > Start:
```
OPENOCD_SCRIPTS environment variable is missing. Please set it in idf.customExtraVars or in your system environment variables.
C:\esp\esp_tools\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin\openocd.exe
```
Nope ☹.
What else? Debug Menu and start "Launch" debug configuration (second item in launch.json file. It returns just:
```
The following Python requirements are not satisfied:
Error while checking requirement 'pywin32>=227; sys_platform == "win32"'. Package was not found and is required by the application: No package metadata was found for pywin32

Error while checking requirement 'esp-debug-backend'. Package was not found and is required by the application: No package metadata was found for esp-debug-backend
To install the missing packages, please run "install.bat"
Diagnostic information:
    IDF_PYTHON_ENV_PATH: C:\esp\esp_tools\python_env\idf5.1_py3.11_env
    Python interpreter used: C:\esp\esp_tools\python_env\idf5.1_py3.11_env\Scripts\python.exe
Command failed: C:\esp\esp_tools\python_env\idf5.1_py3.11_env\Scripts\python.exe c:\esp\v5.1.4\esp-idf\tools\check_python_dependencies.py -r c:\Users\p.bazhenov\.vscode\extensions\espressif.esp-idf-extension-1.8.1\esp_debug_adapter\requirements.txt
```
As soon Im sure environment is ok (by hello_world_no_config project debug) looks like that project configuraion crushes some references to environment, or some parameters was not set esp_idf_project_configuration.json not takes its default value (PS are there any detailed descrpition of esp_idf_project_configuration.json fields?)

So, Im stuck in that place. The best I have - is to launch OpenOCD server connected to ESP but with no Debug session from VSC side 😥

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by executer-uno** [comment]
Extra notices: Start/Stop OpenOCD Server command from ESP-IDF menu returns:
```
OPENOCD_SCRIPTS environment variable is missing. Please set it in idf.customExtraVars or in your system environment variables.
C:\esp\esp_tools\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\bin\openocd.exe
```
Ignoring the fact that OPENOCD_SCRIPTS alredy defined in Settings>Extensions>ESP-IDF>Custom extra vars to proper path
C:\esp\esp_tools\tools\openocd-esp32\v0.12.0-esp32-20230921\openocd-esp32\share\openocd\scripts

**Comment by executer-uno** [comment]
Previous post help for HelloWorld project. But now I can not completly tansfer the solution to my master project. I have following inconsistence: 
In HelloWorld project both "Eclipse CDT GDB Adapter" and "Launch" debug profile starts and connects but in my master project only green play button ▶ works on "Launch" and from debug command bar:
![image](https://github.com/user-attachments/assets/079d25f6-2619-41e0-9c53-2aef401e9a5e)
![image](https://github.com/user-attachments/assets/4d44db85-4a15-4022-8e66-f444aa3afa01)
But all other debugging buttons leads to error message:
![image](https://github.com/user-attachments/assets/dd47f742-46f5-44e1-b080-56b9c40c5aee)
![image](https://github.com/user-attachments/assets/d6137197-3caf-4335-ba21-0a1461d781de)
![image](https://github.com/user-attachments/assets/ad179f35-b6a3-4d50-b6e0-d9fb491a4cb0)
![image](https://github.com/user-attachments/assets/b55a76bc-52e9-4764-a2f1-8bdf8e05c9e4)
Error:
![image](https://github.com/user-attachments/assets/e4042181-218e-40b9-bf11-de8927168d0e)

So I feels standing on shaky floor

**Comment by brianignacio5** [comment]
Is your environment using the network port `43476` ? This is the default network portused by debug adapter server and if it used it will not work.

You can try updating launch.json like this:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "gdbtarget",
      "request": "attach",
      "name": "Eclipse CDT GDB Adapter",
      "debugPort": ###
    }
  ]
} 
```

and replace ### for a different server port.

**Comment by brianignacio5** [comment]
Hi @executer-uno 

Could you please try with the current master vsix installer [link here](https://nightly.link/espressif/vscode-esp-idf-extension/workflows/ci/master/esp-idf-extension.vsix.zip) ?

I've tried using esp32s3 devkitc-1 with the same project configuration you use in a blink ESP-IDF v5.4 example. I didn't observe the issue you posted (cannot read properties of null). We've might have fixed it in master already.

**Comment by executer-uno** [comment]
You are right. VSIX from master works brilliant.
Thank you for quick support!
