### ISSUE TITLE
[Feature Request]: Add button to refresh tests in testing tab (VSC-1515)

### ISSUE THREAD

**Issue by jdbaptista** [espressif/vscode-esp-idf-extension#1336]
The testing tab does not automatically recognize newly created unity tests and requires an IDE restart in order to run new tests through the tab, including test name changes. It would be great if the extension could recognize that a new test was created automatically or if the 'Refresh Tests' button in the testing tab searched through the codebase for new tests. I have asked if there is a way to refresh the tab without an editor restart in the [espressif forums](https://www.esp32.com/viewtopic.php?f=40&t=42590), with no response, so I am assuming this feature doesn't exist. I think that the best way to implement the feature is to use the existing 'Refresh Tests' button for this purpose, unless that is impossible.

**Comment by brianignacio5** [comment]
Thank you for the feature request. The `Refresh Tests` button should indeed search again for new test cases. Will take a look why is not doing so and fix it as soon as possible.
