### ISSUE TITLE
char ssid[] = SECRET_SSID (VSC-1525)

### ISSUE THREAD

**Issue by basibo** [espressif/vscode-esp-idf-extension#1350]
### OS

Windows

### Operating System version

Windows 11

### ESP-IDF version

Version: 1.8.1

### Python version

3.11.7

### Doctor command output

I have no Doctor command output ? 

### Extension

[esp_idf_vsc_ext.log](https://github.com/user-attachments/files/17917968/esp_idf_vsc_ext.log)

### Description

Hello, I have a question: I programmed my passwords into a password.h in a project. This file is then integrated via include. This works very well for the first two entries. As an example: If I place the cursor on ssid, the SECRET_SSID is taken from the include file paswort.h in char ssid[] =.   // result char ssid[10] and SECRET_SSID Expans to: "xxxxxxxxxx". However, an error occurs from the 3rd line in passowort.h. The char mqtt_server[] = SECRET_mqtt_server is displayed completely incorrectly. So char mqtt_server[1] only has one character and with SECRET_mqtt_server I get this display. <error-type> ECRET_mqtt_server. Strangely enough, the correct IP is probably transferred during MQTT connect because the ESP32 connects to the MQTT server and the data exchange also works. Maybe someone can help me understand this? Thanks for the help, greetings Peter

### Debug Message

NO error message during compliation

### Other Steps to Reproduce

I'm a beginner with VC and the PlatformIo. I use Arduino frame work. I had serveral issue but mostly i find solution. Now im at the end of my knowlege. 

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Hi @basibo I think this repository is not the right place for your question. Could you try asking in the esp-idf repository instead ?

**Comment by basibo** [comment]
Hi Brain,Thank you for your reply.The question was moved automatically to this repro.Is it possible to move it ? Or must I open a new issue?Have a nice 2. xmass sunday, PeterMit freundlichen GrüßenPeter BasistaHans-Böckler-Straße 4146236 BottropTel: 0177 4643703Fax: 02041 ***@***.*** 06.12.2024 um 01:38 schrieb Brian A. Ignacio ***@***.***>:﻿
Hi @basibo I think this repository is not the right place for your question. Could you try asking in the esp-idf repository instead ?

**Comment by brianignacio5** [comment]
Hi @basibo I'm unable to move this to another repository. Feel free to open a new GitHub issue in esp-idf repository.
