### ISSUE TITLE
[Feature Request]: make idf.customExtraPaths a list instead of string (VSC-1533)

### ISSUE THREAD

**Issue by gudvinr** [espressif/vscode-esp-idf-extension#1359]
**Is your feature request related to a problem? Please describe.**

After you set up IDF tools, `idf.customExtraPaths` in settings.json will be around 500-1000 characters long depending on your path.

This is rather tricky to inspect or modify if needed.

**Describe the solution you'd like**

Instead, it'd be easier if you define paths as list and turn it into `PATH` string where you need it inside extension.

**Describe alternatives you've considered**
~~A clear and concise description of any alternative solutions or features you've considered.~~

**Additional context**
~~Add any other context or screenshots about the feature request here.~~

**Comment by brianignacio5** [comment]
The settings has been removed in the extension master and will be in the next release.
