### ISSUE TITLE
"debug" hyperlink on the extensions main page links to a non-existing github URL (404) (VSC-1535)

### ISSUE THREAD

**Issue by attilabody** [espressif/vscode-esp-idf-extension#1361]
### OS

Linux

### Operating System version

Irrelevant

### Visual Studio Code version

Irrelevant

### ESP-IDF version

Irrelevant

### Python version

Irrelevant

### Doctor command output

Irrelevant

### Extension

Irrelevant

### Description

debug hyperlink links to https://github.com/espressif/vscode-esp-idf-extension/blob/HEAD/docs/DEBUGGING.md which does not exist.

### Debug Message

Irrelevant

### Other Steps to Reproduce

Just click on the link
![image](https://github.com/user-attachments/assets/396d057d-2b90-4f42-9109-196a7ced31e5)

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Hi @attilabody We have moved the documentation to https://docs.espressif.com/projects/vscode-esp-idf-extension/en/latest/debugproject.html but the links will not be updated in the vscode until we make a new extension release.

Will release very soon !
