### ISSUE TITLE
ESP-IDF Error while configuring (VSC-1536)

### ISSUE THREAD

**Issue by Mo0nShad3** [espressif/vscode-esp-idf-extension#1362]
### OS

Windows

### Operating System version

Windows 11

### Visual Studio Code version

1.95.3

### ESP-IDF version

5.3.2

### Python version

3.10

### Doctor command output

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.22631 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\VMware\VMware Player\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files (x86)\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\MongoDB\Server\7.0\bin;C:\Program Files\MongoDB\mongosh-2.2.10-win32-x64\bin;C:\Program Files\Arduino PLC IDE Tools\;C:<HOMEPATH>\AppData\Local\Microsoft\WindowsApps;C:<HOMEPATH>\AppData\Local\GitHubDesktop\bin;C:\ProgramData\TMJac\GitHubDesktop\bin;C:<HOMEPATH>\.dotnet\tools;C:<HOMEPATH>\AppData\Local\Programs\Microsoft VS Code\bin;C:<HOMEPATH>\AppData\Roaming\npm;C:\Program Files\Azure Data Studio\bin;C:<HOMEPATH>\AppData\Local\Programs\mongosh\;C:<HOMEPATH>\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.95.3 
Visual Studio Code language en 
Visual Studio Code shell C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.8.1 
Workspace folder No workspace folder is open 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) ${env:IDF_PATH}
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
ESP-HomeKit-SDK Path (idf.espHomeKitSdkPath) ${env:HOMEKIT_PATH}
Custom extra paths (idf.customExtraPaths) 
Custom extra vars (idf.customExtraVars)
Virtual env Python Path (idf.pythonBinPath) python
Serial port (idf.port) COM1
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,board/esp32-wrover.cfg
ESP-IDF Tools Path (idf.toolsPath) ${env:IDF_TOOLS_PATH}
Git Path (idf.gitPath) ${env:programfiles}\Git\cmd\git.exe
Notification Mode (idf.notificationMode) All
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) false
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-HomeKit Path (idf.espHomeKitSdkPath) false
Access to ESP-IDF Custom extra paths
Access to Virtual env Python Path (idf.pythonBinPath) false
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) false
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path true
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-HomeKit-SDK Path (idf.espHomeKitSdkPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version undefined
ESP-IDF version undefined
Python version undefined
Python's pip version undefined
-------------------------------------------------- Project configuration settings ----------------------------------------------------------
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages undefined
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages undefined
----------------------------------------------------------- Latest error -----------------------------------------------------------------
{
    "errno": -4058,
    "code": "ENOENT",
    "syscall": "spawn ${env:programfiles}\\Git\\cmd\\git.exe",
    "path": "${env:programfiles}\\Git\\cmd\\git.exe",
    "spawnargs": [
        "--version"
    ],
    "cmd": "${env:programfiles}\\Git\\cmd\\git.exe --version"
}
--------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------- Logfile -----------------------------------------------------------------
{"message":"Cannot access filePath: C:\\Users\\TMJac\\Desktop\\esp-idf\\tools\\idf.py","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\Desktop\\esp-idf\\tools\\idf.py'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat mh.value (\\dist\\extension.js:2:1615589)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Zj.$onMessage (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:90307)\n\tat py.S (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)\n\tat py.Q (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)\n\tat py.M (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)\n\tat py.L (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111418)\n\tat mh.value (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Vn.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)\n\tat mh.value (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13300)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Vn.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)\n\tat MessagePortMain.<anonymous> (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11592)\n\tat MessagePortMain.emit (node:events:519:28)\n\tat MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)","level":"error","timestamp":"2024-12-07T09:29:15.631Z"}
{"message":"Cannot access filePath: C:\\Users\\TMJac\\Desktop\\esp-idf\\tools\\idf.py","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\Desktop\\esp-idf\\tools\\idf.py'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat mh.value (\\dist\\extension.js:2:1615589)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Zj.$onMessage (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:90307)\n\tat py.S (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)\n\tat py.Q (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)\n\tat py.M (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)\n\tat py.L (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111418)\n\tat mh.value (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Vn.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)\n\tat mh.value (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13300)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Vn.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)\n\tat MessagePortMain.<anonymous> (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11592)\n\tat MessagePortMain.emit (node:events:519:28)\n\tat MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)","level":"error","timestamp":"2024-12-07T09:29:28.245Z"}
{"user":true,"message":"Zip file error","stack":"Error: Zip file error\n\tat \\dist\\extension.js:2:1581372\n\tat \\dist\\extension.js:2:1180821\n\tat \\dist\\extension.js:2:1179413\n\tat \\dist\\extension.js:2:1180225\n\tat \\dist\\extension.js:2:544951\n\tat FSReqCallback.wrapper [as oncomplete] (node:fs:684:5)","level":"error","timestamp":"2024-12-07T09:29:47.173Z"}
{"message":"Cannot access filePath: ${env:IDF_TOOLS_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:IDF_TOOLS_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1650736\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.929Z"}
{"message":"Cannot access filePath: ${env:ADF_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:ADF_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1650824\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.930Z"}
{"message":"Cannot access filePath: ${env:IDF_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:IDF_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1650913\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.930Z"}
{"message":"Cannot access filePath: ${env:MDF_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:MDF_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1651002\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.931Z"}
{"message":"Cannot access filePath: ${env:ESP_MATTER_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:ESP_MATTER_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1651094\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.931Z"}
{"message":"Cannot access filePath: ${env:HOMEKIT_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:HOMEKIT_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1651190\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.932Z"}
{"message":"Cannot access filePath: python","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\python'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1651286\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.933Z"}
{"message":"spawn ${env:programfiles}\\Git\\cmd\\git.exe ENOENT","stack":"Error: spawn ${env:programfiles}\\Git\\cmd\\git.exe ENOENT\n\tat ChildProcess._handle.onexit (node:internal/child_process:286:19)\n\tat onErrorNT (node:internal/child_process:484:16)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:82:21)","level":"error","timestamp":"2024-12-07T09:34:33.936Z"}
{"user":true,"level":"warn","message":"Extension configuration report has been copied to clipboard with errors","timestamp":"2024-12-07T09:34:33.936Z"}

--------------------------------------------------------------------------------------------------------------------------------------------

### Extension

{"message":"Cannot access filePath: C:\\Users\\TMJac\\Desktop\\esp-idf\\tools\\idf.py","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\Desktop\\esp-idf\\tools\\idf.py'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat mh.value (\\dist\\extension.js:2:1615589)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Zj.$onMessage (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:90307)\n\tat py.S (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)\n\tat py.Q (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)\n\tat py.M (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)\n\tat py.L (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111418)\n\tat mh.value (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Vn.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)\n\tat mh.value (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13300)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Vn.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)\n\tat MessagePortMain.<anonymous> (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11592)\n\tat MessagePortMain.emit (node:events:519:28)\n\tat MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)","level":"error","timestamp":"2024-12-07T09:29:15.631Z"}
{"message":"Cannot access filePath: C:\\Users\\TMJac\\Desktop\\esp-idf\\tools\\idf.py","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\Desktop\\esp-idf\\tools\\idf.py'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat mh.value (\\dist\\extension.js:2:1615589)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Zj.$onMessage (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:90307)\n\tat py.S (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)\n\tat py.Q (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)\n\tat py.M (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)\n\tat py.L (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111418)\n\tat mh.value (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Vn.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)\n\tat mh.value (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13300)\n\tat D.B (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)\n\tat D.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)\n\tat Vn.fire (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)\n\tat MessagePortMain.<anonymous> (file:///c:/Users/TMJac/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11592)\n\tat MessagePortMain.emit (node:events:519:28)\n\tat MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)","level":"error","timestamp":"2024-12-07T09:29:28.245Z"}
{"user":true,"message":"Zip file error","stack":"Error: Zip file error\n\tat \\dist\\extension.js:2:1581372\n\tat \\dist\\extension.js:2:1180821\n\tat \\dist\\extension.js:2:1179413\n\tat \\dist\\extension.js:2:1180225\n\tat \\dist\\extension.js:2:544951\n\tat FSReqCallback.wrapper [as oncomplete] (node:fs:684:5)","level":"error","timestamp":"2024-12-07T09:29:47.173Z"}
{"message":"Cannot access filePath: ${env:IDF_TOOLS_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:IDF_TOOLS_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1650736\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.929Z"}
{"message":"Cannot access filePath: ${env:ADF_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:ADF_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1650824\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.930Z"}
{"message":"Cannot access filePath: ${env:IDF_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:IDF_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1650913\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.930Z"}
{"message":"Cannot access filePath: ${env:MDF_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:MDF_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1651002\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.931Z"}
{"message":"Cannot access filePath: ${env:ESP_MATTER_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:ESP_MATTER_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1651094\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.931Z"}
{"message":"Cannot access filePath: ${env:HOMEKIT_PATH}","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\${env:HOMEKIT_PATH}'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1651190\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.932Z"}
{"message":"Cannot access filePath: python","stack":"Error: ENOENT: no such file or directory, access 'C:\\Users\\TMJac\\AppData\\Local\\Programs\\Microsoft VS Code\\python'\n\tat Object.accessSync (node:fs:246:11)\n\tat t.accessSync (node:electron/js2c/node_init:2:9332)\n\tat Se (\\dist\\extension.js:2:1421806)\n\tat \\dist\\extension.js:2:1651286\n\tat ua (\\dist\\extension.js:2:1651892)\n\tat async \\dist\\extension.js:2:1868405","level":"error","timestamp":"2024-12-07T09:34:33.933Z"}
{"message":"spawn ${env:programfiles}\\Git\\cmd\\git.exe ENOENT","stack":"Error: spawn ${env:programfiles}\\Git\\cmd\\git.exe ENOENT\n\tat ChildProcess._handle.onexit (node:internal/child_process:286:19)\n\tat onErrorNT (node:internal/child_process:484:16)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:82:21)","level":"error","timestamp":"2024-12-07T09:34:33.936Z"}
{"user":true,"level":"warn","message":"Extension configuration report has been copied to clipboard with errors","timestamp":"2024-12-07T09:34:33.936Z"}

### Description

I am just trying to install ESP-IDF into my visual studio code and I keep getting error: aborted shown in the debug message below.

### Debug Message

idf-git-2.39.2-win64.zip progress: 79.18% (22588.35 / 28526.53) KB
Error: aborted
	at TLSSocket.socketCloseListener (node:_http_client:464:19)
	at TLSSocket.emit (node:events:531:35)
	at node:net:339:12
	at TCP.done (node:_tls_wrap:648:7)
Failed download. Retrying...
Error: Error: HTTP/HTTPS Response error

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
This seems to be a network issue on your setup.
