### ISSUE TITLE
deprecated and removed wmic.exe is used internally (VSC-1538)

### ISSUE THREAD

**Issue by AndreasDiet** [espressif/vscode-esp-idf-extension#1364]
### OS

Windows

### Operating System version

Win 11 24H2

### Visual Studio Code version

n.a.

### ESP-IDF version

n.a.

### Python version

n.a.

### Doctor command output

n.a.

### Extension

n.a.

### Description
follow up for https://github.com/microsoft/vscode/issues/228661

see https://github.com/espressif/vscode-esp-idf-extension/blob/e61f08a1a242de898f9971b1393f59b34a12fa7c/src/PlatformInformation.ts#L94-L96

wmic.exe is marked as deprecated since release of Windows 10 21H2
see https://learn.microsoft.com/en-us/windows/whats-new/deprecated-features and search for wmic
in Win 11 24H2 it is no longer part of the installation bits

please replace the wmic.exe usage by running
powershell -executionPolicy bypass "(Get-WmiObject Win32_OperatingSystem).OSArchitecture"

### Debug Message

n.a.

### Other Steps to Reproduce

n.a.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Thanks for the issue request. You can test the bug fix in #1365 and will be available in marketplace on our next release.

You can also use the vsix installer from the PR or use the master vsix after it is merged in the meantime.

**Comment by AndreasDiet** [comment]
opened a tree of directories - my wmicCatcher is triggered, indicating wmic.exe is used
installed the vsix
opened the very same directory tree- my wmicCatcher is no longer be triggered

thanks for changing to make this extension compatible to Win11 24H2/Server 2025
