### ISSUE TITLE
GUI Configuration Tool does not update for new configuration after changing device target (VSC-383)

### ISSUE THREAD

**Issue by boarchuz** [espressif/vscode-esp-idf-extension#144]
**Describe the bug**
After changing target (ESP32<->ESP32S2), gui configuration tool does not reflect the updated target/sdkconfig until VSCode is restarted.

**To Reproduce**
* Open an existing project.
* Run "ESP-IDF: Launch gui configuration tool" so that "loading initial values" step completes.
* Note target-specific options that are visible (eg. compiler path, "ESP32[xx]-specific" submenu, etc) and any changes from defaults.
* Close the gui configuration tab.
* Run "ESP-IDF: Set Espressif device target" and change to the other (at this point, it appears sdkconfig is reset)
* Run "ESP-IDF: Launch gui configuration tool" again.
* Note that the displayed values still reflect the old config (including previous device target), not the current values in sdkconfig.
* Close VSCode and reopen project. Open the config gui again and now the current sdkconfig is shown correctly.

**Expected behavior**
Menuconfig gui always reflects the actual configuration.
Additionally, it would be great if configuration options that are common to all device targets are not reset when changing target. It is unexpected and unclear that changing target would reset the entire config to default.

**Environment (please complete the following information):**
- OS Name & Version: Linux Mint
- VSCode Version: 1.47.1
- ESP-IDF Version: 4.2
- Extension: 0.3.0

**Comment by brianignacio5** [comment]
Thanks for reporting this. Will provide a fix soon !
