### ISSUE TITLE
[Bug Report]: Background color broken (VSC-432)

### ISSUE THREAD

**Issue by simark1979** [espressif/vscode-esp-idf-extension#164]
After last update of VSCode from 1.48.2. to 1.49.0 I found that extension`s backgroung has ben broken.
Now all text almost invisible (including project configurator)
![screenshot](https://user-images.githubusercontent.com/1710479/93016496-5c5cb580-f5ca-11ea-98a3-166efb020b60.PNG)

**Comment by brianignacio5** [comment]
This is probably due to some change in vscode webview css variables which we reused in the Webviews.
Will take a look thanks for posting !

**Comment by pwmb** [comment]
@brianignacio5 this is due to previously we were using `background: transparent` which then use to show dark background in a dark theme but now we explicitly have to tell vscode to paint the background accordingly

Will create a PR to fix this.
