### ISSUE TITLE
Open Example Project only copies one level deep (VSC-220)

### ISSUE THREAD

**Issue by Devenda** [espressif/vscode-esp-idf-extension#17]
**Describe the bug**
Creating an example only copies one level of folders.

**To Reproduce**
Open the example menu, choose a project containing multiple levels of folders (eg restful server, touch_pad_read,...) click "Create project using example...".
results in nested folders being treated as files:
![afbeelding](https://user-images.githubusercontent.com/2527506/72682239-375f8380-3acb-11ea-8dcf-ff32b072eaaa.png)

**Expected behavior**
Fully recursively copied folders and files.

**Screenshots**
Leftside: original example in esp-idf folder, rightside: the folder after copy.
![afbeelding](https://user-images.githubusercontent.com/2527506/72682196-d3d55600-3aca-11ea-99f8-94cb6cecb0e6.png)

**Environment:**
plugin version 0.1.2
Windows 10

**Comment by Devenda** [comment]
Additionally files in the project root are not copied either:
![afbeelding](https://user-images.githubusercontent.com/2527506/72682323-16e3f900-3acc-11ea-8180-229e3fe51788.png)

**Comment by brianignacio5** [comment]
Thanks for reporting this issue!

Will fix soon!
