### ISSUE TITLE
Feedback of Arduino ESP32 as ESP-IDF Component in Extension (VSC-455)

### ISSUE THREAD

**Issue by pwmb** [espressif/vscode-esp-idf-extension#189]
Please refer this https://github.com/espressif/vscode-esp-idf-extension/issues/179#issuecomment-702230362

From #179

**Comment by sukesh-ak** [comment]
Why is this marked as duplicate? Can you mention duplicate of which one?

**Comment by pwmb** [comment]
Since you originally reported this in #179.

Please note: `Tags` are for internal maintenance purpose.

**Comment by brianignacio5** [comment]
From the conversation in #179 we still haven't received an actual bug of the feature.  Renaming this thread since it is misleading. 

IF you find a bug or have some feedback about this feature please let us know here.

**Comment by sukesh-ak** [comment]
> From the conversation in #179 we still haven't received an actual bug of the feature. Renaming this thread since it is misleading.
> 
> IF you find a bug or have some feedback about this feature please let us know here.


Hi @brianignacio5 
If you use "Arduino ESP32 as ESP-IDF Component" in Extension actions command it errors out (guess due to mismatch in supported version).
Either provide a working version or you can remove the action in the list till its ready.

**Comment by brianignacio5** [comment]
> > From the conversation in #179 we still haven't received an actual bug of the feature. Renaming this thread since it is misleading.
> > IF you find a bug or have some feedback about this feature please let us know here.
> 
> Hi @brianignacio5
> If you use "Arduino ESP32 as ESP-IDF Component" in Extension actions command it errors out (guess due to mismatch in supported version).
> Either provide a working version or you can remove the action in the list till its ready.

Does it work for ESP-IDF 4.0 and ESP-IDF 3.3 ?

**Comment by edouardreg** [comment]
Hello, I have tried with all esp-idf 4.0 versions proposed (4.0.2 and 4.0 release branch) by the extension express setup : none is working with "install arduino as component". The error message is : ESP-IDF 4.0 or 3.3 is required...

**Comment by brianignacio5** [comment]
Thanks for the feedback @edouardreg . Will take a look soon

**Comment by Murloc992** [comment]
Same issue, would love to see a solution. :) For now manually adding the component works.
