### ISSUE TITLE
[Bug Report]: Tasks:Run Task then choose one function,don't work and no freeback (VSC-477)

### ISSUE THREAD

**Issue by QianchengYan** [espressif/vscode-esp-idf-extension#211]
![image](https://user-images.githubusercontent.com/43084711/98434039-0fe3b100-2107-11eb-9940-9ace78573c47.png)

**Comment by brianignacio5** [comment]
**Please fill out the issue template to give us more information to understand your problem.**

Tasks.json are defined in your project's .vscode/tasks.json

Can you share the content of this field.

There is also some output from the task execution in the Output tab (near Terminal) Can you share the output to see what happens?

Have you configure the extension using the onboarding steps ?

**Comment by QianchengYan** [comment]
thanks for your reply.
I had fix this problem which is caused by setting.json.
![image](https://user-images.githubusercontent.com/43084711/98512770-cbd8e380-22a1-11eb-89c6-72d3c914bea6.png)
then I fix this problems:
`    "task.slowProviderWarning": true,
    "task.problemMatchers.neverPrompt": true,`
finally, "Tasks:run task" work well.
