### ISSUE TITLE
[Bug Report]: esp-idf-v4.0.2.zip doesn't exist for v4.0 (release branch) (VSC-489)

### ISSUE THREAD

**Issue by Sterpa** [espressif/vscode-esp-idf-extension#223]
- OS Name & Version: [Win10Pro x64 10.0.19041.630]
- VSCode Version: [1.51.1]
- ESP-IDF Version: [release/v4.0 (release branch)]
- Python Version: [3.9.0]

If I select (release / v4.0 (release branch)) in the (Configure ESP-IDF) step, then I get an error after downloading the framework archive because vscode-esp-idf-extension is trying to find the archive (esp-idf-v4.0.2.zip) for v4.0.2 release version, but not for v.4.0 release branch, screen below.
I think this is a configuration wizard script error ...
![image](https://user-images.githubusercontent.com/7299203/100620359-64a5d080-332f-11eb-9e73-6a6e50a995a3.png)

**Comment by brianignacio5** [comment]
Thanks for reporting this. will work on a fix soon. Please use the release version v4.0.2 in the mean time, or manually enter ESP-IDF in the meantime.
