### ISSUE TITLE
[Feature Request]: Win configuration parameters (VSC-497)

### ISSUE THREAD

**Issue by ViktorTarasovA** [espressif/vscode-esp-idf-extension#234]
There is no information about *Win configuration parameters like idf.portWin in README. I tried to use configuration parameters without Win and got an error, because it used COM1 by default instead of my COM9. Only pressing F1 and "ESP-IDF: Select port to use" clarified the situation.

Could you please add some kind of information about *Win parameters to README? Maybe I just don't know where to search it :)

**Comment by brianignacio5** [comment]
Yes @ViktorTarasovA thank you, will add these parameters to the documentation.
