### ISSUE TITLE
[Feature Request]:  (VSC-506)

### ISSUE THREAD

**Issue by ihouses** [espressif/vscode-esp-idf-extension#242]
I have installed my ESP-ADF framework as described in the official documentation. 
Would be great to be able to create as well the examples in the ESP-ADF framework when is available.

Is there any plan for supporting that?

**Comment by brianignacio5** [comment]
We added an option to the `ESP-IDF: Show ESP-IDF Examples Projects` command to choose between ESP-IDF, ESP-ADF and ESP-MDF. For this to work, you should set the `idf.espAdfPath` configuration setting in Visual Studio Code  to your $ADF_PATH directory

**Comment by ihouses** [comment]
It works!!

This is a really great tool! I was trying platformio as well that was looking very promising but without too much success, one the other hand this tools is exactly what we need.
