### ISSUE TITLE
[Bug Report]: Removed breakpoint still can be triggered but with an error in output. (VSC-508)

### ISSUE THREAD

**Issue by ViktorTarasovA** [espressif/vscode-esp-idf-extension#244]
**Describe the bug**
Seems like removing breakpoints doesn't work correctly. The breakpoint still present and can be triggered with an error. See logs.

**To Reproduce**
Set one hardware breakpoint. Launch debugging. Breakpoint is triggered correctly. Remove this breakpoint. The breakpoint is still triggered with sending an error. See logs.

**Expected behavior**
No triggered breakpoint after removing it.

**Environment (please complete the following information):**

- OS Name & Version: Win10 64bit
- VSCode Version: 1.52.1 (user setup), Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
- ESP-IDF Version: v4.1
- Python Version: 3.7.9

**Logs**
```
2020-12-21 14:24:27,402 - Debug Adapter (main) - ERROR - local variable 'kwargs' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\viktar\.vscode\extensions\espressif.esp-idf-extension-0.5.1\esp_debug_adapter\debug_adapter\command_processor.py", line 52, in __call__
    on_request(protocol_message)
  File "c:\Users\viktar\.vscode\extensions\espressif.esp-idf-extension-0.5.1\esp_debug_adapter\debug_adapter\command_processor.py", line 626, in on_setBreakpoints_request
    response = base_schema.build_response(request, kwargs)
UnboundLocalError: local variable 'kwargs' referenced before assignment
```

**Comment by policeman0077** [comment]
I have similar problem which only the very first breakpoint auto pause the program but if I click continue no other breakpoints would pause the program again. The attached video might explain my issues better.
[Video](https://i.imgur.com/cewlEPa.mp4) 

Os : macOS 11.3
Idf: v4.2
Viscode extension: v1.0.3
Openocd: tried both 20200709 and 20210401 have same problem
