### ISSUE TITLE
[Feature Request]: Is there clean button? (VSC-509)

### ISSUE THREAD

**Issue by ihouses** [espressif/vscode-esp-idf-extension#247]
I don't find the "clean" button in the VS gui. I found out that with the terminal an typing idf.py fullclean is doing the same.

My problem cames that after a unsuccessful build I can not execute that command since I get this message:

![image](https://user-images.githubusercontent.com/5103057/102828731-ba791000-43e5-11eb-9aa8-c9b1912bae6a.png)

If I close virual studio and open again then I can do a clean with idf.py fullclean.

**Comment by brianignacio5** [comment]
I'm sorry for some reason I can't seem to see the attached picture. Will you please upload again ? 

Please follow the issue template, share your system environment details and extension log for us to understand your problem better.

**Comment by bonmotwang** [comment]
I was looking for this "button" last night. But I just did it in the TERMINAL.
