### ISSUE TITLE
[Bug Report]: C:\Users\make\.espressif\python_env\idf4.1_py3.9_env\Scripts\pythone.exe is not accesible. (VSC-510)

### ISSUE THREAD

**Issue by kaibin1111** [espressif/vscode-esp-idf-extension#248]
C:\Users\make\.espressif\python_env\idf4.1_py3.9_env\Scripts\pythone.exe is not accesible.

**Comment by brianignacio5** [comment]
It seems to me you need to fix the value in `idf.pythonBinPathWin` in your extension settings.json with `C:\Users\make.espressif\python_env\idf4.1_py3.9_env\Scripts\python.exe` (a typo error)

**Comment by kaibin1111** [comment]
C:\Users\make.espressif\python_env\idf4.1_py3.9_env\Scripts\pythone.exe is not accesible.

**Comment by kaibin1111** [comment]
> 在我看来，您需要`idf.pythonBinPathWin`使用`C:\Users\make.espressif\python_env\idf4.1_py3.9_env\Scripts\python.exe`（输入错误）在扩展名settings.json中修复值。

C:\Users\make.espressif\python_env\idf4.1_py3.9_env\Scripts\pythone.exe is not accesible.
