### ISSUE TITLE
Problem Matcher support for IDF Build, Flash, and other tasks (VSC-227)

### ISSUE THREAD

**Issue by bitmakk** [espressif/vscode-esp-idf-extension#25]
Hello!

My problem is, that with even the **0.1.3** the VSCode can't highlight me in the Editor (or at the Problems) the errors/warnings given by the output (at build). I tried more settings in the tasks.json file, but none of it worked. 
Can you give me tips to use it properly? 
(I added errors to my code, it fails to build, but the VSCode doesn't recognize it as a problem.
The problem matcher pattern is matched by the output (as I tested in an online tester). )

**Comment by SoumeshBanerjee** [comment]
HI @bitmakk 

The `problem-matcher` for IDF Build, flash and other such task is still under development and will be shipped soon in the upcoming versions of extension.

**Comment by bitmakk** [comment]
Thank you

**Comment by brianignacio5** [comment]
Di you try configuring your c_cpp_properties.json to use compile_commands.json ?

This is specified in [C/C++ Configuration](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/C_CPP_CONFIGURATION.md) as mentioned in [How to use](https://github.com/espressif/vscode-esp-idf-extension#how-to-use).

As we mention in the README file, the C/C++ extension is used to resolve C headers, which is not part of our extension thereby user still need to configure it.

**Comment by SoumeshBanerjee** [comment]
@bitmakk  Adding this feature will take a while, meanwhile you could use the tasks available in task.json or write your own

**Comment by SoumeshBanerjee** [comment]
@holubcsongor This feature request is now released and available in v0.2.2
