### ISSUE TITLE
[Feature Request]: Is it intelliSense/ctrl+click supported in the IDF/ADF structure model? (VSC-513)

### ISSUE THREAD

**Issue by ihouses** [espressif/vscode-esp-idf-extension#252]
I am not sure if the intelliSense plugin in in charge of this but: I see that when I add a module in my project I can not use ctrl+click to jump to the definition.

As well many of my includes can not be found by (intelliSense?). 

I mean, this are details that usually we give by granted since in many programming IDEs is working by default. Do we need to do/install something else in order to enable that functionality?

Thanks!

**Comment by brianignacio5** [comment]
Have you look into [C_CPP_CONFIGURATION.md](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/C_CPP_CONFIGURATION.md) ?

**Comment by ihouses** [comment]
I have used the information in  C_CPP_CONFIGURATION.md  and now all headers are detected and by doubts are solved, thanks so much.
