### ISSUE TITLE
[Bug Report]: Invalid ESP-IDF when configuring the ESP-IDF extension v0.6.0 (VSC-531)

### ISSUE THREAD

**Issue by xiaolongba** [espressif/vscode-esp-idf-extension#271]
**Describe the bug**
**Invalid ESP-IDF** error information occurred when configuring the extension. However, version 0.51 has not such error information when  doing the same instructions

**To Reproduce**
Configure the ESP-IDF extension and then fill in the relevant path and then an error occurred

**Expected behavior**
Can configure the ESP-IDF extension successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/16135532/103727714-e7006f00-5016-11eb-95d8-9f6e4c4d3087.png)

**Environment (please complete the following information):**

- OS Name & Version: Win10
- VSCode Version: 1.52.1
- ESP-IDF Version: preview
- Python Version: 3.9

**Logs**

there are not any logs at this moment

**Comment by brianignacio5** [comment]
What is the value of `git describe --tags` in your ESP-IDF directory ?

**Comment by xiaolongba** [comment]
Hi Bro,

it showed me the following information when I inputted the command you mentioned above:

```
$ git describe --tags
fatal: No names found, cannot describe anything.
```

However, I got the ESP-IDF from espressif repository. also, there is no error that occurred when using the v0.5.1

**Comment by brianignacio5** [comment]
It seems there is a small issue with some ESP-IDF version, will fix soon. Thanks

**Comment by xiaolongba** [comment]
all right, what can I only do at this moment is to build, flash or monitor manually
