### ISSUE TITLE
[Bug Report]: #274, for the monitor issue after 0.6.0 update, works only without the double quotes (VSC-534)

### ISSUE THREAD

**Issue by heilingbrunner** [espressif/vscode-esp-idf-extension#278]
To get the internal terminal device monitor running again, i cloned the latest commit and rebuilded a new local vsix package for me.
It only worked without the additional double quotes inside the single back ticked (`) strings.

Win10
VSCode:
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Datum: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Betriebssystem: Windows_NT x64 10.0.19042

```javascript
function getTxtCmd(variable: string, modifiedEnv: { [key: string]: string }) {
  const shellExecutable = path.basename(vscode.env.shell);
  switch (shellExecutable) {
    case "cmd.exe":
      return `set ${variable}=${modifiedEnv[variable]}`;
    case "powershell.exe":
    case "pwsh.exe":
      return `$Env:${variable}=${modifiedEnv[variable]}`;
    default:
      return `export ${variable}=${modifiedEnv[variable]}`;
  }
}
```

**Comment by brianignacio5** [comment]
Can you show more information about your setup environment and steps to reproduce this behavior? Maybe some special characters in your environment variables ? Which terminal are you using ?

The main reason for double quotes is that some users have spaces in their paths.
