### ISSUE TITLE
[Bug Report]:  ESP-IDF Monitor device failed (VSC-535)

### ISSUE THREAD

**Issue by jlu-battery-biz** [espressif/vscode-esp-idf-extension#280]
**Pre Bug Report Checklist**
Before reporting any bug please make sure of these points.

- [Y] Make sure you have searched for existing bugs and features request before you post an issue.
- [Y] This is a bug report for the ESP-IDF Visual Studio Code extension and **not** an ESP-IDF bug report.
- [Y] I've read the docs and found no information that could have helped solving the issue.

**Describe the bug**
My conclusion:
1. Monitoring device failed with version 0.6.0.

My observation:
1. Building, flashing and monitoring the device successfully with version 0.5.1
2. Building and flashing the device successfully with version 0.6.0.

My guess:
1. Python code is looking for an environment variable "IDF_PATH" when it is checking the IDF version while calling monitor the device

My approaches:
1. After version 0.6.0 installed, I ran through the configuration process again using "ESP-IDF: Configure ESP-IDF extension"
2. After the monitor fail, I manually entered `set IDF_PATH=C:\Users\aaa\Documents\GitHub\esp-idf` in the "ESP-IDF Monitor" terminal then rerun it again. It failed with a different reason `FileNotFoundError: [WinError 2] The system cannot find the file specified`. Stopped here.

**To Reproduce**
Steps to reproduce the behavior (including the full log).

1. Open VSCode
2. Open a folder contain a ESP-IDF project created with version 0.5.1
3. Click on the button "ESP-IDF Monitor Device"
4. Done
5. Please find the log in section Screenshots

**Expected behavior**
Print failure log

**Screenshots**
`
C:\Users\aaa\Documents\GitHub\bbb>c:\Users\aaa\Documents\ESP-IDF_Tools\v4.2\python_env\idf4.2_py3.8_env\Scripts\python.exe c:\Users\aaa\Documents\GitHub\esp-idf\tools\idf.py -p COM5 monitor
Traceback (most recent call last):
  File "c:\Users\aaa\Documents\GitHub\esp-idf\tools\idf.py", line 788, in <module>
    main()
  File "c:\Users\aaa\Documents\GitHub\esp-idf\tools\idf.py", line 704, in main
    checks_output = check_environment()
  File "c:\Users\aaa\Documents\GitHub\esp-idf\tools\idf.py", line 68, in check_environment
    print_idf_version()
  File "c:\Users\aaa\Documents\GitHub\esp-idf\tools\idf.py", line 117, in print_idf_version
    version = idf_version()
  File "c:\Users\aaa\Documents\GitHub\esp-idf\tools\idf_py_actions\tools.py", line 56, in idf_version
    "--git-dir=%s" % os.path.join(os.environ["IDF_PATH"], '.git'),
  File "C:\Users\aaa\AppData\Local\Programs\Python\Python38-32\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'IDF_PATH'
`

**Environment (please complete the following information):**

- OS Name & Version: Windows 10 (64-bit)
- VSCode Version: 1.52.1
- ESP-IDF Version: 4.2
- Python Version: 3.8.6

**Logs**
Please find the log in section Screenshots

**Extension Configuration settings**
Open Command Palette (F1) and type `Preferences: Open Settings (JSON)` or use `{CURRENT_PROJECT}/.vscode/settings.json` to get the following extension configuration settings value:
`
"idf.espIdfPathWin": "c:\\Users\\aaa\\Documents\\GitHub\\esp-idf",
    "idf.toolsPathWin": "c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2",
    "idf.pythonBinPathWin": "c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\python_env\\idf4.2_py3.8_env\\Scripts\\python.exe",
    "idf.customExtraPaths": "c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\python_env\\idf4.2_py3.8_env\\Scripts;C:\\Users\\aaa\\AppData\\Local\\Programs\\Python\\Python38-32;c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\tools\\xtensa-esp32-elf\\esp-2020r3-8.4.0\\xtensa-esp32-elf\\bin;c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\tools\\xtensa-esp32s2-elf\\esp-2020r3-8.4.0\\xtensa-esp32s2-elf\\bin;c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\tools\\esp32ulp-elf\\2.28.51-esp-20191205\\esp32ulp-elf-binutils\\bin;c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\tools\\esp32s2ulp-elf\\2.28.51-esp-20191205\\esp32s2ulp-elf-binutils\\bin;c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\tools\\cmake\\3.16.4\\bin;c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\tools\\openocd-esp32\\v0.10.0-esp32-20200709\\openocd-esp32\\bin;c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\tools\\ninja\\1.10.0;c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\tools\\idf-exe\\1.0.1;c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\tools\\ccache\\3.7;c:\\Users\\aaa\\Documents\\ESP-IDF_Tools\\v4.2\\tools\\dfu-util\\0.9\\dfu-util-0.9-win64",
    "idf.customExtraVars": "{\"OPENOCD_SCRIPTS\":\"c:\\\\Users\\\\aaa\\\\Documents\\\\ESP-IDF_Tools\\\\v4.2\\\\tools\\\\openocd-esp32\\\\v0.10.0-esp32-20200709/openocd-esp32/share/openocd/scripts\",\"IDF_CCACHE_ENABLE\":\"1\"}",
    "idf.showOnboardingOnInit": false,
    "idf.portWin": "COM5",
`

**Additional context**
Should be a fair easy fix
As build and flash is working, the new "Monitor" button just need to follow the same pattern to make it work.

**Comment by wooky** [comment]
When I open the ESP-IDF terminal and hit the up arrow a few times, I see that it's trying to set the environment variables in cmd, but failing:
```cmd
set "Path= 
set "IDF_PATH=
set "IDF_TARGET=
set "PYTHON=
set "IDF_PYTHON_ENV_PATH=
cls
```
I've got the variables set up properly in VSCode, but they're not getting properly input into cmd.
