### ISSUE TITLE
Does this plugin support parallel compilation? (VSC-548)

### ISSUE THREAD

**Issue by modi12jin** [espressif/vscode-esp-idf-extension#294]
I am very curious whether this plugin can be compiled in parallel?

**Comment by brianignacio5** [comment]
Can you explain with a bit more detail what is that you wish to achieve with the extension ?

**Comment by Cycov** [comment]
Add the -j option to your make commands. A command of make -j4 will run make with 4 parallel jobs. Espressif recommends running with option -j(number of CPUs +1)
