### ISSUE TITLE
IDF-4.1.1 get_python_env_path( ) return error path (IDFGH-4675) (VSC-566)

### ISSUE THREAD

**Issue by George-Chao** [espressif/vscode-esp-idf-extension#309]
in idf_tools.py, line number : 964

```python

match = re.match(r'^v([0-9]+\.[0-9]+).*', idf_version_str)

```

**if idf_version_str == "v4.1.1" , then match.group(1) will be "4.1", this is wrong.**
the right version is : 

```python

match = re.match(r'^v(\.,[0-9]+).*', idf_version_str)

```

**Comment by brianignacio5** [comment]
Hi @George-Chao Thanks for reporting this. Will fix asap
