### ISSUE TITLE
Need to update app-template (VSC-236)

### ISSUE THREAD

**Issue by syu-source** [espressif/vscode-esp-idf-extension#31]
**Describe the bug**
CMakefile.txt is using old components registration API, which doesn't have document support.

**To Reproduce**

Press F1 and type ESP-IDF: Create ESP-IDF project to generate a template ESP-IDF project.

**Expected behavior**
I suppose CMakefile.txt should be using `idf_component_register `instead of `register_component`

**Screenshots**
![image](https://user-images.githubusercontent.com/35789043/74238842-93f04000-4d11-11ea-8442-a4f24becf550.png)

**Environment (please complete the following information):**
OS Name & Version: [Win10]
VSCode Version: [1.42]
ESP-IDF Version: [4.1]
Python Version: [3.7]

**Additional context**
https://github.com/espressif/esp-idf-template

**Comment by bitmakk** [comment]
The two code is the same, it is just a cmake macro.
There is no "old components registration API", and it is perfect in these way too.

**Comment by syu-source** [comment]
It works both ways, yes.
But I could only find document at 
https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system.html#

I'm moving my project from legacy GNU Make system, and get confused by Cmakefile.txt of the default app template because it doesn't match the official document.

Anyway, I built my project based on examples which is using `idf_component_register `.
