### ISSUE TITLE
[Bug Report]: Failed to configure the ESP-IDF extension on download ESP-IDF Tools (VSC-571)

### ISSUE THREAD

**Issue by RoyLi-Pvt** [espressif/vscode-esp-idf-extension#317]
**Describe the bug**
try download ESP-IDF Tools in ESP-IDF: Configure ESP-IDF extension get a "Cannot read property '0' of undefined" ErrorMsg

**To Reproduce**
1. VSCode Remote SSH Connect to Host
1. Install ESP-IDF extension
1. ESP-IDF: Configure ESP-IDF extension,chose Advanced, Find ESP-IDF in your system and install
1. In the ESP-IDF Tools page, chose Download ESP-IDF Tools, Click Download Tools 
1. Get a error message "Cannot read property '0' of undefined"

**Environment :**

- OS Name & Version: LocalPC:Win10 ProWorkstation X64 20H2 19042.804 RemoteHost: ArchLinux
- VSCode Version: 1.54.0-insider And 1.53.2
- ESP-IDF Version: master 73db142403c6e5b76
- Python Version: 3.9.1

**ESP-IDF: Doctor command Result:**

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS linux x64 5.10.13-arch1-1 
System environment variable PATH 
 /home/username/.vscode-server-insiders/bin/6eaef7d42f982a0e9b22ac465245fc2c27721fd0/bin:/home/username/.vscode-server-insiders/bin/6eaef7d42f982a0e9b22ac465245fc2c27721fd0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl 
Visual Studio Code version 0.6.1 
Visual Studio Code language en 
Visual Studio Code shell /usr/bin/fish 
ESP-IDF Extension version 1.54.0-insider 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-IDF Path (idf.espIdfPath) /Devel/ESP-IDF
Custom extra paths (idf.customExtraPaths) 
Custom extra vars (idf.customExtraVars) {}
Virtual env Python Path (idf.pythonBinPath) /Devel/Espressif/python_env/idf4.4_py3.9_env/bin/python
Serial port (idf.port) /dev/ttyUSB0
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,board/esp32-wrover.cfg
ESP-IDF Tools Path (idf.toolsPath) /Devel/Espressif
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-IDF Custom extra paths
Access to : false
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH true
Access to Ninja in environment PATH true
Access to ESP-IDF Tools Path (idf.toolsPath) true
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.30.1
ESP-IDF version 4.4
Python version 3.9.1
Python's pip version 20.2.3
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bidict version: 0.21.2
bitstring version: 3.1.7
Brotli version: 1.0.9
certifi version: 2020.12.5
cffi version: 1.14.5
chardet version: 4.0.0
click version: 7.1.2
construct version: 2.10.54
cryptography version: 3.4.6
ecdsa version: 0.16.1
Flask version: 0.12.5
Flask-Compress version: 1.9.0
Flask-SocketIO version: 2.9.6
future version: 0.18.2
gcovr version: 4.2
gdbgui version: 0.13.2.0
gevent version: 1.5.0
greenlet version: 1.0.0
idna version: 2.10
itsdangerous version: 1.1.0
Jinja2 version: 2.11.3
kconfiglib version: 13.7.1
lxml version: 4.6.2
MarkupSafe version: 1.1.1
pip version: 20.2.3
psutil version: 5.8.0
pycparser version: 2.20
pyelftools version: 0.27
pygdbmi version: 0.9.0.2
Pygments version: 2.8.0
pyparsing version: 2.3.1
pyserial version: 3.5
python-engineio version: 4.0.0
python-socketio version: 5.0.4
reedsolo version: 1.5.4
requests version: 2.25.1
setuptools version: 49.2.1
six version: 1.15.0
typing version: 3.7.4.3
urllib3 version: 1.26.3
websocket-client version: 0.57.0
Werkzeug version: 0.16.1
wheel version: 0.36.2
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages undefined
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages undefined
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages undefined
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at Cannot read property '0' of undefined
--------------------------------------------------------------------------------------------------------------------------------------------

**Logs**
[2021-02-19 14:04:53.333] [exthost] [error] TypeError: Cannot read property '0' of undefined
        at /home/username/.vscode-server-insiders/extensions/espressif.esp-idf-extension-0.6.1/dist/extension.js:1:90763
        at new Promise (<anonymous>)
        at d.getPackageList (/home/username/.vscode-server-insiders/extensions/espressif.esp-idf-extension-0.6.1/dist/extension.js:1:90586)
        at d.<anonymous> (/home/username/.vscode-server-insiders/extensions/espressif.esp-idf-extension-0.6.1/dist/extension.js:1:94171)
        at Generator.next (<anonymous>)
        at /home/username/.vscode-server-insiders/extensions/espressif.esp-idf-extension-0.6.1/dist/extension.js:1:90265
        at new Promise (<anonymous>)
        at l (/home/username/.vscode-server-insiders/extensions/espressif.esp-idf-extension-0.6.1/dist/extension.js:1:90010)
        at d.getRequiredToolsInfo (/home/username/.vscode-server-insiders/extensions/espressif.esp-idf-extension-0.6.1/dist/extension.js:1:94074)
        at /home/username/.vscode-server-insiders/extensions/espressif.esp-idf-extension-0.6.1/dist/extension.js:1:81658
        at Generator.next (<anonymous>)
        at s (/home/username/.vscode-server-insiders/extensions/espressif.esp-idf-extension-0.6.1/dist/extension.js:1:78712)

**Extension Configuration settings**

"idf.baudRate": "921600",
"idf.port": "/dev/ttyUSB0",
"idf.espIdfPath": "/Devel/ESP-IDF",
"idf.toolsPath": "/Devel/Espressif"

**Additional context**

Reinstall Ext
Reinstall Remote Server
Completely Delete Remote Folder And Reinstall
Not Worker for this
VSCode 1.53.2 is fresh install on local not work too

**Comment by brianignacio5** [comment]
HI @RoyLi-Pvt Thanks for reporting this.

We had fixed in this repository master with https://github.com/espressif/vscode-esp-idf-extension/commit/ceff3b4070832bcf0cb9d7607eadf4bff765dc38 and will update on next marketplace release soon.
