### ISSUE TITLE
[Bug Report]: ESP-ADF project template is missing  (VSC-572)

### ISSUE THREAD

**Issue by derflaryam** [espressif/vscode-esp-idf-extension#318]
running the latest version and trying to compile the simple ESP-ADF example play_mp3. 

installed the ADF via  vscode-extension. 
Changed the path for ADF windows. 

compiling a IDF project works fine. 

When I change the root CMakeLists.txt including the ADF components the build does not find the ADF  CMakeLists.txt. - see in cmake_log.zip

I tried two differrent path settings - see IDF_settings1.PNG IDF_settings2.PNG.
both with the same result - cant find the ADF CMakeLists.txt.

PLEASE provide a ESP-ADF TEMPLATE  !!!!
Thank you

[cmake_log.zip](https://github.com/espressif/vscode-esp-idf-extension/files/6008314/cmake_log.zip)
![IDF_settings1](https://user-images.githubusercontent.com/4267057/108472064-8a86a580-728c-11eb-8c95-04e315de1304.PNG)
![IDF_settings2](https://user-images.githubusercontent.com/4267057/108472065-8b1f3c00-728c-11eb-88d7-52041f1ffd66.PNG)

**Comment by brianignacio5** [comment]
Thanks for reporting will fix soon.
