### ISSUE TITLE
Impossible to install tools fron Visual Studio Code [Bug Report]:  (VSC-573)

### ISSUE THREAD

**Issue by gmgunderground** [espressif/vscode-esp-idf-extension#321]
Hi, using the wizard I can install ESP-IDF, but not tools

idf_versions.txt has (1) KB
idf_versions.txt progress: 100.00% (0.08 / 0.08) KB
Cannot read property '0' of undefined
Cannot read property '0' of undefined

**Comment by brianignacio5** [comment]
Hi @gmgunderground this is a duplicate of #317
