### ISSUE TITLE
VSC does not find ADF path [Bug Report]:  (VSC-576)

### ISSUE THREAD

**Issue by derflaryam** [espressif/vscode-esp-idf-extension#327]
using the Version 1 of the IDF extension. 

VSC does not find the ADF includes. see png. 

Compiling a ADF application is working now.

![ADF_Path](https://user-images.githubusercontent.com/4267057/108636930-a5be0480-7488-11eb-9b0e-a335c743ba88.PNG)

**Comment by brianignacio5** [comment]
What is the content of `${workspaceFolder}/build/compile_commands.json` ? If you are using the default configuration (as shown in C_CPP_CONFIGURATION documentation) please add

```json
"includePath": [
        "${config:idf.espIdfPath}/components/**",
        "${config:idf.espIdfPathWin}/components/**",
         "${config:idf.espAdfPath}/components/**",
        "${config:idf.espAdfPathWin}/components/**",
        "${workspaceFolder}/**"
      ],
```
or use the compile_commands.json configuration which should provide a more accurately resolution of include headers.

Please take a look at [C_CPP_CONFIGURATION](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/C_CPP_CONFIGURATION.md) documentation for more details about include configuration.

**Comment by derflaryam** [comment]
[compile_commands.zip](https://github.com/espressif/vscode-esp-idf-extension/files/6024189/compile_commands.zip)

with this configuration the ADF includes aren not found in the VSC editor, but VSC can find the IDF includes ! !

**Comment by derflaryam** [comment]
I changed Extension IntelliSense engine to Tag Parser. 

now it works

**Comment by meltdown03** [comment]
I had really good luck using the CMake Tools
(ms-vscode.cmake-tools) extension and `Default` engine. It needs a bit of setup up, but only finds symbols that pertain to the project once it is.

**Comment by brianignacio5** [comment]
Can you expand a bit how did you configured it @meltdown03 ? I've tried using it before without much success.

**Comment by brianignacio5** [comment]
Closing this issue since original issue is fixed.
