### ISSUE TITLE
Closing Monitor before flashing (VSC-579)

### ISSUE THREAD

**Issue by seulater** [espressif/vscode-esp-idf-extension#329]
If you open the monitor, build your project, then close the monitor,  and try to flash you will get a "ESP-IDF Monitor closed" popup. 
The only way to recover is to close VSC and reopen it to flash again. 

Also, if you already have the monitor open, and try to flash it does close the monitor automatically now, but it cannot then flash. I think you need a bit of a delay from the close to when you actually try to flash.

**Comment by brianignacio5** [comment]
Thanks @seulater  for reporting ! Will take a look

**Comment by seulater** [comment]
Just letting you know that this problem is still here. on v 1.0.1 
Did you guys actually connect a board and try it?

**Comment by brianignacio5** [comment]
Yes @seulater we did tested, actually was hoping you try #337 to see if this still happens. Another user tested and it seemed ok. I'll add a PR .

**Comment by seulater** [comment]
OK, To be honest I don't know how to pull in these fixes. I just wait until VSC updates your extension. 
If you feel the need, i can take a video of what happens.
