### ISSUE TITLE
unable to use the latest esp idf vs code extension v 1.0.0 (VSC-587)

### ISSUE THREAD

**Issue by ankit-thealchemist** [espressif/vscode-esp-idf-extension#342]
Hello, 

When ever I installed latest version 1.0.0  of esp idf extension  and start the vs code I found the error in the vs code output window stated as the 
idf_versions.txt has (1) KB
idf_versions.txt progress: 100.00% (0.08 / 0.08) KB
'cmd' is not recognized as an internal or external command,
operable program or batch file.
Command failed: cmd /c echo idf4.3_py3.9_2021-01-07
'cmd' is not recognized as an internal or external command,
operable program or batch file.
Error checking idf-python-wheels version
Error: Command failed: cmd /c echo idf4.3_py3.9_2021-01-07
'cmd' is not recognized as an internal or external command,
operable program or batch file.

while I downgrade to the version 0.5.1 it works fine. I uses the esp-idf master and the python 3.7. 

Please find the detailed esp doctor report 

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 6.3.9600 
System environment variable PATH 
 C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\Python37;C:\Python37\Scripts;C:\Python37\Scripts\;C:\Python37\;C:\Users\programmer\AppData\Local\GitHubDesktop\bin 
Visual Studio Code version 1.0.0 
Visual Studio Code language en 
Visual Studio Code shell C:\Windows\System32\cmd.exe 
ESP-IDF Extension version 1.54.1 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-IDF Path (idf.espIdfPath) d:\IOTCode\framework\esp-idf
Custom extra paths (idf.customExtraPaths) d:\IOTCode\framework\toolchain4.0\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin;d:\IOTCode\framework\toolchain4.0\.espressif\tools\xtensa-esp32s2-elf\esp-2020r3-8.4.0\xtensa-esp32s2-elf\bin;d:\IOTCode\framework\toolchain4.0\.espressif\tools\xtensa-esp32s3-elf\esp-2020r3-8.4.0\xtensa-esp32s3-elf\bin;d:\IOTCode\framework\toolchain4.0\.espressif\tools\riscv32-esp-elf\1.24.0.123_64eb9ff-8.4.0\riscv32-esp-elf\bin;d:\IOTCode\framework\toolchain4.0\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;d:\IOTCode\framework\toolchain4.0\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;d:\IOTCode\framework\toolchain4.0\.espressif\tools\cmake\3.16.4\bin;d:\IOTCode\framework\toolchain4.0\.espressif\tools\openocd-esp32\v0.10.0-esp32-20200709\openocd-esp32\bin;d:\IOTCode\framework\toolchain4.0\.espressif\tools\ninja\1.10.2;d:\IOTCode\framework\toolchain4.0\.espressif\tools\idf-exe\1.0.1;d:\IOTCode\framework\toolchain4.0\.espressif\tools\ccache\3.7;d:\IOTCode\framework\toolchain4.0\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64;d:\IOTCode\framework\toolchain4.0\.espressif\tools\idf-python-wheels\idf4.3_py3.9_2021-01-07
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"d:\\IOTCode\\framework\\toolchain4.0\\.espressif\\tools\\openocd-esp32\\v0.10.0-esp32-20200709/openocd-esp32/share/openocd/scripts","IDF_CCACHE_ENABLE":"1"}
Virtual env Python Path (idf.pythonBinPath) d:\IOTCode\framework\toolchain4.0\.espressif\python_env\idf4.4_py3.7_env\Scripts\python.exe
Serial port (idf.port) /dev/ttyUSB1
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,board/esp32-wrover.cfg
ESP-IDF Tools Path (idf.toolsPath) d:\IOTCode\framework\toolchain4.0\.espressif
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-IDF Custom extra paths
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\xtensa-esp32s2-elf\esp-2020r3-8.4.0\xtensa-esp32s2-elf\bin: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\xtensa-esp32s3-elf\esp-2020r3-8.4.0\xtensa-esp32s3-elf\bin: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\riscv32-esp-elf\1.24.0.123_64eb9ff-8.4.0\riscv32-esp-elf\bin: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\cmake\3.16.4\bin: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\openocd-esp32\v0.10.0-esp32-20200709\openocd-esp32\bin: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\ninja\1.10.2: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\idf-exe\1.0.1: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\ccache\3.7: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: true
Access to d:\IOTCode\framework\toolchain4.0\.espressif\tools\idf-python-wheels\idf4.3_py3.9_2021-01-07: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.27.0.windows.1
ESP-IDF version 4.4
Python version 3.7.8
Python's pip version 20.1.1
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bidict version: 0.21.2
bitstring version: 3.1.7
Brotli version: 1.0.9
certifi version: 2020.12.5
cffi version: 1.14.5
chardet version: 4.0.0
click version: 7.1.2
construct version: 2.10.54
cryptography version: 3.4.6
ecdsa version: 0.16.1
esp-windows-curses version: 0.1
Flask version: 0.12.5
Flask-Compress version: 1.9.0
Flask-SocketIO version: 2.9.6
future version: 0.18.2
gcovr version: 4.2
gdbgui version: 0.13.2.0
gevent version: 1.5.0
greenlet version: 1.0.0
idna version: 2.10
itsdangerous version: 1.1.0
Jinja2 version: 2.11.3
kconfiglib version: 13.7.1
lxml version: 4.6.2
MarkupSafe version: 1.1.1
pip version: 20.1.1
psutil version: 5.8.0
pycparser version: 2.20
pyelftools version: 0.27
pygdbmi version: 0.9.0.2
Pygments version: 2.8.1
pyparsing version: 2.3.1
pyserial version: 3.5
python-engineio version: 4.0.0
python-socketio version: 5.0.4
pywin32 version: 300
reedsolo version: 1.5.4
requests version: 2.25.1
setuptools version: 47.1.0
six version: 1.15.0
typing version: 3.7.4.3
urllib3 version: 1.26.3
websocket-client version: 0.58.0
Werkzeug version: 0.16.1
wheel version: 0.36.2
windows-curses version: 2.2.0
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements from d:\IOTCode\framework\esp-idf\requirements.txt are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements from c:\Users\programmer\.vscode\extensions\espressif.esp-idf-extension-1.0.0\requirements.txt are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements from c:\Users\programmer\.vscode\extensions\espressif.esp-idf-extension-1.0.0\esp_debug_adapter\requirements.txt are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "espidf",
            "name": "Launch",
            "request": "launch",
        }
    ]
}
 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
  "configurations": [
    {
      "name": "Linux",
      "cStandard": "c11",
      "cppStandard": "c++17",
      "includePath": [
        "${config:idf.espIdfPath}/components/**",
        "${config:idf.espIdfPathWin}/components/**",
        "${workspaceFolder}/**"
      ],
      "browse": {
        "path": [
          "${config:idf.espIdfPath}/components",
          "${config:idf.espIdfPathWin}/components",
          "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": false
      }
    }
  ],
  "version": 4
}
 
--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by brianignacio5** [comment]
Can you uninstall your extension, erase `c:\Users\programmer.vscode\extensions\espressif.esp-idf-extension-1.0.0` and install [github master vsix installer](https://github.com/espressif/vscode-esp-idf-extension/suites/2213369212/artifacts/45786627) and try again ? 

We have made some changes to the terminal used by extension tasks and keep improving it, sorry for the issues.

**Comment by ankit-thealchemist** [comment]
> Can you uninstall your extension, erase `c:\Users\programmer.vscode\extensions\espressif.esp-idf-extension-1.0.0` and install [github master vsix installer](https://github.com/espressif/vscode-esp-idf-extension/suites/2213369212/artifacts/45786627) and try again ?
> 
> We have made some changes to the terminal used by extension tasks and keep improving it, sorry for the issues.

sorry to bother!  vs code is unable to see the cmd.exe, thus I added the system32 folder to the path variable. It is working now
! anyway thanks for helping
Closing the ticket!
