### ISSUE TITLE
Uploading data to SPIFFS:  (VSC-588)

### ISSUE THREAD

**Issue by derflaryam** [espressif/vscode-esp-idf-extension#343]
Is there a way to upload SPIFFS content to the target as it is already inplemented in VSC Platformio ?

**Comment by derflaryam** [comment]
![SPIFFS_upload](https://user-images.githubusercontent.com/4267057/110593587-0ed99380-817c-11eb-9afe-f766b9f71472.PNG)

**Comment by brianignacio5** [comment]
We currently don't have this feature in this extension but we are setting up some ground work to implement it.

For now, you could execute `ESP-IDF: Open ESP-IDF Terminal`  to launch a terminal (with env variables loaded) and run
```
parttool.py --port "/dev/ttyUSB1" write_partition --partition-name=factory "factory.bin"
```
to write to partition 'factory' the contents of a file named 'factory.bin'

You can also use `esptool.py` to flash it as well
