### ISSUE TITLE
[Feature Request]: Renaming templates when generated sample app (VSC-589)

### ISSUE THREAD

**Issue by derflaryam** [espressif/vscode-esp-idf-extension#344]
It would be helpful when during project creation the name could be chosen instead manually renaming it. 

Further it would be good to chose one of the many IDF/ADF/MDF samples as start foor a new project. In your eclipse implementation you are already providing this feature. 

![Eclipse_IDF_selection](https://user-images.githubusercontent.com/4267057/110593410-d0dc6f80-817b-11eb-9a16-690822744cdd.PNG)

**Comment by brianignacio5** [comment]
We just merged the [New project wizard PR](https://github.com/espressif/vscode-esp-idf-extension/pull/171) with a new `ESP-IDF: New Project` where you can rename the project and use template projects from ESP-ADF and ESP-MDF if configured in the extension:
*  idf.espAdfPath (idf.espAdfPathWin in Windows)
* idf.espMdfPath (idf.espMdfPathWin in Windows) 

will be part of v1.0.1 release.

There is also the `ESP-IDF: Show Examples` command that allows you to create a project from a template of ESP-IDF, ESP-ADF and ESP-MDF but this one doesn't provide renaming of the project as described in the README.
