### ISSUE TITLE
Ability chance to pause idf monitor (VSC-590)

### ISSUE THREAD

**Issue by drony** [espressif/vscode-esp-idf-extension#345]
I use very intense logging and it goes to fast, i can't follow logs. if pause on mouse over or click its enough to me.

thanks

**Comment by brianignacio5** [comment]
Have you look into the `IDF Monitor`  [commands](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-monitor.html#keyboard-shortcuts) ?

**Comment by drony** [comment]
ctrl+y or cmd+y doesn't works. i'm using macOS

**Comment by brianignacio5** [comment]
To pause the log output do `CTRL + T CTRL + Y`

Maybe disable certain logs as explained in [logging library](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/log.html)
