### ISSUE TITLE
After update to last version 1.01 debugger does not work properly (VSC-594)

### ISSUE THREAD

**Issue by ihouses** [espressif/vscode-esp-idf-extension#350]
Hi,

I have updated to the last version from the V1.0. Now when I debug the program it just pass though and does not stop in any of the breakpoints. Finally it shows a pop up error window with no error text message (empty)
![example](https://user-images.githubusercontent.com/5103057/111052304-fa3a1b80-8459-11eb-9aed-c69dd8be42a8.jpg

Other times I see other error in a pop up message in the right-bottom corner:
OpenOCD Exit with non-zero error code 3221225477

Does anybody else see the same issue?

**Comment by brianignacio5** [comment]
Hi @ihouses I'm not sure where is the issue coming from. v1.0.1 should have no changes in debug adapter.

Are you sure this is the right application offset ? 

Can you provide information about your setup

**NOTE: You can use the `ESP-IDF: Doctor command` to generate a report of your configuration.**
**Logs**
If applicable, please share the log file which can be obtained from

- Windows: `%USERPROFILE%\.vscode\extensions\espressif.esp-idf-extension-VERSION\esp_idf_vsc_ext.log`
- Linux & MacOSX: `$HOME/.vscode/extensions/espressif.esp-idf-extension-VERSION/esp_idf_vsc_ext.log`

Debug log 
<current_project_directory>/debug.log

**Extension Configuration settings**
Open Command Palette (F1) and type `Preferences: Open Settings (JSON)` or use `{CURRENT_PROJECT}/.vscode/settings.json` to get the following extension configuration settings value:

- `idf.espIdfPath` (MacOS or Linux) or `idf.espIdfPathWin` (Windows) also called `Path to locate ESP-IDF framework (IDF_PATH)` in `Preferences: Open Settings (UI)`.
- `idf.pythonBinPath` (MacOS or Linux) or `idf.pythonBinPathWin` (Windows) also called `Python absolute binary path used to execute ESP-IDF Python Scripts` in `Preferences: Open Settings (UI)`.
- `idf.openOcdConfigs` also called `List of configuration files inside OpenOCD Scripts directory` in `Preferences: Open Settings (UI)`.
- `idf.customExtraPaths` also called `Paths to be appended to PATH` in `Preferences: Open Settings (UI)`.
- `idf.customExtraVars` also called `Variables to be added to system environment variables` in `Preferences: Open Settings (UI)`.
- `idf.adapterTargetName` also called `Target name for ESP-IDF Debug Adapter` in `Preferences: Open Settings (UI)`.
- `idf.customAdapterTargetName` is used when `idf.adapterTargetName` is set to `custom`.
