### ISSUE TITLE
Documentation (VSC-612)

### ISSUE THREAD

**Issue by jpnielsen** [espressif/vscode-esp-idf-extension#360]
Documentation does not give the expected result:

![image](https://user-images.githubusercontent.com/27916597/112554352-6b68bf80-8dc6-11eb-9631-eb8f5cfdc867.png)

**Comment by brianignacio5** [comment]
Thanks for reporting. Will update docs.

By the way the command search doesn't have to be exact, just need certain keywords like `create`, `project`, etc.
