### ISSUE TITLE
[Feature Request]: Better error msg for ERROR_INVALID_PYTHON (VSC-620)

### ISSUE THREAD

**Issue by JosuGZ** [espressif/vscode-esp-idf-extension#364]
I have installed the extension on Linux, and I was experiencing the ERROR_INVALID_PYTHON error.

Looking at the source code, I've seen that the problem might be related to PIP (`checkPythonPipExists`). Installing pip has solved the issue. It would be nice to have a more descriptive error message.

```
  const pyCheck = await checkPythonPipExists(pyPath, __dirname);
  if (!pyCheck) {
    const containerNotFoundMsg = `${pyPath} is not valid. (ERROR_INVALID_PYTHON)`;
    Logger.infoNotify(containerNotFoundMsg);
```

## Edit

It has failed again due to not having python3-venv. Perhaps it would be good to check/warn about that too, although it provides the solution so it is not a big hassle: apt-get install python3-venv. (I'm using VS Code on Linux Mint 20). There are some additional errors (`no module named pip`)), I will update this so it can help others.

## Edit 2

I can't get this thing to work... It seems to be installed but it does not work. For example, when trying to run `ESP-IDF: New Project`, I get an `undefined` error. The version of python is 3.8.5.

The linux distribution is:

```
Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa
```

**Comment by brianignacio5** [comment]
Thanks for reporting this, will update the error messages.
System packages are specified in [ESP-IDF documentation prerequisites](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-setup.html#install-prerequisites).

In the extension, we execute something like `python -m pip --version` to check the ESP-IDF. Sometimes pip is not linked to a given python binaries. Maybe try the previous command in a terminal first to see that pip is indeed a module of the selected python executable.

For any additional step, can you provide:

**NOTE**: You can use the `ESP-IDF: Doctor command` to generate a report of your configuration (it will be copied to your clipboard).

**Logs**
If applicable, please share the log file which can be obtained from

- Windows: `%USERPROFILE%\.vscode\extensions\espressif.esp-idf-extension-VERSION\esp_idf_vsc_ext.log`
- Linux & MacOSX: `$HOME/.vscode/extensions/espressif.esp-idf-extension-VERSION/esp_idf_vsc_ext.log`
