### ISSUE TITLE
[Feature Request]: specify esp-chip type in UIconfig for serial download (VSC-623)

### ISSUE THREAD

**Issue by dangbinghoo** [espressif/vscode-esp-idf-extension#366]
it's not convenient if enabled flash encrypt, you need to manually specify chip type and flash size and use the command in bash terminal to perform a serial-port download. please supply option for specifying esp chip type in UIConfig.

**Comment by brianignacio5** [comment]
This should be fixed in #363 

PTAL @dangbinghoo 

Will close this issue. If this [extension installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/55654946.zip) doesn't fix your issue, please feel free to comment here to re-open the issue.
