### ISSUE TITLE
Unable to resolve 'esp32c3' for setting toolchain file (VSC-626)

### ISSUE THREAD

**Issue by TLCary** [espressif/vscode-esp-idf-extension#369]
[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/6290036/esp_idf_vsc_ext.log)
Extension Version v1.0.2 documentation indicated that ESP32C3 is now included.  
Configuration and then Build:

```
/Users/terry/.espressif/python_env/idf4.2_py3.9_env/bin/python /Users/terry/esp/esp-idf/tools/idf.py -p /dev/cu.usbserial-1440 monitor
terry@Terrys-MBP-6 blink % /Users/terry/.espressif/python_env/idf4.2_py3.9_env/bin/python /Users/terry/esp/esp-idf/tools/idf.py -p /dev/cu.usbserial-1440 monitor
Executing action: monitor
Running cmake in directory /Users/terry/esp/blink/blink/build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DCCACHE_ENABLE=0 /Users/terry/esp/blink/blink"...
-- Found Git: /usr/local/bin/git (found version "2.28.0") 
CMake Error at /Users/terry/esp/esp-idf/tools/cmake/targets.cmake:57 (message):
  Unable to resolve 'esp32c3' for setting toolchain file.
Call Stack (most recent call first):
  /Users/terry/esp/esp-idf/tools/cmake/project.cmake:294 (__target_set_toolchain)
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
cmake failed with exit code 1

```

MacOS X 11.2
VSCode 1.551.
ESP-IDF 4.2
Python 3.9

- Linux & MacOSX: `$HOME/.vscode/extensions/espressif.esp-idf-extension-VERSION/esp_idf_vsc_ext.log`
[http://dataaccord.com/esp_idf_vsc_ext.log](url)

**Extension Configuration settings**
Open Command Palette (F1) and type `Preferences: Open Settings (JSON)` or use `{CURRENT_PROJECT}/.vscode/settings.json` to get the following extension configuration settings value:
```
"idf.espIdfPath": "${env:IDF_PATH}",
```

- `idf.espIdfPath` (MacOS or Linux) or `idf.espIdfPathWin` (Windows) also called `Path to locate ESP-IDF framework (IDF_PATH)` in `Preferences: Open Settings (UI)`.
```
/Users/terry/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin:/Users/terry/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin:/Users/terry/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:/Users/terry/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/Users/terry/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200709/openocd-esp32/bin
```

- `idf.pythonBinPath` (MacOS or Linux) or `idf.pythonBinPathWin` (Windows) also called `Python absolute binary path used to execute ESP-IDF Python Scripts` in `Preferences: Open Settings (UI)`.
```
/Users/terry/.espressif/python_env/idf4.2_py3.9_env/bin/python
```

- `idf.openOcdConfigs` also called `List of configuration files inside OpenOCD Scripts directory` in `Preferences: Open Settings (UI)`.
```
{
    "kite.showWelcomeNotificationOnStartup": false,
    "idf.espIdfPath": "/Users/terry/esp/esp-idf",
    "idf.adapterTargetName": "esp32c3",
    "idf.pythonBinPath": "/Users/terry/.espressif/python_env/idf4.2_py3.9_env/bin/python",
    "idf.customExtraPaths": "/Users/terry/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin:/Users/terry/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin:/Users/terry/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:/Users/terry/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/Users/terry/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200709/openocd-esp32/bin",
    "idf.customExtraVars": "{\"OPENOCD_SCRIPTS\":\"/Users/terry/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200709/openocd-esp32/share/openocd/scripts\"}",
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
    "idf.openOcdConfigs": [
    
        "interface/ftdi/esp32_devkitj_v1.cfg",
        "board/esp32-wrover.cfg"
    ]
}
```

- `idf.customExtraPaths` also called `Paths to be appended to PATH` in `Preferences: Open Settings (UI)`.
```
/Users/terry/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin:/Users/terry/.espressif/tools/xtensa-esp32s2-elf/esp-2020r3-8.4.0/xtensa-esp32s2-elf/bin:/Users/terry/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:/Users/terry/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/Users/terry/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200709/openocd-esp32/bin
```

- `idf.customExtraVars` also called `Variables to be added to system environment variables` in `Preferences: Open Setting (UI)`.
```
{"OPENOCD_SCRIPTS":"/Users/terry/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200709/openocd-esp32/share/openocd/scripts"}
```

- `idf.adapterTargetName` also called `Target name for ESP-IDF Debug Adapter` in `Preferences: Open Settings (UI)`.
```
esp32c3
[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/6290035/esp_idf_vsc_ext.log)
```

- `idf.customAdapterTargetName` is used when `idf.adapterTargetName` is set to `custom`.
```
```

**Comment by brianignacio5** [comment]
Hi @TLCary the thing is, although the extension adds ESP32 C3 as IDF_TARGET, you still need to update ESP-IDF and ESP-IDF Tools for those that support ESP32-C3 like [v4.3-beta2](https://github.com/espressif/esp-idf/releases/tag/v4.3-beta2) and update the Visual Studio Code Configuration settings as described [here](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/SETUP.md#json-manual-configuration).

This is not included in the extension setup flow since v4.3 is still in beta phase and we encourage stable releases.
