### ISSUE TITLE
[Bug Report]: sdkconfig options `extra_esptool_args` aren't used by extension when flashing (VSC-633)

### ISSUE THREAD

**Issue by gferard-invn** [espressif/vscode-esp-idf-extension#373]
**Describe the bug**

If setting sdkconfig to not reset the board before and after the UART flash, the configuration is not applied

**To Reproduce**

* In menuconfig, category "Serial Flasher config", change options "before flashing" and "after flashing"
* Build project, the file "flasher_args.json" is created. Fields "extra_esptool_args/after" and "extra_esptool_args/before" have been updated accordingly to previous settings
* Flash project (UART), the command executed always sets "--after hard_reset"

**Expected behavior**

If modifying "Serial Flasher config" options I would expect to update the flash command to reset or not the board before and after flash (i.e. change option `--before` and `--after` of esptool).

**Environment:**

- OS Name & Version: Windows 10
- VSCode Version: 1.55.2
- ESP-IDF Version: 1.0.2
- Python Version: 3.8.2

```
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**How to fix**

* The information of reset option is well generated by build task into `flasher_args.json`
* The point is that these informations aren't used when flashing :
   * In `flashModelBuilder.ts`, when reading `flashArgsJson` the reset info aren't put into `FlashModel` variable
   * In `flashTask.ts`, `flasherArgs` should set args `--after` and `--before` with value in `this.model`

**Comment by brianignacio5** [comment]
Hi @gferard-invn We implemented this in #363 

You can try it installing it this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/51893637.zip)
