### ISSUE TITLE
[Bug Report]: close previous uart when flash or monitor (VSC-638)

### ISSUE THREAD

**Issue by thedayu** [espressif/vscode-esp-idf-extension#381]
**Describe the bug**
when click monitor, terminal will open holding uart port.
after that, if you rebuild proejct, and click flash, the terminal which holds uart port is reused, and the flash command fails.
at this point, only thing to do is re-plug the usb cable, which is troublesome.
(I'm using esp32-devkit). 

**Environment (please complete the following information):**
- OS Name & Version: [win10]
- VSCode Version: [1.0.2]
- ESP-IDF Version: [v3.2]
- Python Version: [3.8]

**Comment by brianignacio5** [comment]
Have you experimented with `idf.killMonitorTimeout` or  in Settings (UI) T_imeout (milliseconds) for ESP-IDF monitor process kill_ to configure the time to wait for monitor kill process.

**Comment by brianignacio5** [comment]
You can also try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/56186808.zip)

**Comment by brianignacio5** [comment]
This should be fixed with #382 . If you any additional issue please comment here to re-open.
