### ISSUE TITLE
Installation failed at setup python env (VSC-640)

### ISSUE THREAD

**Issue by michael999999** [espressif/vscode-esp-idf-extension#385]
Could not fetch URL https://pypi.org/simple/wheel/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/wheel/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by brianignacio5** [comment]
This is not an issue with the extension but with the python setup itself.

Maybe try a solution from https://stackoverflow.com/questions/41328451/ssl-module-in-python-is-not-available-when-installing-package-with-pip3

**Comment by brianignacio5** [comment]
Closing this issue since it is not related to the extension. Please let us know if we can help you fix your setup somehow.

**Comment by ma6254** [comment]
How can an offline environment need to be connected to the Internet? 
Can you apply vscode http_proxy parameter before executing install.ps1?

**Comment by brianignacio5** [comment]
To install python packages to the virtual environment you need to be connect to the internet. The install script (install.ps1) will use offline tools if found, but python packages would most likely be download from the PyPi repository or Espressif python package registry.
