### ISSUE TITLE
Unable to install - Invalid ESP-IDF (VSC-648)

### ISSUE THREAD

**Issue by JamieEC** [espressif/vscode-esp-idf-extension#393]
I get this error when I load the plugin:
![image](https://user-images.githubusercontent.com/48264520/116784319-8eeced00-aa8b-11eb-92c4-fa6db6596a6c.png)
I then get this error when installing:
![image](https://user-images.githubusercontent.com/48264520/116784397-e5f2c200-aa8b-11eb-9396-031c5533b0a6.png)
I tried the version from VSC-592, but to no avail.

**Comment by Pinni3** [comment]
i have the exact same issue

**Comment by brianignacio5** [comment]
Can you provide more information about your setup and steps to reproduce?

You can use the `ESP-IDF: Doctor command` to generate a report of your configuration.

**Logs**
If applicable, please share the log file which can be obtained from

- Windows: `%USERPROFILE%\.vscode\extensions\espressif.esp-idf-extension-VERSION\esp_idf_vsc_ext.log`
- Linux & MacOSX: `$HOME/.vscode/extensions/espressif.esp-idf-extension-VERSION/esp_idf_vsc_ext.log`

**Comment by creandotec** [comment]
Hi! Did you solve it? I was having the same problem, and I solved it enabling git to work from third party software

**Comment by lucatedeschi** [comment]
Just solved the problem.
I was on a fresh install so some element was not set properly, make sure you have the following software installed:

- Python (downloadable here https://www.python.org/downloads/)
- C++ compiler for VS (downloadable here https://visualstudio.microsoft.com/it/visual-cpp-build-tools/)
- Git for windows (dowloadable here https://gitforwindows.org/)

**Comment by brianignacio5** [comment]
We have a [prerequisites](https://github.com/espressif/vscode-esp-idf-extension#prerequisites) sections mentioning this but I guess its not visible right away.

**Comment by brianignacio5** [comment]
Closing this issue due to lack of response from original user.

Please comment to re-open the issue if still facing difficulties.
