### ISSUE TITLE
Extension doesn't use system's CMake (VSC-665)

### ISSUE THREAD

**Issue by tehKaiN** [espressif/vscode-esp-idf-extension#419]
**Describe the bug**
I already have CMake in my system, why does this package installs additional one? Win10.

**To Reproduce**
Install extension, see that cmake 3.16.4 is being installed

**Expected behavior**
Extension detects CMake in system, if version is newer than or equal to required then continues, otherwise asks if it should install latest copy on its own, or retry the check, allowing the user to update CMake to proper version in the meantime.

Same should be applicable to Ninja. Also, I plan to use vscode CMake extension to handle builds, so auto adding compiler kit to this extension would be nice thing to have.

**Environment (please complete the following information):**

- OS Name & Version: Win10 21H1
- VSCode Version: 1.56.2
- ESP-IDF Version: Any
- Python Version: 3.6.4

**Extension Configuration settings**
Clean install, so default config

**Comment by brianignacio5** [comment]
If you want to use an existing CMake and Ninja you can do 2 things:

1) use the [JSON Manual Configuration](https://github.com/espressif/vscode-esp-idf-extension#prerequisites)

2) Use the setup wizard on Advanced mode using existing ESP-IDF Tools

**Comment by brianignacio5** [comment]
Closing this issue for lack of response. Please comment here for additional support.
