### ISSUE TITLE
[Feature Request]: Install openocd udev rules on my behalf. (VSC-705)

### ISSUE THREAD

**Issue by zfields** [espressif/vscode-esp-idf-extension#455]
**Is your feature request related to a problem? Please describe.**
The Espressif extension installs all the dependencies required to get started, so it was very counter-intuitive that would have to install the `60-openocd.rules` file my hand. This caused me unnecessary friction in getting started. I had to spend several minutes researching this caveat, then I had to scan my machine to see where you downloaded the file. If I wasn't forced to use your board, then I may have switched to something I'm more familiar with.

**Describe the solution you'd like**
I would like to be prompted to install the `60-openocd.rules` file into `/etc/udev/rules.d/` during the course of installation.

**Describe alternatives you've considered**
Generate a pop-up or have very explicit messaging that this task is required, and where to file the file.

**Additional context**

**Comment by ajsb85** [comment]
Hi, @zfields & @brianignacio5 

I got an error, maybe need elevation 🛗 

```console
EISDIR: illegal operation on a directory, copyfile '/home/user/.espressif/tools/openocd-esp32/v0.10.0-esp32-20210902/openocd-esp32/share/openocd/contrib/60-openocd.rules' -> '/etc/udev/rules.d/'
```
