### ISSUE TITLE
Option to select where settings should be saved (VSC-251)

### ISSUE THREAD

**Issue by KaeLL** [espressif/vscode-esp-idf-extension#46]
Currently, Onboarding works by appending the settings to the user settings, and building the project won't work if those settings are not specifically there.

There should be a way to choose if the settings should be user-wide and workspace-wide. An option for Onboarding and another one for the Command Palette. Consequently, the extension would default to look for workspace settings first before moving on to look at user settings, following the regular VSCode flow of workspace settings overriding user's, or another option to choose which one should take precedence, should there ever be a need for such a thing.

The main reason why this is a must have it's because it makes it easy to work with multiple projects, versions of the toolchain, and versions of ESP-IDF. Another reason is pollution of user configurations, especially if VSCode isn't used solely for ESP32 development. I'm sure there are others, but these are the ones that I can think of right now.

**Comment by brianignacio5** [comment]
Thanks for the feedback.

Ideally when you set up vscode configuration settings, there is a preference such as workspace folder settings -> workspace settings -> user settings. Although in the current master we had no such feature yet (currently on review) you should be able to override user settings with workspace ones and those would be used instead. **Isn't that the case ?**

**Comment by KaeLL** [comment]
> Isn't that the case ?

No, it's the opposite. User settings should override Workspace settings. Along with the 2 reasons I already mentioned, this is also VSCode's regular flow (User > Workspace).

**Comment by brianignacio5** [comment]
> > Isn't that the case ?
> 
> No, it's the opposite. User settings should override Workspace settings. Along with the 2 reasons I already mentioned, this is also VSCode's regular flow (User > Workspace).

https://code.visualstudio.com/docs/getstarted/settings

**Comment by KaeLL** [comment]
LoL I actually got them backwards in my last comment. I meant to say Workspace > User. Anyway, thanks.
