### ISSUE TITLE
[Bug Report]:  intellisense (VSC-715)

### ISSUE THREAD

**Issue by MiladMohammadi72** [espressif/vscode-esp-idf-extension#475]
Hello 
It's ok and work good I mean I can compile and run and test the code 
But !!! 
I can't use intellisense engine for includes library and variable than I define
 even after compile It work without error but auto complete not work 

Look at this photos plz 

.

![IMG_20210718_131428.jpg](https://user-images.githubusercontent.com/12975530/126061550-a17e1b41-4b0c-4a92-a5b3-7acce5cbcd6d.jpg)

.

![IMG_20210718_131509.jpg](https://user-images.githubusercontent.com/12975530/126061554-9e084619-226c-4e91-922f-ec2daca0a0cb.jpg)

.

![IMG_20210718_131523.jpg](https://user-images.githubusercontent.com/12975530/126061556-cc6588b4-c6f1-4387-b19c-404569258ddd.jpg)

.

- OS Name & Version: win 10 x64
- VSCode Version: 1.58.2
- ESP-IDF Version: 1.1.1
- Python Version: 3.8 above

Thanks

**Comment by brianignacio5** [comment]
Hi @MiladMohammadi72 have you look into [C_CPP configuration ](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/C_CPP_CONFIGURATION.md) documentation ?

We rely on the Microsoft C/C++ extension to provide auto-complete, syntax highlight and code navigation (i.e. Intellisense). IF you can build successfully, I would suggest to add the `compile_commands.json` to `c_cpp_properties.json` file for better results.

**Comment by MiladMohammadi72** [comment]
> Hi @MiladMohammadi72 have you look into [C_CPP configuration ](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/C_CPP_CONFIGURATION.md) documentation ?
> 
> We rely on the Microsoft C/C++ extension to provide auto-complete, syntax highlight and code navigation (i.e. Intellisense). IF you can build successfully, I would suggest to add the `compile_commands.json` to `c_cpp_properties.json` file for better results.


Thanks
yeah [C_CPP configuration ](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/C_CPP_CONFIGURATION.md) it's just work for include and header
But not for struc variable in first Picture...

**Comment by brianignacio5** [comment]
yes it should also work for autocomplete too. If you put the `workspaceFolder` path first in the include array it should give priority for source defined variables.

This is not yet optimized since we do not maintain the Microsoft C/C++ extension. We have yet to optimize this somehow. Very sorry for the inconvenience.

**Comment by brianignacio5** [comment]
Closing this since it is not an issue but user misconfiguration. Please comment here if more help is needed.
