### ISSUE TITLE
[Bug Report]: Menuconfig not showing any output on error (VSC-722)

### ISSUE THREAD

**Issue by alexander-sorokin** [espressif/vscode-esp-idf-extension#484]
Had this problem on Mac and Windows with different esp-idf versions.
Nothing is shown when some errors preventing to run Menuconfig correctly.
Some data blinks in Output for less than half of a second and disappears.

Would be great to report something more or less permanent about configuration problems.

Other projects (configured without problems) can be built successfully.

**Comment by brianignacio5** [comment]
Please take a look at the  [troubleshooting section](https://github.com/espressif/vscode-esp-idf-extension#troubleshooting) which tell us where errors are found and printed.

For example: the `SDK Configuration Editor` Output view will show the confserver output and errors related to that. The log could contain other related errors.
