### ISSUE TITLE
[Feature Request]: Support for unit testing with esp-idf / unity (VSC-723)

### ISSUE THREAD

**Issue by bpietsch** [espressif/vscode-esp-idf-extension#485]
**Is your feature request related to a problem? Please describe.**
Would like to see in-built support for the esp-idf unit testing features from within the IDE

**Comment by bpietsch** [comment]
Bumping so it doesn't get auto-closed.

**Comment by ChrisEAlfred** [comment]
Is there any update?

Bit of a worry if no one is doing unit tests!

**Comment by ZeroX96** [comment]
Any progress or updates?**How may one join the development**

**Comment by ZeroX96** [comment]
Any progress or updates?

**Comment by PrathamG** [comment]
Hi! Is there any updates for this feature?

**Comment by brianignacio5** [comment]
Apologies guys for very late work on this. 

Please take a look at #1013 for an initial implementation of this feature.
