### ISSUE TITLE
[Bug Report]: Changing device port without effect (VSC-724)

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [espressif/vscode-esp-idf-extension#487]
**Describe the bug**
I have two ESP32, one I use for testing, the other for production. The test ESP always is assigned to COM6, but the production ESP is assigned on COM5. When I try to switch using the "ESP-IDF Select Device Port" button at the bottom left corner of the screen, the switch is registered ("Port has been updated to COM5"-Message appears) but it doesn't seem to take effect. Whenever I run "Flash" or "Build, Blash, Monitor", always port COM6 is chosen no matter what I do (it states "Serial port COM6" from esptool.py). My solution is to run a cmd and type the flash command manually each time by specifying the -p flag, but this is annoying.

**To Reproduce**
Use two different ESPs and try to plug in one together with another device and the other without (I plug in a raspberry pi solely as a power consumer but it changes up the order anyway). In case the two ESPs are assigned different COM-ports, try switching device ports with the VSCode built-in botton in the bottom left corner of the window. Then try flashing it and notice that the device port change did not take effect.

**Expected behavior**
The device port change works and the binary is flashed accordingly.

**Screenshots**

**Environment (please complete the following information):**

- OS Name & Version: Windows 10 64bit
- VSCode Version: 1.58.2
- ESP-IDF Version: 4.4

**Extension Configuration settings**
Open Command Palette (F1 or View Menu -> Command Palette) and type `Preferences: Open Settings (JSON)` or use `{CURRENT_PROJECT}/.vscode/settings.json` to get the following extension configuration settings value:

    "idf.espIdfPathWin": "C:\\dev\\esp\\esp-idf",
    "idf.pythonBinPathWin": "C:\\dev\\esp\\.espressif\\python_env\\idf4.4_py3.8_env\\Scripts\\python.exe",
    "idf.customExtraPaths": "C:\\dev\\esp\\.espressif\\tools\\xtensa-esp32-elf\\esp-2020r3-8.4.0\\xtensa-esp32-elf\\bin;C:\\dev\\esp\\.espressif\\tools\\xtensa-esp32s2-elf\\esp-2020r3-8.4.0\\xtensa-esp32s2-elf\\bin;C:\\dev\\esp\\.espressif\\tools\\xtensa-esp32s3-elf\\esp-2020r3-8.4.0\\xtensa-esp32s3-elf\\bin;C:\\dev\\esp\\.espressif\\tools\\riscv32-esp-elf\\1.24.0.123_64eb9ff-8.4.0\\riscv32-esp-elf\\bin;C:\\dev\\esp\\.espressif\\tools\\esp32ulp-elf\\2.28.51-esp-20191205\\esp32ulp-elf-binutils\\bin;C:\\dev\\esp\\.espressif\\tools\\esp32s2ulp-elf\\2.28.51-esp-20191205\\esp32s2ulp-elf-binutils\\bin;C:\\dev\\esp\\.espressif\\tools\\cmake\\3.16.4\\bin;C:\\dev\\esp\\.espressif\\tools\\openocd-esp32\\v0.10.0-esp32-20200709\\openocd-esp32\\bin;C:\\dev\\esp\\.espressif\\tools\\ninja\\1.10.2;C:\\dev\\esp\\.espressif\\tools\\idf-exe\\1.0.1;C:\\dev\\esp\\.espressif\\tools\\ccache\\3.7;C:\\dev\\esp\\.espressif\\tools\\dfu-util\\0.9\\dfu-util-0.9-win64",
    "idf.customExtraVars": "{\"OPENOCD_SCRIPTS\":\"C:\\\\dev\\\\esp\\\\.espressif\\\\tools\\\\openocd-esp32\\\\v0.10.0-esp32-20200709/openocd-esp32/share/openocd/scripts\",\"IDF_CCACHE_ENABLE\":\"1\"}",
    "idf.portWin": "COM6",
    "idf.toolsPathWin": "C:\\dev\\esp\\.espressif",
    "idf.gitPath": "git"

**Comment by brianignacio5** [comment]
This is a local settings.json overriding the global user settings.

Configuration settings precedence are:

1. Workspace folder configuration settings in `${workspaceFolder}/.vscode/settings.json`
2. Workspace configuration settings defined in the workspace's `<name>.code-workspace` file as shown below.
3. User settings defined in
   - *Windows* `%APPDATA%\Code\User\settings.json`
   - *macOS* `$HOME/Library/Application Support/Code/User/settings.json`
   - *Linux* `$HOME/.config/Code/User/settings.json`

This extension uses the `idf.saveScope` configuration setting to determine where to save configuration settings in features such as the *Select port to use* command. Use the `ESP-IDF: Select where to save configuration settings` to change `idf.saveScope` for the current scope.
