### ISSUE TITLE
[Feature Request]:  (VSC-732)

### ISSUE THREAD

**Issue by Zaki23madrid** [espressif/vscode-esp-idf-extension#500]
I am always facing arduino library problem!
Actually, I have a smart servo motor that needs to work with it's specific arduino library! the problem is i can't add the external arduino library with esp idf firmware! the compiler always tells me that there is no such file for Arduino.h and WProgram.h headers that the arduino library uses...
it's been more than 20 days since i started working on that problem but in vain...

I would like to get a new feature that allows the use of external arduino library with esp idf firmware!

there is another alternative, they told me to add arduino as a component, but believe, it's frustrating, i can't get this work! it's very complicated and every time i try to build my project i get hundre of errors...

Thank you!

**Comment by brianignacio5** [comment]
There are several parts here.

1) This extension is not focused on Arduino support. We do however have a command called `Add Arduino ESP32 as ESP-IDF Component` to clone Arduino as ESP-IDF component  as done in the [Arduino ESP32 Repository](https://docs.espressif.com/projects/arduino-esp32/en/latest/esp-idf_component.html) documentation.

2) This doesn't guarantee that any Arduino library will work. For Arduino library support you might need to rely on the libraries in [Arduino ESP32](https://github.com/espressif/arduino-esp32) or modify it yourself. This is not the right repository for your problem and you should seek help in [Arduino ESP32](https://github.com/espressif/arduino-esp32) repository.
