### ISSUE TITLE
[Bug Report]: configure esp-idf extension install error (VSC-738)

### ISSUE THREAD

**Issue by lee-vic** [espressif/vscode-esp-idf-extension#505]
**Describe the bug**
I've tried many times, and the mistakes are the same.See error log.
**Environment (please complete the following information):**

- OS Name & Version: [windows 10]
- VSCode Version: [1.59.1]
- ESP-IDF Version: [4.3]
- Python Version: [3.8.7]

**Additional context**
![image](https://user-images.githubusercontent.com/2107826/130926402-b86c8f67-5b9c-4dc0-9f42-28cd6c91fda8.png)

[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/7052540/esp_idf_vsc_ext.log)

**Comment by brianignacio5** [comment]
Could be many reason, one I can think of is that your proxy might not be routing https request used by pip (i.e. need to set up TLS).

Closing this issue since it is solved.
