### ISSUE TITLE
[Feature Request]: Examples in sub-directories are not shown in "Example Projects" window. (VSC-746)

### ISSUE THREAD

**Issue by vadaliya** [espressif/vscode-esp-idf-extension#511]
problem :
in the show example projects window, it only shows the example which is not in the sub-directory.

for example, in the Bluetooth section, only 3 examples show. but there are actually 4 more folders that have multiple examples in sub-directory style. so that sub-folders are not shown.

**Describe the solution you'd like**
if any folder has sub-folders, then in the example window, that folder shows the sub-folder in the sub-directory style. so the developer knows that this folder has more examples in it. 

--- Bluetooth
      |
        --- bluedroid
             |
             --- ble
             --- ble_50
             --- classic_bt
             --- coex
        --- blufi
        --- esp_ble_mesh
             |
             --- 
             ---
        --- esp_hid_decice
        --- esp_hid_host
        --- hci
             |
             --- 
             ---
        --- nimble
             |
             --- 
             ---

like this.... sorry for my bad english.

**Comment by meltdown03** [comment]
Also the examples in `protocols/http_server` such as `restful_server` and `persistent_sockets` are not shown.

**Comment by brianignacio5** [comment]
It is already fixed in master. Will release a new version on marketplace soon once we fix other important issues.

![Screen Shot 2021-09-03 at 8 47 36 PM](https://user-images.githubusercontent.com/6033246/132007562-bc92df8e-6aea-4d55-919a-9be764e52abe.png)

![Screen Shot 2021-09-03 at 8 49 33 PM](https://user-images.githubusercontent.com/6033246/132007821-6710f7d8-2939-45ad-9453-cfdc84bc1230.png)

**Comment by meltdown03** [comment]
I built it from master just now in Linux and it's sill not working for me. What commit fixed it or is it not on Github yet?

**Comment by meltdown03** [comment]
It seems like the `webpack --mode development` (which the debug method uses) builds a much larger `dist/views/examples-bundle.js` file than the `--mode production`. (~733KB vs ~336KB) If I copy that larger file to the `${VSCODE_EXTENSION_DIR}/dist/views` and overwrite it, then it works outside of the VSCode Extension Development Host

**Comment by brianignacio5** [comment]
Oh very weird. I'll take a look @meltdown03 thanks for reviewing it.
