### ISSUE TITLE
CMake Error at CMakeLists.txt:7 (include):include could not find load file:    /tools/cmake/project.cmake (VSC-751)

### ISSUE THREAD

**Issue by sonictl** [espressif/vscode-esp-idf-extension#521]
CMake Error at CMakeLists.txt:7
OS: OSX
the project.cmake file do exist in that path
see the picture below:

![img](https://snipboard.io/Wi7GIs.jpg)

**Comment by brianignacio5** [comment]
Hi @sonictl this extension doesn't offer CMakeLists.txt syntax highlight support. That is another extension which we don't maintain.

The error comes from the fact that your CMake extension doesn't know about $ENV{IDF_PATH} so when the substitution happens and empty value replaces $ENV{IDF_PATH}. You need to set IDF_PATH in that extension configuration settings env variables.

**Comment by superbignut** [comment]
solved by:
    "cmake.environment": {
        "IDF_PATH" : "/home/... ... /esp/esp-idf"
    }
