### ISSUE TITLE
我的电脑有很多核心 但是编译很慢 (VSC-780)

### ISSUE THREAD

**Issue by yanwuguangjun** [espressif/vscode-esp-idf-extension#561]
**Is your feature request related to a problem? Please describe.**
my computer has alot core  when i compile allways wating alot of time
我的电脑有很多核心 但是编译很慢

**Describe the solution you'd like**
i don't know do we usede  all cput core when we  compile if not   
can we add  option to add some cpu core to improve compilation speed

不知道编译的时候有没有用多核  能不能加个 选项编译时启动多核编译

**Describe alternatives you've considered**

**Additional context**

**Comment by brianignacio5** [comment]
Basically there are settings that control how the build system works. The `idf.cmakeCompilerArgs` is used to set the array of arguments for CMake configuration step with default value `[-G", "Ninja", "-DPYTHON_DEPS_CHECKED=1", "-DESP_PLATFORM=1", ".."]` and `idf.ninjaArgs` with default value `[]`. This is equivalent to running in a terminal these commands:

```
cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 ..
ninja
```

**Comment by xiaolongba** [comment]
So as you mean, users don't need to configure them? Right? The compilation speed is the best with using the default settings, if not, how to configure it to build with all cores.

**Comment by brianignacio5** [comment]
By default `ninja` uses 2 jobs. If you want to specify more, just set `idf.ninjaArgs` to ["j", "N"] where N is the number of parallel jobs to execute. This will depends on your system specs so it might be best to leave empty as default.

**Comment by xiaolongba** [comment]
Hi @brianignacio5 bro,

thanks, `["-j","N"]` or `["j", "N"]`?  it seems that the current version cannot support this feature yet. but the master branch supported it already. right?

**Comment by xiaolongba** [comment]
@brianignacio5 I tested it with the master branch, the correct value should be` ["-j","N"]`, however, I tried to configure the value to` ["-j","8"]`, the compilation time is around 50 seconds, while the default value is around 45 seconds. as seen from the test results, this configuration is invalid for compilation time improvement. could you double-check it on your side?

**Comment by brianignacio5** [comment]
Yeah sorry that was a typo it is indeed `["-j", "N"]` for example. But this is not necessary going to improve the compilation speed, this is just for Ninja to set the number of parallels tasks of your code compilation. You need to improve the performance of your code itself with suggestions like the [Performance documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/index.html)

**Comment by xiaolongba** [comment]
> But this is not necessary going to improve the compilation speed, this is just for Ninja to set the number of parallels tasks of your code compilation.

ok, I may misunderstand, I just want to try to improve the compilation speed as my PC can support up to 12 cores, 45 or 50 seconds is too long for me. I tested and found that the command `cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1` took me around 10 seconds. based on this situation,  is it possible to improve the compilation speed?

> You need to improve the performance of your code itself with suggestions like the [Performance documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/index.html)

thanks for your reminder, but that is not what I need. as I said above, I just want to try to improve the compilation speed.



> You should also consider using [CCache](https://ccache.dev) if you are on Windows (is included in IDF Tools downloaded by setup or installer)

yes, I enabled this feature already. indeed, it is faster when build twice.

**Comment by brianignacio5** [comment]
The command `cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1` is just to create the configuration files for for selected generator, in this case `Ninja`. When you run `ninja` is where the actual compilation happens. Just because your computer has 12 cores doesn't mean that you can parallelize jobs to more than default 2 jobs (`idf.ninjaArgs`: []) or if it actually would help. The code should be designed in a way to improve compilation time itself. 

Another thing to consider is to add IDF and IDF Tools to Windows Defender exceptions for example using the [IDF-ENV's command](https://github.com/espressif/idf-env#working-with-antivirus):

`idf-env antivirus get
idf-env antivirus get --property displayName
idf-env antivirus exclusion add --path "C:\....exe"
idf-env antivirus exclusion add --tool cmake
idf-env antivirus exclusion add --all
idf-env antivirus exclusion add --all --chunk 5
idf-env antivirus exclusion remove --path "C:\....exe"
idf-env antivirus exclusion remove --tool cmake
idf-env antivirus exclusion remove --all
idf-env antivirus exclusion list
idf-env antivirus exclusion manage
`

**Comment by xiaolongba** [comment]
> The command `cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1` is just to create the configuration files for for selected generator, in this case `Ninja`. When you run `ninja` is where the actual compilation happens. Just because your computer has 12 cores doesn't mean that you can parallelize jobs to more than default 2 jobs (`idf.ninjaArgs`: []) or if it actually would help.

clear.



> The code should be designed in a way to improve compilation time itself. With default code itself I'm not sure if we can improve performance without significant change in the ESP-IDF itself (which we are working on 😄 )

good news, hope it can succeed.

> Another thing to consider is to add IDF and IDF Tools to Windows Defender exceptions for example using the [IDF-ENV's command](https://github.com/espressif/idf-env#working-with-antivirus):
> 
> ```
> idf-env antivirus get
> idf-env antivirus get --property displayName
> idf-env antivirus exclusion add --path "C:\....exe"
> idf-env antivirus exclusion add --tool cmake
> idf-env antivirus exclusion add --all
> idf-env antivirus exclusion add --all --chunk 5
> idf-env antivirus exclusion remove --path "C:\....exe"
> idf-env antivirus exclusion remove --tool cmake
> idf-env antivirus exclusion remove --all
> idf-env antivirus exclusion list
> idf-env antivirus exclusion manage
> ```

In fact, I did it already. the time is the longest only for the first build, it will be faster afterward. one more thing is :

> idf-env antivirus exclusion add --path "C:\....exe"

which path should be added? antivirus software or esp-idf?

**Comment by brianignacio5** [comment]
You could use the `idf-env antivirus exclusion add --all` to add all esp-idf and esp-idf tools for Windows Defender exclusion or set each tool path individually with `idf-env antivirus exclusion add --path "C:\path\to\tool.exe"`

**Comment by xiaolongba** [comment]
@brianignacio5 fully clear, bro. you are a good man.
