### ISSUE TITLE
[Bug Report]: got error in development (VSC-781)

### ISSUE THREAD

**Issue by Nehal197** [espressif/vscode-esp-idf-extension#563]
[hello___world___vscode___project.docx](https://github.com/espressif/vscode-esp-idf-extension/files/7415708/hello___world___vscode___project.docx
[eror.docx](https://github.com/espressif/vscode-esp-idf-extension/files/7415710/eror.docx)
)

**Comment by brianignacio5** [comment]
Closing this issue for lack of response. Please comment here if you have any more issues or share the requested information.
