### ISSUE TITLE
终端将被任务重用，按任意键关闭。[Bug Report]:  (VSC-782)

### ISSUE THREAD

**Issue by LailuoA77** [espressif/vscode-esp-idf-extension#565]
在编译的时候，遇见这个问题
`.......
[85/86] Linking C executable bootloader.elf
[86/86] Generating binary image from built executable
esptool.py v3.1-dev
Merged 1 ELF section
Generated C:/Users/Administrator/Desktop/hello_world/build/bootloader/bootloader.bin
[663/966] Generating x509_crt_bundle
FAILED: esp-idf/mbedtls/x509_crt_bundle
cmd.exe /C "cd /D C:\Users\Administrator\Desktop\hello_world\build\esp-idf\mbedtls && C:\Users\Administrator\.espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe C:/Users/Administrator/esp/esp-idf/components/mbedtls/esp_crt_bundle/gen_crt_bundle.py --input C:/Users/Administrator/esp/esp-idf/components/mbedtls/esp_crt_bundle/cacrt_all.pem -q"
gen_crt_bundle.py: Invalid certificate in C:/Users/Administrator/esp/esp-idf/components/mbedtls/esp_crt_bundle/cacrt_all.pem
Invalid certificate
ninja: build stopped: subcommand failed.
终端进程“C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command cmake --build .”已终止，退出代码: 1。

终端将被任务重用，按任意键关闭。`

然后修改了task.json中的presentation的内容，还是这样的，
有解决办法没有 ？

**Comment by brianignacio5** [comment]
This is already posted in esp-idf [here](https://github.com/espressif/esp-idf/issues/7660)
