### ISSUE TITLE
[Feature Request]: Serial Port Access in WSL (VSC-785)

### ISSUE THREAD

**Issue by zebulon501** [espressif/vscode-esp-idf-extension#571]
## Problem

#224 allows using native serial port when running in WSL. I understand this changes ease the access to some people, but it has a few limitations IMHO:

* Native Windows processes are launched without any warning;
* Python must be installed on Windows, along with pySerial (missing dependency by the way);
* Specifying an RFC2217 serial port doesn't prevent using this mechanism;
* WSL2 will soon offer USBIP (see https://devblogs.microsoft.com/commandline/connecting-usb-devices-to-wsl/), thus bringing native WSL USB ports, like /dev/ttyUSB0, which is unusable due to this mechanism;
* Using devcontainer is also broken: this configuration is detected as WSL but has no access to Windows binaries.

## Expected Solution

This behavior (using powershell.exe and path substitution) shall only be used when the user specifies idf.port as COMx and running under Linux. Detecting WSL using the kernel information is not working (docker use case), better use the environment variable WSL_DISTRO_NAME.

**Comment by brianignacio5** [comment]
Hi @zebulon501 thanks for your review. Indeed this approach was always means as a temporal solution for WSL 2 users.

Within the container itself is hard to know if you are using WSL or not. I'll take a look at WSL_DISTRO_NAME to see if it works better for identify a WSL and remove this completely when WSL 2 releases serial support.
