### ISSUE TITLE
Menuconfig dont open (VSC-789)

### ISSUE THREAD

**Issue by baldhead69** [espressif/vscode-esp-idf-extension#574]
Hi,

I am trying to open menuconfig but it dont open
![Sem título](https://user-images.githubusercontent.com/17574492/142073482-7a389f74-acb7-4ece-b710-ecfcf37ba233.png)
.

**Comment by baldhead69** [comment]
@brianignacio5 ,

Some suggestion ?

What other way to open the menuconfig only with the visual studio code extension ?

In cmd i can't open menuconfig too.

**Comment by brianignacio5** [comment]
Hi @baldhead69 Could you please share the required troubleshoot information as specified [here](https://github.com/espressif/vscode-esp-idf-extension#troubleshooting)

Have you configured the extension as explained [here](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/install.md) ?

**Comment by baldhead69** [comment]
[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/7556476/esp_idf_vsc_ext.log)

**Comment by baldhead69** [comment]
![Sem título](https://user-images.githubusercontent.com/17574492/142246359-6d52c989-9e53-4a67-8e76-86b041f53bd8.png)
[vscode-app-1637168186362.log](https://github.com/espressif/vscode-esp-idf-extension/files/7556508/vscode-app-1637168186362.log)
![Sem título1](https://user-images.githubusercontent.com/17574492/142246394-820a92b4-b709-4e5d-abed-e184b624f111.png)

**Comment by baldhead69** [comment]
I am using my old project setup in vsc.

There is some project example ?

**Comment by baldhead69** [comment]
".vscode" folder inside project

[.vscode.zip](https://github.com/espressif/vscode-esp-idf-extension/files/7556628/default.vscode.zip)

**Comment by baldhead69** [comment]
The first time i tried to open menuconfig after installing the expressif extension, menuconfig open normally.

Now, the menuconfig dont open more.

**Comment by baldhead69** [comment]
Building an flashing are ok.

**Comment by baldhead69** [comment]
Now the menuconfig apparently opened.

I removed the dot from the name of a folder from my components.

The strange thing is that even with the dotted folder the project was compiling.

But full clean still does not work:
![full-clean_busy](https://user-images.githubusercontent.com/17574492/142254378-7f4650a8-78f8-4ac8-aab5-c8c24ce315da.png)

**Comment by baldhead69** [comment]
if i open visual studio code as an admin, the first time the full clean work, but if i build again and try to full clean again, the full clean work. 

if i open visual studio code as an admin, the first time the full clean work, but if i build again, open menuconfig, close menuconfig, and try to full clean again, the full clean dont work( EBUSY message again ).

**Comment by brianignacio5** [comment]
The issue with the `SDK Configuration editor` is a build issue you are having with the `__component_get_requirements`. Here is the error:

```
CMake Error at C:/esp-idf/tools/cmake/component.cmake:238 (message):
Call Stack (most recent call first):
  C:/esp-idf/tools/cmake/build.cmake:491 (__component_get_requirements)
  C:/esp-idf/tools/cmake/project.cmake:378 (idf_build_process)
  CMakeLists.txt:15 (project)

,stack:Error: CMake Error at C:/esp-idf/tools/cmake/component.cmake:238 (message):
Call Stack (most recent call first):
  C:/esp-idf/tools/cmake/build.cmake:491 (__component_get_requirements)
  C:/esp-idf/tools/cmake/project.cmake:378 (idf_build_process)
  CMakeLists.txt:15 (project)


        at m.printError (c:sers�3893983\.vscodetensionspressif.esp-idf-extension-1.2.0\disttension.js:1:28725)
        at Socket.<anonymous> (c:sers�3893983\.vscodetensionspressif.esp-idf-extension-1.2.0\disttension.js:1:28154)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Sometime the `ESP-IDF Full Clean` can't fully delete the build folder because another process is using some file with it. Maybe try to run `Dispose current SDK Configuration Editor server process` and try `ESP-IDF Full Clean` again. If that doesn't work try to delete the folder yourself from the file explorer.
