### ISSUE TITLE
I have ever install IDF with shell in ubuntu, but the vscode extension not identify it (VSC-794)

### ISSUE THREAD

**Issue by Yecgaa1** [espressif/vscode-esp-idf-extension#580]
![image](https://user-images.githubusercontent.com/38446391/143023570-bc078d07-a4cd-477d-ba9b-b82ed3fa3eb2.png)
I have ever set  IDF_PATH=$HOME/esp/esp-idf
And I have ever try to set this
![image](https://user-images.githubusercontent.com/38446391/143023753-6b621a16-f7d3-46fa-bf9b-5ba166e927b1.png)
![image](https://user-images.githubusercontent.com/38446391/143023773-75aca7f5-82ae-4ef9-ab96-153845fe6a44.png)
I can build but not flash with this extension. If with shell and export.sh, I can do it
I know the reason is that I dont set the path with export.sh
But how I can solve this problem with this extension automatically

**Comment by Yecgaa1** [comment]
I know this topic so I have set IDF_PATH=$HOME/esp/esp-idf
![image](https://user-images.githubusercontent.com/38446391/143024442-000f563e-d201-4453-ad3d-423e8bcb8c1c.png)

**Comment by brianignacio5** [comment]
HI @Yecgaa1 the documentation you cited is the part of the extension setup wizard, where we try to detect an existing setup in $HOME/esp/esp-idf and if found the setup wizard will show the `Use existing setup` option. The setup wizard appears when you click on menu View -> Command Palette -> search `ESP-IDF: Configure ESP-IDF extension`.

In the [settings documentation](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/SETTINGS.md#use-of-environment-variables-in-esp-idf-settingsjson-and-tasksjson) we specify that we don't recognize in $HOME in the extension configuration settings. Just replace it with `${env:HOME}/esp/esp-idf`. 

If you are also manually configuring the extension, please review the [Setup documentation for json manual configuration](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/SETUP.md#json-manual-configuration) or I'll recommend using the setup wizard for UI configuration by clicking menu View -> Command Palette -> search `ESP-IDF: Configure ESP-IDF extension`

**Comment by Yecgaa1** [comment]
Yes，you are right, thanks. And I want to remind others that remember to set the "Python Bin Path" and "Tools Path"
