### ISSUE TITLE
[Bug Report]: ESP-ADF fails to install because of Git (VSC-798)

### ISSUE THREAD

**Issue by simon4web** [espressif/vscode-esp-idf-extension#588]
**Pre Bug Report Checklist**
Before reporting any bug please make sure of these points.

- [x ] Make sure you have searched for existing bugs and features request before you post an issue.
- [ x] This is a bug report for the ESP-IDF Visual Studio Code extension and **not** an ESP-IDF bug report.
- [ x] I've read the docs and found no information that could have helped solving the issue.

**Describe the bug**
When triing to install ESP-ADF, the message "Git is not found in idf.gitPath or PATH" is shown

**To Reproduce**
install ESP-ADF with the command in VS code
Win 10, VS code 1.62.3., IDF Plugin 1.2.0

**Expected behavior**
ESP-ADF should install

**Screenshots**
-

**Environment (please complete the following information):**

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.19042 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\doxygen\bin;C:\Program Files (x86)\Atmel\Studio\7.0;C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\;C:\Program Files (x86)\vera++\bin;C:\Program Files\Microchip\xc32\v2.50\bin;C:\Program Files (x86)\Altium Designer S09 Viewer\System;C:\Program Files\Microsoft VS Code\bin;C:\Users\Simon Weber\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.4\bin;C:\Users\Simon Weber\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\PyCharm 2020.2.4\bin;C:\Users\Simon Weber\AppData\Local\gitkraken\bin;C:\Users\Simon Weber\AppData\Local\Microsoft\WindowsApps;C:\Program Files\CMake\bin;C:\Program Files\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\Simon Weber\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.4\bin;C:\Users\Simon Weber\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\PyCharm 2020.2.4\bin;C:\Users\Simon Weber\AppData\Local\gitkraken\bin;C:\Users\Simon Weber\AppData\Local\Microsoft\WindowsApps;C:\Users\Simon Weber\.dotnet\tools 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.62.3 
Visual Studio Code language en 
Visual Studio Code shell C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.2.0 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) c:\dev\ESP32\esp-adf
ESP-IDF Path (idf.espIdfPath) c:\dev\ESP32\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
Custom extra paths (idf.customExtraPaths) c:\dev\ESP32\tools\xtensa-esp32-elf\esp-2021r2-8.4.0\xtensa-esp32-elf\bin;c:\dev\ESP32\tools\xtensa-esp32s2-elf\esp-2021r2-8.4.0\xtensa-esp32s2-elf\bin;c:\dev\ESP32\tools\xtensa-esp32s3-elf\esp-2021r2-8.4.0\xtensa-esp32s3-elf\bin;c:\dev\ESP32\tools\riscv32-esp-elf\esp-2021r2-8.4.0\riscv32-esp-elf\bin;c:\dev\ESP32\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;c:\dev\ESP32\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;c:\dev\ESP32\tools\cmake\3.20.3\bin;c:\dev\ESP32\tools\openocd-esp32\v0.10.0-esp32-20211111\openocd-esp32\bin;c:\dev\ESP32\tools\ninja\1.10.2;c:\dev\ESP32\tools\idf-exe\1.0.2;c:\dev\ESP32\tools\ccache\4.3\ccache-4.3-windows-64;c:\dev\ESP32\tools\dfu-util\0.9\dfu-util-0.9-win64
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"c:\\dev\\ESP32\\tools\\openocd-esp32\\v0.10.0-esp32-20211111/openocd-esp32/share/openocd/scripts","IDF_CCACHE_ENABLE":"1"}
Virtual env Python Path (idf.pythonBinPath) c:\dev\ESP32\python_env\idf4.4_py3.8_env\Scripts\python.exe
Serial port (idf.port) COM13
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,target/esp32.cfg
ESP-IDF Tools Path (idf.toolsPath) c:\dev\ESP32
Git Path (idf.gitPath) git
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) true
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-IDF Custom extra paths
Access to c:\dev\ESP32\tools\xtensa-esp32-elf\esp-2021r2-8.4.0\xtensa-esp32-elf\bin: true
Access to c:\dev\ESP32\tools\xtensa-esp32s2-elf\esp-2021r2-8.4.0\xtensa-esp32s2-elf\bin: true
Access to c:\dev\ESP32\tools\xtensa-esp32s3-elf\esp-2021r2-8.4.0\xtensa-esp32s3-elf\bin: true
Access to c:\dev\ESP32\tools\riscv32-esp-elf\esp-2021r2-8.4.0\riscv32-esp-elf\bin: true
Access to c:\dev\ESP32\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin: true
Access to c:\dev\ESP32\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin: true
Access to c:\dev\ESP32\tools\cmake\3.20.3\bin: true
Access to c:\dev\ESP32\tools\openocd-esp32\v0.10.0-esp32-20211111\openocd-esp32\bin: true
Access to c:\dev\ESP32\tools\ninja\1.10.2: true
Access to c:\dev\ESP32\tools\idf-exe\1.0.2: true
Access to c:\dev\ESP32\tools\ccache\4.3\ccache-4.3-windows-64: true
Access to c:\dev\ESP32\tools\dfu-util\0.9\dfu-util-0.9-win64: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.24.0.windows.2
ESP-IDF version 4.4
Python version 3.8.7
Python's pip version 21.3.1
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 3.1.9
Brotli version: 1.0.9
certifi version: 2021.10.8
cffi version: 1.15.0
charset-normalizer version: 2.0.9
click version: 8.0.3
colorama version: 0.4.4
construct version: 2.10.54
contextlib2 version: 21.6.0
cryptography version: 36.0.0
ecdsa version: 0.17.0
esp-windows-curses version: 0.1
Flask version: 0.12.5
Flask-Compress version: 1.10.1
Flask-SocketIO version: 2.9.6
future version: 0.18.2
gcovr version: 5.0
gdbgui version: 0.13.2.0
gevent version: 1.5.0
greenlet version: 1.1.2
idf-component-manager version: 0.3.2b0
idna version: 3.3
itsdangerous version: 2.0.1
Jinja2 version: 3.0.3
kconfiglib version: 13.7.1
lxml version: 4.6.4
MarkupSafe version: 2.0.1
pip version: 21.3.1
psutil version: 5.8.0
pycparser version: 2.21
pyelftools version: 0.27
pygdbmi version: 0.9.0.2
Pygments version: 2.10.0
pyparsing version: 2.3.1
pyserial version: 3.5
python-engineio version: 3.14.2
python-socketio version: 4.6.1
pywin32 version: 302
PyYAML version: 6.0
reedsolo version: 1.5.4
requests version: 2.26.0
requests-toolbelt version: 0.9.1
schema version: 0.7.5
semantic-version version: 2.8.5
setuptools version: 59.5.0
six version: 1.16.0
tqdm version: 4.62.3
urllib3 version: 1.26.7
websocket-client version: 1.2.2
Werkzeug version: 0.16.1
wheel version: 0.37.0
windows-curses version: 2.3.0
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements from c:\dev\ESP32\esp-idf\requirements.txt are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements from c:\Users\Simon Weber\.vscode\extensions\espressif.esp-idf-extension-1.2.0\requirements.txt are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements from c:\Users\Simon Weber\.vscode\extensions\espressif.esp-idf-extension-1.2.0\esp_debug_adapter\requirements.txt are satisfied.
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at ENOENT: no such file or directory, open 'c:\dev\ESP32\workspace\dali-wlan\.vscode\launch.json'
--------------------------------------------------------------------------------------------------------------------------------------------

Click the menu `View` and select `Output`. This extension uses several output channels: ESP-IDF, ESP-IDF Debug Adapter, Heap Trace, OpenOCD and SDK Configuration Editor.

Please share the output of the channel related to your issue. For example ESP-IDF is used mostly for the extension setup process.

**Logs**
If applicable, please share the log file which can be obtained from

- Windows: `%USERPROFILE%\.vscode\extensions\espressif.esp-idf-extension-VERSION\esp_idf_vsc_ext.log`
- Linux & MacOSX: `$HOME/.vscode/extensions/espressif.esp-idf-extension-VERSION/esp_idf_vsc_ext.log`

**Extension Configuration settings**
Open Command Palette (F1 or View Menu -> Command Palette) and type `Preferences: Open Settings (JSON)` or use `{CURRENT_PROJECT}/.vscode/settings.json` to get the following extension configuration settings value:

- `idf.espIdfPath` (MacOS or Linux) or `idf.espIdfPathWin` (Windows) also called `Path to locate ESP-IDF framework (IDF_PATH)` in `Preferences: Open Settings (UI)`.
- `idf.pythonBinPath` (MacOS or Linux) or `idf.pythonBinPathWin` (Windows) also called `Python absolute binary path used to execute ESP-IDF Python Scripts` in `Preferences: Open Settings (UI)`.
- `idf.openOcdConfigs` also called `List of configuration files inside OpenOCD Scripts directory` in `Preferences: Open Settings (UI)`.
- `idf.customExtraPaths` also called `Paths to be appended to PATH` in `Preferences: Open Settings (UI)`.
- `idf.customExtraVars` also called `Variables to be added to system environment variables` in `Preferences: Open Settings (UI)`.
- `idf.adapterTargetName` also called `Target name for ESP-IDF Debug Adapter` in `Preferences: Open Settings (UI)`.
- `idf.customAdapterTargetName` is used when `idf.adapterTargetName` is set to `custom`.

**Additional context**
I did a little digging: it seems like the checkGitExists() in "utils.ts" is failing, although git is installed correctly and the path is also valid. I manipulated the function to always return a version string other than "not found" and the installing process worked. 
My best guess is that if the path is just "git" the function pathExists() fails, and if the path is the full path like "C:\Path\to\git.exe" execution of the version check fails, because powershell for any reason doesn't allow/understand such calls?!???

**Comment by brianignacio5** [comment]
Hmm interesting, on extension setup the value of `idf.gitPath` should be updated to the embed git executable in the `c:\dev\ESP32\tools`. I'll take a look. How did you install ESP-IDF and ESP-IDF tools ? Our windows installer ?

Have you try updating `idf.gitPath` in your settings.json to the path of `git.exe` in `c:\dev\ESP32\tools`
