### ISSUE TITLE
[Bug Report]: NVS partition editor empty (VSC-803)

### ISSUE THREAD

**Issue by guivo** [espressif/vscode-esp-idf-extension#593]
**Pre Bug Report Checklist**
Before reporting any bug please make sure of these points.

- [X] Make sure you have searched for existing bugs and features request before you post an issue.
- [X] This is a bug report for the ESP-IDF Visual Studio Code extension and **not** an ESP-IDF bug report.
- [X] I've read the docs and found no information that could have helped solving the issue.

**Describe the bug**
I have a nvs.csv file in the root directory of my project. Right clicking on the file and selecting on the editor field 

**To Reproduce**
Try to open the editor.

**Expected behavior**
I would have expected the field

**Screenshots**
![image](https://user-images.githubusercontent.com/33522004/146142275-40a14184-1ead-477b-a379-84744f0b6e09.png)

**Environment (please complete the following information):**

- OS Name & Version: Windows 10
- VSCode Version: 1.63.1
- ESP-IDF Version: 4.3.1
- Python Version: 3.8.7

**Comment by brianignacio5** [comment]
As specified in [NVS Partition editor doc](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/NVS_PARTITION_EDITOR.md) first 2 lines should contain:

```csv
key,type,encoding,value     <-- column header (must be the first line)
namespace_name,namespace,,  <-- First entry must be of type "namespace"
```

**Comment by guivo** [comment]
The file should satisfy the the constraints:

```
key,type,encoding,value
configuration,namespace,,
board,data,string,ledstrip
version,data,u32,1
cert,file,string,rsa_cert.pem
key,file,string,rsa_private.pem
server,file,string,google_roots.pem
```

It is actually properly seen by another PC, same VS code version, from which I got the code from git.

**Comment by brianignacio5** [comment]
It might be fixed by #545 in master which adds some testing to this feature. This is not yet publish to marketplace but will be released soon.

**Comment by guivo** [comment]
As additional comment, if a start adding keys and values the file become usable in the interface.

However, I still cannot generate the binary file.

To stress the scenario, in case it may help, I have 2 computer:
1. Originally created the nvs.csv file, I can update the generate, the binary and flash the partition
2. Checks out the file from git, it cannot edit the file or create the binary

**Comment by brianignacio5** [comment]
Can you try with this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/127236607.zip) and see if it works ?

So the idea is that if you are getting the csv file from git is not working ? Maybe there is some OS specific characters in the csv ?

**Comment by guivo** [comment]
You right!

I forced the end line to LF and the NSV partition UI and ability to generate the NSV binary were restored.

**Comment by mbastida123** [comment]
Hi, I'm facing the same issue. The moment I change branches or anything related to git the NVS partition editor shows a blank configuration.

I see the issue is closed but it isn't clear to me if the issue was fixed.

**Comment by mbastida123** [comment]
> Can you try with this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/127236607.zip) and see if it works ?
> 
> So the idea is that if you are getting the csv file from git is not working ? Maybe there is some OS specific characters in the csv ?

It is exactly that:
![image](https://user-images.githubusercontent.com/78351485/216322218-8ab68b69-0b39-4c4d-af4d-bef32c79e0e9.png)

Using notepad I change to the unix format:
![image](https://user-images.githubusercontent.com/78351485/216322313-04b9450e-7e96-4f0e-a3f0-0dc126db4bd4.png)

And now it works. Will you be able to fix this?

**Comment by brianignacio5** [comment]
@mbastida123 Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/656267342.zip) ?
