### ISSUE TITLE
[Bug Report]: Extension should support spaces in Git path (VSC-805)

### ISSUE THREAD

**Issue by obones** [espressif/vscode-esp-idf-extension#596]
**Describe the bug**
I'm using this extension under Windows and have configured the `Idf: Git Path` option to the location where my GIT command is located, which is the rather standard `C:\Program Files\Git\cmd\git.exe`
Every time I open an ESP-IDF project, I get an error message popping up saying it cannot find the Git command.

Thanks to #506 and #522, I went and looked at the log file and found this:

    {"user":true,"message":"Git is not found in current environment","stack":"Error: Command failed: C:\\Program Files\\Git\\cmd\\git.exe --version\n'C:\\Program' n'est pas reconnu en tant que commande interne\r\nou externe, un programme ex�cutable ou un fichier de commandes.\r\n\n\tat ChildProcess.exithandler (child_process.js:317:12)\n\tat ChildProcess.emit (events.js:315:20)\n\tat ChildProcess.EventEmitter.emit (domain.js:467:12)\n\tat maybeClose (internal/child_process.js:1048:16)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)","level":"error","timestamp":"2021-12-20T10:31:55.586Z"}

The error message is in French but it says that 'C:\\Program' is not recognized as a valid command. 
This is the message one is used to get when double quotes were forgotten around a path with spaces.

**To Reproduce**
Use a path with spaces for the `Idf: Git Path` option

**Expected behavior**
The extensions should support spaces in paths, especially considering that external tools are usually installed in the `C:\Program Files` folder

**Screenshots**
![image](https://user-images.githubusercontent.com/1314739/146755944-3dd1ad0f-0162-4122-82d5-85abf7e81c9f.png)

**Environment :**

- OS Name & Version: Windows 10x64 20H2
- VSCode Version: 1.63.2
- ESP-IDF Version: 4.4
- Python Version: 3.8

**Comment by brianignacio5** [comment]
This should be fixed #533 but has not been released yet to marketplace. Will release next version soon!
