### ISSUE TITLE
[Bug Report]: When setting a target, the compiler path in the JSON file cannot be changed (VSC-816)

### ISSUE THREAD

**Issue by HaydenHu** [espressif/vscode-esp-idf-extension#608]
win10
vscode-esp-idf-extension-1.3.0
![image](https://user-images.githubusercontent.com/30103277/149502638-a788fe2f-d43e-47d5-8352-519c442d2059.png)

**Comment by brianignacio5** [comment]
Hi @HaydenHu means you want the extension to update the compilerPath in the c_cpp_properties.json whenever you change the IDF_TARGET ?

**Comment by HaydenHu** [comment]
> 嗨@HaydenHu意味着您希望扩展程序在您更改 IDF_TARGET 时更新 c_cpp_properties.json 中的 compilerPath ？

yes

**Comment by brianignacio5** [comment]
Can you please try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/148991859.zip) ?
