### ISSUE TITLE
[Feature Request]: (more an user advice)! don't try to use the same environment for CLI and VS (VSC-817)

### ISSUE THREAD

**Issue by philippe44** [espressif/vscode-esp-idf-extension#610]
If I may, a small piece of advice: at least on Windows, tell users to NOT try to use the same environment between VS and CLI. Tell them to have FULLY separated systems. I've tried and it s...d up my whole CLI, could not build anything

**Comment by brianignacio5** [comment]
Why you can't use the same environment between Vscode and CLI ?

Actually, if your environment variables are set (IDF_PATH, IDF_TARGET, OPENOCD_SCRIPTS) and the required IDF Tools are in PATH (git, xtensa-esp32-elf, opened-esp32, etc.) you should be able to use the extension without even using the extension setup.

Could you provide more information about what is happening in your setup ? Like the build output, extension log, etc. as defined in the [troubleshooting section](https://github.com/espressif/vscode-esp-idf-extension#troubleshooting)

**Comment by philippe44** [comment]
I will try but I already did reinstall everything separately because I really had to have it working back quickly. Typically, my CLI build system (just installed using the install.bat) stopped working after I ran the .visx installer and told it I wanted to use an existing toolset (4.3.2) whose location I gave. The idf.py build/menuconfig would fail to just run because of an issue with (missing) windows-curses and the advice to use pip to install it was a no-go.

**Comment by brianignacio5** [comment]
how did you try to use idf.py build/menuconfig ? Did you just open a terminal on vscode or did you use the `ESP-IDF: Open ESP-IDF Terminal` command ? The 2nd option is the one that is going to use the extension settings to override a terminal with environment variables IDF_PATH, etc.

**Comment by philippe44** [comment]
I use a cmd box (as usual) that launches the idf_cmd_init.bat (truly the export.bat) to set ENV variables and work form there

**Comment by brianignacio5** [comment]
So you are not using the extension settings in this cmd box. The extension does install other python packages to the python virtual environment so I'll add a comment in the docs.

**Comment by philippe44** [comment]
Thanks for the explanations
