### ISSUE TITLE
[Bug Report]: The IDF downloaded with the extension is "dirty". (VSC-821)

### ISSUE THREAD

**Issue by JosuGZ** [espressif/vscode-esp-idf-extension#614]
**Describe the bug**

The IDF downloaded with the extension is "dirty".

This is what `esp_get_idf_version()` returns:
- `v4.4-rc1-dirty` on the `v4.4-rc1` version
- `v4.3.1-dirty` on the `v4.3.1`version

To reproduce, all I have to do is download a new IDF version and run `git describe --dirty` or `git status` to see that the downloaded IDF version is not in a clean state.

**Expected behavior**

The downloaded IDF should be in a clean state.

**Environment**

- OS Name & Version: Windows 10
- VSCode Version: 1.63.2
- ESP-IDF Version: multiple
- ESP-IDF Extension version: 1.3.0

**Comment by brianignacio5** [comment]
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/152144402.zip) ? and see if it fixes the issue ?
