### ISSUE TITLE
[Bug Report]: issue to build with managed component (VSC-823)

### ISSUE THREAD

**Issue by chegewara** [espressif/vscode-esp-idf-extension#616]
Im not sure if it is a bug, because i am not working on windows and i am not using VS code extension, but my client got problem to build app when managed component is used:
https://components.espressif.com/component/espressif/button

The component seems to be not installed/downloaded.

Thanks

**Comment by brianignacio5** [comment]
Is the component manager enabled in the extension ? Using the `idf.enableIdfComponentManager` configuration setting.

**Comment by chegewara** [comment]
Probably not. Thanks for info about that option, as i simply assumed it should just work out of the box.
