### ISSUE TITLE
No README.md files showing for the examples (VSC-827)

### ISSUE THREAD

**Issue by meltdown03** [espressif/vscode-esp-idf-extension#624]
IDF - Master branch
OS - Archlinux
Extension - 1.3.0

When I open the Project Examples, no Readme files are displayed for any examples. I get a notification that `No README.md available for this project`. I verified the files are there.

I did some debugging with VS Code Extension Host and found this Exception when I click a Example.
It occurs at Line 998 of `utils.ts` (`marked.SetOptions`)

``` typescript
Exception has occurred: TypeError: Cannot read property 'setOptions' of undefined
t Module.markdownToWebviewHtml (/home/neal/git/vscode-esp-idf-extension/dist/extension.js:84191:52)
	at ExamplesPlanel.<anonymous> (/home/neal/git/vscode-esp-idf-extension/dist/extension.js:73174:108)
	at Generator.next (<anonymous>)
	at fulfilled (/home/neal/git/vscode-esp-idf-extension/dist/extension.js:73098:58)
```

I see the the contents of the readme in `markdownToWebviewHtml.content` as seen here: 
![Screenshot from 2022-01-28 20-25-49](https://user-images.githubusercontent.com/6166536/151643736-e47ac047-322d-435e-801e-0dfafdcbb30a.png)

**Comment by brianignacio5** [comment]
Thanks for reporting this @meltdown03 will take a look

**Comment by brianignacio5** [comment]
Could you please try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/159034891.zip)

**Comment by meltdown03** [comment]
It works good now. All the readme files show nicely.
