### ISSUE TITLE
[Bug Report]: Extension incorrectly keeps setting IDF_TARGET to "esp32" despite choosing "esp32s2" (VSC-829)

### ISSUE THREAD

**Issue by moefear85** [espressif/vscode-esp-idf-extension#627]
**Describe the bug**
Whenever I have a pre-existing project, that I would like to compile for a different chip, then even after full clean, even after deleting all sdkconfig files, build folder, and .vscode folder, then if I select menuconfig or hit build directly, I get the following error:

> Project sdkconfig was generated for target 'esp32s2', but environment variable IDF_TARGET is set to 'esp32'

**To Reproduce**
Steps to reproduce the behavior (including the full log).

**Expected behavior**
I expect the extension to do all encessary preparations and set environment variables properly so that a rebuild completes successfully for the new target chip.

**Environment (please complete the following information):**

- OS Name & Version: Ubuntu 21.10 (latest updates)
- VSCode Version: 1.63
- ESP-IDF Version: v4.4
- Python Version: 3.9.7

> ---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS linux x64 5.13.0-27-generic 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 /home/moefear85/.local/bin:/home/moefear85/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/moefear85/Scripts:/home/moefear85/Software/.espressif/tools/xtensa-lx106-elf/bin:/home/moefear85/Scripts:/home/moefear85/Software/.espressif/tools/xtensa-lx106-elf/bin 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.63.2 
Visual Studio Code language en 
Visual Studio Code shell bash 
ESP-IDF Extension version 1.3.0 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) /home/moefear85/Source/esp-adf
ESP-IDF Path (idf.espIdfPath) /home/moefear85/Source/esp-idf-v4.4
ESP-MDF Path (idf.espMdfPath) /home/moefear85/Source/esp-mdf
Custom extra paths (idf.customExtraPaths) /home/moefear85/Software/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin:/home/moefear85/Software/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-8.4.0/xtensa-esp32s2-elf/bin:/home/moefear85/Software/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin:/home/moefear85/Software/.espressif/tools/riscv32-esp-elf/esp-2021r2-8.4.0/riscv32-esp-elf/bin:/home/moefear85/Software/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:/home/moefear85/Software/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/home/moefear85/Software/.espressif/tools/cmake/3.20.3/bin:/home/moefear85/Software/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/bin:/home/moefear85/Software/.espressif/tools/ninja/1.10.2
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"/home/moefear85/Software/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts"}
Virtual env Python Path (idf.pythonBinPath) /home/moefear85/Software/.espressif/python_env/idf4.4_py3.9_env/bin/python
Serial port (idf.port) /dev/ttyUSB1
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,board/esp32-wrover.cfg
ESP-IDF Tools Path (idf.toolsPath) /home/moefear85/Software/.espressif
Git Path (idf.gitPath) /usr/bin/git
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) true
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) true
Access to ESP-IDF Custom extra paths
Access to /home/moefear85/Software/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin: true
Access to /home/moefear85/Software/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-8.4.0/xtensa-esp32s2-elf/bin: true
Access to /home/moefear85/Software/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin: true
Access to /home/moefear85/Software/.espressif/tools/riscv32-esp-elf/esp-2021r2-8.4.0/riscv32-esp-elf/bin: true
Access to /home/moefear85/Software/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin: true
Access to /home/moefear85/Software/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin: true
Access to /home/moefear85/Software/.espressif/tools/cmake/3.20.3/bin: false
Access to /home/moefear85/Software/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/bin: true
Access to /home/moefear85/Software/.espressif/tools/ninja/1.10.2: false
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH true
Access to Ninja in environment PATH true
Access to ESP-IDF Tools Path (idf.toolsPath) true
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.32.0
ESP-IDF version 4.4
Python version 3.9.7
Python's pip version 21.3.1
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 3.1.9
Brotli version: 1.0.9
certifi version: 2021.10.8
cffi version: 1.15.0
charset-normalizer version: 2.0.11
click version: 8.0.3
construct version: 2.10.54
contextlib2 version: 21.6.0
cryptography version: 36.0.1
ecdsa version: 0.17.0
Flask version: 0.12.5
Flask-Compress version: 1.10.1
Flask-SocketIO version: 2.9.6
future version: 0.18.2
gcovr version: 5.0
gdbgui version: 0.13.2.0
gevent version: 1.5.0
greenlet version: 1.1.2
idf-component-manager version: 1.0.1
idna version: 3.3
itsdangerous version: 2.0.1
Jinja2 version: 3.0.3
kconfiglib version: 13.7.1
lxml version: 4.7.1
MarkupSafe version: 2.0.1
pip version: 21.3.1
psutil version: 5.9.0
pycparser version: 2.21
pyelftools version: 0.27
pygdbmi version: 0.9.0.2
Pygments version: 2.11.2
pyparsing version: 2.3.1
pyserial version: 3.5
python-engineio version: 3.14.2
python-socketio version: 4.6.1
PyYAML version: 6.0
reedsolo version: 1.5.4
requests version: 2.27.1
requests-toolbelt version: 0.9.1
schema version: 0.7.5
semantic-version version: 2.8.5
setuptools version: 60.6.0
six version: 1.16.0
tqdm version: 4.62.3
urllib3 version: 1.26.8
websocket-client version: 1.2.3
Werkzeug version: 0.16.1
wheel version: 0.37.0
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements from /home/moefear85/Source/esp-idf-v4.4/requirements.txt are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements from /home/moefear85/.vscode/extensions/espressif.esp-idf-extension-1.3.0/requirements.txt are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements from /home/moefear85/.vscode/extensions/espressif.esp-idf-extension-1.3.0/esp_debug_adapter/requirements.txt are satisfied.
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at ENOENT: no such file or directory, open '/media/moefear85/BACKUP/Projects/Programming/ESP32/mesh_standard/.vscode/launch.json'
--------------------------------------------------------------------------------------------------------------------------------------------

**Extension Configuration settings**
{
    "C_Cpp.intelliSenseEngine": "Tag Parser",
    "idf.adapterTargetName": "esp32s2",
    "idf.customExtraPaths": "/home/moefear85/Software/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin:/home/moefear85/Software/.espressif/tools/xtensa-esp32s2-elf/esp-2021r2-8.4.0/xtensa-esp32s2-elf/bin:/home/moefear85/Software/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin:/home/moefear85/Software/.espressif/tools/riscv32-esp-elf/esp-2021r2-8.4.0/riscv32-esp-elf/bin:/home/moefear85/Software/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:/home/moefear85/Software/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/home/moefear85/Software/.espressif/tools/cmake/3.20.3/bin:/home/moefear85/Software/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/bin:/home/moefear85/Software/.espressif/tools/ninja/1.10.2",
    "idf.customExtraVars": "{\"OPENOCD_SCRIPTS\":\"/home/moefear85/Software/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts\"}",
    "idf.espIdfPath": "/home/moefear85/Source/esp-idf-v4.4",
    "idf.espAdfPath": "/home/moefear85/Source/esp-adf",
    "idf.espMdfPath": "/home/moefear85/Source/esp-mdf",
    "idf.openOcdConfigs": [
        "interface/ftdi/esp32_devkitj_v1.cfg",
        "target/esp32s2.cfg"
    ],
    "idf.port": "/dev/ttyUSB1",
    "idf.pythonBinPath": "/home/moefear85/Software/.espressif/python_env/idf4.4_py3.9_env/bin/python",
    "idf.toolsPath": "/home/moefear85/Software/.espressif"
}

**Additional context**
[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/7973428/esp_idf_vsc_ext.log)

I've narrowed down the source of the problem. It depends purely on whether I'm using a saved vs unsaved workspace. If i close the currently open workspace, then I can compile without problems, change the chip type as often as I want without problems, and rerun menuconfig whenever I want without problems. But, the moment I save that very same unproblematic "default"/unsaved workspace, then afterwards I am no longer able to set the chip to anything besides esp32, otherwise it won't compile, nor will menuconfig successfully open. Once I close the workspace again, it works again, even without restarting visual studio (although that doesn't have any effect in itself). This is a recent problem that didn't exist just a few weeks ago.

**Comment by moefear85** [comment]
ok I've solved the problem, but I still consider it a "bug", since it is practically undocumented, and even references within the issues section are ambiguous, it was never clear to me that per-user, per-workspace, and per-project/folder settings for every extension are individually settable from within the settings menu of visual studio code, and that this even applies to chip type, and that this applies even when your ".code-workspace". To be specific, my settings.json file explicitly sets the chip type as esp32s2, yet still it doesn't take any effect as long as a workspace is open, even though nowhere in any of the files within the folder nor within the ".code-workspace" file is the chip type overwritten, such that it is natural to assume that when one clicks at the bottom of the screen and selects a specific chipt type, that esp-idf will then actually use that chip type. The truth is that it won't. You'll also have to open the settings, go the "Extensions" section, specifically the "ESP-IDF" subsection and go to the "Idf: Adapter Target Name) setting, and change its value to what you want, and you have 3 versions of this and any other setting, once under the "User" tab (still within settings), once under the "Workspace" tab, and then again under the project-folder tab. And these are independent of any overrides you explicitly enter into any files within your project or ".code-workspace" file. So it's a mess and very confusing. So incase anyone else runs into these problems, hope this helps. All of it also applies to other settings such as which usb port gets used. If esp uses the wrong one despite you specifying otherwise at the bottom of the screen, then look in all the files in your folder, but also under all the tabs of vscode settings under the esp-idf extension.

Some pictures and some official esp-idf extension documentation would be nice. Unfortunately even if it exists, it's impossible to find, as I have searched alot.

**Comment by brianignacio5** [comment]
We do mention it in several places in the extension documentation and there has been many closed issues related to this topic. In the latest version we try to set IDF_TARGET and serial port just to the `<project-folder>/.vscode/settings.json`. IF you are working with workspace with multiple folders instead of a single folder, you need to specify which subfolder to use as described in [Working with multiple projects](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/MULTI_PROJECTS.md).

[README.md](https://github.com/espressif/vscode-esp-idf-extension#how-to-use)

```
(OPTIONAL) Press F1 and type ESP-IDF: Select where to save configuration settings, which can be User settings, Workspace settings or workspace folder settings. Please take a look at [Working with multiple projects](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/MULTI_PROJECTS.md) for more information. Default is User settings.
```

[Install tutorial](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/install.md)

```
(OPTIONAL) Press F1 and type ESP-IDF: Select where to save configuration settings, which can be User settings, Workspace settings or workspace folder settings. Please take a look at [Working with multiple projects](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/MULTI_PROJECTS.md) for more information. Default is User settings.
```

Could you please specify which keywords you used to search ? We try to make as clear and concise as we can, yet we may not achieve this goal, that's why your feedback is greatly appreciated.

**Comment by fizarum** [comment]
2026, ESP-IDF v5.4.0 and its still doesn't work as it should. Why `idf.py set-target ...` can't simply set target for current project? Why  global `IDF_TARGET` still has bigger priority over local, provided by explicit command???
Switching back to platform.io

**Comment by brianignacio5** [comment]
@fizarum A lot has changed in the extension since this issue was reported. Whatever IDF_TARGET is set in sdkconfig tends to be the preference by the extension.

I don't believe many users don't have an issue with this recently. 

Are you still using an old version of this extension perhaps?

Would you care to open an issue with the errors you are facing?
