### ISSUE TITLE
Setting "idf.enableCCache" to true does not work (VSC-835)

### ISSUE THREAD

**Issue by meltdown03** [espressif/vscode-esp-idf-extension#635]
I tried setting `"idf.enableCCache": true` in the project `settings.json` file and globally.  When building, I watch the CMake configuration info at the beginning, I do not see the line `-- ccache will be used for faster recompilation`. 

I have to add this line in the `CMakeLists.txt` file
`set(CCACHE_ENABLE "1")`
in order to get it to work.

**Comment by brianignacio5** [comment]
Oh I see. We were using a compiler flag `-DCCACHE_ENABLE=1` in the build compilation step. 

I'll take a look thanks :)

**Comment by meltdown03** [comment]
It may actually be working now. Last night it wasn't, but today it is. It seemed hit-or-miss before though, idk.

**Comment by meltdown03** [comment]
Another question, is it supposed to ask the flash method every time now? UART, DFU, or JTAG? Even when I set it in the `settings.json` to UART, it still asks.

**Comment by meltdown03** [comment]
Ok I figured out when it does not work. So after it has run the cmake command and built (ninja) at least once, if I change something in the `sdkconfig` and rebuild. Then it only runs the `ninja` build so it does not use the `-CCACHE_ENABLE=1` compiler line

**Comment by meltdown03** [comment]
**Initial Build:**
![Screenshot from 2022-02-08 20-50-54](https://user-images.githubusercontent.com/6166536/153113176-76526aff-86be-422f-82a7-1b8ecbbce290.png)

**Re-Running CMake:**
![Screenshot from 2022-02-08 20-53-43](https://user-images.githubusercontent.com/6166536/153113285-65481ca4-350a-4b05-a0c4-30b9fc8f7acb.png)

**Not Re-Running CMake for some reason:**
![Screenshot from 2022-02-08 20-49-20](https://user-images.githubusercontent.com/6166536/153113358-94f3fceb-94b8-4e64-b22e-592427add73c.png)

**Comment by meltdown03** [comment]
I think I found how to make it glitch.

1. set `idf.enableCCache` to true and build project
2. Close VS Code or close the project (Ctrl-K, F)
3. Reopen VS Code and/or the project
4. Open "SDK Configuration editor" (not necessary to make any changes)
5. Build again. It will Re-Run CMake config, but no ccache anymore

If you watch the `./build/CMakeCache.txt` file when you open the SDK Configuration editor (step 4), you will see the `CCACHE_ENABLE:UNINTIALIZED=1` change to `CCACHE_ENABLE:UNINITIALIZED=0`

**Comment by meltdown03** [comment]
Ok, it works now when I perform those steps. If I find any other situations
where this happens, I will let you know. At least I know if it does happen,
a full clean will force it to work.

**Comment by meltdown03** [comment]
I another time when CCache gets disabled, When you set the target to a different board, It forces a reconfigure and does not have the CCache arg when it does this. (As long as you don't run the SDK Config editor before building, if you do run it or do a manual full clean, it will work.)
