### ISSUE TITLE
[Bug Report]: F5 to debug, error with "Failed to init Debug Adapter" (VSC-837)

### ISSUE THREAD

**Issue by acebearxp** [espressif/vscode-esp-idf-extension#638]
Press F5 to launch debug , a message box with the error "Failed to init Debug Adapter".
But if I manually execute "idf.py gdbgui" , everything works fine.

OS: Windows11 21H2(22000.469)
VSCode: 1.64.1
vscode-esp-idf-extension: v1.3.0
esp-idf: release-4.4 [8153bfe4]

There're many different development environments in my laptop, stm32, esp32, dotnet, java... So I'm not starting vscode as most other people doing. Instead, I start a command shell window, executing "**$HOME/.espressif/idf_cmd_init.bat esp-idf-esp-idf-3bca1dcff0a1a9a66f79892b92e8174c**" first, as pic below
![image](https://user-images.githubusercontent.com/11573054/153211009-0ca10258-d071-4689-8d22-da018a579ab0.png)

After that change to a workspace, then execute cmd "**code .**" to start the vscode  for my project.

esp-tools chain is installed into `C:\Users\acebear\.espressif`
esp-idf is installed into `C:\Users\acebear\source\esp-idf`
before executing idf_cmd_init.bat, only 2 esp related env-variables defined
```
IDF_PATH=C:\Users\acebear\source\esp-idf
IDF_TOOLS_PATH=C:\Users\acebear\.espressif
```

building, flash and any other functions are working fine, except "F5 Debug", when I launch debug, there's always a message box with the error "Failed to init Debug Adapter".
Any suggestion can I have a try?

the Debug console only 2 lines:
```
Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
```
the output for "ESP-IDF Debug Adapter":
```
DEBUG_ADAPTER_STARTED
2022-02-09 22:59:48,751 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
DEBUG_ADAPTER_READY2CONNECT
2022-02-09 22:59:48,757 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
DEBUG_ADAPTER_STOPPED
2022-02-09 22:59:48,799 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STOPPED
[Stopped] : ESP-IDF Debug Adapter
```

the output for "OpenOCD":
```
Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2

Info : only one transport option; autoselect 'jtag'
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000
Warn : Transport "jtag" was already selected
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : esp_usb_jtag: Device found. Base speed 40000KHz, div range 1 to 255
Info : clock speed 40000 kHz
Info : JTAG tap: esp32s3.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32s3.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s3.cpu0: Target halted, PC=0x420072B8, debug_reason=00000001
Info : esp32s3.cpu1: Target halted, PC=0x420189A6, debug_reason=00000000
Info : starting gdb server for esp32s3.cpu0 on 3333
Info : Listening on port 3333 for gdb connections
```

if I manually execute `idf.py gdbgui`, the web gdb debugger looks good
![image](https://user-images.githubusercontent.com/11573054/153229444-0f0a3230-9433-497c-bce5-5231dcbf6cc5.png)

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "espidf",
        "name": "debug",
        "request": "launch"
      }
    ]
  }
```

.vscode/settings.json
```
{
    "git.autoRepositoryDetection": "subFolders",
    "makefile.extensionOutputFolder": "./.vscode",

    "idf.pythonBinPathWin": "${env:IDF_PYTHON}",
    "idf.espIdfPathWin": "${env:IDF_PATH}",
    "idf.customExtraPaths": "${env:PATH}",
    "idf.adapterTargetName": "esp32s3",
    "idf.customExtraVars": "{\"OPENOCD_SCRIPTS\":\"C:/Users/acebear/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts\"}",
    "idf.openOcdConfigs": [
        "board/esp32s3-builtin.cfg"
    ],
    "idf.openOcdDebugLevel": 2,
    "idf.portWin": "COM5",
    "idf.flashType": "JTAG",
    "files.associations": {
        "timer.h": "c"
    }
}
```

the `ESP-IDF: Doctor Command` report looks very bad, but I think it is the "doctor command" perhaps has some bug, not the environment. 
> ---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.22000 
System environment variable IDF_PYTHON_ENV_PATH 
 C:\Users\acebear\.espressif\python_env\idf4.4_py3.8_env 
System environment variable PATH 
 C:\Users\acebear\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32s3-elf\bin;C:\Users\acebear\.espressif\tools\riscv32-esp-elf\esp-2021r2-patch2-8.4.0\riscv32-esp-elf\bin;C:\Users\acebear\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;C:\Users\acebear\.espressif\tools\cmake\3.20.3\bin;C:\Users\acebear\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin;C:\Users\acebear\.espressif\tools\ninja\1.10.2\;C:\Users\acebear\.espressif\tools\idf-exe\1.0.3\;C:\Users\acebear\.espressif\tools\ccache\4.3\ccache-4.3-windows-64;C:\Users\acebear\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64;C:\Users\acebear\source\esp-idf\tools;C:\Users\acebear\.espressif\python_env\idf4.4_py3.8_env\Scripts\;C:\Users\acebear\.espressif\tools\idf-git\2.30.1\cmd\;C:\Users\acebear\.espressif;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\SystemInternals;C:\Program Files\LLVM\LLVM\bin;C:\Program Files (x86)\gnu-make\gnu-make\bin;C:\Program Files\dotnet\;C:\Program Files\JAVA\jdk\bin;C:\Users\acebear\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Python\Python;C:\Program Files\Python\Python\Scripts;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\libnvvp;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.2.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\extras\CUPTI\lib64;C:\Program Files\NVIDIA GPU Computing Toolkit\cuDNN\v8.2.2\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\gcc-arm\gcc-arm\bin;C:\Program Files (x86)\STMicroelectronics\st_toolset\asm;C:\Users\acebear\AppData\Local\Microsoft\WindowsApps;C:\Users\acebear\.dotnet\tools;C:\Users\acebear\AppData\Roaming\Python\Python\Scripts;C:\Program Files (x86)\COSMIC\FSE_Compilers\CXSTM8;C:\Program Files (x86)\COSMIC\FSE_Compilers\CXSTM32 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.64.1 
Visual Studio Code language en 
Visual Studio Code shell C:\WINDOWS\System32\cmd.exe 
ESP-IDF Extension version 1.3.0 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) ${env:IDF_PATH}
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
Custom extra paths (idf.customExtraPaths) ${env:PATH}
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"C:/Users/acebear/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts"}
Virtual env Python Path (idf.pythonBinPath) ${env:IDF_PYTHON}
Serial port (idf.port) COM5
OpenOCD Configs (idf.openOcdConfigs) board/esp32s3-builtin.cfg
ESP-IDF Tools Path (idf.toolsPath) ${env:IDF_TOOLS_PATH}
Git Path (idf.gitPath) /usr/bin/git
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) false
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-IDF Custom extra paths
Access to ${env:PATH}: false
Access to Virtual env Python Path (idf.pythonBinPath) false
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version undefined
ESP-IDF version undefined
Python version undefined
Python's pip version undefined
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages undefined
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages undefined
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages undefined
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at Command failed: "/usr/bin/git" --version
ϵͳ�Ҳ���ָ����·����

--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by acebearxp** [comment]
There are some errors in "esp_idf_vsc_exg.log" as shown below

But all these errors related to ESP32/ESP32-S2, since the only chip I have is ESP32-S3 , I did not install tools for the other 2 chips

```
{"message":"Command failed: xtensa-esp32s2-elf-gcc --version\n'xtensa-esp32s2-elf-gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���\r\n","stack":"Error: Command failed: xtensa-esp32s2-elf-gcc --version\n'xtensa-esp32s2-elf-gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���\r\n\n\tat ChildProcess.exithandler (child_process.js:317:12)\n\tat ChildProcess.emit (events.js:315:20)\n\tat maybeClose (internal/child_process.js:1048:16)\n\tat Socket.<anonymous> (internal/child_process.js:439:11)\n\tat Socket.emit (events.js:315:20)\n\tat Pipe.<anonymous> (net.js:673:12)","level":"error","timestamp":"2022-02-10T06:17:22.577Z"}
{"message":"Error checking xtensa-esp32s2-elf version","stack":"Error: Command failed: xtensa-esp32s2-elf-gcc --version\n'xtensa-esp32s2-elf-gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���\r\n\n\tat ChildProcess.exithandler (child_process.js:317:12)\n\tat ChildProcess.emit (events.js:315:20)\n\tat maybeClose (internal/child_process.js:1048:16)\n\tat Socket.<anonymous> (internal/child_process.js:439:11)\n\tat Socket.emit (events.js:315:20)\n\tat Pipe.<anonymous> (net.js:673:12)","level":"error","timestamp":"2022-02-10T06:17:22.579Z"}
{"message":"Command failed: xtensa-esp32-elf-gcc --version\n'xtensa-esp32-elf-gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���\r\n","stack":"Error: Command failed: xtensa-esp32-elf-gcc --version\n'xtensa-esp32-elf-gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���\r\n\n\tat ChildProcess.exithandler (child_process.js:317:12)\n\tat ChildProcess.emit (events.js:315:20)\n\tat maybeClose (internal/child_process.js:1048:16)\n\tat Socket.<anonymous> (internal/child_process.js:439:11)\n\tat Socket.emit (events.js:315:20)\n\tat Pipe.<anonymous> (net.js:673:12)","level":"error","timestamp":"2022-02-10T06:17:22.581Z"}
...
```

**Comment by acebearxp** [comment]
I just tried the [Use Microsoft C/C++ extension to debug](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/DEBUGGING.md#use-microsoft-cc-extension-to-debug)
This works great!

**Comment by brianignacio5** [comment]
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/164922661.zip) ?

We made some fixes to the extension in GitHub master but haven't yet to publish to marketplace

**Comment by brianignacio5** [comment]
Thanks for your feedback @acebearxp closing this issue then. 

Please let me know if you have an additional issue, will be releasing this new version to marketplace soon!

**Comment by Ashutosh-017** [comment]
> I just tried the [Use Microsoft C/C++ extension to debug](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/DEBUGGING.md#use-microsoft-cc-extension-to-debug) This works great!
Please tell me how to change this configuration setting 
![1](https://github.com/espressif/vscode-esp-idf-extension/assets/113367859/bac57059-1bbc-4580-8401-7fec1a493b7d)
![2](https://github.com/espressif/vscode-esp-idf-extension/assets/113367859/ea22ef50-96e4-4699-8f47-a5f27921aa4e)
