### ISSUE TITLE
[Feature Request]: Refresh for EFuse Explorer (VSC-840)

### ISSUE THREAD

**Issue by eos1d3** [espressif/vscode-esp-idf-extension#643]
**Is your feature request related to a problem? Please describe.**
The EFuse Explorer works. But whenever the development board is changed, or UART port is changed, I can't get data from new device. The only way is to restart VS Code.

**Describe the solution you'd like**
Add a refresh button to it, like what RainMaker tab does there.

**Comment by brianignacio5** [comment]
Thanks for reporting this @eos1d3 will take a look

**Comment by brianignacio5** [comment]
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/166107379.zip)

**Comment by eos1d3** [comment]
@brianignacio5 Sorry for my late reply. The vsix installer works very well. Great thank for the improvement!
