### ISSUE TITLE
[Bug Report]: Unable to run the extention (VSC-842)

### ISSUE THREAD

**Issue by ademyankov** [espressif/vscode-esp-idf-extension#647]
The extension is stuck at the welcome screen.

![image](https://user-images.githubusercontent.com/13845895/154092896-86fe51de-1d90-4684-afc2-81adfdf4b262.png)

I tried re-installing the extension many times, also tried deleting the folder at _.vscode\extensions\espressif.esp-idf-extension-1.3.0_, nothing helps.

There is no _esp_idf_vsc_ext.log_ file, I guess since the configuration phase was not finished.

VS Code:

![image](https://user-images.githubusercontent.com/13845895/154091981-a336e74d-3115-4f44-bfe9-e356f195f0de.png)

Python:

![image](https://user-images.githubusercontent.com/13845895/154092146-d2d67995-b8c5-434e-943e-59d4deeab624.png)

Have anyone encountered a problem like this?

**Comment by thegoodhen** [comment]
I had the same issue, downgrading to v. 1.2. seems to be a workaround.

**Comment by brianignacio5** [comment]
Or fixed in #602  in GitHub master This is a duplicate.
