### ISSUE TITLE
Visual Studio Install does not work (VSC-845)

### ISSUE THREAD

**Issue by daverathbone** [espressif/vscode-esp-idf-extension#655]
Please fix the 
 ESPRESSIF
ESP-IDF Extension for Visual Studio Code
Welcome.
restart Visual Studio Code and run this wizard again.

WHICH KEEPS DOING THIS BEFORE YOU HAVE DONE ANYTHING!!!!!!!
TIME TO MAKE DEVTOOLS  THAT WORK SO WE CAN USE YOUR CHIPS.....

**Comment by wangzishi** [comment]
I have the same issue here.

**Comment by wangzishi** [comment]
I found that I need to set idf.gitPath to `C:\Program Files\Git\cmd\git.exe` which was `/usr/bin/git`.

**Comment by brianignacio5** [comment]
This is fixed in GitHub master since #602 but will release a fix soon to marketplace. We have many things we wanted to fix to make the extension better.

Apologies for the wait, will release the new version today.
