### ISSUE TITLE
[Bug Report]: v1.4.0 no longer shows build terminal window (VSC-851)

### ISSUE THREAD

**Issue by rtheil-growlink** [espressif/vscode-esp-idf-extension#660]
With the update to 1.4.0 I can't see the progress of a build in the terminal window because it's hidden. If I want to see the build terminal window, I have to put an error in code and build in order to see that terminal window. Once that terminal window is visible, it is no longer focused when a build starts. We, as developers, rely on the progress window of compilation, even when successful. I need to see the flash progress, and on chips that require the setup button to be pressed I need to see when it's waiting for me to press that button. Why remove it? Why not make it an option?

Had to downgrade to v1.3.0 to get this functionality back.

**Comment by taamo-code** [comment]
因为这个原因，我目前也选择使用v1.3.0

**Comment by brianignacio5** [comment]
You just need to set `idf.notificationSilentMode: true` in your settings.json

**Comment by rtheil-growlink** [comment]
That works. I think that option is a good addition. It'll be nice to not have the error notifications stick around until dismissed.
