### ISSUE TITLE
由于VSCode同步导致的插件配置被修改出错。 (VSC-866)

### ISSUE THREAD

**Issue by BunnySakura** [espressif/vscode-esp-idf-extension#676]
VSCode会自动同步插件及其配置，而本插件有部分配置包含了用户绝对路径，且**默认不会忽略同步**，导致我在两台设备上使用时，由于系统用户名不同，同步的配置路径不同而出错，手动修改回正确路径可以恢复。

涉及到的有关配置截图如下，一共七个配置选项：
![image](https://user-images.githubusercontent.com/48341563/159173835-b2b4d9d8-6f13-4ea6-ad35-87463d63ad29.png)

![image](https://user-images.githubusercontent.com/48341563/159173880-c70eb3f9-43dd-43bf-a45f-5c9ff492827c.png)

# 希望能改为默认忽略同步以避免问题。

**Comment by brianignacio5** [comment]
This is related to how vscode stores settings. Please take  a look at the [settings precedence](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence).

In this extension when you use the ** ESP-IDF: Select where to save configuration settings** command you can choose where the extension setup will save the settings.
