### ISSUE TITLE
[Bug Report]: PROBLEMS tab empty when build succeeds (VSC-868)

### ISSUE THREAD

**Issue by littleboot** [espressif/vscode-esp-idf-extension#678]
**Describe the bug**
A succesfull build clears all warnings from the "PROBLEMS" window, This makes finding and fixing the warnings difficult when no error is present in the code.

**To Reproduce**
Open a project for example the "blinky" example.
Declare a function prototype and nothing else, this will introduce the [-Wunused-function] warning.
add `static void unusedFunc();` for example

Build the project: 
`>ESP-IDF: Build your project`

Open build output (should open automatically but someone already requested this feature) to validate the warning is present.
![image](https://user-images.githubusercontent.com/17753602/159688060-14c9a2e4-e9b6-4e5b-a6cb-96663a356307.png)

Check "Problems" tab, observe no warnings are listed.
![image](https://user-images.githubusercontent.com/17753602/159688270-68520610-33f7-40da-8d11-1033d9c0609c.png)

Introduce an error that stops the build, (I added "error" to end of the file, this is invalid c).
Now the warning is listed together with the error inside the "PROBLEMS" tab.
![image](https://user-images.githubusercontent.com/17753602/159688973-6cecf868-e43a-49ba-8fd7-9be643308566.png)

**Expected behavior**
Always show the warnings even when the build succeeds.

**Environment:**
- OS: Windows 10 64-bit
- VSCode Version: 1.65.2
- ESP-IDF Version: 1.4.0

**Comment by brianignacio5** [comment]
I think this happens because the `IDF Size task` is executed afterwards clearing out the warning from the previous task.

Will check if there is a way to persist the task problems

**Comment by littleboot** [comment]
> I think this happens because the `IDF Size task` is executed afterwards clearing out the warning from the previous task.
> 
> Will check if there is a way to persist the task problems

Thank you for looking into this. I really like the VScode IDF extension sadly this bug made me switch to Eclipse for compiling and debugging, I hope I can switch back soon.

**Comment by MarkusvonStaden** [comment]
I'm sorry to dig out this old topic, but I still have this problem, even though I am on the newest version of the extension and the issue is marked as completed. Am I missing something?

**Comment by brianignacio5** [comment]
Are you using the vsix installer from master or the marketplace version ? We haven't released in marketplace these changes.

**Comment by MarkusvonStaden** [comment]
I installed 1.4.0 from the Github releases Tab.

**Comment by brianignacio5** [comment]
Yes the fix is not part of the 1.4.0 release. Will release a new version soon :'(

**Comment by electronick-co** [comment]
Hello!
I'm having the same issue on version 1.6.5 install from the marketplace (that seems to be the same as the latest release available at the moment).

I'm using Ubuntu 22.04. and nothing shows in the problems except when i actually have an error (then all the warnings appear)

**Comment by gonzabrusco** [comment]
Same issue. After a successful build, the PROBLEMS tab gets cleared. It's impossible to check for warnings.

**Comment by littleboot** [comment]
Found a solution, have a look at the pull requests:
Someone fixed the issues so you can compile with idd v5
https://github.com/hiruna/lvgl_esp32_drivers/tree/develop/lvgl_8.3.7_idf_5.2

**Comment by brianignacio5** [comment]
Have you tried disabling the idf size task after build task @gonzabrusco ?

**Comment by gonzabrusco** [comment]
> Have you tried disabling the idf size task after build task @gonzabrusco ?

How do I do that?

**Comment by brianignacio5** [comment]
In your project `.vscode/settings.json` add `idf.enableSizeTaskAfterBuildTask: false`

**Comment by gonzabrusco** [comment]
Is it possible to work on a solution that runs idf size task but also keeps the compilation workings? Not sure why we have to choose between both options when they are displayed on different tabs (size info in TERMINAL and warnings in PROBLEMS).

**Comment by mmrein** [comment]
I would suggest disabling the Size Task by default until/if this gets resolved. Showing build output with it's warnings is basic and expected functionality.
