### ISSUE TITLE
"Configure ESP-IDF Extension" with "release/v4.4", checks out the wrong branch! (VSC-869)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/vscode-esp-idf-extension#681]
VSC Extension 1.4.0

Steps to repro:
1. delete esp-idf folder
2. run Configure ESP-IDF Extension with release/v4.4 (release branch)
3. cd into XXXXX/esp-idf
4. git status

**Expectation**, the branch should be checked out in esp-idf folder. No dirty files. 

How are we supposed to verify what commit and branch we are on if it checks out saying "no branch". Very confusing. 

I used release/v4.4, despite what the screenshot shows...
<img width="944" alt="Screen Shot 2022-03-23 at 11 43 10 PM" src="https://user-images.githubusercontent.com/1863934/159858147-6f3ac9b4-bfbc-4357-a6b0-4c33325870d2.png">

<img width="606" alt="Screen Shot 2022-03-23 at 11 45 29 PM" src="https://user-images.githubusercontent.com/1863934/159858170-0a12a6c9-c57f-4db8-b9b8-5a8cf51f6721.png">

**Comment by chipweinberger** [comment]
Uh Oh! I just opened a random file to check if it really is checking out release/v4.4 and it is not even the right code!

components/heap/heap_caps.c is missing the latest changes!

Checking out a release branch seems to be broken!

**Comment by chipweinberger** [comment]
any comments on this? I haven't tried again since

**Comment by brianignacio5** [comment]
Sorry for late reply! 

This should have been fixed with #622 but will look at it and fix it soon!
