### ISSUE TITLE
idf.notificationSilentMode doesn't work (VSC-870)

### ISSUE THREAD

**Issue by remyhx** [espressif/vscode-esp-idf-extension#682]
Tried to get rid of the annoying notifications (not errors) by checking idf.notificationSilentMode. It doesn't work, also not after restarting. 

Using the latest 1.4.0 version and the master branch of esp-idf (just updated by git pull). Windows 10.

Dokter report:

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.19044 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\IVI Foundation\IVI\bin;C:\Program Files\IVI Foundation\IVI\bin;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microchip\xc16\v1.70\bin;C:\Program Files\Microchip\xc32\v3.00\bin;C:\Program Files\Microchip\xc8\v2.31\bin;C:\Program Files\PuTTY\;C:\Users\localadmin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts;C:\Program Files\Git\cmd;C:\Users\localadmin\.cargo\bin;C:\Users\localadmin\AppData\Local\Microsoft\WindowsApps;C:\Espressif/tools/xtensa-esp32-elf-clang/esp-13.0.0-20211203-x86_64-pc-windows-msvc/bin/;C:\ESPRESSIF/tools/xtensa-esp32-elf-clang/esp-13.0.0-20211203-x86_64-pc-windows-msvc/bin/;C:\esp\tools/tools/xtensa-esp32-elf-clang/esp-13.0.0-20211203-x86_64-pc-windows-msvc/bin/;C:\Espressif\tools/tools/xtensa-esp32-elf-clang/esp-13.0.0-20211203-x86_64-pc-windows-msvc/bin/;C:\Users\localadmin\AppData\Local\Programs\Microsoft VS Code\bin 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.65.2 
Visual Studio Code language en 
Visual Studio Code shell C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.4.0 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) C:/Espressif/esp-idf/
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
Custom extra paths (idf.customExtraPaths) C:\Espressif\tools\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin;C:\Espressif\tools\tools\xtensa-esp32s2-elf\esp-2021r3-patch2-8.4.0\xtensa-esp32s2-elf\bin;C:\Espressif\tools\tools\xtensa-esp32s3-elf\esp-2021r3-patch2-8.4.0\xtensa-esp32s3-elf\bin;C:\Espressif\tools\tools\riscv32-esp-elf\esp-2021r3-patch3-8.4.0\riscv32-esp-elf\bin;C:\Espressif\tools\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;C:\Espressif\tools\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;C:\Espressif\tools\tools\cmake\3.20.3\bin;C:\Espressif\tools\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin;C:\Espressif\tools\tools\ninja\1.10.2;C:\Espressif\tools\tools\idf-exe\1.0.3;C:\Espressif\tools\tools\ccache\4.3\ccache-4.3-windows-64;C:\Espressif\tools\tools\dfu-util\0.9\dfu-util-0.9-win64
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"C:\\Espressif\\tools\\tools\\openocd-esp32\\v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts","IDF_CCACHE_ENABLE":"1"}
Virtual env Python Path (idf.pythonBinPath) C:/Espressif/tools/python_env/idf5.0_py3.8_env/Scripts/python.exe
Serial port (idf.port) COM3
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,target/esp32.cfg
ESP-IDF Tools Path (idf.toolsPath) C:\Espressif\tools
Git Path (idf.gitPath) C:/Espressif/tools/tools/idf-git/2.34.2/cmd/git.exe
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-IDF Custom extra paths
Access to C:\Espressif\tools\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin: true
Access to C:\Espressif\tools\tools\xtensa-esp32s2-elf\esp-2021r3-patch2-8.4.0\xtensa-esp32s2-elf\bin: false
Access to C:\Espressif\tools\tools\xtensa-esp32s3-elf\esp-2021r3-patch2-8.4.0\xtensa-esp32s3-elf\bin: false
Access to C:\Espressif\tools\tools\riscv32-esp-elf\esp-2021r3-patch3-8.4.0\riscv32-esp-elf\bin: false
Access to C:\Espressif\tools\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin: true
Access to C:\Espressif\tools\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin: true
Access to C:\Espressif\tools\tools\cmake\3.20.3\bin: true
Access to C:\Espressif\tools\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin: true
Access to C:\Espressif\tools\tools\ninja\1.10.2: true
Access to C:\Espressif\tools\tools\idf-exe\1.0.3: true
Access to C:\Espressif\tools\tools\ccache\4.3\ccache-4.3-windows-64: true
Access to C:\Espressif\tools\tools\dfu-util\0.9\dfu-util-0.9-win64: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.34.1.windows.1
ESP-IDF version 5.0
Python version 3.8.7
Python's pip version 20.3.3
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 3.1.9
certifi version: 2021.10.8
cffi version: 1.15.0
charset-normalizer version: 2.0.11
click version: 8.0.4
colorama version: 0.4.4
construct version: 2.10.68
contextlib2 version: 21.6.0
cryptography version: 36.0.1
ecdsa version: 0.17.0
future version: 0.18.2
gcovr version: 5.0
idf-component-manager version: 1.0.1
idna version: 3.3
Jinja2 version: 3.0.3
kconfiglib version: 14.1.0
lxml version: 4.7.1
MarkupSafe version: 2.0.1
pip version: 20.3.3
psutil version: 5.9.0
pycparser version: 2.21
pyelftools version: 0.27
pygdbmi version: 0.9.0.2
Pygments version: 2.11.2
pyparsing version: 3.0.7
pyserial version: 3.5
pywin32 version: 303
PyYAML version: 6.0
reedsolo version: 1.5.4
requests version: 2.27.1
requests-toolbelt version: 0.9.1
schema version: 0.7.5
semantic-version version: 2.8.5
setuptools version: 60.9.3
six version: 1.16.0
tqdm version: 4.62.3
urllib3 version: 1.26.8
websocket-client version: 1.2.3
wheel version: 0.36.2
windows-curses version: 2.3.0
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "C:\\Espressif\\tools\\tools\\xtensa-esp32-elf\\esp-2021r2-patch3-8.4.0\\xtensa-esp32-elf\\bin\\xtensa-esp32-elf-gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            },
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
} 
--------------------------------------------------------------------------------------------------------------------------------------------

settings.json:
{
    "C_Cpp.intelliSenseEngine": "Default",
    "idf.adapterTargetName": "esp32",
    "idf.customExtraPaths": "C:\\Espressif\\tools\\tools\\xtensa-esp32-elf\\esp-2021r2-patch3-8.4.0\\xtensa-esp32-elf\\bin;C:\\Espressif\\tools\\tools\\xtensa-esp32s2-elf\\esp-2021r3-patch2-8.4.0\\xtensa-esp32s2-elf\\bin;C:\\Espressif\\tools\\tools\\xtensa-esp32s3-elf\\esp-2021r3-patch2-8.4.0\\xtensa-esp32s3-elf\\bin;C:\\Espressif\\tools\\tools\\riscv32-esp-elf\\esp-2021r3-patch3-8.4.0\\riscv32-esp-elf\\bin;C:\\Espressif\\tools\\tools\\esp32ulp-elf\\2.28.51-esp-20191205\\esp32ulp-elf-binutils\\bin;C:\\Espressif\\tools\\tools\\esp32s2ulp-elf\\2.28.51-esp-20191205\\esp32s2ulp-elf-binutils\\bin;C:\\Espressif\\tools\\tools\\cmake\\3.20.3\\bin;C:\\Espressif\\tools\\tools\\openocd-esp32\\v0.11.0-esp32-20211220\\openocd-esp32\\bin;C:\\Espressif\\tools\\tools\\ninja\\1.10.2;C:\\Espressif\\tools\\tools\\idf-exe\\1.0.3;C:\\Espressif\\tools\\tools\\ccache\\4.3\\ccache-4.3-windows-64;C:\\Espressif\\tools\\tools\\dfu-util\\0.9\\dfu-util-0.9-win64",
    "idf.customExtraVars": "{\"OPENOCD_SCRIPTS\":\"C:\\\\Espressif\\\\tools\\\\tools\\\\openocd-esp32\\\\v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts\",\"IDF_CCACHE_ENABLE\":\"1\"}",
    "idf.espIdfPathWin": "C:/Espressif/esp-idf/",
    "idf.openOcdConfigs": [
        "interface/ftdi/esp32_devkitj_v1.cfg",
        "target/esp32.cfg"
    ],
    "idf.portWin": "COM3",
    "idf.pythonBinPathWin": "C:/Espressif/tools/python_env/idf5.0_py3.8_env/Scripts/python.exe",
    "idf.toolsPathWin": "C:\\Espressif\\tools",
    "files.associations": {
        "sensirion_gas_index_algorithm.h": "c"
    },
    "idf.flashType": "UART"
}

- Windows: `%USERPROFILE%\.vscode\extensions\espressif.esp-idf-extension-VERSION\esp_idf_vsc_ext.log`

**Comment by brianignacio5** [comment]
Should be fixed with #662 

Can you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/201258128.zip) ?

**Comment by brianignacio5** [comment]
In your settings.json i don't see you set `idf.notificationSilentMode: true`to disable those notifications.

Closing this issue for this and lack of response.

**Comment by remyhx** [comment]
Well. Maybe that is the problem…  This is the updated version via your six file, as i mentioned before it didn’t work now. I was waiting for your response:))

[Image.jpeg]

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Brian A. Ignacio ***@***.***>
Verzonden: Friday, April 8, 2022 8:52:58 AM
Aan: espressif/vscode-esp-idf-extension ***@***.***>
CC: Remy Hurx ***@***.***>; Author ***@***.***>
Onderwerp: Re: [espressif/vscode-esp-idf-extension] idf.notificationSilentMode doesn't work (VSC-870) (Issue #682)


In your settings.json i don't see you set idf.notificationSilentMode: trueto disable those notifications.

Closing this issue for this and lack of response.

**Comment by remyhx** [comment]
It doesn’t work yet for me. While building there is still the notice.

Van: Brian A. Ignacio ***@***.***>
Verzonden: Saturday, 2 April 2022 13:04
Aan: espressif/vscode-esp-idf-extension ***@***.***>
CC: Remy Hurx ***@***.***>; Author ***@***.***>
Onderwerp: Re: [espressif/vscode-esp-idf-extension] idf.notificationSilentMode doesn't work (VSC-870) (Issue #682)


Should be fixed with #662<https://github.com/espressif/vscode-esp-idf-extension/pull/662>

Can you try this vsix installer<https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/201258128.zip> ?

**Comment by brianignacio5** [comment]
Could you share the required [troubleshooting information](https://github.com/espressif/vscode-esp-idf-extension#troubleshooting) and describe the current behavior ?

**Comment by remyhx** [comment]
Strange: I replied (by email reply) the 3rd of April  and 'my reply' says I replied 15 days ago haha. Stuck somewhere I guess. It still doesn't work on my mac and windows computer, but I just learned to live with it ...

I usually put my output/terminals at the right, so it blocks the recent updates from the chip. But it's ok.
