### ISSUE TITLE
[Bug Report]: compile_commands.json (VSC-871)

### ISSUE THREAD

**Issue by flair0626** [espressif/vscode-esp-idf-extension#684]
我在使用VScode 新建项目后，会弹出通知 是否要使用 compile_commands.json 文件 为此文件夹自动配置 IntelliSense? 这时候如果点击了是，项目里的组件就不能正常编译了 如果点击否，每次打开项目都会弹出通知。请问如何关闭这个通知。

**Comment by brianignacio5** [comment]
This is a feature of the [Microsoft C/C++extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools). 

Set `"compileCommands": "${workspaceFolder}/build/compile_commands.json"` in your `c_cpp_properties.json` to set  it properly as specified in [C/C++ Configuration](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/C_CPP_CONFIGURATION.md).
