### ISSUE TITLE
[Bug Report]: suggested command for copying openocd-udev-rule should not clobber destination (VSC-888)

### ISSUE THREAD

**Issue by ankostis** [espressif/vscode-esp-idf-extension#698]
After completing a new installation/configuring the extension, a final screen suggests: 

> All settings have been configured. You can close this window.
> For Linux users, OpenOCD needs to add 60-openocd.rules for permission delegation in USB devices to be added in /etc/udev/rules.d/.
> 
> Run this command in a terminal with sudo privileges:
> 
> ```
> sudo cp ${home}/.espressif/tools/openocd-esp32/${esp-version}/openocd-esp32/share/openocd/contrib/60-openocd.rules /etc/udev/rules.d
> ```

## Expected behavior

A safe choice would be the last command to wanr the user if the file already exists 9and contain possible user modifications),
by using the `-n` option:
```
> sudo cp -n ${home}/.espressif/tools/openocd-esp32/${esp-version}/openocd-esp32/share/openocd/contrib/60-openocd.rules /etc/udev/rules.d
```
- OS Name: Linux (Debian)
- VSCode Version: 1.66.1
- ESP-IDF Version: 1.4.0

**Comment by mbana** [comment]
This worked for me, I think. Does it work for anybody else?

```sh
$ fd .rules .      
./tools/openocd-esp32/v0.12.0-esp32-20230921/openocd-esp32/share/openocd/contrib/60-openocd.rules
$ sudo cp -vn ~/.espressif/tools/openocd-esp32/v0.12.0-esp32-20230921/openocd-esp32/share/openocd/contrib/60-openocd.rules /etc/udev/rules.d
'/home/mbana/.espressif/tools/openocd-esp32/v0.12.0-esp32-20230921/openocd-esp32/share/openocd/contrib/60-openocd.rules' -> '/etc/udev/rules.d/60-openocd.rules'
$ sudo udevadm control --reload-rules && sudo udevadm trigger
```

I am on Fedora (39), if that helps.
