### ISSUE TITLE
[Bug Report]:Erase flash device fails when monitor is open (VSC-891)

### ISSUE THREAD

**Issue by andrewteta** [espressif/vscode-esp-idf-extension#704]
When selecting "ESP-IDF: Erase flash memory from device" while monitoring the program already running, the command fails.

**To Reproduce**
- Select "ESP-IDF: Build, Flash and start a monitor on your device"
- Select "ESP-IDF: Erase flash memory from device"

**Expected behavior**
I would expect the extension to close the monitor before erasing the flash, just as it does when selecting "ESP-IDF: Build, Flash and start a monitor on your device". This way, the workflow can be controlled entirely through extension commands without fumbling to find the monitor terminal tab if it is not in view.

**Environment**

- OS Name & Version: MacOS 12.3.1
- VSCode Version: 1.66.2
- ESP-IDF Version: release/v4.4
- Python Version: 3.9.7

**Comment by brianignacio5** [comment]
Thanks for reporting this !

Will fix with #705
