### ISSUE TITLE
Example(s) suggestion (VSC-893)

### ISSUE THREAD

**Issue by seedub158** [espressif/vscode-esp-idf-extension#706]
Hello,

I would like to send ONLY 10 bytes over BLE.
I want it to be as minimal as possible (no extra TIME or CURRENT DRAW).
What would be the best example projects to do this or to start with and modify to do this?
Would I need two demo boards to do this?

If this is not the correct location for this request please let me know where to post it.

Thank you
Chris 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brianignacio5** [comment]
You could explore the forum https://www.esp32.com to ask users for feedback of best approach or you could read the esp-idf examples under the bluetooth's BLE section such as GATT or SPP and optimize the code for your use case.
