### ISSUE TITLE
[Feature Request]: SPI connections ESP32-DEVKITM-1 (VSC-895)

### ISSUE THREAD

**Issue by seedub158** [espressif/vscode-esp-idf-extension#708]
Hello,

I have the ESP32-DEVKITM-1 v1.0

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/user-guide-devkitm-1.html
has pin descriptions

Datasheet references GPIO17 for SCLK but also states that clock, chip-select, MOSI, and MISO can be configured to any GPIO

The example peripherial SPI master HD_eeprom, readme shows:
          | ESP32 | ESP32 | ESP32S2 | ESP32C3 | ESP32S3 |
| Host | SPI1   | HSPI   | FSPI         | SPI2        | SPI2    |
| DO   | 7        | 18       | 37           | 2             | 13      |
| DI     | 8        | 23       | 35           | 7             | 11      |
| SK    | 6        | 19       | 36           | 6             | 12      |
| CS    | 13      | 13       | 34           | 10           | 10      |

I am not familiar with SPI1 vs HSPI, FSPI, SPI2
I believe I need the ESP32 and my guess is the SPI1.  Then MOSI would be DO = pin 7, MISO would be DI = pin 8, SCLK would be SK = pin 6, and chip-select would be CS = pin 13.  Is that correct?

If this is not the correct location for this request please let me know where to post it.

Thank you
Chris

**Comment by brianignacio5** [comment]
Hi @seedub158  this repository is focused on vscode extension issues.

For this kind  of questions you can ask  in the [esp32 forums](https://www.esp32.com) but basically  yeah, you can use those GPIO pins for SPI assuming your source code is using SPI properly too.
