### ISSUE TITLE
[Bug Report]: /root/esp/esp-idf already exists. Delete it or use another location. (ERROR_EXISTING_ESP_IDF) (VSC-905)

### ISSUE THREAD

**Issue by jixishi** [espressif/vscode-esp-idf-extension#720]
![image](https://user-images.githubusercontent.com/57534147/170006906-4bdacb57-4086-488d-a96a-dc3f294f418e.png)

ERROR: /root/esp/esp-idf already exists. Delete it or use another location. (ERROR_EXISTING_ESP_IDF)

**Comment by jixishi** [comment]
Linux orangepi3-lts 5.16.17-sun50iw6 #3.0.2 SMP Wed May 18 09:47:29 CST 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by xiaguangbo** [comment]
@jixishi 在“Select ESP-IDF version”里选择“Find...”，就是使用本地的（如果文件不全就手动“git pull”之类的），其他选项会要求重新下载

**Comment by jixishi** [comment]
问题出现在py虚拟环境安装上

**Comment by brianignacio5** [comment]
Try the `Use existing ESP-IDF` option....

![useExistingEspIDf](https://user-images.githubusercontent.com/6033246/170202153-b7568bba-8ad3-45e5-ac29-8305a95046f8.png)
