### ISSUE TITLE
Arduino IDE new install ERROR (VSC-909)

### ISSUE THREAD

**Issue by seedub158** [espressif/vscode-esp-idf-extension#725]
Hello, I just installed Arduino IDE for Windows 7 and newer (using windows 10). I installed support for the ESP32, selected DOIT ESP32 DEVKIT V1 and selected the ESP32 BLE Arduino EXAMPLE: BLE_write. It compiled the first time but when I went to upload I got an error:
Error compiling for board DOIT ESP32 DEVKIT V1
Can you help me figure out what is going wrong?

Thank you
![Untitled4](https://user-images.githubusercontent.com/103335578/170894982-cf8bd63c-2d03-4d70-83b4-0dff2ec39256.png)

**Comment by brianignacio5** [comment]
I'm sorry @seedub158 This repository is for Visual Studio Code ESP-IDF extension  development. 

We do not maintain any Arduino IDE integration here.
