### ISSUE TITLE
[Feature Request]: 希望能够让esp-idf examples中的示例介绍内容支持中文 (VSC-913)

### ISSUE THREAD

**Issue by qf-wy** [espressif/vscode-esp-idf-extension#731]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WangShuoran** [comment]
这个应该发到ESP-IDF仓库，这个是IDF开发框架的Vscode插件，所以你可能发错位置了
