### ISSUE TITLE
[Feature Request]: Stop Monitor with CRTL+C (VSC-918)

### ISSUE THREAD

**Issue by MarkusvonStaden** [espressif/vscode-esp-idf-extension#736]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to stop the monitor without closing the terminal.
If i remember correctly, this once worked. But now I have to use` CRTL + J`, which closes the terminal

**Describe the solution you'd like**
when pressing `CRTL + C` the monitor stop, but the terminal stays

**Describe alternatives you've considered**
- None -

**Comment by brianignacio5** [comment]
To stop the monitor use the `CTRL + ]` as mentioned in [ESP-IDF Monitor keyboard shortcuts](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-monitor.html#keyboard-shortcuts)

**Comment by MarkusvonStaden** [comment]
Thank you!
I did some digging. Since we don't have the `]` Key on the german keyboard layout, the german version is `CTRL + '+'`.
In VSCode this just zooms in and is not passed to the terminal.
I tried to get `ctrl + '+'` to work, but even with modifying the vscode key bindings i could not get it to work.

The only thing, that worked for me is, to use `CTRL + T + X`
Even though that works, another binding would be nice.

**Comment by brianignacio5** [comment]
Oh interesting! The thing is this one of those python SIGINT signals that is embedded into the `idf_monitor.py` script directly and not really part of vscode extension.

I could discuss with IDF colleagues about a way, but it is most likely that there is a different keyboard shortcut to achieve this too in this language.
