### ISSUE TITLE
[Feature Request]: Store ESPRESSIF configuration in workspace settings. (VSC-930)

### ISSUE THREAD

**Issue by mistadave** [espressif/vscode-esp-idf-extension#754]
**Is your feature request related to a problem? Please describe.**
I'm using the esp-idf-extension on different projects with different environments. (Different machines which i access via VS Code SSH).
When I switch the local environment to an ssh machine, I've always to reconfigure ESPRESSIF with the right paths of the esp-idf environment.

**Describe the solution you'd like**
Would be nice, to be able to save the ESPRESSIF configuration in the workspace settings (.vscode/settings.json). 
So it will be possible to open different projects with different environments and don't need to reconfigure the esp-idf environment each time. For example on project with release-4.4, and second with release-4.3.

**Additional context**
Both project's where already setup with the extension.
First opened the left one, and then the second one on the right side, which prompts me again for the setup (paths comming from the first project).
![image](https://user-images.githubusercontent.com/7965357/177286666-7f815d80-02af-43fa-8c2b-f0652f93b297.png)

**Comment by brianignacio5** [comment]
Closing this issue since the feature it is implemented and documented.

Please comment here if you have any more issues.
