### ISSUE TITLE
[Bug Report]:  (VSC-935)

### ISSUE THREAD

**Issue by moefear85** [espressif/vscode-esp-idf-extension#758]
**Describe the bug**
QEMU isn't launching

**To Reproduce**
create a new sample project. build it. click on ESP-IDF QEMU. Click on start QEMU.

**Expected behavior**
that qemu launches

**Environment (please complete the following information):**

- OS Name & Version: Ubuntu 22.04
- VSCode Version: 1.69
- ESP-IDF Version: 5.0 (latest master)
- Python Version: 3.10

**Additional context**
I also tried opening a remote container. But the standard .devcontainer settings result in esp-idf v4.3 being installed (very outdated). Even after rebuilding within said container, I still get the same error when starting QEMU.

**Comment by brianignacio5** [comment]
Could you fill the issue with the troubleshooting information specified in the template ?

Is hard to know what is happening in your setup without any debug information.

**Comment by moefear85** [comment]
here's the full log
[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/9102495/esp_idf_vsc_ext.log)

I will clear it, then start a new fresh project, wait till the error happens, then upload that "differential" log. just a minute...

**Comment by moefear85** [comment]
then I start a new project
![Screenshot from 2022-07-13 15-22-00](https://user-images.githubusercontent.com/39313692/178743799-e21c32b4-f34e-4617-9a7b-dd796e0721eb.png)
then I create a new project using template-app and open it in a new window and close the old one
then it gives me the message "folder contains a devcontainer.... reopen ...". I click "reopen in container"
![Screenshot from 2022-07-13 15-23-45](https://user-images.githubusercontent.com/39313692/178744236-9b5fe991-3ea1-49f1-ba93-762f0768b773.png)
then it starts configuring/installing, but the first problem, it is using esp-idf-v4.3
![Screenshot from 2022-07-13 15-27-33](https://user-images.githubusercontent.com/39313692/178744969-f43fe80e-cdb2-4690-8aa6-390214640fe1.png)
here are the last messages I get after installing:
![Screenshot from 2022-07-13 15-32-17](https://user-images.githubusercontent.com/39313692/178745949-65ff8645-767a-4f2f-bb0f-c223fd29a63d.png)
then the window to reconfigure the esp-idf extension pops up:
![image](https://user-images.githubusercontent.com/39313692/178746115-52d2774b-160a-4581-960b-f5ef01e66f2b.png)
I don't use it, because it would overwrite my preexisting esp-idf in my home folder. Instead I close it, then try to build. it fails:
![image](https://user-images.githubusercontent.com/39313692/178747186-b85df618-9e5a-45c1-a9a5-2b4af1fc9c4c.png)
it fails because there is still the .vscode folder, which still has references to the esp-idf in my home folder. I think when opening a container, it should automatically know that it shouldn't use this. Moreover, supposedly an esp-idf-v4.3 was just downloaded and installed. I have no idea where. Why doesn't the esp-idf extension automatically detect and use it?
Anyways, I delete the .vscode folder, delete the build folder. then reload the workspace. Now I can build, and it correctly uses the /opt/esp and /opt/esp/idf folders automatically. But notice the outdated contents of the .devcontainer folder, that caused it to download the outdated v4.3 in the first place:
![image](https://user-images.githubusercontent.com/39313692/178749481-a87dd25f-176f-4fbc-8050-a09c9b7ff17d.png)
Anyways... it builds successfully:
![image](https://user-images.githubusercontent.com/39313692/178749589-1ab95460-5215-41dc-841a-1ed43ae3cf3c.png)
so then I click on [ESP-IDF QEMU] and I get the following screen:
![image](https://user-images.githubusercontent.com/39313692/178749798-23cf8c34-db52-4577-ab2f-c59e5b0b6806.png)
I click on Start QEMU at the top, then I get the following error message:
![image](https://user-images.githubusercontent.com/39313692/178749939-aebba530-a265-41ba-a2dd-2dca7eff7c7b.png)

here's the log afterwards:
[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/9102788/esp_idf_vsc_ext.log)

**Comment by moefear85** [comment]
- OS Name & Version: Ubuntu 22.10
-  "uname -r": 5.15.0-41-generic
- ESP-IDF Version: [latest master (but in the container it's 4.3]
- Python Version: 3.10 (but in the container I think it's 3.6)

![image](https://user-images.githubusercontent.com/39313692/178750922-a56b3fca-e7f2-4b41-b31b-d24acaaf0a10.png)

**Comment by moefear85** [comment]
ESP-Doctor Command Output:

```
---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS linux x64 5.15.0-41-generic 
System environment variable IDF_PYTHON_ENV_PATH 
 /opt/esp/python_env/idf4.3_py3.6_env 
System environment variable PATH 
 /vscode/vscode-server/bin/linux-x64/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/bin/remote-cli:/opt/esp/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin:/opt/esp/tools/xtensa-esp32s2-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s2-elf/bin:/opt/esp/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin:/opt/esp/tools/riscv32-esp-elf/esp-2021r2-patch3-8.4.0/riscv32-esp-elf/bin:/opt/esp/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:/opt/esp/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/opt/esp/tools/cmake/3.16.4/bin:/opt/esp/tools/openocd-esp32/v0.11.0-esp32-20211220/openocd-esp32/bin:/opt/esp/python_env/idf4.3_py3.6_env/bin:/opt/esp/idf/tools:/opt/qemu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.69.1 
Visual Studio Code language en 
Visual Studio Code shell /bin/bash 
ESP-IDF Extension version 1.4.0 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) /opt/esp/idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
Custom extra paths (idf.customExtraPaths) 
Custom extra vars (idf.customExtraVars) {}
Virtual env Python Path (idf.pythonBinPath) /opt/esp/python_env/idf4.3_py3.6_env/bin/python
Serial port (idf.port) /dev/ttyUSB1
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,board/esp32-wrover.cfg
ESP-IDF Tools Path (idf.toolsPath) /opt/esp
Git Path (idf.gitPath) /usr/bin/git
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-IDF Custom extra paths
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH true
Access to Ninja in environment PATH true
Access to ESP-IDF Tools Path (idf.toolsPath) true
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.17.1
ESP-IDF version 4.3.2
Python version 3.6.9
Python's pip version 21.3.1
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 3.1.9
Brotli version: 1.0.9
certifi version: 2021.10.8
cffi version: 1.15.0
charset-normalizer version: 2.0.12
click version: 8.0.4
construct version: 2.10.54
contextlib2 version: 21.6.0
cryptography version: 3.4.8
ecdsa version: 0.17.0
Flask version: 0.12.5
Flask-Compress version: 1.11
Flask-SocketIO version: 2.9.6
future version: 0.18.2
gdbgui version: 0.13.2.0
gevent version: 1.5.0
greenlet version: 1.1.2
idf-component-manager version: 1.0.1
idna version: 3.3
importlib-metadata version: 4.8.3
importlib-resources version: 5.4.0
itsdangerous version: 2.0.1
Jinja2 version: 3.0.3
kconfiglib version: 13.7.1
MarkupSafe version: 2.0.1
pip version: 21.3.1
pycparser version: 2.21
pyelftools version: 0.28
pygdbmi version: 0.9.0.2
Pygments version: 2.12.0
pyparsing version: 2.3.1
pyserial version: 3.5
python-engineio version: 3.14.2
python-socketio version: 4.6.1
PyYAML version: 6.0
reedsolo version: 1.5.4
requests version: 2.27.1
requests-toolbelt version: 0.9.1
schema version: 0.7.5
semantic-version version: 2.9.0
setuptools version: 59.6.0
six version: 1.16.0
tqdm version: 4.64.0
typing_extensions version: 4.1.1
urllib3 version: 1.26.9
Werkzeug version: 0.16.1
wheel version: 0.37.1
zipp version: 3.6.0
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements from /opt/esp/idf/requirements.txt are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Error
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Error
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at ENOENT: no such file or directory, open '/workspaces/qemu/.vscode/launch.json'
--------------------------------------------------------------------------------------------------------------------------------------------

```

**Comment by moefear85** [comment]
I think the only error that really matters here is the last line of the doctor command:
> Latest error at ENOENT: no such file or directory, open '/workspaces/qemu/.vscode/launch.json'

I don't think this is referencing the .vscode folder that I deleted, and that is incompatible/irrelevant anyways. Rather I think it is referencing one inside the "qemu environment" or the devcontainer, but that was never setup or created. Or the workspaces folder is supposed to be a variable. I don't know, but how does this work for everybody else? What am I doing that's so wrong? I'm new to docker/msc-remote-containers, I only installed them (latest versions), to get qemu to launch, which I read would only launch in a dev container.

**Comment by brianignacio5** [comment]
With regards to the settings, the issue is the following:

1) You create a project from the New Project Wizard, which uses your existing host system settings and copies them in the newly created project settings.
2) You open the project folder in the host system.
3) You Reopen the project folder in the container. The container is an isolated environment independent of the host system. Settings are useless and need to be update.

If you open a container window first and then create the project with the New Project Wizard, you should get proper settings.

About the error at the end, we have made some bug fixes related to this and update the esp-idf to master in the Dockerfile template. Open a container windows, uninstall the extension from the container itself and delete the folder from container extensions ($HOME/.vscode-server/extensions/espressif.esp-idf-extension-1.4.0) and install [this vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/301447416.zip) in the dev container (by default when the container is build it will pull the extension from marketplace)

**Comment by moefear85** [comment]
ok thx, but I've managed to get qemu running without containers. Still it can help others? Is there a timeline when the esp-idf extension will get updated to officially support idf latest master?
