### ISSUE TITLE
OpenOCD board.cfg configuration (VSC-280)

### ISSUE THREAD

**Issue by jmpmscorp** [espressif/vscode-esp-idf-extension#76]
Hi.

I can finally work with vscode debugger, but I want to ask about board.cfg passed to openocd. 

When I started trying debugger and clicked on Lauch, every time an error "OpenOCD exit with error code 1" was shown. Reviewing logs, error was related with board/esp32-wrover.cfg file. As I have an esp-wrover-kit 4.1, I knew that I must use board/esp32-wrover-kit-3.3v.cfg. Extension uses board/esp32-wrover.cfg by default but I couldn't find an option to change it. Finally, I edited package.json file in vscode extension directory and then, debugger started and worked without problem. 

So, my question, is there any option in launch.json or any other file where I can set board.cfg file instead of modify package.json?

Regards.

**Comment by brianignacio5** [comment]
As explained in the readme, there is configuration setting:

> **idf.openOcdConfigs** is used to store an array of openOCD scripts directory relative path config files to use with OpenOCD server. (Example: ["interface/ftdi/esp32_devkitj_v1.cfg", "board/esp32-wrover.cfg"]).

**Comment by jmpmscorp** [comment]
Thank you @brianignacio5 and excuse me.

It was my fault. I clicked on "guide" link in release tag that point to Debug title in readme and I didn't read this options.

**Comment by brianignacio5** [comment]
Don't need to excuse yourself man hehe, Happy to help.

Let us know how the extension experience goes, and if you have any feedback you can either open another issue here or on the [Spectrum channel](https://spectrum.chat/espidf-vsc?tab=posts)
