### ISSUE TITLE
[Bug Report]: cannot use install latest version of esp-idf (VSC-946)

### ISSUE THREAD

**Issue by v-3n0m** [espressif/vscode-esp-idf-extension#772]
**Describe the bug**
Not able to install the latest version of esp-idf  using vscode extension getting 404 error when downloading the version 4.4.2 .

**To Reproduce**
Install the release version 4.4. or latest 4.4 .

**Environment:**

- OS Name & Version: [Windows 11]
- VSCode Version: [e.g.1.4.0 ]
- ESP-IDF Version: [e.g. v4.4]
- Python Version: [e.g. 3.10]

**Comment by brianignacio5** [comment]
Does this happens with GitHub or Espressif or both download mirrors?

**Comment by v-3n0m** [comment]
@brianignacio5 yes it is happening with both GitHub and Espressif. Here is the screen shot of using github 
![Screenshot (2)](https://user-images.githubusercontent.com/96908119/183012323-76b3da20-8078-4b73-86df-13e587fe5297.png)

and this is using Espressif:
![Screenshot (3)](https://user-images.githubusercontent.com/96908119/183013607-868bd6f8-e5c0-488f-8498-f99c89afeb09.png)

**Comment by brianignacio5** [comment]
Thanks for reporting this. This is an issue in ESP-IDF itself, seems the release zip is not available.

Will ask for them to fix it asap.

**Comment by v-3n0m** [comment]
Now it works fine thank you.
