### ISSUE TITLE
[Bug Report]: QEMU manager can't recognize project target? (VSC-948)

### ISSUE THREAD

**Issue by luo980** [espressif/vscode-esp-idf-extension#778]
**Describe the bug**
ESP-IDP: QEMU Manager -> Start QEMU, then it shows nothings, i found the logs in ~/.vscode/extensions/espressif.esp-idf-extension-1.4.0/esp_idf_vsc_ext.log
```
{"user":true,"message":"qemu-system-xtensa is not in PATH or access is denied","stack":"Error: qemu-system-xtensa is not in PATH or access is denied\n    at l.<anonymous> (/dist/extension.js:8:599442)\n    at Generator.next (<anonymous>)\n    at s (/dist/extension.js:8:597424)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","level":"error","timestamp":"2022-08-16T01:41:15.678Z"}
```
However my project target is esp32c3, which is riscv32-based. I have cloned the espressif-qemu, configured and built a qemu-system-riscv32. Is qemu-system-riscv32 not supported now ? I think qemu manager should find the proper cpu target.

**To Reproduce**
Just create from an example project, and set cpu target esp32c3, build then try qemu manager.

**Expected behavior**
Want the hello-world program behave well on qemu.

**Environment (please complete the following information):**

- OS Name & Version: Ubuntu 22.04 LTS
- VSCode Version: 1.67.1
- ESP-IDF Version: 1.4.0
- Python Version: 3.10.4

**Comment by brianignacio5** [comment]
Hi @luo980 so far we only have implemented support for target ESP32 in QEMU. We are working hard to add support for our other targets but we haven't released them yet.


When other targets are available in QEMU we will add support in the extension. For now, we should add a notification explaining this feature is only available for ESP32.
