### ISSUE TITLE
[Feature Request]: Allow setting a custom build path by conf setting (VSC-953)

### ISSUE THREAD

**Issue by gfurtadoalmeida** [espressif/vscode-esp-idf-extension#786]
**Is your feature request related to a problem? Please describe.**
As the build is heavy on disk usage, it is, depending on the project, very slow.
The #668 work allows setting a custom build folder, but relative to the workspace.

**Describe the solution you'd like**
Being able to set a custom build path, that for speed, would be on a [RAM Drive](https://en.wikipedia.org/wiki/RAM_drive).

**Describe alternatives you've considered**
Moving the entire project to a RAM Drive.

**Additional context**
For testing on Windows, one could use the [ImDisk Toolkit](https://sourceforge.net/projects/imdisk-toolkit/)

**Comment by brianignacio5** [comment]
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/345066569.zip) ?

[how to Install extension from vsix](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix)

**Comment by gfurtadoalmeida** [comment]
Sure! I'll do it first thing in the morning and post the result.

**Comment by brianignacio5** [comment]
Sorry for late reply. Could you take a look at this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/372458811.zip) ?

**Comment by gfurtadoalmeida** [comment]
No problems :thumbsup:
The build is working now, both in-memory and on-disk!
I just need to verify if it will flash from memory too.

**Comment by gfurtadoalmeida** [comment]
Everything is working, build and flash!
We might close this issue.
Thank you @brianignacio5 !

**Comment by gfurtadoalmeida** [comment]
The [last vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/372458811.zip) is working as expected.
The work to fix the issue is being done on #794.
