### ISSUE TITLE
error when trying to run menuconfig (VSC-961)

### ISSUE THREAD

**Issue by T0biasCZe** [espressif/vscode-esp-idf-extension#796]
### OS

Windows

### Operating System version

windows 10

### Visual Studio Code version

1.71

### ESP-IDF version

4.3

### Python version

3.8.7

### Doctor command output

doesnt output anything

### Description

i am folowing the blink example tutorial, and when clicking ESP IDF SDK Configuration editor, it throws 
`[SDK Configuration Editor]
---------------------------ERROR--------------------------

Error: spawn C:\Users\user\.espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:478:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
-----------------------END OF ERROR-----------------------
`
when running tghe menuconfig from terminal, it says missing module click
![obrazek](https://user-images.githubusercontent.com/44525446/188324589-8211d1ae-2b0c-49df-b25e-94ef30c52b7b.png)

### Debug Message

```plain
cant find the file
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Seems your python virtual environment is missing some packages. Could you share the `ESP-IDF Doctor Command` output ? When you run this command the result is copied in the clipboard and you can paste it anywhere.

**Comment by brianignacio5** [comment]
Closing this issue for lack of response. Comment here if you still have any issues.
