### ISSUE TITLE
Using existing Python install results in failure to find module 'future' when building. (VSC-183)

### ISSUE THREAD

**Issue by Devenda** [espressif/vscode-esp-idf-extension#8]
**Describe the bug**
Error when building: 
`    from future.utils import iteritems
ModuleNotFoundError: No module named 'future'`

**To Reproduce**
Use a pre installed python distribution and build the project. By following the onboarding, keeping the suggested python install and (re)installing the ESP-IDF Tools.

**Expected behavior**
A build without errors.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/2527506/72094714-4732d700-3317-11ea-800e-516876f7b198.png)

**Environment (please complete the following information):**
- OS Name & Version: [Windows 10]
- VSCode Version: [e.g. 1.41.1]
- ESP-IDF Version: master
- Python Version: [3.7]

**Additional context**
The python path "C:\Users\tinus\AppData\Local\Programs\Python\Python37\" was suggested in the onboarding.
After changing the above path to "C:\Users\tinus\.espressif\python_env\idf4.1_py3.7_env\Scripts\" in the option Custom Extra Paths the build runs successfully.

Thank you for providing this great extension!

**Comment by brianignacio5** [comment]
Hi @Devenda Thank you so much for your feedback !

We also recently discover this issue internally and we fixed for release v0.1.2 which should be coming in the next days on marketplace and GitHub releases.

Please let us know if these keeps happening or if you face any other issue.
