### ISSUE TITLE
I can't install vscode esp idf extension because of python error. (VSC-969)

### ISSUE THREAD

**Issue by soulk87** [espressif/vscode-esp-idf-extension#807]
### OS

Windows

### Operating System version

Window 10

### Visual Studio Code version

1.71.2(user setup)

### ESP-IDF version

4.4.3

### Python version

3.8.10

### Doctor command output

- ---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
- OS undefined undefined undefined 
- System environment variable IDF_PYTHON_ENV_PATH 
-  undefined 
- System environment variable PATH 
-  undefined 
- System environment variable PYTHON 
-  undefined 
- Visual Studio Code version undefined 
- Visual Studio Code language undefined 
- Visual Studio Code shell undefined 
- ESP-IDF Extension version undefined 
- Workspace folder undefined 
- ---------------------------------------------------- Extension configuration settings ------------------------------------------------------
- ESP-ADF Path (idf.espAdfPath) undefined
- ESP-IDF Path (idf.espIdfPath) undefined
- ESP-MDF Path (idf.espMdfPath) undefined
- ESP-Matter Path (idf.espMatterPath) undefined
- Custom extra paths (idf.customExtraPaths) undefined
- Custom extra vars (idf.customExtraVars) undefined
- Virtual env Python Path (idf.pythonBinPath) undefined
- Serial port (idf.port) undefined
- OpenOCD Configs (idf.openOcdConfigs) undefined
- ESP-IDF Tools Path (idf.toolsPath) undefined
- Git Path (idf.gitPath) undefined
- -------------------------------------------------------- Configurations access -------------------------------------------------------------
- Access to ESP-ADF Path (idf.espAdfPath) undefined
- Access to ESP-IDF Path (idf.espIdfPath) undefined
- Access to ESP-MDF Path (idf.espMdfPath) undefined
- Access to ESP-Matter Path (idf.espMatterPath) undefined
- Access to ESP-IDF Custom extra paths
- Access to Virtual env Python Path (idf.pythonBinPath) undefined
- Access to CMake in environment PATH undefined
- Access to Ninja in environment PATH undefined
- Access to ESP-IDF Tools Path (idf.toolsPath) undefined
- -------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
- Spaces in system environment Path undefined
- Spaces in ESP-ADF Path (idf.espAdfPath) undefined
- Spaces in ESP-IDF Path (idf.espIdfPath) undefined
- Spaces in ESP-MDF Path (idf.espMdfPath) undefined
- Spaces in ESP-Matter Path (idf.espMatterPath) undefined
- Spaces in ESP-IDF Custom extra paths
- Spaces in Virtual env Python Path (idf.pythonBinPath) undefined
- Spaces in ESP-IDF Tools Path (idf.toolsPath) undefined
- ----------------------------------------------------------- Executables Versions -----------------------------------------------------------
- Git version undefined
- ESP-IDF version undefined
- Python version undefined
- Python's pip version undefined
- -------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
- Python packages undefined
- ---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
- Check ESP-IDF Python packages undefined
- ---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
- Check Extension Python packages undefined
- ---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
- Check Debug AdapterPython packages undefined
- ----------------------------------------------------------- Latest error -----------------------------------------------------------------
- Latest error at Cannot read properties of undefined (reading 'fsPath')
- --------------------------------------------------------------------------------------------------------------------------------------------
- 

### Description

I can't install esp-idf extension. Please check My log below...
![esp](https://user-images.githubusercontent.com/14542488/191645030-d1fbee37-bbe8-4b6b-a43f-e4c625ac9531.PNG)
### Debug Message

```plain
Warning File C:\esp\espressif\tools\idf-python\3.8.7\vcruntime140_1.dll
                                        already exists and was not updated.
Warning File C:\esp\espressif\tools\idf-python\3.8.7\winsound.pyd
                                        already exists and was not updated.
Extracted C:\esp\espressif\tools\idf-python\3.8.7 ...
C:\esp\espressif\tools\idf-python\3.8.7\python.exe is not valid. (ERROR_INVALID_PYTHON)
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by radurentea** [comment]
Hi @soulk87,

If you have followed the [Installation tutorial](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/install.md) your IDF_TOOLS_PATH should be `C:\Users\<YOUR WINDOWS USER>\.espressif`.

If you didn't follow the tutorial installation I recommend you do it, because you might not have installed the Pre-Requisites and this might be another reason for your error. Since you are using Windows, I recommend you installing them by using the [ESP-IDF Tools Installers](https://dl.espressif.com/dl/esp-idf/?idf=4.4)

**Comment by soulk87** [comment]
Hi @radurentea ,
Thank you for your answer~!
Actually I already installed ESP_IDF before installing the ESP_IDF extension.
ESP_IDF could not be started properly due to an error at the time. (Please check the attached image)
![error](https://user-images.githubusercontent.com/14542488/191918352-916db910-6332-4fc5-8d96-656dba319c2f.PNG)
I couldn't start with ESP_IDF, so I was looking for another way to build an esp32 project and it was the idf extension.
But still I can't install the ESP_IDF...

**Comment by radurentea** [comment]
I think the easiest way to fix the installation is to uninstall ESP-IDF and install it via the [ESP-IDF Tools Installer](https://dl.espressif.com/dl/esp-idf/?idf=4.4)

**Comment by brianignacio5** [comment]
Hi @soulk87 

Could you share log file which can be obtained from:

* **Windows**: %USERPROFILE%\.vscode\extensions\espressif.esp-idf-extension-VERSION\esp_idf_vsc_ext.log
* **Linux & MacOSX**: $HOME/.vscode/extensions/espressif.esp-idf-extension-VERSION/esp_idf_vsc_ext.log

**Comment by soulk87** [comment]
Hi @brianignacio5 
Thank you for your response.
I think my pc(window) has some problem with ESP-IDF.
Still I can't install ESP-IDF(not with extension).
I will ask about this situation at the another repository.
After check about ESP-IDF will come here again.
