### ISSUE TITLE
[Feature Request]: Add New Debugging Views for Variables in "Watch"-Window (VSC-1008)

### ISSUE THREAD

**Issue by Delzye** [espressif/vscode-esp-idf-extension#842]
The new way to display structs is really nice, but it only works for local variables. If I want to watch e.g. a global variable, the old view is used (which admittedly is not very useful).
The "View Memory"-Button is also unavailable for the "Watch"-View.
 
Is It possible to also use the new way of displaying variables in the "Watch"-View, as well as adding the "view memory" button?

I wouldn't know how to properly look into some variables otherwise.

Also there is no "View Memory" button for pointers right now (second screenshot, `atBuf` points at an array inside of another array, but I cannot look at its contents, no button).

**Additional context**
 "Watch"-View still uses the old representation:
![grafik](https://user-images.githubusercontent.com/48919898/202120758-5d871be9-3645-4706-8dbc-06fefd2399c0.png)
No Memory-View for a pointer to the start of an array:
![grafik](https://user-images.githubusercontent.com/48919898/202125075-ba9935d4-426f-4ccf-8685-ac73e0ad852f.png)

**Comment by brianignacio5** [comment]
Thanks for your feature request @Delzye 

Could you provide an example in c of those variables for me to reproduce ? There are a few GDB call need to happen on the debug adapter to get further information from those pointers for example. Understanding what kind of value is a pointer does help to query these values.

**Comment by Delzye** [comment]
Hi @brianignacio5 
Sure, let's take these variables:
```c
    volatile struct struct_t local_a = {
      .x = 6,
      .y = 7,
      .z = 8
    };

    volatile int local_arr[] = {1,2,3,4,5};
    volatile int* local_arr_ptr = local_arr;
```
with:
```c
struct struct_t {
    int x;
    int y;
    int z;
};
```
This is the result:
![grafik](https://user-images.githubusercontent.com/48919898/203787852-889551c0-b58e-49f2-a6fc-2b74a9585d12.png)

**Comment by Delzye** [comment]
Could this be reopened, please?
It has not been completed.

**Comment by brianignacio5** [comment]
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/496257414.zip) ??
