### ISSUE TITLE
Why ask users to install cmake ninja first thing? (VSC-1011)

### ISSUE THREAD

**Issue by ramiws** [espressif/vscode-esp-idf-extension#846]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when you ask the uses to do something but then I see that you install cmake and ninja anyways during the tools download. 
I wasted time installing them without brew, for nothing. Thanks!

**Describe the solution you'd like**
remove the request to install cmake and ninja Prerequisites

**Describe alternatives you've considered**
Platformio

**Comment by brianignacio5** [comment]
Could you describe where you see this requisites ?

**Comment by ramiws** [comment]
What is the first thing you see when you install the extension? have you tried ?

**Comment by brianignacio5** [comment]
Something like this?
<img width="637" alt="Screen Shot 2022-11-03 at 2 51 35 PM" src="https://user-images.githubusercontent.com/1863934/199842609-80cff204-3062-4358-b5d5-2a831bbfce40.png">

or these
![Screen Shot 2022-11-29 at 1 03 37 PM](https://user-images.githubusercontent.com/6033246/204444890-a965a409-201c-4c09-98b3-3824b4e76645.png)

**Comment by ramiws** [comment]
Both having the same issue...
