### ISSUE TITLE
App trace log‘s "Show Report" button no behavior (VSC-1022)

### ISSUE THREAD

**Issue by WangShuoran** [espressif/vscode-esp-idf-extension#858]
### OS

Windows

### Operating System version

win10

### Visual Studio Code version

1.74.2

### ESP-IDF version

4.4.3

### Python version

3.8.7(but my pc have python3.10 with environment path)

### Doctor command output

[output.txt](https://github.com/espressif/vscode-esp-idf-extension/files/10298218/output.txt)

### Extension

[output.txt](https://github.com/espressif/vscode-esp-idf-extension/files/10298220/output.txt)

### Description

When I am finish the trace and in the project have trace folder and a file was created in the folder. The file name prefix is trace.
Like this:
![image](https://user-images.githubusercontent.com/43474491/209427222-764ed3ca-1b8e-40f0-aa34-d9fc0f113801.png)
But when I enter the trace archives:
![image](https://user-images.githubusercontent.com/43474491/209427276-7fd4617e-c0c2-4fce-9cda-1eaf0603103d.png)
This click without any behavior. And I test the file is correct, because I use the file enter the powershell cammand(use idf environment):
```bash
python C:\Espressif\frameworks\esp-idf-v4.4.3\tools\esp_app_trace\logtrace_proc.py D:\mine\debug_temp\app_trace_to_host\trace\trace_1671867825325.trace D:\mine\debug_temp\app_trace_to_host\build\app_trace_to_host.elf
```
And the output is:
![image](https://user-images.githubusercontent.com/43474491/209427390-4eb8ded2-62cc-4702-8c2a-63ecca741130.png)

So I have last possible causes:
1. The logtrace_proc.py is not find
2. [extension](https://github.com/espressif/vscode-esp-idf-extension) can not know my elf file

### Debug Message

```plain
Not relevant
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by WangShuoran** [comment]
And I follow the document https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/app_tracing.md which let me only open openocd, but as my test this cannot report data.

When I try open openocd and run debuuger and run the code(without breakpoint stop), and the record is recorded. I don't know why? Is my operation worry or document miss this?

**Comment by brianignacio5** [comment]
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/497499446.zip)

**Comment by WangShuoran** [comment]
It can working, I expect it to become the official version.
![image](https://user-images.githubusercontent.com/43474491/210511480-d9823c71-926c-4728-a26a-37d9b13982da.png)

And I have a little tip:
![image](https://user-images.githubusercontent.com/43474491/210511749-2d5de0cf-2740-4b65-ac88-54192142eea3.png)
If an Trace log is 0kb(empty) when I show report it will no output like this:
![image](https://user-images.githubusercontent.com/43474491/210511942-ac04017f-e4ef-44d3-b50d-b837dc272282.png)
But if the extension give any tip show this trace log is 0KB, I will very happy to doesn't spend time check this file.

**Comment by brianignacio5** [comment]
Something like this?

![Screen Shot 2023-01-04 at 5 32 31 PM](https://user-images.githubusercontent.com/6033246/210525145-ab32bc4f-9f21-41f7-8624-b0d7c6ae3668.png)


Added in the same PR
