### ISSUE TITLE
VScode  one-click script to configure esp-idf does not download the tool chain correctly for linux-arm64. (VSC-1024)

### ISSUE THREAD

**Issue by longcat99** [espressif/vscode-esp-idf-extension#861]
VScode  one-click script to configure esp-idf does not download the tool chain correctly for linux-arm64.

**Comment by brianignacio5** [comment]
This is a duplicate of #840

**Comment by brianignacio5** [comment]
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/runs/3834819964/esp-idf-extension.vsix.zip) ?
