### ISSUE TITLE
Install python requirements when installing ESP-MATTER (VSC-1029)

### ISSUE THREAD

**Issue by Diegorro98** [espressif/vscode-esp-idf-extension#868]
**Is your feature request related to a problem? Please describe.**
Since commit https://github.com/espressif/esp-matter/commit/85abe2cdd457f6f1d198af0ff1ee339ccd3c9bfb, some python packages are required to build a Matter project with ESP-IDF.

**Describe the solution you'd like**
When installing ESP-MATTER, install also the python requirements that are stored (since https://github.com/espressif/esp-matter/commit/350dc6ae8b011b1e29070797daa55100840b3fbf) in [requirements.txt](https://github.com/espressif/esp-matter/blob/main/requirements.txt) at the ESP-MATTER repo.

Maybe a new command like `Install ESP-IDF extension Python Packages` but for ESP-MATTER python packages that is also executed when `Install ESP-MATTER` command is executed, so that if you change your idf python environment you don't need to reinstall ESP-MATTER to get this python requirements satisfied.

**Comment by brianignacio5** [comment]
Thanks for your contribution @Diegorro98 :)
