### ISSUE TITLE
[Feature Request]: Multiple projects in the same workspace  (VSC-1037)

### ISSUE THREAD

**Issue by ramiws** [espressif/vscode-esp-idf-extension#877]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I cannot easily switch between projects in the same workspace in VStudio 

**Describe the solution you'd like**
Similar to platformio, ability to select which project i want to build, flash etc...
**Describe alternatives you've considered**
Stop using the extension and going back to platformio

**Comment by mustafaalialaleemi** [comment]
هذا لي

في الأحد، ٢٢ يناير ٢٠٢٣ ١:٣٦ ص ramiws ***@***.***> كتب:
