### ISSUE TITLE
Minor 'export not recognized...' error when starting monitor (VSC-184)

### ISSUE THREAD

**Issue by Devenda** [espressif/vscode-esp-idf-extension#9]
**Describe the bug**
Minor error when running monitor:
`export IDF_PATH=c:\Users\tinus\esp\esp-idf
'export' is not recognized as an internal or external command,
operable program or batch file.`

**To Reproduce**
Start monitor, look at console output.

**Expected behavior**
No error.

**Environment (please complete the following information):**
- OS Name & Version: [Windows 10]
- VSCode Version: [e.g. 1.41.1]
- ESP-IDF Version: master
- Python Version: [3.7]

**Additional context**
This seems to originate from this piece of code:
![afbeelding](https://user-images.githubusercontent.com/2527506/72095724-5024a800-3319-11ea-801c-78d829c18d25.png)

However this line seems to be unnecessary as (at least on Windows) it does not seem to do anything as the monitor command afterward runs fine.

Thank you for providing this great extension!

**Comment by brianignacio5** [comment]
We were trying to override system IDF_PATH with extension configured idf.espIdfPath (if defined) but windows set VAR=value got lost on merging. Will fix in v0.1.2 

Thanks !
