### ISSUE TITLE
[Feature Request]: Allowing only one monitor terminal window (VSC-1058)

### ISSUE THREAD

**Issue by SilverBut** [espressif/vscode-esp-idf-extension#903]
**Is your feature request related to a problem? Please describe.**
<img width="222" alt="image" src="https://user-images.githubusercontent.com/6560655/222982600-803b5450-c2e1-4a3c-8c42-7e7f76c52a76.png">

When developing projects, this 'Build, Flash and Monitor' button is helpful. However, for each time I clicked it, a new monitor window appears, instead of reusing old ones. It's easy to became this after dozens of compiling, which is quite annoying.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/6560655/222982643-0c6a3cb9-55a5-480c-b5aa-c732706f59a3.jpg">

**Describe the solution you'd like & alternatives you've considered**

When create monitor window, check if it already exists before creation, like how ESP-IDF Size/Flash works.

https://github.com/espressif/vscode-esp-idf-extension/blob/d2ca138efad73249cd12dd2b9656695d476d36d3/src/espIdf/size/idfSizePanel.ts#L32-L35

And if already exists, close it, or reuse it to run monitor command.

If necessary, only do the check when called automatically via "Build, Flash and Monitor" button, so users can still create multiple monitor window manually.

**Comment by SilverBut** [comment]
not stale. still need this feature.

**Comment by SilverBut** [comment]
Any maintainer?

**Comment by brianignacio5** [comment]
@SilverBut Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/666045721.zip) ?
