### ISSUE TITLE
Extension keeps old settings when choosing USE EXISTING SETUP (VSC-1062)

### ISSUE THREAD

**Issue by MohammedBENHADINE** [espressif/vscode-esp-idf-extension#906]
### OS

Windows

### Operating System version

Windows 11

### Visual Studio Code version

1.76.1

### ESP-IDF version

5.0.1

### Python version

3.8.7

### Doctor command output

N/A

### Description

- Step 1 : I installed ESP-IDF extension with EXPRESS method , IDF version  5.0.1, rapidally i figure that the code I want to compile need a lot of changes since it was developed with a 4.4.3 IDF version. So I decided to go back and remove the IDF version.

- Step 2 : I removed the folder where the extension installed the framework and tools , I removed the extension folder from .vscode path on my HOME then i removed the extension and reloaded VSCode.

- Step 3 : I installed IDF version directly from https://dl.espressif.com/dl/esp-idf/ with the Online Installer so i can choose custom installation.

- Step 4 : I have reinstalled ESP-IDF extension, i tried to USE EXISTING SETUP method so i can point to my IDF framework and tools installation but it keeps showing me the older configuration with IDF version set to 5.0.1 ! 

### Debug Message

```plain
N/A
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/601331439.zip) ?
