### ISSUE TITLE
shutil.SameFileError (VSC-1067)

### ISSUE THREAD

**Issue by Bloodance** [espressif/vscode-esp-idf-extension#913]
### OS

Windows

### Operating System version

Ubuntu 22

### Visual Studio Code version

1.76.2

### ESP-IDF version

5.0

### Python version

3.10

### Doctor command output

idf_versions.txt has (1) KB
idf_versions.txt progress: 100.00% (0.10 / 0.10) KB

Downloading GDB for Xtensa
Found xtensa-esp-elf-gdb in /home/aike/.espressif/dist
Downloading GDB for RISC-V
Found riscv32-esp-elf-gdb in /home/aike/.espressif/dist
Downloading Toolchain for Xtensa (ESP32) based on GCC
Found xtensa-esp32-elf in /home/aike/.espressif/dist
Downloading Toolchain for Xtensa (ESP32-S2) based on GCC
Found xtensa-esp32s2-elf in /home/aike/.espressif/dist
Downloading Toolchain for Xtensa (ESP32-S3) based on GCC
Found xtensa-esp32s3-elf in /home/aike/.espressif/dist
Downloading Toolchain for 32-bit RISC-V based on GCC
Found riscv32-esp-elf in /home/aike/.espressif/dist
Downloading Toolchain for ESP32 ULP coprocessor
Found esp32ulp-elf in /home/aike/.espressif/dist
Downloading OpenOCD for ESP32
Found openocd-esp32 in /home/aike/.espressif/dist
Downloading ESP ROM ELFs
Found esp-rom-elfs in /home/aike/.espressif/dist

Using existing GDB for Xtensa in /home/aike/.espressif/tools/xtensa-esp-elf-gdb/11.2_20220823
Using existing GDB for RISC-V in /home/aike/.espressif/tools/riscv32-esp-elf-gdb/11.2_20220823
Using existing Toolchain for Xtensa (ESP32) based on GCC in /home/aike/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0
Using existing Toolchain for Xtensa (ESP32-S2) based on GCC in /home/aike/.espressif/tools/xtensa-esp32s2-elf/esp-2022r1-11.2.0
Using existing Toolchain for Xtensa (ESP32-S3) based on GCC in /home/aike/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0
Using existing Toolchain for 32-bit RISC-V based on GCC in /home/aike/.espressif/tools/riscv32-esp-elf/esp-2022r1-11.2.0
Using existing Toolchain for ESP32 ULP coprocessor in /home/aike/.espressif/tools/esp32ulp-elf/2.35_20220830
Using existing OpenOCD for ESP32 in /home/aike/.espressif/tools/openocd-esp32/v0.11.0-esp32-20221026
Installing package ESP ROM ELFs
Installing tar.gz package ESP ROM ELFs

Requirement already satisfied: virtualenv in ./.local/lib/python3.10/site-packages (16.7.12)

Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/aike/.espressif/python_env/idf5.0_py3.10_env/bin/python3
/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:24: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:25: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import distutils.sysconfig
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 2656, in <module>
    main()
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 859, in main
    create_environment(
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 1183, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 1553, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python3.10/shutil.py", line 234, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/usr/bin/python3' and '/home/aike/.espressif/python_env/idf5.0_py3.10_env/bin/python3' are the same file
Command failed: "/usr/bin/python3" -m virtualenv "/home/aike/.espressif/python_env/idf5.0_py3.10_env" -p "/usr/bin/python3"
/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:24: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:25: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import distutils.sysconfig
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 2656, in <module>
    main()
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 859, in main
    create_environment(
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 1183, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 1553, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python3.10/shutil.py", line 234, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/usr/bin/python3' and '/home/aike/.espressif/python_env/idf5.0_py3.10_env/bin/python3' are the same file
Command failed: "/usr/bin/python3" -m virtualenv "/home/aike/.espressif/python_env/idf5.0_py3.10_env" -p "/usr/bin/python3"
/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:24: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:25: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import distutils.sysconfig
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 2656, in <module>
    main()
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 859, in main
    create_environment(
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 1183, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/home/aike/.local/lib/python3.10/site-packages/virtualenv.py", line 1553, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python3.10/shutil.py", line 234, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/usr/bin/python3' and '/home/aike/.espressif/python_env/idf5.0_py3.10_env/bin/python3' are the same file

### Extension

{"message":"Open On-Chip Debugger v0.11.0-esp32-20221026 (2022-10-26-14:47)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger v0.11.0-esp32-20221026 (2022-10-26-14:47)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /dist/extension.js:1:9835\n\tat ChildProcess.exithandler (node:child_process:399:7)\n\tat ChildProcess.emit (node:events:526:28)\n\tat maybeClose (node:internal/child_process:1092:16)\n\tat Socket.<anonymous> (node:internal/child_process:451:11)\n\tat Socket.emit (node:events:526:28)\n\tat Pipe.<anonymous> (node:net:687:12)","level":"error","timestamp":"2023-03-20T17:56:57.863Z"}
{"message":"Open On-Chip Debugger v0.11.0-esp32-20221026 (2022-10-26-14:47)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n","stack":"Error: Open On-Chip Debugger v0.11.0-esp32-20221026 (2022-10-26-14:47)\nLicensed under GNU GPL v2\nFor bug reports, read\n\thttp://openocd.org/doc/doxygen/bugs.html\n\n\tat /dist/extension.js:1:9835\n\tat ChildProcess.exithandler (node:child_process:399:7)\n\tat ChildProcess.emit (node:events:526:28)\n\tat maybeClose (node:internal/child_process:1092:16)\n\tat Socket.<anonymous> (node:internal/child_process:451:11)\n\tat Socket.emit (node:events:526:28)\n\tat Pipe.<anonymous> (node:net:687:12)","level":"error","timestamp":"2023-03-20T17:57:02.739Z"}
{"message":"Command failed: \"/usr/bin/python3\" -m virtualenv \"/home/aike/.espressif/python_env/idf5.0_py3.10_env\" -p \"/usr/bin/python3\"\n/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:24: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n  import distutils.spawn\n/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:25: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead\n  import distutils.sysconfig\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 2656, in <module>\n    main()\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 859, in main\n    create_environment(\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 1183, in create_environment\n    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 1553, in install_python\n    shutil.copyfile(executable, py_executable)\n  File \"/usr/lib/python3.10/shutil.py\", line 234, in copyfile\n    raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\nshutil.SameFileError: '/usr/bin/python3' and '/home/aike/.espressif/python_env/idf5.0_py3.10_env/bin/python3' are the same file\n","stack":"Error: Command failed: \"/usr/bin/python3\" -m virtualenv \"/home/aike/.espressif/python_env/idf5.0_py3.10_env\" -p \"/usr/bin/python3\"\n/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:24: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n  import distutils.spawn\n/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:25: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead\n  import distutils.sysconfig\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 2656, in <module>\n    main()\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 859, in main\n    create_environment(\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 1183, in create_environment\n    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 1553, in install_python\n    shutil.copyfile(executable, py_executable)\n  File \"/usr/lib/python3.10/shutil.py\", line 234, in copyfile\n    raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\nshutil.SameFileError: '/usr/bin/python3' and '/home/aike/.espressif/python_env/idf5.0_py3.10_env/bin/python3' are the same file\n\n\tat ChildProcess.exithandler (node:child_process:408:12)\n\tat ChildProcess.emit (node:events:526:28)\n\tat maybeClose (node:internal/child_process:1092:16)\n\tat Socket.<anonymous> (node:internal/child_process:451:11)\n\tat Socket.emit (node:events:526:28)\n\tat Pipe.<anonymous> (node:net:687:12)","level":"error","timestamp":"2023-03-20T17:57:04.824Z"}
{"user":true,"message":"Command failed: \"/usr/bin/python3\" -m virtualenv \"/home/aike/.espressif/python_env/idf5.0_py3.10_env\" -p \"/usr/bin/python3\"\n/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:24: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n  import distutils.spawn\n/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:25: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead\n  import distutils.sysconfig\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 2656, in <module>\n    main()\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 859, in main\n    create_environment(\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 1183, in create_environment\n    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 1553, in install_python\n    shutil.copyfile(executable, py_executable)\n  File \"/usr/lib/python3.10/shutil.py\", line 234, in copyfile\n    raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\nshutil.SameFileError: '/usr/bin/python3' and '/home/aike/.espressif/python_env/idf5.0_py3.10_env/bin/python3' are the same file\n","stack":"Error: Command failed: \"/usr/bin/python3\" -m virtualenv \"/home/aike/.espressif/python_env/idf5.0_py3.10_env\" -p \"/usr/bin/python3\"\n/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:24: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n  import distutils.spawn\n/home/aike/.local/lib/python3.10/site-packages/virtualenv.py:25: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead\n  import distutils.sysconfig\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 2656, in <module>\n    main()\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 859, in main\n    create_environment(\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 1183, in create_environment\n    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)\n  File \"/home/aike/.local/lib/python3.10/site-packages/virtualenv.py\", line 1553, in install_python\n    shutil.copyfile(executable, py_executable)\n  File \"/usr/lib/python3.10/shutil.py\", line 234, in copyfile\n    raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\nshutil.SameFileError: '/usr/bin/python3' and '/home/aike/.espressif/python_env/idf5.0_py3.10_env/bin/python3' are the same file\n\n\tat ChildProcess.exithandler (node:child_process:408:12)\n\tat ChildProcess.emit (node:events:526:28)\n\tat maybeClose (node:internal/child_process:1092:16)\n\tat Socket.<anonymous> (node:internal/child_process:451:11)\n\tat Socket.emit (node:events:526:28)\n\tat Pipe.<anonymous> (node:net:687:12)","level":"error","timestamp":"2023-03-20T17:57:04.827Z"}

### Description

Already installed esp-idf, when in ESP-IDF setup page, select EXPRESS, then click install, error appeared.

### Debug Message

```plain
no
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by radurentea** [comment]
Hi @Bloodance,

Please run the Doctor Command by opening Command Palette in VSCODE(CTRL + SHIFT + P) and type Doctor Command. This command will copy the results to clipboard. Paste them in here so we can have a look.
