### ISSUE TITLE
VS Code Peripheral View not updated due to missing libusb? (VSC-1069)

### ISSUE THREAD

**Issue by ingpjb** [espressif/vscode-esp-idf-extension#915]
### OS

Windows

### Operating System version

Windows 11

### Visual Studio Code version

1.76.2

### ESP-IDF version

5.0.1

### Python version

3.10.7

### Doctor command output

OS win32 x64 10.0.22621 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python310\Scripts\;C:\Python310\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;D:\PuTTY\;C:\ProgramData\chocolatey\bin;C:\Program Files\CMake\bin;D:\Git\cmd;C:\ProgramData\chocolatey\lib\openocd\tools\OpenOCD-20211118-0.11.0\bin;C:\Microchip\xc8\v2.41\bin;D:\VSCode\bin;D:\GNU\10_2021_10\bin;C:<HOMEPATH>\AppData\Local\Microsoft\WindowsApps; 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.76.2 
Visual Studio Code language en 
Visual Studio Code shell C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.6.0 
Workspace folder e:\Workspace\VSCode\blink 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) D:\espressif\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
Custom extra paths (idf.customExtraPaths) D:\espressif\.espressif\tools\xtensa-esp-elf-gdb\11.2_20220823\xtensa-esp-elf-gdb\bin;D:\espressif\.espressif\tools\riscv32-esp-elf-gdb\11.2_20220823\riscv32-esp-elf-gdb\bin;D:\espressif\.espressif\tools\xtensa-esp32-elf\esp-2022r1-11.2.0\xtensa-esp32-elf\bin;D:\espressif\.espressif\tools\xtensa-esp32s2-elf\esp-2022r1-11.2.0\xtensa-esp32s2-elf\bin;D:\espressif\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1-11.2.0\xtensa-esp32s3-elf\bin;D:\espressif\.espressif\tools\riscv32-esp-elf\esp-2022r1-11.2.0\riscv32-esp-elf\bin;D:\espressif\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;D:\espressif\.espressif\tools\cmake\3.24.0\bin;D:\espressif\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin;D:\espressif\.espressif\tools\ninja\1.10.2;D:\espressif\.espressif\tools\idf-exe\1.0.3;D:\espressif\.espressif\tools\ccache\4.6.2\ccache-4.6.2-windows-x86_64;D:\espressif\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64;D:\espressif\.espressif\tools\esp-rom-elfs\20220823
Custom extra vars (idf.customExtraVars)
    OPENOCD_SCRIPTS: D:\espressif\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026/openocd-esp32/share/openocd/scripts
    IDF_CCACHE_ENABLE: 1
    ESP_ROM_ELF_DIR: D:\espressif\.espressif\tools\esp-rom-elfs\20220823/
Virtual env Python Path (idf.pythonBinPath) D:\espressif\.espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe
Serial port (idf.port) COM5
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,target/esp32.cfg
ESP-IDF Tools Path (idf.toolsPath) D:\espressif\.espressif
Git Path (idf.gitPath) D:\espressif\.espressif\tools\idf-git\2.30.1\cmd\git.exe
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-IDF Custom extra paths
Access to D:\espressif\.espressif\tools\xtensa-esp-elf-gdb\11.2_20220823\xtensa-esp-elf-gdb\bin: true
Access to D:\espressif\.espressif\tools\riscv32-esp-elf-gdb\11.2_20220823\riscv32-esp-elf-gdb\bin: true
Access to D:\espressif\.espressif\tools\xtensa-esp32-elf\esp-2022r1-11.2.0\xtensa-esp32-elf\bin: true
Access to D:\espressif\.espressif\tools\xtensa-esp32s2-elf\esp-2022r1-11.2.0\xtensa-esp32s2-elf\bin: true
Access to D:\espressif\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1-11.2.0\xtensa-esp32s3-elf\bin: true
Access to D:\espressif\.espressif\tools\riscv32-esp-elf\esp-2022r1-11.2.0\riscv32-esp-elf\bin: true
Access to D:\espressif\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: true
Access to D:\espressif\.espressif\tools\cmake\3.24.0\bin: true
Access to D:\espressif\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin: true
Access to D:\espressif\.espressif\tools\ninja\1.10.2: true
Access to D:\espressif\.espressif\tools\idf-exe\1.0.3: true
Access to D:\espressif\.espressif\tools\ccache\4.6.2\ccache-4.6.2-windows-x86_64: true
Access to D:\espressif\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: true
Access to D:\espressif\.espressif\tools\esp-rom-elfs\20220823: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path true
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in D:\espressif\.espressif\tools\xtensa-esp-elf-gdb\11.2_20220823\xtensa-esp-elf-gdb\bin: false
Spaces in D:\espressif\.espressif\tools\riscv32-esp-elf-gdb\11.2_20220823\riscv32-esp-elf-gdb\bin: false
Spaces in D:\espressif\.espressif\tools\xtensa-esp32-elf\esp-2022r1-11.2.0\xtensa-esp32-elf\bin: false
Spaces in D:\espressif\.espressif\tools\xtensa-esp32s2-elf\esp-2022r1-11.2.0\xtensa-esp32s2-elf\bin: false
Spaces in D:\espressif\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1-11.2.0\xtensa-esp32s3-elf\bin: false
Spaces in D:\espressif\.espressif\tools\riscv32-esp-elf\esp-2022r1-11.2.0\riscv32-esp-elf\bin: false
Spaces in D:\espressif\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: false
Spaces in D:\espressif\.espressif\tools\cmake\3.24.0\bin: false
Spaces in D:\espressif\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin: false
Spaces in D:\espressif\.espressif\tools\ninja\1.10.2: false
Spaces in D:\espressif\.espressif\tools\idf-exe\1.0.3: false
Spaces in D:\espressif\.espressif\tools\ccache\4.6.2\ccache-4.6.2-windows-x86_64: false
Spaces in D:\espressif\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: false
Spaces in D:\espressif\.espressif\tools\esp-rom-elfs\20220823: false
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.30.1.windows.1
ESP-IDF version 5.0.1
Python version 3.8.7
Python's pip version 23.0.1
-------------------------------------------------- Project configuration settings ----------------------------------------------------------
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 4.0.1
CacheControl version: 0.12.11
certifi version: 2022.12.7
cffi version: 1.15.1
charset-normalizer version: 3.1.0
click version: 8.0.4
colorama version: 0.4.6
construct version: 2.10.68
contextlib2 version: 21.6.0
cryptography version: 36.0.2
ecdsa version: 0.18.0
esp-coredump version: 1.4.2
esptool version: 4.5.1
freertos-gdb version: 1.0.2
future version: 0.18.2
gcovr version: 6.0
idf-component-manager version: 1.2.2
idna version: 3.4
Jinja2 version: 3.0.3
kconfiglib version: 14.1.0
lockfile version: 0.12.2
lxml version: 4.9.2
MarkupSafe version: 2.1.2
msgpack version: 1.0.5
packaging version: 23.0
pip version: 23.0.1
psutil version: 5.9.4
pycparser version: 2.21
pyelftools version: 0.27
pygdbmi version: 0.9.0.2
Pygments version: 2.14.0
pyparsing version: 3.0.9
pyserial version: 3.5
pywin32 version: 305
PyYAML version: 6.0
reedsolo version: 1.6.0
requests version: 2.28.2
requests-file version: 1.5.1
requests-toolbelt version: 0.10.1
schema version: 0.7.5
setuptools version: 67.6.0
six version: 1.16.0
tqdm version: 4.65.0
urllib3 version: 1.26.15
websocket-client version: 1.5.1
wheel version: 0.36.2
windows-curses version: 2.3.1
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "OpenOCD",
      "request": "launch"
    },
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "D:\\espressif\\.espressif\\tools\\xtensa-esp32-elf\\esp-2022r1-11.2.0\\xtensa-esp32-elf\\bin\\xtensa-esp32-elf-gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            },
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
} 

### Extension

{"message":"Open On-Chip Debugger v0.11.0-esp32-20221026 (2022-10-26-14:48)\r\nLicensed under GNU GPL v2\r\nFor bug reports, read\r\n\thttp://openocd.org/doc/doxygen/bugs.html\r\n","stack":"Error: Open On-Chip Debugger v0.11.0-esp32-20221026 (2022-10-26-14:48)\r\nLicensed under GNU GPL v2\r\nFor bug reports, read\r\n\thttp://openocd.org/doc/doxygen/bugs.html\r\n\n\tat \\dist\\extension.js:1:9835\n\tat ChildProcess.exithandler (node:child_process:399:7)\n\tat ChildProcess.emit (node:events:526:28)\n\tat maybeClose (node:internal/child_process:1092:16)\n\tat ChildProcess._handle.onexit (node:internal/child_process:302:5)","level":"error","timestamp":"2023-03-24T14:04:13.335Z"}
{"user":true,"message":"OpenOCD server failed to start because of Error: libusb_open() failed with LIBUSB_ERROR_NOT_\n❌ Error: libusb_open() failed with LIBUSB_ERROR_NOT_","stack":"Error: OpenOCD server failed to start because of Error: libusb_open() failed with LIBUSB_ERROR_NOT_\n\tat Socket.<anonymous> (\\dist\\extension.js:1:108687)\n\tat Socket.emit (node:events:526:28)\n\tat addChunk (node:internal/streams/readable:315:12)\n\tat readableAddChunk (node:internal/streams/readable:289:9)\n\tat Readable.push (node:internal/streams/readable:228:10)\n\tat Pipe.onStreamRead (node:internal/stream_base_commons:190:23)","level":"error","timestamp":"2023-03-24T14:04:15.667Z"}

### Description

When starting a debug session (using the ESP-Prog) everything seems ok, including opening and displaying the ESPPeripheral View. But when the debugger hits a breakpoint, the peripheral register values are never updated and remain in their reset satus.

### Debug Message

```plain
Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
Debug Adapter initialized
Debug Adapter is running
WARNING! This feature can't update UI after execution.
```

### Other Steps to Reproduce

When I check the Espressif IDF extension's "Runtime Status" this says,

Activation Event:onView:espIdf.peripheralView
Activation Time:220ms
Uncaught Errors (3)
OpenOCD server failed to start because of Error: libusb_open() failed with LIBUSB_ERROR_NOT_
Unhandled error. (<Buffer 45 78 63 65 70 74 69 6f 6e 20 69 6e 20 74 68 72 65 61 64 20 54 68 72 65 61 64 2d 31 3a 0d 0a 54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 ... 418 more bytes>)
Unhandled error. (<Buffer 4f 53 45 72 72 6f 72 3a 20 5b 45 72 72 6e 6f 20 32 32 5d 20 49 6e 76 61 6c 69 64 20 61 72 67 75 6d 65 6e 74 0d 0a>)

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by radurentea** [comment]
Hi @ingpjb ,

This is the current behaviour, the values are not updated on demand. There is an initial request for values but we don't track the changes of the values for now. However, I've created a feature request: https://github.com/espressif/vscode-esp-idf-extension/issues/918

**Comment by ingpjb** [comment]
Thanks Radurentea,

Pitty its not functional yet.

Greetings,

Peter
