### ISSUE TITLE
[Feature Request]: Toggle Status Bar via settings.json (VSC-1079)

### ISSUE THREAD

**Issue by Delzye** [espressif/vscode-esp-idf-extension#927]
**Is your feature request related to a problem? Please describe.**
At our company, we use one VSCode Installation for multiple kinds of work, one of which is working with esp-idf.
The status bar tends to get pretty cluttered with icons, so we manually have to turn on/off the idf whenever we (don't) use it.
That is tedious and probably easily solvable.

**Describe the solution you'd like**
Add a setting in settings.json to turn off the status bar, simila to the one CMake-Tools or GitLens has.
This enables us to disable the status bar by default and enable it in our idf-project-template for that specific workspace.

**Describe alternatives you've considered**
Keeping it manual or using multiple VSCode Installations. Both is suboptimal, to put it nicely.

**Additional context**
CMake-Tools status bar setting:
![image](https://user-images.githubusercontent.com/48919898/230075512-6737d839-3bcd-4704-a36c-afd12f6281e5.png)

**Comment by Delzye** [comment]
I'm still waiting for a response from the developers.

**Comment by brianignacio5** [comment]
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/667838659.zip) ?

**Comment by Delzye** [comment]
Hi Brian,

works like a charm, thank you very much!

**Comment by AndriiFilippov** [comment]
Tested on: 
OS - Windows 10
ESP-IDF: master 
VSCode: 1.78.0

LGTM 👍
