### ISSUE TITLE
Command 'ESP-IDF: Configure ESP-IDF extension' resulted in an error. (VSC-1081)

### ISSUE THREAD

**Issue by solarslurpi** [espressif/vscode-esp-idf-extension#929]
### OS

Windows

### Operating System version

10

### Visual Studio Code version

1.77.1

### ESP-IDF version

?

### Python version

?

### Doctor command output

[Freenove ESP32 cam](https://www.amazon.com/dp/B0BMQ8F7FN?psc=1&ref=ppx_yo2ov_dt_b_product_details)

i don't know what the 'ESP-IDF Doctor command' is....

### Extension

this message over and over...

{"message":"Cannot access filePath: c:\\Users\\happy\\Documents\\Projects\\test_esp32_cam\\CMakeLists.txt","stack":"Error: ENOENT: no such file or directory, access 'c:\\Users\\happy\\Documents\\Projects\\test_esp32_cam\\CMakeLists.txt'\n\tat Object.accessSync (node:fs:250:3)\n\tat e.accessSync (node:electron/js2c/asar_bundle:5:8277)\n\tat k (\\dist\\extension.js:1:6328)\n\tat \\dist\\extension.js:1:8128\n\tat B (\\dist\\extension.js:1:8307)\n\tat \\dist\\extension.js:1:37265\n\tat Generator.next (<anonymous>)\n\tat \\dist\\extension.js:1:36354\n\tat new Promise (<anonymous>)\n\tat d (\\dist\\extension.js:1:36099)\n\tat g (\\dist\\extension.js:1:37214)\n\tat \\dist\\extension.js:1:1222971\n\tat Generator.next (<anonymous>)\n\tat \\dist\\extension.js:1:1219342\n\tat new Promise (<anonymous>)\n\tat Ne (\\dist\\extension.js:1:1219087)\n\tat ct (\\dist\\extension.js:1:1219976)\n\tat gn.eb (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:110:14676)\n\tat gn.db (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:110:14380)\n\tat \\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:110:12406\n\tat async E.n (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:96:6646)\n\tat async E.m (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:96:6609)\n\tat async E.l (\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:96:6066)","level":"error","timestamp":"2023-04-05T21:01:16.732Z"}

### Description

fails with error message: espidf.setup.start not found.

### Debug Message

```plain
see othe rcomments.
```

### Other Steps to Reproduce

i tried installing the ESP-IDF dev envioronment separately.  That's not the problem.  There is something simple I fundamentally don't seem to understand?

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
It seems you haven't checked for existing issues. This was fixed in master with #909
