### ISSUE TITLE
[Feature Request]: Getting Offset for Flash (VSC-1085)

### ISSUE THREAD

**Issue by AliMoal** [espressif/vscode-esp-idf-extension#934]
I'm working on a project with OTA structure. My project has 2 OTA slots, I use first one as 3rd stage bootloader and my main program is on second one. In VS Code Extension, flashing device uses the first offset of app in partitions.csv. If I want to flash my program on second slot, I should flash that manually with Fhash binary to partition OR run flashing by CLI.
Is there any way for choosing offset for my main program regardless of partition.csv?
I mean configuring the command which will be run when I click on Flash device icon. Generally, it is good for users to select offsets for each .bin files by their owns.
Thanks.

**Comment by AliMoal** [comment]
That's good but for first time I cannot flash bootloader.bin and partition_table.bin, because bootloader and partition table options are not in partition table. how can I flash them manually?

**Comment by brianignacio5** [comment]
Oh I see. but why not ? You can specify a custom partition table using csv and the partitions will be flashed according to the `${project_dir}/build/flasher_args.json` offset for each partition. As long as the partitions doesn't overlap which each other the offset should be correct and the boot loader and partition table should be flashed to device which you can use later to flash a binary to OTA partition.

What is the content of `${project_dir}/build/flasher_args.json` ?

**Comment by AliMoal** [comment]
That's exactly what I'm looking for. This file will be created when we build the program and with every build it will be changed. Is there any way to change it regardless of partition csv file? I mean the *app* key in this Json file.

**Comment by brianignacio5** [comment]
Try the [vsix installer]() to add an option for right click on a .bin file and enter a custom hexadecimal offset value to flash on your serial device.
