### ISSUE TITLE
[Feature Request]: Allowing manually specify which terminal edf runs on (VSC-1086)

### ISSUE THREAD

**Issue by rogue-shadowdancer** [espressif/vscode-esp-idf-extension#935]
**Is your feature request related to a problem? Please describe.**
As shown in #854, for those who are using bash(and do not want to change it) in Windows, an error will occur because the Windows style path cannot be correctly shown in the bash terminal. 
**Describe the solution you'd like**
Currently edf is running at the default terminal, if we can manually let edf running at a non-default terminal(powershell or other terminals), this problem can be solved
**Describe alternatives you've considered**
or we can manually set the path through the setting.json

Many thanks!

**Comment by brianignacio5** [comment]
I've just found this information of Visual Studio Code documentation in [here](https://code.visualstudio.com/docs/terminal/profiles#_configuring-the-taskdebug-profile):

```json
"terminal.integrated.automationProfile.windows": {
    "path": "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
}
```

replaces the default terminal profile for tasks and debug purposes. Can you give it a try @rogue-shadowdancer ?

**Comment by rogue-shadowdancer** [comment]
> I've just found this information of Visual Studio Code documentation in [here](https://code.visualstudio.com/docs/terminal/profiles#_configuring-the-taskdebug-profile):
> 
> ```json
> "terminal.integrated.automationProfile.windows": {
>     "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
> }
> ```
> 
> replaces the default terminal profile for tasks and debug purposes. Can you give it a try @rogue-shadowdancer ?

Thanks! This is a good idea! However, because of some reason, I have to use bash for most situations. So it will be troublesome each time I switch to powershell when using edf..

**Comment by brianignacio5** [comment]
Can you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/698416721.zip) from the linked PR ?

We added `idf.customTerminalExecutable` and `idf.customTerminalExecutableArgs` to customize the terminal used by extension tasks. Many terminals need arguments such as `/bin/bash` needs `["-c"]` respectively..

**Comment by rogue-shadowdancer** [comment]
Wow! It's great! many thanks!

**Comment by 424778940z** [comment]
Sorry for reply to an old issue, it seems `idf.customTerminalExecutable` won't effect cmake configure and build process?
I set it to wrong path then both debug and monitor will fail, but configure and build still works.

The problem I'm facing is, micropython build script using sed with regex, but cmake defaults to generate ninja script with cmd.exe
Unless I set it to use bash from msys, or set `COMSPEC` env to bash.exe, but seems both are not possible from idf vscode plugin

Another thing is, I try to use a patched build cmake, but somehow the latest plugin with customize cmake path will never consider valid
