### ISSUE TITLE
[Feature Request]: Allow clangd plugin for code completion instead of the Microsoft Intellisense (VSC-1087)

### ISSUE THREAD

**Issue by CJCombrink** [espressif/vscode-esp-idf-extension#936]
**Is your feature request related to a problem? Please describe.**
I want to use the "llvm-vs-code-extensions.vscode-clangd" extension for code completion and code browsing instead of the Microsoft one (ms-vscode.cpptools).
When I install and enable the clangd plugin it prompts me to disable the MS one, which is what I want. But I can not disable the MS one since it informs me that I will have to disable this plugin as well with the following error:

>  Cannot disable 'C/C++' extension alone. 'Espressif IDF' extension depends on this. Do you want to disable all these extensions?

**Describe the solution you'd like**
I want the ability to disable the MS intelliSense plugin without having to disable this ESP plugin and use the clangd plugin instead. 

**Describe alternatives you've considered**
I guess the alternative is live with the shortcomings of the MS IntelliSense.

**Additional context**
I am on Windows 11 but guessing that does not matter, I will probably have the same issue on other OSes.

**Comment by brianignacio5** [comment]
You could try using our release for OpenVSX in the GitHub repository in [here](https://github.com/espressif/vscode-esp-idf-extension/releases/download/v1.6.1/esp-idf-extension-open-1.6.1.vsix) or in the [OpenVSX registry](https://open-vsx.org/extension/espressif/esp-idf-extension)
