### ISSUE TITLE
VSCode Crashing (VSC-1097)

### ISSUE THREAD

**Issue by MoreTore** [espressif/vscode-esp-idf-extension#948]
### OS

Windows

### Operating System version

11

### ESP-IDF version

5.0

### Python version

3.10

### Doctor command output

n/a

### Description

After building my program a few times I start getting endless error popups from my extensions like cppchecker and linters. After a minute vscode freezes and I need to force kill the editor. This extension seems very unstable.

### Debug Message

```plain
na
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
How is this extension very unstable ? What is this extension doing ? Maybe check these extension cppchecker and linters instead ?

You have provided zero information about the issue you are having with this extension in this GitHub issue and no steps to reproduce.
