### ISSUE TITLE
[Feature Request]: Running the size task after the build task succeeds should not be so interruptive (VSC-1100)

### ISSUE THREAD

**Issue by henryshunt** [espressif/vscode-esp-idf-extension#954]
After the build task completes without errors, the size task runs. This is very annoying because it opens a new terminal tab when I'm trying to read the output of the build task. If I catch that the build task has something I wish to look at (e.g. warnings), the size task quickly switches in and I have to click to get back to the build task. Also, I often start the build task and then close the terminal, but the size task inevitably causes it to open back up again unannounced. Finally, I personally don't really have any need to see the size info, certainly not after every single build.

The contents of the size task should run as part of the build task (so it doesn't open a separate tab), or there should be an option to disable the size task from automatically running after the build task (something I looked for but did not find).

**Comment by brianignacio5** [comment]
Hi @henryshunt thank you for your feedback. Will add an extension setting to disable this size task after build and share the vsix installer for you to try and see if it's okay.

I'll add a link in a bit from the PR

**Comment by henryshunt** [comment]
Much appreciated, thank you!

**Comment by brianignacio5** [comment]
Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/682972274.zip) to see if the issue is fixed ?

**Comment by vsh-ektos** [comment]
@brianignacio5 It seems to work well, but the build task (not the build itself) does not complete
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/113985827/e78d9447-8c6d-4942-b22c-e1fee258acaa)
