### ISSUE TITLE
Cannot add breakpoint if running. (VSC-1101)

### ISSUE THREAD

**Issue by AndrewCapon** [espressif/vscode-esp-idf-extension#958]
### OS

MacOS

### Operating System version

macOS 12.6.5

### Visual Studio Code version

 1.77.3

### ESP-IDF version

5.0.1

### Python version

3.9.12

### Doctor command output

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS darwin x64 21.6.0 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/ARM/bin:/Applications/CMake.app/Contents/bin:/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.openocd.macos64_2.1.0.202110201500/tools/bin: 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.77.3 
Visual Studio Code language en 
Visual Studio Code shell /bin/zsh 
ESP-IDF Extension version 1.6.1 
Workspace folder /Volumes/T7/Development2/esp/VS/espidf/blink 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) 
ESP-IDF Path (idf.espIdfPath) /Volumes/T7/Development2/esp/VS/esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
Custom extra paths (idf.customExtraPaths) /Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp-elf-gdb/11.2_20220823/xtensa-esp-elf-gdb/bin:/Volumes/T7/Development2/esp/VS/espressif/tools/riscv32-esp-elf-gdb/11.2_20220823/riscv32-esp-elf-gdb/bin:/Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin:/Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp32s2-elf/esp-2022r1-11.2.0/xtensa-esp32s2-elf/bin:/Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin:/Volumes/T7/Development2/esp/VS/espressif/tools/riscv32-esp-elf/esp-2022r1-11.2.0/riscv32-esp-elf/bin:/Volumes/T7/Development2/esp/VS/espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin:/Volumes/T7/Development2/esp/VS/espressif/tools/openocd-esp32/v0.11.0-esp32-20221026/openocd-esp32/bin:/Volumes/T7/Development2/esp/VS/espressif/tools/esp-rom-elfs/20220823
Custom extra vars (idf.customExtraVars)
    OPENOCD_SCRIPTS: /Volumes/T7/Development2/esp/VS/espressif/tools/openocd-esp32/v0.11.0-esp32-20221026/openocd-esp32/share/openocd/scripts
    ESP_ROM_ELF_DIR: /Volumes/T7/Development2/esp/VS/espressif/tools/esp-rom-elfs/20220823/
Virtual env Python Path (idf.pythonBinPath) /Volumes/T7/Development2/esp/VS/espressif/python_env/idf5.0_py3.9_env/bin/python
Serial port (idf.port) /dev/cu.usbmodem4
OpenOCD Configs (idf.openOcdConfigs) board/esp32s3-builtin.cfg
ESP-IDF Tools Path (idf.toolsPath) /Volumes/T7/Development2/esp/VS/espressif
Git Path (idf.gitPath) git
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-IDF Custom extra paths
Access to /Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp-elf-gdb/11.2_20220823/xtensa-esp-elf-gdb/bin: true
Access to /Volumes/T7/Development2/esp/VS/espressif/tools/riscv32-esp-elf-gdb/11.2_20220823/riscv32-esp-elf-gdb/bin: true
Access to /Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin: true
Access to /Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp32s2-elf/esp-2022r1-11.2.0/xtensa-esp32s2-elf/bin: true
Access to /Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin: true
Access to /Volumes/T7/Development2/esp/VS/espressif/tools/riscv32-esp-elf/esp-2022r1-11.2.0/riscv32-esp-elf/bin: true
Access to /Volumes/T7/Development2/esp/VS/espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin: true
Access to /Volumes/T7/Development2/esp/VS/espressif/tools/openocd-esp32/v0.11.0-esp32-20221026/openocd-esp32/bin: true
Access to /Volumes/T7/Development2/esp/VS/espressif/tools/esp-rom-elfs/20220823: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH true
Access to Ninja in environment PATH true
Access to ESP-IDF Tools Path (idf.toolsPath) true
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path false
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in /Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp-elf-gdb/11.2_20220823/xtensa-esp-elf-gdb/bin: false
Spaces in /Volumes/T7/Development2/esp/VS/espressif/tools/riscv32-esp-elf-gdb/11.2_20220823/riscv32-esp-elf-gdb/bin: false
Spaces in /Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin: false
Spaces in /Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp32s2-elf/esp-2022r1-11.2.0/xtensa-esp32s2-elf/bin: false
Spaces in /Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin: false
Spaces in /Volumes/T7/Development2/esp/VS/espressif/tools/riscv32-esp-elf/esp-2022r1-11.2.0/riscv32-esp-elf/bin: false
Spaces in /Volumes/T7/Development2/esp/VS/espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin: false
Spaces in /Volumes/T7/Development2/esp/VS/espressif/tools/openocd-esp32/v0.11.0-esp32-20221026/openocd-esp32/bin: false
Spaces in /Volumes/T7/Development2/esp/VS/espressif/tools/esp-rom-elfs/20220823: false
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.35.3
ESP-IDF version 5.0.1
Python version 3.9.12
Python's pip version 23.1.2
-------------------------------------------------- Project configuration settings ----------------------------------------------------------
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 4.0.2
CacheControl version: 0.12.11
certifi version: 2022.12.7
cffi version: 1.15.1
charset-normalizer version: 3.1.0
click version: 8.0.4
colorama version: 0.4.6
construct version: 2.10.68
contextlib2 version: 21.6.0
cryptography version: 36.0.2
ecdsa version: 0.18.0
esp-coredump version: 1.5.0
esptool version: 4.5.1
freertos-gdb version: 1.0.2
future version: 0.18.2
gcovr version: 6.0
idf-component-manager version: 1.2.2
idna version: 3.4
Jinja2 version: 3.0.3
kconfiglib version: 14.1.0
lockfile version: 0.12.2
lxml version: 4.9.2
MarkupSafe version: 2.1.2
msgpack version: 1.0.5
packaging version: 23.1
pip version: 23.1.2
psutil version: 5.9.5
pycparser version: 2.21
pyelftools version: 0.27
pygdbmi version: 0.9.0.2
Pygments version: 2.15.1
pyparsing version: 3.0.9
pyserial version: 3.5
PyYAML version: 6.0
reedsolo version: 1.6.0
requests version: 2.29.0
requests-file version: 1.5.1
requests-toolbelt version: 0.10.1
schema version: 0.7.5
setuptools version: 67.7.2
six version: 1.16.0
tqdm version: 4.65.0
urllib3 version: 1.26.15
websocket-client version: 1.5.1
wheel version: 0.40.0
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "/Volumes/T7/Development2/esp/VS/espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            },
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
} 
--------------------------------------------------------------------------------------------------------------------------------------------

### Extension

Deleted file, replicated issue, no log file created.

### Description

When the process is running trying to add a breakpoint causes command_processor.py to exception.

### Debug Message

```plain
2023-04-30 08:20:09,837 - Debug Adapter (main) - ERROR - unhashable type: 'dict'
Traceback (most recent call last):
  File "/Volumes/T7/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/command_processor.py", line 700, in on_setBreakpoints_request
    try_set_once(get_good_path(source.path), src_line, condition)
  File "/Volumes/T7/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/command_processor.py", line 676, in try_set_once
    raise e
  File "/Volumes/T7/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/command_processor.py", line 674, in try_set_once
    return self.da.source_break_add(source_path, line, condition=condition)
  File "/Volumes/T7/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/debug_adapter.py", line 523, in source_break_add
    bp_num = self._gdb.add_bp("{}:{}".format(src, line), ignore_count=0, cond=condition)
  File "/Volumes/T7/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/debug_backend/debug_backend/gdb.py", line 487, in add_bp
    raise DebuggerError('Failed to insert BP!')
debug_adapter.debug_backend.debug_backend.defs.DebuggerError: Failed to insert BP!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/T7/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/command_processor.py", line 52, in __call__
    on_request(protocol_message)
  File "/Volumes/T7/.vscode/extensions/espressif.esp-idf-extension-1.6.1/esp_debug_adapter/debug_adapter/command_processor.py", line 706, in on_setBreakpoints_request
    bp.update({{'message': e}})
TypeError: unhashable type: 'dict'
```

### Other Steps to Reproduce

Tried with S3Box, ProS3 and XIAO ESP32S3. All have same problem.

Eclipse esp-idf plugin works perfectly.

VSCode platformIO works perfectly.

To replicate:

1. Clean installation of esp-idf plugin
2. Install esp-idf and tools via plugin.
3. Create project using example
4. Set up jtag, flashing via jtag works fine.
5. Add breakpoint somewhere in loop code and Launch debugger, breakpoint is hit.
6. Continue execution, breakpoint is hit again.
7. Remove breakpoint and continue execution.
8. Try to add breakpoint while it is now running, breakpoint not hit as it is not added due to exception.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Could you provide more information about the error? What is the breakpoint request being sent to debug backend ? What kind of breakpoint are you trying to insert and where? What kind of value is being set ?

**Comment by brianignacio5** [comment]
Change the `logLevel` to 4 in launch.json to see more output from debug adapter. There is also debug log file in your project workspace folder. Before the error there should some debug adapter messages and also the request to GDB from debug adapter

**Comment by AndrewCapon** [comment]
Adding working breakpoint while paused:

```
[Debug Adapter]
2023-05-04 09:46:05,634 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'Content-Length: 223\\r\\n'<<

[Debug Adapter]
2023-05-04 09:46:05,634 - Debug Adapter (ReaderThread) - DEBUG - read line: >>b'\\r\\n'<<

2023-05-04 09:46:05,634 - Debug Adapter(Command Processor) - DEBUG - Got json: {
    "arguments": {
        "breakpoints": [
            {
                "line": 86
            }
        ],
        "lines": [
            86
        ],
        "source": {
            "path": "/Volumes/T7/Development2/esp/VS/espidf/blink/main/blink_example_main.c"
        },
        "sourceModified": false
    },
    "command": "setBreakpoints",
    "seq": 25,
    "type": "request"
}
2023-05-04 09:46:05,634 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Got json: {\n    \"arguments\": {\n        \"breakpoints\": [\n            {\n                \"line\": 86\n            }\n        ],\n        \"lines\": [\n            86\n        ],\n        \"source\": {\n            \"path\": \"/Volumes/T7/Development2/esp/VS/espidf/blink/main/blink_example_main.c\"\n        },\n        \"sourceModified\": false\n    },\n    \"command\": \"setBreakpoints\",\n    \"seq\": 25,\n    \"type\": \"request\"\n}\n", "source": {}}, "seq": 88}

[Debug Adapter]
2023-05-04 09:46:05,634 - Gdb - DEBUG - MI->: -break-insert -i 0 /Volumes/T7/Development2/esp/VS/espidf/blink/main/blink_example_main.c:86
[Debug Adapter]
2023-05-04 09:46:05,637 - Gdb - DEBUG - MI<-:
[{'message': 'done',
  'payload': {'bkpt': {'addr': '0x42007bc4',
                       'disp': 'keep',
                       'enabled': 'y',
                       'file': '/Volumes/T7/Development2/esp/VS/espidf/blink/main/blink_example_main.c',
                       'fullname': '/Volumes/T7/Development2/esp/VS/espidf/blink/main/blink_example_main.c',
                       'func': 'app_main',
                       'line': '86',
                       'number': '6',
                       'original-location': '/Volumes/T7/Development2/esp/VS/espidf/blink/main/blink_example_main.c:86',
                       'thread-groups': ['i1'],
                       'times': '0',
                       'type': 'breakpoint'}},
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]
[Debug Adapter]
2023-05-04 09:46:05,637 - Gdb - DEBUG - RESULT: done {'bkpt': {'addr': '0x42007bc4',
          'disp': 'keep',
          'enabled': 'y',
          'file': '/Volumes/T7/Development2/esp/VS/espidf/blink/main/blink_example_main.c',
          'fullname': '/Volumes/T7/Development2/esp/VS/espidf/blink/main/blink_example_main.c',
          'func': 'app_main',
          'line': '86',
          'number': '6',
          'original-location': '/Volumes/T7/Development2/esp/VS/espidf/blink/main/blink_example_main.c:86',
          'thread-groups': ['i1'],
          'times': '0',
          'type': 'breakpoint'}}
2023-05-04 09:46:05,637 - Debug Adapter(Command Processor) - DEBUG - Processed command: setBreakpoints
[Debug Adapter]
2023-05-04 09:46:05,637 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "response", "request_seq": 25, "success": true, "command": "setBreakpoints", "body": {"breakpoints": [{"line": 86, "verified": "true", "source": {"path": "/Volumes/T7/Development2/esp/VS/espidf/blink/main/blink_example_main.c"}}]}, "seq": 89}

2023-05-04 09:46:05,637 - Debug Adapter (WriterThread) - DEBUG - Writing: {"type": "event", "event": "output", "body": {"output": "Processed command: setBreakpoints\n", "source": {}}, "seq": 90}
```

**Comment by brianignacio5** [comment]
@AndrewCapon It is not broken the debug adapter. The thing is that the user is trying to add a breakpoint while the program is running and not interrupting the execution. In the terminal you would usually run the interrupt command but the debug adapter when you set a breakpoint doesn't interrupt the program execution. Need to add the workflow of interrupting the program if executing before adding breakpoint.

**Comment by AndrewCapon** [comment]
Hi @brianignacio5 

Thanks, this used to work, something must have changed in the last few weeks?

**Comment by AndrewCapon** [comment]
Hi @brianignacio5 

This was working a few weeks ago, I know as I was using it.

Are you saying that adding a breakpoint in the debugger when code is running has never worked?

Wouldn't you have had loads or reports if this was the case?
