### ISSUE TITLE
[Feature Request]:  support encrypted-app-flash and encrypted-flash (VSC-1103)

### ISSUE THREAD

**Issue by ramiws** [espressif/vscode-esp-idf-extension#960]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I cannot use encrypted-app-flash

**Describe the solution you'd like**
Another button to flash encrypted that button can be enabled/disabled via settings 
**Describe alternatives you've considered**
command line

**Comment by brianignacio5** [comment]
Have you look at the https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/flash-encryption.html ESP-IDF about flash encryptions ? If partitions are listed as encrypted in the `build/flasher_args.json` as encrypted, when you flash it will flash these partitions as encrypted.
