### ISSUE TITLE
Cannot restart install/configuration procedure for Espressif's VS Code extension (VSC-1131)

### ISSUE THREAD

**Issue by benniflash** [espressif/vscode-esp-idf-extension#998]
### OS

Windows

### Operating System version

Windows 10

### Visual Studio Code version

1.79.2

### ESP-IDF version

5.0

### Python version

3.10.4

### Doctor command output

I cannot launch ESP-IDF Doctor command anymore

### Description

Starting from this link https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/get-started/index.html and following the steps to install VSCode and the Espressif IDF extension (https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/get-started/index.html), I cannot configure ESPRESSIF extension: I didn't have the Python line during the Express configuration 

![2023-06-20 10_21_56-Window](https://github.com/espressif/vscode-esp-idf-extension/assets/137156795/455dd584-c53d-4c3d-9fd0-95c7b3e7b666)

Then, I tried to uninstall everything, VS Code and Espressif IDF extension, but ASAP I restart the configuration, it doesn't restart from the beginning and it does not advance.
![2023-06-20 10_24_14-Window](https://github.com/espressif/vscode-esp-idf-extension/assets/137156795/765442e3-778f-4476-afa5-d597930c7294)

How can I restart everything from the beginning?

### Debug Message

```plain
Cannot get Debug Message
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by brianignacio5** [comment]
Can you share the log file ?

It was part of the issue template Extension part:

Please share related content of extension log file located in:

Windows (%USERPROFILE%.vscode\extensions\espressif.esp-idf-extension-VERSION\esp_idf_vsc_ext.log)
Linux-MacOS ($HOME/.vscode/extensions/espressif.esp-idf-extension-VERSION/esp_idf_vsc_ext.log)

**Comment by brianignacio5** [comment]
Seems there is an error getting this file:

https://dl.espressif.com/dl/esp-idf/idf_versions.txt

Can you access to it directly? Also When you try to open the `ESP-IDF: Configure ESP-IDF extension`, what does happen?

**Comment by benniflash** [comment]
This is my idf_version.txt file
[idf_versions.txt](https://github.com/espressif/vscode-esp-idf-extension/files/11798373/idf_versions.txt)

I cannot open ESP-IDF: Configure ESP-IDF extension from command palette, maybe because it is still loading the initial configuration:
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/137156795/a8317e1d-4e13-4cc3-bdc4-51fb0a6e481a)

**Comment by benniflash** [comment]
I can open your file

**Comment by benniflash** [comment]
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/137156795/fc284a4e-b529-4a07-b86d-2acbb79832d5)

**Comment by brianignacio5** [comment]
Then it seems there is a connection issue from vscode itself.  Have you try closing all windows of vscode an re opening them ? 

Are you using a proxy in vscode ?

**Comment by benniflash** [comment]
Yes, I'm using my company's Proxy

**Comment by radurentea** [comment]
Hi @benniflash,

You can follow the steps for uninstalling [here](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/INSTALL.md#uninstalling-the-plugin).

You can also delete the esp-idf. Default location is C:\Espressif

**Comment by benniflash** [comment]
Hello again,
I'm now trying to follow the step in the following link https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/windows-setup.html
I've updated the driver in order to establish a USB connection with the ESP32-C3-DevKitM-1.
However when I try to configure my project (hello_world) I get this error .log. How can I solve this problem?
[CMakeError.log](https://github.com/espressif/vscode-esp-idf-extension/files/11946847/CMakeError.log)
[CMakeOutput.log](https://github.com/espressif/vscode-esp-idf-extension/files/11946849/CMakeOutput.log)

**Comment by brianignacio5** [comment]
How are your running the build? Did you follow the [install tutorial](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/install.md) and [basic use tutorial](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/basic_use.md) ?

**Comment by brianignacio5** [comment]
I'm very confused. So if you using Windows you didn't need to install Python yourself (the extension and Windows installer will install Python for your on Windows). The `/usr/bin/python` tells me you are trying to use Linux. Are you running from Linux in Windows (WSL) ?

The CMake error points me your environment is not properly configured. So we need to get that configured properly first.

**Comment by benniflash** [comment]
Actually I'm not running WSL. I followed step by step the guide for the windows installation, so I don't know where I switch from Win10 to Linux process.

How can I configure my environment properly?
However If I follow the link you attached I'm not able to CONFIGURE espressif, even if I download both Visual studio and Espressif extension properly.

**Comment by benniflash** [comment]
I have an update. I tried to use the espressif IDE instead of VS, I tried to build the hello_world project, but I get this error : 
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/137156795/c4ca1409-fc37-4476-883d-3bcaccc3d320)
So i followed this youtube video to install the missing Tools, and everything seemed to be ok but than i get the following error log file. Can you help me?
[Setup Log 2023-07-04 #003.txt](https://github.com/espressif/vscode-esp-idf-extension/files/11949455/Setup.Log.2023-07-04.003.txt)

**Comment by brianignacio5** [comment]
Have you tried the new version of the extension in visual studio code ? 

About Espressif IDE you need to go to the [Eclipse Plugin repository](https://github.com/espressif/idf-eclipse-plugin) for assistance
